### ISSUE TITLE
Use django-taggit 0.11's prefetch_related support instead of workaround in wagtailadmin/taggable.py

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1]
https://github.com/torchbox/wagtail/blob/70e91d6759e86a0490b478d7f5ae4dafae8bc663/wagtail/wagtailadmin/taggable.py#L51 implements a workaround to the taggit API to allow us to pull in tags on prefetch_related queries. django-taggit 0.11 introduces proper prefetch_related support, so we should use that instead.

(Note that https://github.com/torchbox/django-modelcluster/issues/1 currently blocks us from upgrading to 0.11)

**Comment by kaedroho** [comment]
Fixed in: https://github.com/torchbox/wagtail/pull/1478/files
