### ISSUE TITLE
Document running tests for contributing

### ISSUE THREAD

**Issue by m-sanders** [torchbox/wagtail#1004]
Hello

I am currently evaluating wagtail for $DAY_JOB. Maybe I am being obtuse, but I have struggled this evening to get the wagtail tests running locally. In the end I resorted to stealing and modifying the vagrant script from the wagtaildemo site as I didn't fancy installing postgres + elasticsearch locally. Is it worth submitting the VagrantFile as a pull request?

**Comment by kaedroho** [comment]
Hi @m-sanders 

I think a Vagrantfile would be really useful, please feel free to send us a pull request.


As for running tests, you do not need to run postgres/elasticsearch. If you don't install the elasticsearch pip package, all of the elasticsearch tests should be skipped. Also, if you run the tests with the ``DATABASE_ENGINE`` enironment variable set to ``django.db.backends.sqlite3``, i would run them against an SQLite database.

Try this with a fresh virtual environment:
```
python setup.py develop
pip install mock==1.0.1 python-dateutil==2.2 pytz==2014.7
DATABASE_ENGINE=django.db.backends.sqlite3 python runtests.py
```

**Comment by m-sanders** [comment]
Cheers @kaedroho 

I have been doing that from within Vagrant and all is well. it is probably my local environment (since up dating to Yosemite on my Mac brew install of python has been weird). But documentation is a good thing.

**Comment by kaedroho** [comment]
Documented in: https://github.com/kaedroho/wagtail/commit/c14407e4467621944fd3fc9e25c05d16e06e15c5

**Comment by kaedroho** [comment]
Documentation for this can now be found at: http://docs.wagtail.io/en/latest/howto/contributing.html#running-the-unit-tests

Also, SQLite is now the default backend for testing, so you no longer need to specify the ``DATABASE_ENGINE`` (unless you want to test against PostgreSQL/MySQL).
