### ISSUE TITLE
Oembed fails behind proxy

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#1007]
We have a test installation of Wagtail behind a required proxy for outside access. Embeds that use Oembed fail in this case.

**Comment by gasman** [comment]
Hi @mhnbcu,
According to [the docs for Python's urllib library](https://docs.python.org/2/library/urllib.html#urllib.urlopen), it should be possible to specify a proxy by setting the 'http_proxy' environment variable. Adding something like this to your settings file should do the trick:

    import os
    os.environ['http_proxy'] = "http://proxy.example.com:3128"

**Comment by mhnbcu** [comment]
Thank you @gasman, issue resolved.
