### ISSUE TITLE
Allow specifying child page types for page chooser

### ISSUE THREAD

**Issue by mattbrailsford** [torchbox/wagtail#1015]
It would be handy if rather than listing all page types when creating a new page that you are able to specify which pages types are allowed beneath any given page and only those pages types are listed.

For example, given a Blog Archive page type, if you click "add page" when viewing the blog archive in the admin, it would be nice to only see Blog Post as the available child page type and not all other page types.

**Comment by bgrace** [comment]
This feature exists as the `Page.subpage_types` attribute. See: http://docs.wagtail.io/en/stable/core_components/pages/creating_pages.html?highlight=subpage_types#page-attributes-properties-and-methods-reference

If only one page type is allowed, the 'add child' operation will skip the list and take you directly to the correct editor for that page type.

The converse `parent_page_types` attribute also exists, but it doesn't appear to be documented. Useful if you want to constrain where a page can be created, or block it from being created in the admin at all (e.g., I typically set unique pages to have a `parent_page_types = []`).

**Comment by mattbrailsford** [comment]
Sweet! I didn't know that. Thanks for the reference.

**Comment by mattbrailsford** [comment]
Have created PR #1017 to add parent_page_types to the docs and also adding the tip of setting the attributes to empty arrays to block creation altogether.

**Comment by DanielTate** [comment]
This link is dead does this still exist?
