### ISSUE TITLE
DateTime and Date Form Field

### ISSUE THREAD

**Issue by SableWalnut** [torchbox/wagtail#1016]
When selecting DateTime or Date in wagtailadmin it sets the html for the form to `type='text'` instead of `type='date'`.

**Comment by gasman** [comment]
Hi @SableWalnut,
The `type` attribute we use here is inherited from Django's own `DateInput` / `DateTimeInput` widgets. According to https://code.djangoproject.com/ticket/16630#comment:11, Django made the decision not to adopt `type='date'` at the same time as implementing `type='email'`, `type='url'` etc, as this would disallow certain date formats that we wish to accept. This would be an issue on Wagtail too, so I think it's best to keep the current `type='text'` behaviour.

#880 adds the ability to override the widget on a `FieldPanel`, so it will be possible for users to replace the default widget with a custom one that uses `type='date'` if desired.
