### ISSUE TITLE
Broken admin datepicker l10n dateformat when not using defaults

### ISSUE THREAD

**Issue by asmaps** [torchbox/wagtail#1028]
If you change your localization flavor the datepicker in the admin breaks as django (intentionally) outputs another date format (e.g. dd.mm.yyyy) than the default (yyyy-mm-dd).

So if you click on the date field in the admin the date picker doesn't understand the date and selects today as default. When the field now looses the focus the date is set to "today" which is pretty annoying when you just accidentially clicked on the field and your date is "broken". Probably it's possible to set the format for the picker to settings.DATE_FORMAT.

**Comment by gasman** [comment]
This should be fixed by #1018. (The fix forces the format to be yyyy-mm-dd, so unfortunately it won't respect your localization setting, but at least it will now be consistent between Django and Javascript.)
