### ISSUE TITLE
We need a way to recover username

### ISSUE THREAD

**Issue by ollywillans** [torchbox/wagtail#1030]
If an editor forgets her username, there's no easy way to find it, so she can't then login.

**Comment by davecranwell** [comment]
Django is traditionally all about usernames for login, rather than email, which I find quite out-moded. At the least we should make it "username or email address", I think.

**Comment by zerolab** [comment]
#722 is related.

**Comment by zerolab** [comment]
Closing in favor of #722 as the discussion bulk is there.
