### ISSUE TITLE
Table generator for rich text editor or other

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1039]
The ability for editors to add tables to pages is a fairly sort after piece of functionality that many of my clients has commented on. It would be great to see it introduced to Wagtail in some way.

**Comment by gasman** [comment]
This was one of the original motivations for developing StreamField (#823), which will be able to accommodate table editing far better than the rich text editor would. Hopefully the opportunity to develop this as a StreamField add-on will come up soon!

**Comment by gasman** [comment]
Implemented for StreamField in #1705.
