### ISSUE TITLE
Recently published conflicts with manual ordering content ordering system

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1052]
If I have a set of pages I've manually ordered using (such as for their placement in a primary menu etc) this order is undermined when I edit a page as it's pulled out of the ordering and placed at the top of the list when published.

**Comment by davecranwell** [comment]
The ordering interface is enabled by clicking the ordering label at the top left of the page listing. Only when enabled does the page listing reflect the order of pages. When disabled the pages automatically order by last modified date.

**Comment by tmsndrs** [comment]
Ah I see. That makes sense. I think that feature could do with some UX thought (this problem came from a client). Even the button itself is pretty hidden but I'll close this and maybe we can talk through it at some other point.

**Comment by gasman** [comment]
This ticket is probably relevant to what you're after: #882
