### ISSUE TITLE
Rich text `LINK_HANDLERS` needs abstraction into associated apps.

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1055]
Related to #961.

`wagtailcore/rich_text.py` seems to define how placeholder links present in rich text fields get "expanded" to real links. 

If you've got a custom document model it needs to be possible to register additional custom link handlers like `DocumentLinkHandler` so you can ensure it's the objects in your custom model that get searched, instead of `Documents.objects`.

More generally it seems the rich text handlers for expanding images/documents/pages etc probably ought to be abstracted into their associated apps, with a hooks system used to add them to the `LINK_HANDLERS` iterated over by `expand_db_html()`.

Of course if an `AbstractDocument` were possible this might not be needed, but it seems the link handlers should probably be refactored all the same.

**Comment by davecranwell** [comment]
Paging @timheap who, given his excellent work on the widgets, might feel inclined to work on this also :)

**Comment by gasman** [comment]
Implemented in #1093
