### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1056]
Just thought I'd ticket this, since we're going to want it soon. I think we should aim to implement this as soon as we can so any libraries that depend on Wagtail can get started on implementing Django 1.8 support a well.

TODO (feel free to add to this list):
 - [x] Wait for/add Django 1.8 support in django-taggit (PR https://github.com/alex/django-taggit/pull/297)
 - [x] Add Django 1.8 support into Django modelcluster (PR https://github.com/torchbox/django-modelcluster/pull/20)
 - [ ] Change API of routablepage to avoid new restriction in url() function
 - [x] Get tests working (PR https://github.com/torchbox/wagtail/pull/1060)
 - [ ] Work out a way to test with custom user model on both Django 1.7 and 1.8 (there are schema differences between the two which makes this tricky)
 - [ ] Include PageManager in migrations

**Comment by kaedroho** [comment]
Just submitted a PR to django taggit, adding support for Django 1.8 beta 2. https://github.com/alex/django-taggit/pull/297. Reviews wanted!

**Comment by timheap** [comment]
The basic project created from `wagtail start projectname` fails to start on Django 1.8 because of migration issues.

**Comment by gasman** [comment]
Updating the project template to support 1.8 will be dealt with as part of #1109.

Closing this ticket now, as the work to support 1.8 in Wagtail itself is now completed (#1060, #1180, #1161).
