### ISSUE TITLE
Document use of feature detection with a custom image model

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#1057]
When specifying a WAGTAILIMAGES_IMAGE_MODEL, WAGTAILIMAGES_FEATURE_DETECTION_ENABLED will not assign the focal point on upload. 

A workaround is possible by creating receivers for the WAGTAILIMAGES_IMAGE_MODEL that call the original receiver functions. 

Is this a bug or expected?

**Comment by kaedroho** [comment]
This is expected as you have you redefine this signal handler on your new image model: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/models.py#L242-L248

I'll mark this as a documentation issue. But there could be a way we can make it automatically switch to your custom image model if one is specified

**Comment by kaedroho** [comment]
Documented here: http://docs.wagtail.io/en/v1.0/topics/images/advanced_topics.html#feature-detection-custom-image-model
