### ISSUE TITLE
Pages directly under root visible in Explorer menu regardless of permission settings

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#1058]
In testing the Sites functionality 2 sites in addition to the default were setup: Site B, Site C. Also 2 sets of Editors and Moderators groups were created, one with page permissions on Homepage B under the Root and the other with page permissions on Homepage C under the Root.

When navigating as a Site B editor using the Explorer menu the default Homepage and Homepage C are visible, although clicking on either does not allow editing.

Ideally with the permissions set this way Homepage and Homepage C would not be visible when logged-in as a Site B editor.

**Comment by davecranwell** [comment]
This is currently intentional, although not ideal and is something we want to address. True multi-tenancy installations are currently not possible as the permissions model currently allows any page to be viewable, even if it isn't editable.

**Comment by mhnbcu** [comment]
@davecranwell thanks for the follow up. Looking back on this I'm not sure there is even a strong enough case for a single installation to support multi-tenancy. 

At the time I was trying to anticipate needs of a team where one site was being used for two distinct television shows. So I explored possibilities of orchestrating a pattern aimed at getting more flexibility. The exploration was premature given the reasonable constraints at hand.

**Comment by davecranwell** [comment]
Personally I'd quite like multi-tenancy to be possible, but it's a massive task and it's obviously much simpler for now to create multiple django/wagtail installations on your server!

The solution we have at present is relatively simple, if slightly unclear. We do however want to improve the user group permissions UI, which doesn't adequately explain Wagtail's permission system https://github.com/torchbox/wagtail/issues/1488
