### ISSUE TITLE
Missing image results in 500 error

### ISSUE THREAD

**Issue by mjdavies** [torchbox/wagtail#1066]
Morning all

We're noticing some 500 error emails getting sent out when an image is missing, not on the file system, for whatever reason.

I tracked it down to here

https://github.com/torchbox/wagtail/blob/stable/0.8.x/wagtail/wagtailimages/views/frontend.py#L18

I know how to stop it happening, but I'm not %100 certain on what you'd like to return.

Something like this would probably do it.

```
def serve(request, signature, image_id, filter_spec):
    image = get_object_or_404(get_image_model(), id=image_id)

    if not verify_signature(signature.encode(), image_id, filter_spec):
        raise PermissionDenied

    try:
        rendition = image.get_rendition(filter_spec)
        try:
          rendition.file.open('rb')
        except IOError:
          return HttpResponse("File not present", content_type='text/plain', status=404)
        return HttpResponse(FileWrapper(rendition.file), content_type='image/jpeg')
    except Filter.InvalidFilterSpecError:
        return HttpResponse("Invalid filter spec: " + filter_spec, content_type='text/plain', status=400)```

**Comment by kaedroho** [comment]
Hi @mjdavies 

Thanks for reporting. Yes, I agree raising a 500 error is a bit extreme for a missing image. (marked as bug)

It looks like you're getting this error for missing rendition images, are the source images on your server?

If so, you may be able to fix this by clearing the renditions table (this will need tweaking if you are using a custom image model):

```python
>>> from wagtail.wagtailimages.models import Rendition
>>> Rendition.objects.all().delete()
```

Maybe the behaviour of Wagtail could be changed as follows:
 - If the rendition image is missing, but source image is present. Regenerate the rendition
 - If both are missing, return a 404

**Comment by mjdavies** [comment]
Hi Karl

We're not getting the errors on the live system any more, i went in and just added images for the missing ones.

Some bots are still asking for old images though, so they spark off a 500, but we can live with that for now.

"If the rendition image is missing, but source image is present. Regenerate the rendition
If both are missing, return a 404"

That sounds like a plan!!

Matt
