### ISSUE TITLE
'Sites' menu item is displayed for non-admin users

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1074]
If you create a user that is only a member of the 'Editors' group, and log in as them, the left-hand menu includes the Settings menu, with 'Sites' as the only item. This should be hidden from non-admins.

On current wagtaildemo, clicking on this redirects to the broken URL `http://localhost:8111/admin/sites/django.contrib.auth.views.login?next=/admin/sites/`, which makes me suspect that this is a regression from the `LOGIN_URL` change in 0.9.

**Comment by kaedroho** [comment]
Sorry, I assigned this to myself thinking I had time to look at it (which I didn't). I'll look into this now.
