### ISSUE TITLE
Streamfield: StreamBlock renders its child StructBlocks as plain text

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/wagtail#1078]
This can be fixed by calling `child.render()` here:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/blocks/stream_block.py#L193
Instead of `[(child, child.block_type) for child in value]`

Or would it be better to have an `__str__` method for blocks that call render?

**Comment by gasman** [comment]
note to self: this specifically occurs when rendering the StreamField directly with `{{ self.content }}` as opposed to looping over it. Passing the child through `force_text` on the way into `format_html_join` seems to fix it - need to figure out why this isn't happening automatically.
