### ISSUE TITLE
creating ui component in wagtail..

### ISSUE THREAD

**Issue by getsiddd** [torchbox/wagtail#1079]
Could anyone tell me the steps of creating a new ui component in wagtail?

**Comment by gasman** [comment]
Hi @getsiddd,
Please use [the Google group](https://groups.google.com/forum/#!forum/wagtail) for support questions.

(You'll need to clarify exactly what you mean by a "ui component" - a new field type in the page editor? A new button for the rich text field? A new item for the main Wagtail menu?)

**Comment by getsiddd** [comment]
i want to write an e commerce plugin for wagtail, please guide me in it's creation

**Comment by SalahAdDin** [comment]
Please, put your question in the google group.
