### ISSUE TITLE
Initialized new wagtail project, static files not loading.

### ISSUE THREAD

**Issue by allthetime** [torchbox/wagtail#1082]
I've gone through the whole set up process, got postgres working, can run the dev server, but none of the style sheets are loading.

I'm attempting to run wagtail on an ubuntu server proxy-passed behind nginx. The site shows up just fine, but if I look in the console there are a few "could not load resource errors"

`Failed to load resource: the server responded with a status of 404 (Not Found)`

`mydomain.com/static/CACHE/css/myproject.d41d8cd98f00.css`

**Comment by kaedroho** [comment]
Hi @allthetime 
Please could you ask this on our Google Group? https://groups.google.com/forum/#!forum/wagtail

Github is mainly for bug reports/feature requests. General support is usually done on the Google Group.

Thanks
