### ISSUE TITLE
Transparent gifs lose transparency when uploaded

### ISSUE THREAD

**Issue by SableWalnut** [torchbox/wagtail#1084]
When uploading gifs to wagtail I expect the transparency to exist after the image has been processed.
The transparency fails to work when the image is displayed after the image has been processed.

1. Upload a gif with transparency to wagtail.   *For example:*
![sedona-logo](https://cloud.githubusercontent.com/assets/10582038/6772988/817f8816-d15d-11e4-9d48-1570fdb40568.gif)
2. Look at the image via the image list.

It will look something like this:
![sedona-logo-changed](https://cloud.githubusercontent.com/assets/10582038/6773009/fa5d5056-d15d-11e4-93c4-eb6221505c5e.gif)

**Comment by kaedroho** [comment]
Which version of wagtail are you using? Do you have Wand and/or Pillow installed?

**Comment by SableWalnut** [comment]
Currently running on wagtail 0.8.6 with Pillow installed.

**Comment by zerolab** [comment]
This will be added to the docs, but you need Wand for proper gif handling. PIL has an issue with this particular image, @SableWalnut

**Comment by SableWalnut** [comment]
Ref: https://github.com/torchbox/Willow/issues/16, I think this is both a wagtail and willow problem.
