### ISSUE TITLE
Page.move doesn't work without the `pos` argument

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/wagtail#1085]
The tests fail too if it's omitted, e.g. if it's changed to `events_index.move(about_us_page)` here:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/tests/test_page_model.py#L350
with this error:
`AssertionError: u'/home/events/' != '/home/about-us/events/`
so the move itself fails silently.

**Comment by kaedroho** [comment]
The move command is behaving correctly here as the default value for "pos" is the next sibling. It just happens to be that the page is moving from that position so nothing appears to happen.
