### ISSUE TITLE
IMAGE_COMPRESSION_QUALITY setting is not passed to Willow

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1089]
Since the move to Willow, the IMAGE_COMPRESSION_QUALITY setting has been ignored when saving .jpg images.

**Comment by kaedroho** [comment]
This is mostly done. Just needs backwards compatibility (I renamed the setting to ``WAGTAILIMAGES_JPEG_COMPRESSION_QUALITY``)
