### ISSUE TITLE
Wagtail cannot install on some RHEL6-based OSes

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#1091]
Because of Wagtail's dependency on libsass, it's impossible to install Wagtail on any OS derived from the base install of Red Hat Enterprise Linux 6. RHEL6 comes with GCC 4.4, which libsass [cannot compile on](https://github.com/sass/libsass#libsass).

I learned this the hard way when trying to use my code shop's chef cookbooks to install Wagtail onto a CentOS 6 vagrant. After many hours of frustration and research, we finally discovered that it's possible to install GCC 4.8 into CentOS 6 by using RPMs from Scientific Linux, but it was a huge hurdle that really should not have been necessary.

Is there anything that can be done about this? We don't use Sass, which made this especially annoying. Could there possibly be a way to install Wagtail without libsass? Issue #35 may be related, since it talks about compiling the existing sass in the repo to CSS for each release.

**Comment by tomdyson** [comment]
Thanks for raising this, @coredumperror. We're aware that libsass is an annoyance for some users - although we hadn't realised that it was so complicated on RHEL installs - and we've decided on a compile-on-release approach which is outlined here:

https://github.com/torchbox/wagtail/issues/35#issuecomment-78029863

@gasman is looking into the specifics and we'd like to get a good solution in the next release if possible. In the meantime, @salvadormrf and other users have workarounds which they may be able to share.

**Comment by SalahAdDin** [comment]
I don't understand, you put two options: non-comiled sass files and compile sass files?
I try much, much time for install libsass in webfaction and the end i could did it :D

**Comment by kaedroho** [comment]
Also, RHEL6 uses Python 2.6 (which is no longer supported by Wagtail from 1.0).

**Comment by coredumperror** [comment]
Ah, good to know. I wasn't aware that Python 2.6 support was being dropped.

Makes sense, though, considering that Django just dropped support for it.

**Comment by gasman** [comment]
Wagtail no longer depends on libsass as of version 1.0.
