### ISSUE TITLE
Vagrant demo fails during install

### ISSUE THREAD

**Issue by dperetti** [torchbox/wagtail#1095]
==> default: /home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
    ==> default:   class MP_NodeManager(models.Manager):

By the way, what about using Docker ?

**Comment by kaedroho** [comment]
This is just a warning, it's fixed in the next release
