### ISSUE TITLE
Inconsistency between DateField model field and the fieldpanel in the admin interface

### ISSUE THREAD

**Issue by jordij** [torchbox/wagtail#1099]
Hi guys,

Just noticed a minor bug with the ways dates are formatted. In one of my page models I have a date field declared as:

```
...
date = models.DateField("Post date", default=date.today())
..
BlogPage.content_panels = [
    FieldPanel('title', classname="full title"),
    FieldPanel('date'),
    ...
```

When I add a new BlogPage through the admin interface:

![screen shot 2015-03-25 at 2 58 25 pm](https://cloud.githubusercontent.com/assets/3124220/6816981/79c77cfc-d2ff-11e4-9357-bb271da6be5d.png)

The default date is properly set but with the wrong formatting (uses / instead of - characters). Because the *page-editor.js* uses the format ```format: 'Y-m-d'``` when working with the datetimepicker, the value is not recognised.

As a workaround I have to override the init method to something like:
````
def __init__(self, *args, **kwargs):
    super(BlogPage, self).__init__(*args, **kwargs)
    self.date = self.date.strftime("%Y-%m-%d")
```

Not sure it's due to my config or wagtail. Maybe someone else's with the same problem?

Cheers!

**Comment by jordij** [comment]
Oh, I think with the changes you've made to https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/widgets.py should be solved as you  force the widget date input with:
```
class AdminDateInput(WidgetWithScript, widgets.DateInput):
    # Set a default date format to match the one that our JS date picker expects -
    # it can still be overridden explicitly, but this way it won't be affected by
    # the DATE_INPUT_FORMATS setting
    def __init__(self, attrs=None, format='%Y-%m-%d'):
```

Will wait for the next release then :)

**Comment by gasman** [comment]
Yep, this is (hopefully...) covered by #1018.

**Comment by bgrace** [comment]
@jordij - as a side note, I think you have a bug here:

    date = models.DateField("Post date", default=date.today())

You probably want:

    date = models.DateField("Post date", default=date.today)

Python defaults are evaluated exactly once, so the default value in this case will end up being the date on which you started the CMS, but if it runs for a year, it will still be that date. See http://effbot.org/zone/default-values.htm

Django helps you out with this by detecting if the argument to `default` is callable (function, lambda, static method). See https://docs.djangoproject.com/en/1.7/ref/models/fields/#default

**Comment by jordij** [comment]
It's all good, thanks!
