### ISSUE TITLE
<MySnippet: such and such> is not JSON serializable - snippets in streamfield

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1102]
Given the following Snippet:

```
class InfographicSnippet(models.Model):
    name = models.CharField(max_length=255, help_text="The name of this infographic, for identification within Wagtail")
    html = models.TextField()

    panels = [
        FieldPanel('name'),
        FieldPanel('html')
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Infographic"
        ordering = ['name']
```

and the following streamfield block

```
from models import InfographicSnippet

class InfographicBlock(FieldBlock):
    field = SnippetChooserBlock(InfographicSnippet)
```

While it's possible to choose a snippet to appear in my streamfield, it's not possible to save the page. I get the error `<InfographicSnippet: Myanmar oil and gas> is not JSON serializable`

**Comment by gasman** [comment]
class InfographicBlock(FieldBlock):
        field = SnippetChooserBlock(InfographicSnippet)

This is invalid - a SnippetChooserBlock is not a field object. You should use `infographic = SnippetChooserBlock(InfographicSnippet)` directly in your streamfield definition instead.
