### ISSUE TITLE
Reordering arrows in streamfield overlap with right-hand labels

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1117]
![screen shot 2015-03-30 at 13 49 42](https://cloud.githubusercontent.com/assets/85097/6896503/f70a40fe-d6e3-11e4-9471-20f205cf0a7e.png)

**Comment by zerolab** [comment]
Work already in progress on the [streamfield-labels](https://github.com/torchbox/wagtail/tree/streamfield-labels) branch

**Comment by davecranwell** [comment]
Technically this is with @gasman to programmatically resolve how to generate headings and when to display them.

**Comment by gasman** [comment]
Fixed in latest round of design changes (5bcd7841da6964dc0b3366b61383c7b28e5a62c1)
