### ISSUE TITLE
System checks for parentpage_types and subpage_types

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1128]
These two settings take a list of model names but if these models don't exist, the admin will crash in certian places. System checks to check that all of the models specified in these settings exist would be really helpful.

**Comment by tmsndrs** [comment]
Additionally, it appears that you can move a page outside of its parentpage_types subpage_types boundaries meaning editors can circumnavigate the specified parent/subpage relationships.

**Comment by gasman** [comment]
That's covered by #638 (mostly implemented, but some awkward edge cases to deal with)
