### ISSUE TITLE
Bug in Documentation Code

### ISSUE THREAD

**Issue by negletios** [torchbox/wagtail#1129]
I think there is a bug in http://wagtail.readthedocs.org/en/v1.0b1/pages/streamfield.html?highlight=blocks#listblock

The code example: 

<pre>
('ingredients_list', blocks.ListBlock(blocks.StructBlock(
    ('ingredient', blocks.CharBlock(required=True)),
    ('amount', blocks.CharBlock()),
)))
</pre>

is missing [] in StructBlock which takes a list. 

It should be something like:

<pre>
('ingredients_list', blocks.ListBlock(blocks.StructBlock([
    ('ingredient', blocks.CharBlock(required=True)),
    ('amount', blocks.CharBlock()),
])))
</pre>

**Comment by kaedroho** [comment]
@negletios Good spot, thanks for reporting!

**Comment by negletios** [comment]
:+1:
