### ISSUE TITLE
Error in Documentation Code

### ISSUE THREAD

**Issue by negletios** [torchbox/wagtail#1130]
I think there some bugs in http://wagtail.readthedocs.org/en/v1.0b1/pages/streamfield.html?highlight=blocks#streamblock

At the first code example:
<pre>
('carousel', blocks.StreamBlock(
    [
        ('image', ImageChooserBlock()),
        ('quotation', blocks.StructBlock([
            ('text', blocks.TextBlock()),
            ('author', blocks.CharBlock),
        ])),
        ('video', blocks.EmbedBlock()),
    ],
    icon='cogs'
))
</pre>

the <b>blocks.CharBlock</b> need some paranthesis at the end <b>blocks.CharBlock()</b> and also the <b>blocks.EmbedBlock()</b> can't be referenced like that since <i>wagtail.wagtailcore.blocks</i> doesn't contain it. Since you are doing the same thing with <i>ImageChooserBlock()</i> and you reference it right it away, I would suggest to do the same thing with <i>EmbedBlock()</i>.

Something like:
<pre>
('carousel', blocks.StreamBlock(
    [
        ('image', ImageChooserBlock()),
        ('quotation', blocks.StructBlock([
            ('text', blocks.TextBlock()),
            ('author', blocks.CharBlock()),
        ])),
        ('video', EmbedBlock()),
    ],
    icon='cogs'
))
</pre>

The same errors occure at the next code example in the documentation, in which you are demonstrating the same code in class based form. Note: Missing parenthesis at the EmbedBlock

**Comment by kaedroho** [comment]
Thanks for spotting! Do you have time to make those fixes and send us a pull request?

**Comment by negletios** [comment]
Sure thing :)
