### ISSUE TITLE
Instagram with HTTPS URL doesn't work.

### ISSUE THREAD

**Issue by drwlrsn** [torchbox/wagtail#1134]
If trying to embed an Instagram URL with 'https://' `get_oembed_provider` returns nothing.

**Comment by kaedroho** [comment]
Fixed by #1135

**Comment by ghostwords** [comment]
Does this need to also handle the www? For example: https://www.instagram.com/p/BDWENjTkpMI/

**Comment by gasman** [comment]
@ghostwords Good catch! Fixed in #2453.
