### ISSUE TITLE
hallojustify plugin for wagtail

### ISSUE THREAD

**Issue by taishizhiqiu** [torchbox/wagtail#1136]
Hello, I find hallojustify plugin(used for text alignment)  disabled in wagtail.

I really need to enable alignment function in the WYSIWYG editor. I tried the following step:

1. add the following js to admin webpage:

       registerHalloPlugin('hallojustify');

    but alignment buttons appear without icons.

2. then I tried to link font-awesome 3 to the admin webpage and found most WYSIWYG icons gone.

So I have the following questions:

1. why don't wagtail enable hallojustify?

2. I know wagtail css has contradiction with font-awesome 3, but is there a workaround to have alignment function with its icons?

**Comment by gasman** [comment]
1. Wagtail is designed to encourage separation of content and presentation, and in general we would want to discourage putting alignment information into page content - that should be handled by the page template, or in front-end CSS. For this reason, we don't provide this option by default. If you're using text alignment to provide different visual styling for different types of content - for example, floating 'pull quotes' - then the StreamField feature coming in Wagtail 1.0 will be a better fit for this. (For more details on this: https://torchbox.com/blog/rich-text-fields-and-faster-horses/)

2. We use a custom icon font containing just the icons used by Wagtail, to reduce download time. I'm not sure if we currently have a good solution for adding extra user-specified icons, and I suspect this is going to come up more and more in future - @davecranwell?

**Comment by davecranwell** [comment]
Regarding adding new icons, I've not tested this yet but it should be possible to include any icon font library required, using the `insert_editor_css` hook (or `insert_editor_js`, but fontawesome only needs CSS). It would obviously but up to the user to ensure the correct class names are in the markup.

**Comment by taishizhiqiu** [comment]
What I don't know is whether wagtail does some tricks on css. I tried in another webpage of the same site and the icon showed up correctly, but it failed to show up in the admin interface.

**Comment by taishizhiqiu** [comment]
Ok, I think I will use streamfield instead.
