### ISSUE TITLE
Adding a child page via the front end

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1140]
Interested to get thoughts on this one. 

Currently the Wagtail UI visible on the front end of the site to editors allows you to add a sibling page to the page you are currently viewing (along with editing the current page and accessing the Wagtail dashboard). 

This means if you're at the end of the tree branch you can't add a child page via this interface. I know some of our clients prefer to navigate through the front end of the site rather than through the explorer ui but this presents a problem for their workflow. 

Option 1. Change the 'add' button so that it adds a child page. This means you can still add siblings but you would have to add them as child pages of the parent. This could be disruptive to editors who are already familiar to with the existing workflow. We could make the label more explicit by changing it to 'add child page' but my experience is that editors don't always understand the parent/sibling/child terminology (though it is used elsewhere in the ui already). I know you can hover on the button for help text but generally people won't wait long enough to realise this. 

Option 2. Add an additional stage to the workflow that allows you to specify adding either a sibling or child.

**Comment by zerolab** [comment]
Hi Tom,

This is what #728 tackled. Can you test the latest master, please?

**Comment by tmsndrs** [comment]
Apologies. Thought I was on the latest release. I'll take a look.

**Comment by zerolab** [comment]
@tmsndrs did you get a chance to test the latest release?

**Comment by gasman** [comment]
Addressed by #728.
