### ISSUE TITLE
Documentation of hooks

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1141]
Unless I've missed it, or unless the search index on readthedocs is out of date, we're missing a single-pace list of all the hooks in one place.

A list of hooks is a great reference for developers, but it also gives anyone evaluating Wagtail over other CMS a good metric for comparison.

**Comment by kaedroho** [comment]
Hi @davecranwell, this has been added in the latest docs: http://docs.wagtail.io/en/latest/reference/hooks.html

**Comment by davecranwell** [comment]
My mistake, ta.
