### ISSUE TITLE
DateBlock Bug

### ISSUE THREAD

**Issue by negletios** [torchbox/wagtail#1142]
I have created a test HomePage: 

<pre>
# Homepage
class HomePage(Page):
    body = StreamField([
        ('date', blocks.DateBlock()),
    ])

HomePage.content_panels = Page.content_panels + [
    StreamFieldPanel('body'),
]
</pre>

Pick a date and save it as draft. When the page is saved, try to saved it again as draft. It throughs a message error that the date field is missing. 

Same thing is happening no matter what field I am trying to change after the "first draft save".

**Comment by tomdyson** [comment]
@bertrandbordage, could you look at this, please?

**Comment by BertrandBordage** [comment]
@tomdyson OK, I just need 15 minutes to discover that new StreamField, what it does and how it’s made :)

**Comment by tomdyson** [comment]
@BertrandBordage you might need more than 15 minutes... start with https://torchbox.com/blog/rich-text-fields-and-faster-horses/ and http://docs.wagtail.io/en/v1.0b1/pages/streamfield.html

**Comment by BertrandBordage** [comment]
Yeah, that’s indeed bigger than I thought… I’ll make a first review of #1109 then spend the evening on this issue to have a first good dive in Wagtail’s development!

**Comment by BertrandBordage** [comment]
@negletios I can’t reproduce the bug. I tried using 1.0b1 & master@3fcf04f8a3af323482f85c8657e7277af0215961, Django 1.7.7, Python 2.7, Chrome 41 & Firefox 36. Which versions are you using?

Has someone else reproduced the bug?

**Comment by negletios** [comment]
I can see the bug on Python 3.4.2, Django 1.7.7 and Wagtail @ streamfield-label branch

**Comment by zerolab** [comment]
@negletios can you test with the latest master?

**Comment by negletios** [comment]
I just did and it works fine

**Comment by BertrandBordage** [comment]
I tested using Python 3.4.0, Django 1.7.7 and wagtail@streamfield-labels. Everything works fine given the exact model you provided.
I also merged streamfield-labels into master: works as well.

This issue can be closed and labeled as invalid IMHO.
