### ISSUE TITLE
Add a system check to reject invalid block names in StreamField

### ISSUE THREAD

**Issue by negletios** [torchbox/wagtail#1154]
On wagtail==1.0b1,  python==3.4.2 and django==1.7.7 when I write the following:

<pre>
class ServicePage(Page):
    body = StreamField([
        ('Rich text', blocks.RichTextBlock()),
        ('Image', ImageChooserBlock()),
    ], blank=True)

ServicePage.content_panels = [
    StreamFieldPanel('body'),
]
</pre>

and I run the migrations everything seems to be fine. When I go to the actual page (backend) and try to add a Rich Text field, it doesn't retrieve it. Same thing happens in every block type.  

The problem is the space at the (<b>'Rich text'</b>, blocks.RichTextBlock()).

**Comment by zerolab** [comment]
Hi @negletios,

'Rich text' should really be "rich_text' -- that is the field machine name, not a label. Think of StreamField as a model with special field definitions.

As such, your code should look like:

```python
class ServicePage(Page):
    body = StreamField([
        ('rich_text', blocks.RichTextBlock(label="Rich text")),
        ('Image', ImageChooserBlock()),
    ], blank=True)

ServicePage.content_panels = [
    StreamFieldPanel('body'),
]
```

Read about the optional arguments that basic block types accept at http://docs.wagtail.io/en/v1.0b1/pages/streamfield.html#basic-block-types

**Comment by negletios** [comment]
HI @zerolab , thanks for you response.

I just saying that I expected Wagtail to throw an error while I was doing the migrations :)

**Comment by zerolab** [comment]
Will leave this it to @gasman, as the architect, to chip in on the expected behavior.

**Comment by kaedroho** [comment]
Might be something a system check could help with

**Comment by gasman** [comment]
Agreed. This isn't a bug - it's failing because the name is invalid - but it would be good to add a system check to make this throw an explicit error.
