### ISSUE TITLE
Nav and content wrappers: Figure out which visual element is on top 

### ISSUE THREAD

**Issue by JoshBarr** [torchbox/wagtail#1156]
When working on the menu today, I noticed we're often swapping the z-index with the content panel, to get one showing up above the other.

In the first example, the content wrapper is on top: 

![screen shot 2015-04-04 at 11 08 59 am](https://cloud.githubusercontent.com/assets/1715456/6989719/04065e7e-dabc-11e4-9cfa-5cac40d9e6fa.png)

And in this example, the nav wrapper is on top: 

![screen shot 2015-04-04 at 11 09 09 am](https://cloud.githubusercontent.com/assets/1715456/6989721/1a5e41be-dabc-11e4-8284-3b1320284936.png)

I think it would be helpful to land on whether the nav or the content panel is going to be in front. It might mean some small design tweakage, though. If the content area is always going to be in front, the nav area could be a 'drawer' that pushes the content panel over, similar to the mobile behaviour: 

![screen shot 2015-04-04 at 11 11 43 am](https://cloud.githubusercontent.com/assets/1715456/6989754/7734e442-dabc-11e4-8a47-6d3dfe9b5e0e.png)

However, this would mean shifting lots of pixels around the screen and isn't going to be super performant. I'd suggest we think of the nav wrapper always being in front of the content area. What do you reckon?

**Comment by davecranwell** [comment]
I think this is mostly resolved now, right? There's certainly no swapping going on any more.

**Comment by gasman** [comment]
Yep, looks like the menu bar is consistently on top now.
![screen shot 2015-10-07 at 10 37 11](https://cloud.githubusercontent.com/assets/85097/10334018/66e6dcd4-6cdf-11e5-9dce-76b5b57861c1.png)
