### ISSUE TITLE
Site field should be editable in Redirects wagtail admin

### ISSUE THREAD

**Issue by excieve** [torchbox/wagtail#1163]
`Redirect` model contains a `site` field, which is used in the middleware to decide if current site is affected by it. However, it's not possible to edit this field in the wagtail admin - it's not exposed. In fact, when user adds a redirect it stores current site (i.e. the one wagtail admin is located) in this field, which is an undesirable behaviour in case there are several sites.

So I believe it would be better to allow editing this field instead of always assigning it automatically.

**Comment by tomdyson** [comment]
Thanks for this, @excieve. You're right. Do you have time to submit a PR?

**Comment by excieve** [comment]
Yeah, would be happy to.
