### ISSUE TITLE
submit for moderation - email notification to moderators group members

### ISSUE THREAD

**Issue by lboc80** [torchbox/wagtail#1182]
I noticed that in the docs it's clearly mentioned that an email is sent when a page is submitted for moderators:

***Email Notifications***
*WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = ’wagtail@myhost.io’*
*Wagtail sends email notifications when content is submitted for moderation, and when the content is accepted or rejected. This setting lets you pick which email address these automatic notifications will come from. If omitted, Django will fall back to using the DEFAULT_FROM_EMAIL variable if set, and webmaster@localhost if not.*

I tried locally, and an email is sent, but to the administrator users. 
Is it possible to change this behaviour and add more control over it? I need an email to be sent to the moderators users.
The only way that I noticed for now is to override the *save_revision* method in the ***Page*** model

Thanks
L

**Comment by gasman** [comment]
Query moved to google group.
