### ISSUE TITLE
staticsitegen command fails for documents since commit 918f286

### ISSUE THREAD

**Issue by pcraston** [torchbox/wagtail#1183]
The staticsitegen command uses django-medusa to generate a static version of the wagtail site. Since commit 918f286eeac567ec460d786a6cfd3dd4d95185a6 wagtail uses StreamingHttpResponse to return Documents, which causes medusa to fail as it simply saves response.content to disk (https://github.com/ctxis/django-medusa/blob/master/django_medusa/renderers/disk.py#L56) and StreamingHttpResponse has no content attribute.

I've pushed a fix to our fork of django-medusa (https://github.com/ctxis/django-medusa) and submitted a pull request (https://github.com/mtigas/django-medusa/pull/20). It iterates over the streaming_response attribute if response is streaming and saves the chunks to file, otherwise it uses response.content.

Until this PR has been merged, do you think it's worth adding a note to the staticsitegen section of the wagtail docs?

**Comment by taishizhiqiu** [comment]
Yes, staticsitegen fails using release 1.0b1 and I think a note is necessary.

**Comment by tomdyson** [comment]
Thanks for raising this, @pcraston. We'll look at a fix; in the meantime could you do a PR for a note in the docs?

**Comment by taishizhiqiu** [comment]
I downloaded the zip from (https://github.com/ctxis/django-medusa) and copy the module to a fresh started project mysite. But I still get the following error:
```
Chongs-MacBook-Air:mysite chongwang$ python manage.py staticsitegen
Skipping app 'mysite'... (No 'renderers.py')
Skipping app 'django.contrib.admin'... (No 'renderers.py')
Skipping app 'django.contrib.auth'... (No 'renderers.py')
Skipping app 'django.contrib.contenttypes'... (No 'renderers.py')
Skipping app 'django.contrib.sessions'... (No 'renderers.py')
Skipping app 'django.contrib.messages'... (No 'renderers.py')
Skipping app 'django.contrib.staticfiles'... (No 'renderers.py')
Skipping app 'compressor'... (No 'renderers.py')
Skipping app 'taggit'... (No 'renderers.py')
Skipping app 'modelcluster'... (No 'renderers.py')
Skipping app 'wagtail.wagtailcore'... (No 'renderers.py')
Skipping app 'wagtail.wagtailadmin'... (No 'renderers.py')
Skipping app 'wagtail.wagtaildocs'... (No 'renderers.py')
Skipping app 'wagtail.wagtailsnippets'... (No 'renderers.py')
Skipping app 'wagtail.wagtailusers'... (No 'renderers.py')
Skipping app 'wagtail.wagtailsites'... (No 'renderers.py')
Skipping app 'wagtail.wagtailimages'... (No 'renderers.py')
Skipping app 'wagtail.wagtailembeds'... (No 'renderers.py')
Skipping app 'wagtail.wagtailsearch'... (No 'renderers.py')
Skipping app 'wagtail.wagtailredirects'... (No 'renderers.py')
Skipping app 'wagtail.wagtailforms'... (No 'renderers.py')
Found renderers for 'wagtail.contrib.wagtailmedusa'...
Skipping app 'core'... (No 'renderers.py')
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/chongwang/Workspace/test/mysite/django_medusa/management/commands/staticsitegen.py", line 17, in handle
    r.generate()
  File "/Users/chongwang/Workspace/test/mysite/django_medusa/renderers/base.py", line 69, in generate
    self.render_path(path)
  File "/Users/chongwang/Workspace/test/mysite/django_medusa/renderers/base.py", line 65, in render_path
    raise NotImplementedError
NotImplementedError
```
environment:
python 2.7.9
wagtail 1.0b1
django 1.7.7

**Comment by davecranwell** [comment]
We've agreed to investigate ways to make work without medusa patch.

**Comment by kaedroho** [comment]
This can now be worked around by setting the ``SENDFILE_BACKEND`` setting to ``sendfile.backends.simple``.

https://github.com/torchbox/wagtail/blob/40092e18526d59c8ca0966743de7f93d14a8304c/docs/contrib/staticsitegen.rst#installing-django-medusa
