### ISSUE TITLE
'Content', 'Promote', 'Settings' tab labels need i18n

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1185]
gettext strings are currently missing from https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L717-722

**Comment by kaedroho** [comment]
Fixed in: https://github.com/torchbox/wagtail/pull/1197

**Comment by kaedroho** [comment]
Fixed by: d397dd1ef49e63b5d0d3a279ad03393c06f057a6
