### ISSUE TITLE
Add relevant {% block title %} content to 404 and 500 pages 

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1187]
As part of the core 404 and 500 pages. 

The current <title> template variables don't get completed for 404 or 500 pages as part of cores base.html file. 

<title>{% block title %}{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}{% endblock %}{% block title_suffix %}{% endblock %}</title>

Neither self.seo_title or self.title exist for 404s or 500s so something relevant should be output instead. I would suggest something containing the response code so that it's easier to track in GA but there is some argument for not presenting the complexity of response codes to users (even if it is just in the page title). Personally I don't agree with this argument. 

I can't think of an argument for this to take place on a project by project basis. A developer could always change the content but something should get output as standard.

**Comment by kaedroho** [comment]
This is one for ``wagtail-cookiecutter`` (https://github.com/torchbox/wagtail-cookiecutter). Could you repost this there?

**Comment by gasman** [comment]
@kaedroho Wouldn't this change also apply to https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/core/templates/404.html?

**Comment by kaedroho** [comment]
Weren't we going to get rid of that template soon? https://github.com/torchbox/wagtail/pull/1109

**Comment by gasman** [comment]
Ah - fair enough. I didn't realise we were dropping the 404 template there - the object of that exercise was to remove any 'opinionated' elements such as the Vagrant setup, and rolling it back to the point of not even having a 404 template seems a bit extreme to me. But that's a separate discussion!
