### ISSUE TITLE
Admin search fails with unicode characters

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1192]
If you search for a string containing unicode characters you get an internal server error. 

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 7: ordinal not in range(128)

I guess it should either accept unicode or at least validate against it?

**Comment by kaedroho** [comment]
Looks like a bug to me. Do you have any more traceback? (would be useful to know where this error is being raised from)

This is likely to be something that only affects Python 2 users

**Comment by tmsndrs** [comment]
I've forwarded you the report @kaedroho.

**Comment by kaedroho** [comment]
Thanks @tmsndrs. This doesn't look like a Wagtail bug.

The particular site this is happening on has a template context processor to calculate the urls of the current page in different languages. (eg, it turns /admin/ into /en/admin/ and /fr/admin/). Theres a call to urllib in here which seems to be crashing.
