### ISSUE TITLE
Sites need a title/name field

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1194]
Site hostnames are often output on the front end when generating Open Graph tags, and other places where absolute URLs or "official urls" of the site are needed.

Additionally the "friendly" name of the site is also required for OG tags or `title` tags: `<title>My page about things | My Site</title>`. At the moment we have to hard-coded this friendly site name, meaning templates can't be reused as easily.

It would be good if the `Sites` object were updated to include a human friendly name field for the site. Obviously the `WAGTAIL_SITE_NAME` is insufficient if the installation is hosting multiple domains.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
Man, please, review this, you can see in this pic how see the sitename in the login page:
![cambiassitename](https://cloud.githubusercontent.com/assets/5034215/9232249/4847560a-40f2-11e5-8ec9-ec77cec4f40b.png)

**Comment by timorieber** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Implemented in #1814.

**Comment by SalahAdDin** [comment]
Thank you very much, Did you put this in the documentation?
