### ISSUE TITLE
Feature request: Add markdown support

### ISSUE THREAD

**Issue by ckcollab** [torchbox/wagtail#1199]
The WYSIWYG editor is difficult to use, it would be so awesome to be able to bust out some markdown instead!

I'm not familiar with the Wagtail codebase, some guidance on how best to accomplish this would be super helpful. My plan is to add an option in `SETTINGS` to change all WYSIWYG forms to use markdown instead, but I'm not sure if this will break other things or if this is even possible with how Wagtail works.

**Comment by gasman** [comment]
Any reason why you couldn't just use a plain `TextField` in your model, and apply the Markdown transformation within the template (something like `{{ self.body|markdown }}`)?

I guess there are additional questions about how you'd represent things like internal page links and images, but I think it's quite likely that this could be implemented without any changes to Wagtail core.

**Comment by ckcollab** [comment]
Thanks for the advice!
