### ISSUE TITLE
Wagtail should optimize images better

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1203]
We run our new launches through Google Page Speed, which is frequently alerting us to images which could be compressed more. According to the tool there are **lossless** savings possible in images created by wagtail, of between **50-80%** quite a lot of the time, which seems rather high.

Is wagtail able to improve it's image compression during generation? 

While this kind of thing _can_ be handled by third party software like mod_pagespeed, this feels like an inefficiency, a bug of sorts, and not something the implementer should need to work around.

**Comment by balazs-endresz** [comment]
It might not help with lossless compression but `IMAGE_COMPRESSION_QUALITY` was just added back recently: https://github.com/torchbox/wagtail/blob/master/CHANGELOG.txt#L283

**Comment by balazs-endresz** [comment]
Sorry, it's actually `WAGTAILIMAGES_JPEG_QUALITY` now.

**Comment by davecranwell** [comment]
Is that documented? Readthedocs search seems to be down but I can't find that in the docs manually either.

**Comment by gasman** [comment]
Improving *lossless* compression would be the responsibility of Willow, and is covered by https://github.com/torchbox/Willow/issues/10. Issues around JPEG compression level are covered by #908 and #1205.

**Comment by SalahAdDin** [comment]
Needs more documentation :+1:

**Comment by casey-chow** [comment]
Since this issue was closed, https://github.com/wagtail/Willow/pull/39 was merged, which enables PNG and JPG optimization. Are there any updates on the integration here?

**Comment by scythargon** [comment]
+1
