### ISSUE TITLE
JS error in stream.js when attempting to add content with StreamField

### ISSUE THREAD

**Issue by ababic** [torchbox/wagtail#1207]
Hi folks.

Are there any known issues with the JS for StreamField? I've created a custom StreamBlock by extending blocks.StreamBlock, and when used with a StreamField on a simple page model, I get the initial menu to a allow a block type to be selected (along with correct icons and labels), but selecting any block to begin adding content raises a JS error :(

The Chrome console is telling me that the error is occuring at line 75 of  **stream.js**:

    Uncaught TypeError: Cannot read property 'initializer' of undefined

I've tried with a much simpler StreamBlock definition too (with just a couple of CharBlocks), but the error is still happening.

Possibly related... I'm also seeing a JS warning from line 11 of **rangy-core.js**:

     'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

It could well be to do with my implementation, but this is my first Wagtail project, and the setup is all pretty vanilla. Any help would be greatly appreciated!

Thanks,
Andy

**Comment by gasman** [comment]
Hi @ababic,
I've not seen any issues like that, and I can't immediately how it would arise... The JS error would imply that a JS definition is missing for the particular block type you're trying to add, but those definitions are generated from the same list that produces the menu itself - I suspect it's something like an invalid character in the block name. Please can you post your StreamBlock definition?

The rangy-core.js warning is unrelated - that comes from third-party code used in the rich text editor, and shows up all the time.

**Comment by ababic** [comment]
My apologies @gasman. It seems that the error was occuring because I was using *FieldPanel* to represent the field in content_panels, rather than the newly introduced *StreamFieldPanel*. 

Thank you for getting back to me, though. Much appreciated!

**Comment by timheap** [comment]
I also had this issue when I started using StreamFields. The StreamField widget *almost* seems to work while using a FieldPanel, which confused the hell out of me! Having a warning about this in the console would be nice, although I am not sure how to go about doing this.

**Comment by litchfield** [comment]
Yeah me too, @timheap @ababic a sanity check/warning on this would be nice huh?

**Comment by coredumperror** [comment]
I just ran into this problem in my own project. Thanks so much for explaining how you fixed it, guys! I would have probably wasted hours pulling my hair out over this.
