### ISSUE TITLE
Locally hosted video and audio

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1229]
Just wondering what people's thoughts are on how this would be managed by Wagtail. I presume you can add it to documents (if it's less than 10mb without changing the upload limit) but personally I don't see video and audio as 'documents' as such. Could we have an additional 'media' library? Could we rename documents to something more accurate to cover different file types and add some sort of filter for file types? Is there any way that Wagtail could help with issues around compression etc?

**Comment by davecranwell** [comment]
This can be quite a sprawling topic. The hosting/bandwidth requirements are one big consideration. The duplication of more fully featured third party video management offerings e.g zencoder.com is another. Then there's playback which is best handled by third party software (flowplayer.org).

We haven't discussed it (even outside Wagtail) for a while, but it usually tends to head in the direction of "why reinvent the wheel?" and suggesting offloading to third parties.

**Comment by tmsndrs** [comment]
I understand and would tend to agree but we have clients asking for this type of thing which, as far as I know if harder to achieve using third party services?  http://shorthand.pilots.bbcconnectedstudio.co.uk/state-of-terror/

**Comment by gasman** [comment]
See https://github.com/torchbox/wagtail/issues/907#issuecomment-70271268 . Doing video hosting *properly* would be a Wagtail-scale project of its own, and would be better suited as an external Wagtail add-on.

**Comment by tomdyson** [comment]
As discussed with @tmsndrs just now, an easier solution (without transcoding, thumbnail generation etc) could be a video snippet type. It would need progressive upload and ideally an S3 storage backend.
