### ISSUE TITLE
RoutablePageMixin doesn't work if included after Page

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/wagtail#1241]
When defining a `Page` subclass then `RoutablePageMixin` works only if it's included before `Page`:

So this works:
`class EventPage(RoutablePageMixin, Page):`

but this one yields a 404:
`class EventPage(Page, RoutablePageMixin):`

**Comment by gasman** [comment]
That's because RoutablePageMixin's `serve` method needs to override the default one provided by Page. Is this a problem?

**Comment by balazs-endresz** [comment]
Well, I've just realised that this is how MRO works in python, so there's technically nothing wrong with it but it's easy to miss (e.g. it's in the wrong order in the example on #764 too). Could we perhaps call `RoutablePageMixin.serve` from `Page.serve` if it's a `RoutablePageMixin` class?

**Comment by gasman** [comment]
I'm absolutely against giving RoutablePage any special-case treatment in wagtailcore, as per the reasoning in https://github.com/torchbox/wagtail/issues/1012#issuecomment-75143188. If this is catching people out regularly, then we could add a note to the docs to point out that the order is significant, or perhaps add a system check on startup that outputs a warning if they're in the wrong order.
