### ISSUE TITLE
Move title/slug validation out of wagtailadmin/views/pages.py

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1245]
Currently, the page create/edit views perform some ugly monkey-patching of the form object returned by the edit handler framework, to insert some extra validation specific to the Page model. In
https://github.com/gasman/wagtail/commit/b8711ff8b42f0c2e81d56d816ee31479a7fba473 I made a start on moving these validators to a dedicated `PageModelForm` class, thinking this was necessary in order to fix #1216. It turns out that it wasn't - but it would be good to clean up that code anyway.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Fixed in #1867
