### ISSUE TITLE
Wagtail fonts don't all support non-latin alphabets

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtail#1248]
Fonts used by Wagtail doesn't look the same for all languages. As example, take a look at how it looks like when mixing english words and russian:
![screenshot from 2015-04-29 16 19 33](https://cloud.githubusercontent.com/assets/121781/7391762/1420eb2e-ee8c-11e4-8f12-0fa91fb573a8.png)
Note "email" between other words.
For example, Ubuntu font looks the same for all languages!

**Comment by davecranwell** [comment]
The font is Open Sans, which I believe should support the Russian alphabet https://www.google.com/fonts/specimen/Open+Sans however comparing the size of the font files in the repo, against a fresh download of Open Sans from Google Fonts with all the extended characters enabled, it suggests we're not currently included the necessary Cyrillic characters. They were probably omitted originally to save on file-size.

**Comment by MechanisM** [comment]
Also note that field labels are not translated somehow, but I'm submitted russian translation with 100% coverage. Didn't checked out if these words are actually not enabled for translation or translations didn't synced yet.

**Comment by gasman** [comment]
Translations don't get synced with Transifex automatically - we need to pull them manually. We'll do this before the 1.0 release.

**Comment by davecranwell** [comment]
Hi @MechanisM there's another custom text font used in the page editor interface: Bitter. It's used for any charFields where you've applied the "title" or "full" `classnames` configurations in your model (See http://wagtail.readthedocs.org/en/latest/pages/editing_api.html?highlight=title#defining-panels)

As far as I can tell this font is _not available_ with cyrillic characters, which is a bit of a show-stopper. It would really help if you could try out `title` or `full` and screenshot the result with Russian characters. 

Its only while procuring the cyrillic version of Open Sans that I've realised Bitter might not be international enough for use in Wagtail.

**Comment by davecranwell** [comment]
A close alternative to Bitter, one of only 5 serif fonts that Google Fonts provides with Extended Cyrillic characters, is https://www.google.com/fonts/specimen/Roboto+Slab

I'm tempted to remove the Serif font completely, given how little it's used. It could still be added back to the page editor interface on a per-implementation basis with wagtail's hooks if so desired.

**Comment by davecranwell** [comment]
Merged in e08e35d + parents.
