### ISSUE TITLE
AdminAutoHeightTextInput doesn't auto-height on page load

### ISSUE THREAD

**Issue by nimasmi** [torchbox/wagtail#1249]
`wagtailadmin.widgets.AdminAutoHeightTextInput` appears now to be the new default widget for `django.db.models.TextField`. It auto-heights when you type into it

![screen shot 2015-04-29 at 15 56 55](https://cloud.githubusercontent.com/assets/1473980/7393980/bbafebaa-ee88-11e4-83d5-01996cb5000a.png)

…but on reloading the page, the auto-heighting appears not to occur. This is four rows of text after reloading the page:

 ![screen shot 2015-04-29 at 15 57 14](https://cloud.githubusercontent.com/assets/1473980/7393979/bbaeeb4c-ee88-11e4-8f25-477b0f84eac9.png)

Three rows, with the exact same widget height:

![screen shot 2015-04-29 at 15 55 51](https://cloud.githubusercontent.com/assets/1473980/7393982/bbb10ac6-ee88-11e4-9892-1b2df7c6176a.png)

But two rows with a reduced widget height:

![screen shot 2015-04-29 at 15 52 37](https://cloud.githubusercontent.com/assets/1473980/7393984/bbb511a2-ee88-11e4-978e-a86c3a133465.png)

@davecranwell suggested an off-by-one error, which seems reasonable, given the slightly different heights above.

**Comment by gasman** [comment]
My guess is that the height adjustment is being applied before the CSS has loaded, so it's not taking the margins into account. Maybe hooking it into the real document.onload event rather than the jquery 'ready' one would fix it...

**Comment by davecranwell** [comment]
:+1: @gasman

**Comment by gasman** [comment]
Fixed in #1274
