### ISSUE TITLE
Image feature detection fails on 1.0b1 with "I/O operation on closed file"

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1256]
As reported here: https://groups.google.com/d/msg/wagtail/5zSvx5g_vhM/LlrxA9Y73ncJ

**Comment by kaedroho** [comment]
I'll also see if I can add a test or two for feature detection to hopefully catch these sort of problems in the future

**Comment by kaedroho** [comment]
This was caused by ``get_willow_image`` (used by feature detection) closing the file after the feature detection was done, causing an error to be raised when Django tried to save it.

Fix: https://github.com/torchbox/wagtail/pull/1273
