### ISSUE TITLE
Using wagtail with Jinja

### ISSUE THREAD

**Issue by dchaplinsky** [torchbox/wagtail#1259]
That's not an issue but more like a proposal to extend documentation.

I've tried to integrate wagtail to the project where I'm already using jinja2 (via django_jinja lib).
That's how my Page model looking now:
```python
class StaticPage(Page):
    body = RichTextField()
    template = "cms_pages/static_page.jinja"

    def get_context(self, request, *args, **kwargs):
        return {
            'page': self,
            'request': request,
        }
```
Key things here is to point to a specific template (with .jinja extension) because by default wagtail is using .html template which is rendered using django, not jinja.

Another thing is to use `page` instead of `self` as self is used by jinja to refer to it's own template object.

Hope this will help someone.

**Comment by davecranwell** [comment]
Hi @dchaplinsky we'd welcome you create a Pull Request to add help to the documentation on how to integrate with jinja2. Since this Github Issue isn't something we can resolve - rather it's just here for reference, I'll close it - the documentation is the best place for this.

**Comment by nilssolanki** [comment]
@dchaplinsky did you manage to get `wagtailimages_tags` and the like to work with `django_jinja`?
I haven't had any luck so far. And since there is no load statement, I'm not sure how to do it.

Is this part of the `context_processors` or the `extensions` options?

**Comment by arthurio** [comment]
@nilssolanki I just made some jinja2 extensions that might help you: https://github.com/minervaproject/wagtail-jinja2
It's my first time building extensions so all feedback is welcome.
