### ISSUE TITLE
LoaderError: Cannot find backend that can load this image file

### ISSUE THREAD

**Issue by asmaps** [torchbox/wagtail#1262]
There seems to be a bug in python 3.4's `imghdr.what()` that causes Photoshop 3.0 jpgs to not be recognized as jpg, which causes willow to raise an exception (see torchbox/willow#12). 

This bug shows that if you upload an unsupported image big parts of wagtail crash with 500 which maybe should be prevented: All places where the "broken" image gets loaded => Image Overview, Image selection, every page that uses the image, etc make the CMS close to unusable

Wagtail does not catch the exception raised here:
https://github.com/torchbox/Willow/blob/master/willow/image.py#L140. This get's called in wagtail here: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/models.py#L102

I am using python 3.4 and can provide a full traceback if needed.

Example image:  
![deckblatt_neurofit2014_febjerk](https://cloud.githubusercontent.com/assets/2535908/7445496/e696b318-f1b6-11e4-8e60-0ab5ab3a9905.jpg)

**Comment by kaedroho** [comment]
This should be fixed by: https://github.com/torchbox/Willow/commit/d60dc40d2578ef4ddd5b6c62e677290291c874da

Will need to update Willow in Wagtail.

**Comment by asmaps** [comment]
I still think it is also a bug in wagtail. this exact problem seems to be fixed, but if I upload any other unsupported image format most parts of the wagtail installation crash, which is imho a bug...

**Comment by emullaney** [comment]
I'm hitting this bug today with a JPG file. Not sure if it's photoshop, because my client created it.

@asmaps how are you getting around this bug for now?

**Comment by kaedroho** [comment]
I've just pushed Willow 0.2.1 which includes the fix for this bug

**Comment by emullaney** [comment]
Thanks @kaedroho!
