### ISSUE TITLE
Need a mechanism to define custom validators on page edit forms

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1291]
As requested here (although in this particular case we would ideally [fix the validation to happen as standard](https://github.com/torchbox/django-modelcluster/issues/28), negating the need for a custom validator): https://groups.google.com/d/msg/wagtail/zDe5ocpL5xA/_If71AkzCmkJ

There's some ongoing work to clean up the page-model-specific validation on title / slug / publish date / expiry date (#1217, #1245) but even with this completed, the validation mechanism will still be locked away between wagtailadmin/views/pages.py and edit_handlers.py. We should implement a way to specify additional validation on a per-page-model basis - possibly with a hook, or by allowing developers to pass in a custom ModelForm subclass.

**Comment by gasman** [comment]
Another use-case for being able to override the auto-generated ModelForm - overriding the default form field, e.g. to pass in a callable choices list: https://groups.google.com/d/msg/wagtail/C-RXpmTfFyw/lMXFHklXVswJ

**Comment by gasman** [comment]
Fixed in #1867

**Comment by ghostwords** [comment]
Could I override models.URLField validation in Wagtail 1.4.1, say to replicate behavior in #917?

**Comment by dentemm** [comment]
The unique_together constraint requested for the m2m relationship can be solved by adding a unique=True attribute to the ForeignKey field.

```
class FocusAreaCaseStudy(Orderable, models.Model):
    focusarea = models.ForeignKey(FocusArea, related_name="+", unique=True)
    page = ParentalKey(CaseStudyPage, related_name='focus_areas')
    panels = [
        FieldPanel('focusarea'),
    ]

    class Meta:
        unique_together = ("focusarea", "page")
```

**Comment by jordmantheman** [comment]
@dentemm Why does that work? It seems like you'd violate unique constraints on focus areas eve nif the pages are different.
