### ISSUE TITLE
XSS Image filename is interpreted as HTML

### ISSUE THREAD

**Issue by salvadormrf** [torchbox/wagtail#1293]
When  uploading an image called "test\<h1>test.invalidextention", the error message will interpret the HTML. Same thing when uploading a valid image.

Reported by: 
Daniel Fabian from the Google Security Team

**Comment by tomdyson** [comment]
Thanks, @salvadormrf (and Daniel).

**Comment by tomdyson** [comment]
@salvadormrf are you happy with this fix?

**Comment by salvadormrf** [comment]
@tomdyson We were using a different solution using "document.createTextNode" but we may use this one. Thanks!

**Comment by timheap** [comment]
`document.createTextNode()` is a much more reliable solution. By definition, anything created by `document.createTextNode()` is text, so injecting HTML is simply not possible.

**Comment by SalahAdDin** [comment]
:+1:
