### ISSUE TITLE
Custom Template Tags do not function in Preview mode

### ISSUE THREAD

**Issue by emullaney** [torchbox/wagtail#1305]
I added a custom template tag (https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/), and had to add some code around it in order to prevent this error:
AttributeError at /admin/pages/16/edit/preview/ 'FakeQuerySet' object has no attribute 'distinct'

The custom tag I created, requires hasattr() in order to avoid this error. So now, this custom template tag I created only runs in Live mode, not in Preview mode. 

Here's the code, including the fix I implemented to shut off the tag during Preview mode:

```python
from django import template

register = template.Library()

@register.filter
def make_unique(value, unique_var): 
    """Make the queryset unique by unique_var, sort by unique_var"""
    if hasattr(value, "distinct"): # Need to check so that this does not break in Preview mode in Wagtail
        return value.distinct(unique_var).order_by(unique_var)
    else:
        return value
```

**Comment by kaedroho** [comment]
Thanks for reporting @emullaney 

The ``django-modelcluster`` s ``FakeQuerySet`` class (used in previews) is missing a few methods. I've created a ticket there https://github.com/torchbox/django-modelcluster/issues/29

**Comment by gasman** [comment]
Closing as this is covered by https://github.com/torchbox/django-modelcluster/issues/29
