### ISSUE TITLE
wagtail themes

### ISSUE THREAD

**Issue by BigaDev** [torchbox/wagtail#1313]
First of all, I would thank all who contributing in wagtail really impressive work !

I have a question, are there marketplaces for wagtail UI themes ?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by davecranwell** [comment]
Hi @BigaDev questions not pertaining to specific parts of the codebase are better suited to the wagtail support Google Group https://groups.google.com/forum/#!forum/wagtail

**Comment by SalahAdDin** [comment]
@BigaDev Man, i see that the wagtails scss structure enable us that change all static files and then compile it, is enough that change the variable colors in variable.scss and we can change all them.

If you want work with me we can create some themes and publish it as third party works.

**Comment by robmoorman** [comment]
This might be helpful https://github.com/moorinteractive/wagtail-themes

**Comment by SalahAdDin** [comment]
@robmoorman How works these package? Is easy change the `wagtail` admin stiles compiling the proper assets, so, i don't understand your package.

**Comment by robmoorman** [comment]
@SalahAdDin in case of styling the Admin interface, then this would not fit your requirements. For more frontend related theming, it can be useful, especially in a multisite/multitenant setup (even different Admin templates per site would be possible).
