### ISSUE TITLE
update_index command will fail if a page is updated while it is rebuilding an Elasticsearch index

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1320]
The update_index command first clears the index, including all data and mappings. The index is then rebuilt one model at a time. For each model, a new mapping is installed then the data is added.

Unfortunately, it appears that if a page is updated before it's new mapping is installed, Elasticsearch will make up a mapping for it that will conflict with it's real mapping. Causing the update_index command to crash with a ``MergeMappingException`` when the real mapping gets installed.

Possible solutions:
- Install the new mappings as soon as possible after reseting the index
- Make update_index work on a different index, then rename when it's ready (would mean that the search would keep working during an index rebuild as well)
- Prevent the signal handler from adding documents when no mapping exists in elasticsearch for the model

**Comment by tomdyson** [comment]
+1 for option 2 (rename when ready).

**Comment by kaedroho** [comment]
It doesn't looke like Elasticsearch can actually rename an index. But there is an alias feature that we could use for that: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

I'm not sure how well that would work on an external service like searchly though

**Comment by kaedroho** [comment]
Searchly supports aliases. But as this requires a separate index to be made, shall we make this optional?

**Comment by kaedroho** [comment]
Another option. We can disable "dynamic mapping" on the index: https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html

**Comment by kaedroho** [comment]
Option 2 implemented in Wagtail 1.1. Currently "experimental" but may become the default in the future.
