### ISSUE TITLE
Account settings button 

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1323]
The way of navigating to account settings isn't particularly clear especially if you have a gravatar set up and there is no sense of what you can expect when you do click.

This came up during a client training session a while ago and it just caught me out as well when looking for notification settings.

The issue the client had was that the proximity to 'log out' makes it look like it's related to that action.

**Comment by tomdyson** [comment]
Thanks, @tmsndrs - can you mock up a better alternative?

**Comment by tmsndrs** [comment]
Hi @tomdyson, 

As a fairly quick change you could have something along these lines. I'm not a massive fan of having things at the bottom of the viewport like this but didn't want to disrupt any of the other UI elements. 

![wagtail-login2](https://cloud.githubusercontent.com/assets/7290588/7728412/fb23307e-ff06-11e4-809c-9a9bfd7fc37f.jpg)

It's not a millions miles away from patterns Twitter and Spotify use. It does introduce an extra click from the current UI but I think it adds clarity that will reduces cognitive load overall.

**Comment by tomdyson** [comment]
Thanks, @tmsndrs, looks good to me.

**Comment by SalahAdDin** [comment]
Soooo good: thank you.

**Comment by SalahAdDin** [comment]
What's about this?

**Comment by gasman** [comment]
Fixed in #2805
