### ISSUE TITLE
Whole page crashes with EmbedNotFoundException when an embed on the page cannot be found

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1324]
Embeds in rich text don't get affected by this issue usually as embeds they have to be selected with the chooser which checks that the embed exists first (and if it does, the embed would get cached in the Embed table in case it does get deleted).

However, this check is not done when an embed is being made from a URL field. If the embed at the URL cannot be found, the frontend will crash.

I think we could do two things to help with this:
1) Make the ``|embed`` filter fail gracefully
2) Add an ``EmbedChooserPanel`` which allows the embed chooser to be used on any URL field (#634)

**Comment by kaedroho** [comment]
Should we display something nice in the rich text editor if the embed is broken?

**Comment by davecranwell** [comment]
As we have no embed management interface, the fact that an embed is broken is something we can only display at the point where the embed is made, otherwise users are left to guess why their embed isn't working: yes I think we need to display something.

**Comment by davecranwell** [comment]
What happens when an existing embed is broken at the embed-providers end? e.g a youtube video being taken down.

**Comment by kaedroho** [comment]
It would continue to work until someone removes it from the embed model
