### ISSUE TITLE
Remove cursor: pointer from field titles when not collapsable. 

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#1325]
Remove cursor: pointer from field titles unless the CSS class 'collapsable' or 'collapsed' is also present. 

![screen shot 2015-05-20 at 15 52 05](https://cloud.githubusercontent.com/assets/7290588/7728626/4519e6ae-ff08-11e4-9589-5b626856a342.png)

It feels like it's 'broken' at the moment.

**Comment by davecranwell** [comment]
Fixed in https://github.com/torchbox/wagtail/commit/9b326631a93d494999d8fb7f5a26bb97f8bc23ce
