### ISSUE TITLE
Broken core migration in project template

### ISSUE THREAD

**Issue by Ylodi** [torchbox/wagtail#1330]
There is no `name` field on ContentType model in Django 1.8 (https://github.com/django/django/blob/master/django/contrib/contenttypes/migrations/0002_remove_content_type_name.py) and line 19 in /project_template/core/migrations/0002_create_homepage.py causes an exception **TypeError: 'name' is an invalid keyword argument for this function**.

**Comment by kaedroho** [comment]
Thanks @Ylodi 

The project template doesn't currently support Django 1.8. We plan on replacing it before the 1.0 release though. See: https://github.com/torchbox/wagtail/pull/1109

**Comment by tony** [comment]
Arrived here with the same error.  How close is #1109 for a stopping point to be merged to master?

**Comment by SalahAdDin** [comment]
Yes, i have this error, i had to use django 1.7.8, We have wait for the next release.

**Comment by kaedroho** [comment]
@tony
Very close, it just needs to be reviewed. If you have time, please try it out and let me know how it goes

**Comment by kaedroho** [comment]
#1109 is now merged
