### ISSUE TITLE
Hallo toolbar wrongly positioned on initial focus in StreamField

### ISSUE THREAD

**Issue by mattots** [torchbox/wagtail#1333]
If the first field of a StreamField is a RichText field, when the block is loaded for the first time and focus is given to the RichText field, the hallo toolbar is positioned incorrectly some way below the field it applies to (see screenshot attached). Removing focus from the rich text field and then refocussing it again causes it to appear back in the correct position.

(Ignore the custom styling and the fact that I've disabled some of the hallo bar plugins - I've checked and the issue still occurs if I remove all my own tweaks).

![screenshot](https://cloud.githubusercontent.com/assets/301729/7769052/eb0b60a8-0078-11e5-9dea-70b0e33abb68.png)

**Comment by davecranwell** [comment]
@mattots Are you able to replicate this with the wagtaildemo project and wagtail 1.0rc2?

**Comment by SalahAdDin** [comment]
i have the same problem in the production server, is some extrange.

**Comment by gasman** [comment]
Closing due to lack of updates / inability to replicate.
