### ISSUE TITLE
Login "sign in" button styling issue

### ISSUE THREAD

**Issue by apidictor** [torchbox/wagtail#1340]
The Login page "sign in" button has a styling issue in tablet and mobile breakpoints.

![login_tablet](https://cloud.githubusercontent.com/assets/329282/7789420/68edc74e-0214-11e5-9532-d9e693f6c65a.png)

**Comment by SalahAdDin** [comment]
Did you try see scss sources in a computer?

**Comment by apidictor** [comment]
@SalahAdDin I see the issue is not in 1.0b2, it was in 0.8.7 which is old. So ... I'll close this.
