### ISSUE TITLE
Redirects: The "Redirect from:" field does not strip leading/trailing whitespace

### ISSUE THREAD

**Issue by strife25** [torchbox/wagtail#1350]
When editing a redirect record, if I put whitespace before or after the main content in the "Redirect from" field, the extra whitespace is never stripped from the value when it is saved to the database. This can create hard to debug errors in redirects that are created.

When I compare this to the "Redirect to any URL" field, trailing whitespace is correctly stripped and leading whitespace creates a validate error.

**Comment by strife25** [comment]
Looking at [wagtailredirects/models.py](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailredirects/models.py#L43), it looks like adding a line to the `normalise_path` method to strip out whitespace would fix this.

**Comment by SalahAdDin** [comment]
Try it please.

**Comment by kaedroho** [comment]
@strife25
Thanks for spotting. It looks like you're right, should be an easy fix.

**Comment by dperetti** [comment]
Actually the ```normalise_path``` is causing issues because it removes the trailing slash.

My urls **do end** with trailing slashes, and the redirect is now broken for me.

**Comment by gasman** [comment]
Hi @dperetti - that sounds like a separate issue to this one, which is specifically about handling whitespace. Please can you open a new issue with full details about this problem?
