### ISSUE TITLE
Tests fail if sendfile is not installed

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1367]
Now that `django-sendfile` has been removed from the dependencies (#1363), bringing up a fresh Wagtail environment (using https://github.com/gasman/vagrant-wagtail-develop) and running `./runtests.py` immediately fails. This is because wagtail/tests/settings.py still includes `sendfile` in `INSTALLED_APPS`. With this commented out, the tests run, but the `test_sendfile_*_backend` tests fail with an ImportError.

Either `django-sendfile` needs to be added to requirements-dev.txt, or (preferably) the tests set up to be skipped if it's not installed.

**Comment by zerolab** [comment]
That is odd. I ran all the test locally before merging #1363. Will spin up a new environment with latest master.

**Comment by zerolab** [comment]
Can confirm the above. Cleared the wrong venv and had django-sendfile still installed, which is why the tests worked fine.

**Comment by zerolab** [comment]
PR: #1377
