### ISSUE TITLE
404 Not found - How to find you on the DjangoCon sprints

### ISSUE THREAD

**Issue by asmaps** [torchbox/wagtail#1370]
Can't find you in Cardiff. Find me on freenode #wagtail

**Comment by tomdyson** [comment]
Hi @asmaps, @kaedroho is just finding the room. Please 301 redirect yourself to the large Shandon lecture theatre and look for a friendly chap with long hair and a black laptop.

**Comment by asmaps** [comment]
I'm the one with the stickers on the laptop *hahaha*

I'm wearing the wagtail tshirt, I'm already in that room :-)
