### ISSUE TITLE
Feature Request: Add a link destination chooser

### ISSUE THREAD

**Issue by asmaps** [torchbox/wagtail#1372]
I have a feature proposal:

Add the possibility to choose a link's target. (same tab, new tab, new window, etc)

http://www.w3schools.com/tags/att_a_target.asp

**Comment by asmaps** [comment]
Looks like it already has been proposed here: #1167

**Comment by davecranwell** [comment]
Also here: https://github.com/torchbox/wagtail/pull/309

I'll close this as it duplicates existing issues.
