### ISSUE TITLE
Latest blog post Wagtail 1.0b2 contains a broken link

### ISSUE THREAD

**Issue by twoblokeswithapostie** [torchbox/wagtail#1376]
This post https://wagtail.io/blog/wagtail-10b2/ contains a broken link to "full list of changes". It goes to https://github.com/torchbox/wagtail/releases/tag/v1.0b2. which 404s

**Comment by prydie** [comment]
The link itself links to `https://github.com/torchbox/wagtail/releases/tag/v1.0b2.` (including the `.`). Otherwise it's pointing at the right place.

**Comment by zerolab** [comment]
Sorted now, thank you.
