### ISSUE TITLE
Page query set methods don't return subclass instances. 

### ISSUE THREAD

**Issue by sethrh** [torchbox/wagtail#1378]
Say I make a subclass of Page: 

    class MyPage(Page): 
        my_flag = models.BooleanField(...)

Then later, I want to generate a link to the next sibling that has `my_flag` set to `True`. 

    >>> p = MyPage.objects.all().first()
    >>> p2 = p.get_next_sibling()
    >>> p2. my_flag
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
    AttributeError: 'Page' object has no attribute 'my_flag'

get_next_sibling always returns a `Page`, rather than an instance of `MyPage`. 

This can probably be fixed by changing the direct [`Page` references](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L973) from this: 

    Page.objects.sibling_of(self, inclusive)

To this: 

    self.__class__.objects.sibling_of(self, inclusive)

**Comment by gasman** [comment]
Hi @sethrh,
This is a necessary limitation of the data model. In general we can't guarantee that the siblings of a page are of the same type as the original, and we can't return a queryset of different models, so we have to return them as plain Page instances instead. Often this is sufficient (if you're only interested in IDs / titles / URLs), but you can turn them into the more specific page object (at the cost of an extra database hit) by accessing `page.specific`.

To query for pages based on fields that aren't part of the basic Page object, you'll need to write your own logic. To find the next sibling of `page` with `my_flag` set to true, I think the following should work:

    MyPage.objects.sibling_of(page).filter(path__gt=page.path).first()
