### ISSUE TITLE
Errors with model 'Tag'

### ISSUE THREAD

**Issue by chadsaun** [torchbox/wagtail#1383]
When I run `django-admin runserver` it reports these errors:

    ERRORS:
    wagtaildocs.Document.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
    wagtailimages.Image.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
    
    System check identified 2 issues (0 silenced).

**Comment by gasman** [comment]
Hi @chadsaun,
Do you have `django-taggit` installed (it should be installed automatically as a dependency of Wagtail) and `'taggit'` listed in the `INSTALLED_APPS` section of your settings file?

**Comment by chadsaun** [comment]
Ah yes that was it.  I just forgot to make sure that was in the `INSTALLED_APPS` section.  Thanks
