### ISSUE TITLE
Image Upload returns 500 error and Sorry, upload failed. message on ec2

### ISSUE THREAD

**Issue by bkavanagh** [torchbox/wagtail#1385]
Uploading images at /admin/images/multiple/add/ fails with a 500 message internally and a 'Sorry upload failed' message on the front end. When run on an amazon ec2 instance, micro-instance, Ubuntu 14.04 LTS.
Document upload works just fine.
Images tested @ 300kb and 3kb

Image upload works fine when run on my dev environment (manage.py runserver 0.0.0.0:8000) and accessed within LAN.
Image upload fails when run on ec2 production server with exposed debugging port (manage.py runserver 0.0.0.0:8000), document upload works correctly
Image upload fails when run with gunicorn and nginx, document upload works correctly.

I've updated Pillow to latest  version available via pip and ensured that I have the correct permissions on my projects 'media' directory (proven with document upload)

Main problem I have is the lack of meaningful error messaging or output which could help to diagnose the issue.

**Comment by diansheng** [comment]
experiencing the same error while uploading a document. Works fine on dev, but failed with nginx and gunicorn.

**Comment by diansheng** [comment]
My problem turns out to be related to nginx settings,  client_max_body_size. It was limited to 1MB

**Comment by ibrahimawadhamid** [comment]
same as @diansheng my issue was nginx setting (client_max_body_size)
