### ISSUE TITLE
Inaccurate confirmation message when publishing a page with a future go-live date

### ISSUE THREAD

**Issue by mope** [torchbox/wagtail#1389]
**Version:** 1.0b2

**Steps to reproduce:**

1. Set a future "Go live date/time" on a page and click "publish".
2. View the page again and click "publish".

-> Page is not published. Success message incorrectly states that page has been published.

**Comment by gasman** [comment]
The only thing I can see here that's (arguably) incorrect is that the message ought to say something like "page X has been scheduled for publishing" instead of "page X has been published". Is that the only issue you're raising here, or is there some other incorrect behaviour? If the latter, please can you explain in more detail?

**Comment by mope** [comment]
This issue arose while investigating a different issue where a page with a go live date in the future failed to be published at the correct time. The editor subsequently clicked the "publish" button in the hopes that it would cause the page to go live, and the success message was displayed. The page was not made live and the editor resolved the issue by setting a date in the past before clicking "publish" again (though of course they could have just deleted the date).

I suggest that there are two problems here:

1) Success message incorrectly displayed.
2) UX issue around ambiguous usage of the word "publish".

**Comment by gasman** [comment]
> This issue arose while investigating a different issue where a page with a go live date in the future failed to be published at the correct time. The editor subsequently clicked the "publish" button in the hopes that it would cause the page to go live, and the success message was displayed.

Hmm, that doesn't really clarify things much... Was that a Wagtail bug? Had the go-live date passed by the time the editor clicked 'publish'? (In which case, surely setting a date further in the past wouldn't have made a difference?)

If the editor's confusion was actually a result of buggy behaviour elsewhere, then I don't think we can draw any useful conclusions from the fact that the UX cues here failed to put them back on track.

**Comment by mope** [comment]
Apologies, what I wrote was unclear. Here's a quote from the ticket that was raised about the issue:

> We have tried to use it twice for press releases to go live at a particular time and both times it has not  worked. We set the report page to go live at midnight on Tuesday, not only did it not go live, the page prevented us from publishing it manually until we set the go live date to Monday or earlier.

I haven't finished investigating the issue yet, but if it turns out to be a Wagtail bug I'll raise another ticket. Note however the ambiguity in the phrase "the page prevented us from publishing it". Do they mean "published" as in saved or "published" as in made live? In this case they mean "made live" but that's not always what the button does.

**Comment by gasman** [comment]
Marking this as "ready to develop", so to clarify: the only thing to be fixed here is to show the confirmation message "page X has been scheduled for publishing" instead of "page X has been published" if the page has a future go-live date.

**Comment by gasman** [comment]
Fixed in #2145
