### ISSUE TITLE
Error in BlogPage example

### ISSUE THREAD

**Issue by marctc** [torchbox/wagtail#1393]
I think there's is a mistake in,
https://github.com/torchbox/wagtail/blob/v1.0b2/docs/reference/pages/creating_pages.rst
when defining `content_panels`, '+' symbol is needed in that assignation.

**Comment by gasman** [comment]
Hi @marctc - thanks for the report! Looks like this has already been fixed in the latest revision of the 1.0 documentation: http://docs.wagtail.io/en/latest/topics/creating_pages.html

**Comment by marctc** [comment]
Ok, thank you!
