### ISSUE TITLE
Previewing pages causes undesirable Google Analytics hits 

### ISSUE THREAD

**Issue by domeheid** [torchbox/wagtail#1394]
As someone who has implemented Google Analytics in my site, I want to ensure that admin pages do not appear in my Google Analytics reports e.g.

![screen shot 2015-06-10 at 16 45 55](https://cloud.githubusercontent.com/assets/478791/8087022/78d69a12-0f90-11e5-9a33-5009f99692ab.png)

Could you please update Wagtail to tell the page it was being previewed, and use that knowledge to exclude the Google Analytics or Google Tag Manager snippets as appropriate?

At the moment, I'm having to fix this issue by either a) adding an exception trigger / blocking rule to exclude page URLs containing /admin/ in the main Google Analytics pageview tag in Google Tag Manager or b) adding a view filter in Google Analytics to exclude subdirectories that contain /admin/.

**Comment by davecranwell** [comment]
GTM/GA tags are nothing to do with wagtail, of course, but the key here is just to ensure that page are aware when they're being previewed or not, so that content within can be altered.

**Comment by gasman** [comment]
Fixed in #1870.
