### ISSUE TITLE
Error Uploading an Image

### ISSUE THREAD

**Issue by chadsaun** [torchbox/wagtail#1397]
When I click the "Upload" button to upload an image from a page, I get `ValueError: The file cannot be reopened.`

Here is the full stack trace:

    [11/Jun/2015 13:05:29] "POST /cms/images/chooser/upload/ HTTP/1.1" 500 23947
    Internal Server Error: /cms/images/chooser/upload/
    Traceback (most recent call last):
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 141, in     chooser_upload
        {'image_json': get_image_json(image)}
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/views/chooser.py", line 22, in     get_image_json
        preview_image = image.get_rendition('max-130x100')
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 196, in get_rendition
        generated_image = filter.process_image(image_file, backend_name=backend_name, focal_point=self.get_focal_point())
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 371, in process_image
        input_file.open('rb')
      File "/Users/john/.virtualenvs/website/lib/python2.7/site-packages/django/core/files/base.py", line 128, in open
        raise ValueError("The file cannot be reopened.")
    ValueError: The file cannot be reopened.

**Comment by chadsaun** [comment]
UPDATE:

So when this error happened, the image did actually upload just fine.  After the error I went over to "Images" in the left menu and it showed up and I could select it for the page and everything.  So this error is happening *after* the image is uploaded successfully.

**Comment by kaedroho** [comment]
Looks like Wagtail is trying to generate a rendition on an image that has just been uploaded (in the same view). This is probably an easy fix, just need to refresh the image object before generating a rendition from it.

**Comment by tomdyson** [comment]
Hi @chadsaun, can you confirm which version of Wagtail you're using? Please post the output of `pip freeze`.

**Comment by kaedroho** [comment]
What version of Django are you using? Are you storing files locally?

**Comment by chadsaun** [comment]
Here's my `pip freeze`

```
Babel==1.3
BabelDjango==0.2.2
beautifulsoup4==4.3.2
boto==2.38.0
braintree==3.12.0
cairocffi==0.6
CairoSVG==1.0.13
cffi==0.9.2
click==4.0
cryptography==0.8.2
Django==1.7.8
django-appconf==1.0.1
django-compressor==1.5
django-datetime-widget==0.9.3
django-debug-toolbar==1.3.0
django-images==0.4.1
django-libsass==0.3
django-livefield==2.1.0
django-model-utils==2.0.3
django-modelcluster==0.6.2
django-mptt==0.7.4
django-offsite-storage==0.0.5
django-overextends==0.3.2
django-payments==0.6.5
django-prices==0.3.4
django-recaptcha==1.0.3
django-selectable==0.8.0
django-taggit==0.12.3
django-treebeard==2.0
djangorestframework==3.0.3
djrill==1.3.0
docopt==0.4.0
enum34==1.0.4
fake-factory==0.4.2
feedparser==5.2.0
google-measurement-protocol==0.1.3
html5lib==0.999
jsonfield==1.0.0
libsass==0.8.2
mailchimp==2.0.9
Markdown==2.5.2
mysqlclient==1.3.6
ndg-httpsclient==0.3.3
Pillow==2.8.2
prices==0.5.1
psycopg2==2.5.4
pyasn1==0.1.7
pycparser==2.13
pycrypto==2.6.1
PyJWT==1.0.1
pyOpenSSL==0.15.1
python-dotenv==0.1.2
pytz==2015.4
reportlab==2.7
requests==2.7.0
saleor==0.1.0a0
satchless==1.1.3
six==1.9.0
South==1.0.2
sphinx-me==0.3
sqlparse==0.1.15
stripe==1.22.1
suds-jurko==0.6
unicodecsv==0.13.0
Unidecode==0.4.18
Unipath==1.0
wagtail==0.8.7
XlsxWriter==0.7.2
```

**Comment by chadsaun** [comment]
These images are being stored in an S3 bucket.  Everything seems to work perfectly through the "Images" menu page/uploader though.  Just seems to be an issue with the modal window uploader tool thingymabob.

**Comment by gasman** [comment]
I take it you're using [django-offsite-storage](https://github.com/mirumee/django-offsite-storage) for that, and you have `DEFAULT_FILE_STORAGE` set to `'offsite_storage.storages.S3MediaStorage'`...?

**Comment by chadsaun** [comment]
Yes
`DEFAULT_FILE_STORAGE = 'offsite_storage.storages.S3MediaStorage'`

**Comment by kaedroho** [comment]
It might be the fact that we're calling ``image.file.file.open()``. In wagtail 1.0+ we call ``image.file.open()`` which is probably a bit higher level and may be able to handle this.

**Comment by kaedroho** [comment]
I can confirm that this issue appears in the current master as well

**Comment by kaedroho** [comment]
This PR should hopefully solve this: https://github.com/torchbox/wagtail/pull/1605
