### ISSUE TITLE
Allow slugs to completely override urls for legacy sites

### ISSUE THREAD

**Issue by arthanson** [torchbox/wagtail#1399]
Currently the slug field will take the parent's page slug for the full url path and also dis-allow certain characters.  When converting an existing site over to use wagtail this can be a problem as the urls might not directly map this way and they will loose some SEO benefits if moved, even if a redirect is used.

It would be better if you can completely override the url of a given page.   For example one existing site uses underscores between words in the slug, but wagtail will strip these out.  The site also wants to use a new menu structure but keep the urls the same as the old site.

**Comment by gasman** [comment]
Stripping out underscores is a bug - I'll fix that.

Overriding URLs to be something entirely different from the tree location - this can be done on an ad-hoc basis by [implementing a custom `route` method](http://docs.wagtail.io/en/v0.8.7/core_components/pages/model_recipes.html#adding-endpoints-with-custom-route-methods) on the page model at the site root, and with a bit of work this could possibly be made into an add-on module. I wouldn't be keen on adding this as an out-of-the-box feature of Wagtail, though - having URLs that match the site structure is a good practice that Wagtail should promote by default, and allowing editors to casually override that would make sites harder to manage, as well as making Wagtail's internals more complex.
