### ISSUE TITLE
Configurable headers for wagtail documents

### ISSUE THREAD

**Issue by chhantyal** [torchbox/wagtail#1407]
It seems `Content-Disposition` header is always set to 'attachments' https://github.com/torchbox/wagtail/blob/v0.8.7/wagtail/wagtaildocs/views/serve.py#L16 which results in browsers prompting users to download the file.

Since modern browsers can easily display PDF files, it would be great if we could make above header configurable.

**Comment by chhantyal** [comment]
Oh that one was old branch, but it seems same on new branch too https://github.com/torchbox/wagtail/blob/master/wagtail/wagtaildocs/views/serve.py#L16

**Comment by chhantyal** [comment]
Ok, found a workaround. 

Instead of using `link_document.url`, if I use `link_document.file.url` - django default behaviour will work.

**Comment by SalahAdDin** [comment]
Can you put here an example?

**Comment by chhantyal** [comment]
@SalahAdDin what do you mean example?

When you want to display document in UI, instead of doing `document.url` which is Wagtail default - do `document.file.url` which is django default. It will work only in specified field, not for documents embedded inside RichTextField or StreamField

**Comment by gasman** [comment]
To be addressed by #1420. (Related: #733, #1158, #1176)

**Comment by BrendanBerkley** [comment]
I have a user story that plays out like this: 1. User uploads PDF in Wagtail Documents, 2. User copies link location to clipboard, 3. User pastes link to another spot in Django admin to link up an image he uploaded. In this situation, the PDF downloads rather than opening in the browser. Will the changes in #1420 address a situation like this?

**Comment by gasman** [comment]
@BrendanBerkley I don't follow what you mean by step 3 - but the issue of downloading PDFs versus displaying them in the browser is covered by the "TODO: decide how to incorporate #733" note at the bottom. So, addressing this is indeed on the task list for #1420, but we're yet to decide on the exact mechanism.

**Comment by eyjolfur12** [comment]
So, any news on this issue. It seams still that pdf's inserted in RicheText or Stream Fields are served as Content-Type: application/octet-stream and  Content-Disposition: attachment; and so downloaded instead of displayed in the browser. Any way yet to affect this behavior?

**Comment by gasman** [comment]
Hi @eyjolfur12,

Wagtail development happens in the open - if there's no new activity on the Github issue, you can safely assume that there's nothing new to report.

**Comment by ipmb** [comment]
Ran into this on a couple of client sites, specifically related to PDF documents not being previewable.

Here's a workaround that overrides Wagtail's default document view and redirects to the file URL:

```python
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from wagtail.wagtaildocs.models import Document


def serve_wagtail_doc(request, document_id, document_filename):
    """
    Replacement for ``wagtail.wagtaildocs.views.serve.serve``
    Wagtail's default document view serves everything as an attachment.
    We'll bounce back to the URL and let the media server serve it.
    """
    doc = get_object_or_404(Document, id=document_id)
    return HttpResponseRedirect(doc.file.url)
```

Then add this to the top of your urlpatterns (above any wagtail includes):

```python
    # override default wagtail view
    url(r'^documents/(\d+)/(.*)$', [path.to].serve_wagtail_doc,
        name='wagtaildocs_serve'),
```

**Comment by XiangxiangXu** [comment]
> Ran into this on a couple of client sites, specifically related to PDF documents not being previewable.
> 
> Here's a workaround that overrides Wagtail's default document view and redirects to the file URL:
> 
> ```python
> from django.http import HttpResponseRedirect
> from django.shortcuts import get_object_or_404
> from wagtail.wagtaildocs.models import Document
> 
> 
> def serve_wagtail_doc(request, document_id, document_filename):
>     """
>     Replacement for ``wagtail.wagtaildocs.views.serve.serve``
>     Wagtail's default document view serves everything as an attachment.
>     We'll bounce back to the URL and let the media server serve it.
>     """
>     doc = get_object_or_404(Document, id=document_id)
>     return HttpResponseRedirect(doc.file.url)
> ```
> 
> Then add this to the top of your urlpatterns (above any wagtail includes):
> 
> ```python
>     # override default wagtail view
>     url(r'^documents/(\d+)/(.*)$', [path.to].serve_wagtail_doc,
>         name='wagtaildocs_serve'),
> ```

Remark: In wagtail 2.0+, one should use wagtail.**documents**.models instead of wagtail.**wagtaildocs**.models.
