### ISSUE TITLE
  Transparent pngs lose transparency when uploaded

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1410]
I found this about transparent gifs https://github.com/torchbox/wagtail/issues/1084

I upgraded to willow0.2b2, installed wand and imagemagick, but I still have no luck.

I am using Wagtail 1.0b1. Is there a solution to this?

**Comment by kaedroho** [comment]
This was actually a but in Wagtail, not Willow. It was fixed in 1.0 beta 2

**Comment by lee-kagiso** [comment]
Thanks, fixed!
