### ISSUE TITLE
Documents: This backend doesn't support absolute paths. (Update to 1.0b2)

### ISSUE THREAD

**Issue by nilssolanki** [torchbox/wagtail#1415]
1. Bug since Wagtail update
--------------

I recently upgraded to 1.0b2 (from 1.0b1) and now, when I try to access I document I uploaded via a `wagtaildocs.Document` field, I get the following error:

    NotImplementedError at /documents/3/headphones.svg
    This backend doesn't support absolute paths.

The field is specified as:

    svg_mask = models.ForeignKey(
        verbose_name=u"Mask (SVG)",
        to='wagtaildocs.Document',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

Is this a wagtail bug or a configuration error?

2. Unexpected behaviour
--------------

I would like to serve the svg as a `image/svg+xml`, not as a stream (which was the case in 1.0b1). I set the mimetype in my settings as follows:

    mimetypes.add_type("image/svg+xml", ".svg", True)
    mimetypes.add_type("image/svg+xml", ".svgz", True)

Yet (in 1.0b1) it always got served as a stream. I couldn't test it in 1.0b2 yet, because of the above problem.

Thank you in advance.

**Comment by gasman** [comment]
Are you using a non-standard file storage backend? If so, what do you have as your `DEFAULT_FILE_STORAGE` setting?

**Comment by nilssolanki** [comment]
Yes, we are using S3:

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
    STATICFILES_STORAGE = DEFAULT_FILE_STORAGE

Do I need to change any settings for this?

**Comment by nilssolanki** [comment]
@gasman Do you have any ideas for "2. Unexpected behaviour"?

**Comment by kaedroho** [comment]
The streaming behaviour isn't dictated by the mime type. You can switch it off globally though by installing ``django-sendfile`` and adding the following to your settings:
```
SENDFILE_BACKEND = 'sendfile.backends.simple'
```

**Comment by nilssolanki** [comment]
@kaedroho: Thank you very much. Is there any way to selectively disable it (ie. for a specific field in the model).
If not, I'll probably go with this.

**Comment by nilssolanki** [comment]
@kaedroho I didn't get it to work with sendfile and the settings, it still streams the file. Is there anything else I can/need to do?

**Comment by gasman** [comment]
@nilssolanki Please can you open a separate issue for the "2. Unexpected behaviour" point?

**Comment by michealjroberts** [comment]
This is purely an issue with the default File Storage backend.
