### ISSUE TITLE
Information disappearing on copied page

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#1418]
We have a page type with orderable items, which when copied starts to display incorrectly.

So if the original page is edited, with no changes made, and you click publish, the copied page doesn't display the orderable items for that page. It also works in the other direction, so if you edit the copied page, the orderable items in the original stop displaying. 

They display fine in the preview for both. The templates that displays the items for the page uses a regroup template tag. 

Only pages copied from each other at the same level in the tree seemed to be affected.

The items are always still there when you go back to edit the page, so they're not being lost, just not displayed if the copied or original page is edited and re-published.

**Comment by jossingram** [comment]
We're using 0.8.7 btw

**Comment by gasman** [comment]
Thanks @jossingram - have confirmed that this bug still exists on current master using wagtaildemo:

* Create a new 'person' page within People, with a single related link, and publish it
* Copy that page within the same parent (entering a new title and slug, and leaving 'Publish copied page' ticked)
* Edit the new page, and publish
* View the live version of the original page
* The related link is no longer present on the original page
