### ISSUE TITLE
Model save() method not saving changes to database

### ISSUE THREAD

**Issue by michaelfillier** [torchbox/wagtail#1421]
I am attempting to geocode an address and save the results to the model using django's save method. The method is being called, but any changes to self are not being saved in the database. Here is the code containing the models.

http://dpaste.com/2BA3Q27

(I added a simple update to self.telephone, just to rule out the geocoding code not working. self.telephone is not saving to the model.)

**Comment by gasman** [comment]
Are you testing this from `./manage.py shell`, or through the Wagtail admin backend? The page admin interface has a non-standard workflow involving Page and PageRevision objects, which can make it look as if changes haven't been written to the database.

**Comment by michaelfillier** [comment]
I am testing this through the admin. Is there a specific hook or method I would need to use instead of the save method?

**Comment by mixxorz** [comment]
I've also encountered this problem. How would you go about overriding a field's value if overriding `save()` won't work?

**Comment by gasman** [comment]
Unfortunately Wagtail is currently lacking a 'streamlined' way of updating fields so that the update takes effect on both the Page and PageRevision record - but there's some discussion of how we might achieve that on #1101.
