### ISSUE TITLE
Garlic doesn't work with Streamfield and RichTextField

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1427]
I am using http://garlicjs.org/ to try and autosave the admin forms, as I don't want the content writers to lose their work whilst in progress.

I notice it doesn't work with RichTextFields, and Streamfields.

Is there a simple solution?

**Comment by kaedroho** [comment]
Related #475

**Comment by gasman** [comment]
Given the amount of dynamic updating that happens on the page edit form, I wouldn't expect a third-party add-on such as Garlic to be able to handle this. This is something that Wagtail itself would need to address, as covered by #475.
