### ISSUE TITLE
Can't open settings when in styleguide

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#1432]
A very minor one in the release candidate, all I've found so far, is when you're in the styleguide, the menu for settings won't appear, if I click on one of the other menus like documents, I can then access settings!

**Comment by jossingram** [comment]
For Chrome v43, it's fine in Safari and FF actually

**Comment by davecranwell** [comment]
Thanks for reporting. It's been present for a while and I'm still trying to figure out why it's happening. It's a CSS rendering bug somehow connected to `translate` properties.

**Comment by gasman** [comment]
Fixed in #1987
