### ISSUE TITLE
Admin user index page is broken for user models without last_name and first_name

### ISSUE THREAD

**Issue by seddonym** [torchbox/wagtail#1433]
I'm trying to integrate Wagtail with a site that uses a custom user model that does not have first_name or last_name fields.

The user index view in the Wagtail admin is broken, because it attempts to order by last name and first name.  I can't see any obvious way of overriding this other than rewriting the view and including my own urls.py to use that one instead.
 
Here's the line:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailusers/views/users.py#L47

**Comment by davecranwell** [comment]
Perhaps the simplest way of addressing this would be to order by those fields only if they exist, using try/except. 

Similarly on ln.54 https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailusers/views/users.py#L54

@kaedroho does this seem plausible?

**Comment by gasman** [comment]
Fixed in #2225
