### ISSUE TITLE
Serving files from s3 always returns files with a content-length of 0 bytes.

### ISSUE THREAD

**Issue by ser1us** [torchbox/wagtail#1436]
Hi everyone,

With the change to rc1 we can download the files from s3. The problem is, we always get 0 bytes returned. After investigating the code a little bit it might be because of this FIXME in the documents serve method:

```
# FIXME: storage backends are not guaranteed to implement 'size'
response['Content-Length'] = doc.file.size
```

The webserver also complains about this:
```2015-06-23T06:39:05.519199+00:00 app[web.1]: WARNING:waitress:application-written content exceeded the number of bytes specified by Content-Length header (0)```

I guess the header could be removed since closing the connection should be enough. Anyway, I think this fixme prevents us from downloading any files from wagtail right now.

Best regards,
Christoph

**Comment by gasman** [comment]
What storage backend (i.e. `DEFAULT_FILE_STORAGE` setting) are you using? If the backend doesn't support the `size` method, it should be throwing a `NotImplementedError` rather than returning 0 (as per the [Storage API docs](https://docs.djangoproject.com/en/1.8/ref/files/storage/#django.core.files.storage.Storage.size)), so either the storage backend is at fault, or there's something else going wrong.

**Comment by ser1us** [comment]
Thanks for your answer. 
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

**Comment by gasman** [comment]
Just tried with the S3BotoStorage backend from django-storages 1.1.8, and file sizes are being correctly reported in the Content-Length header here. Looking at the django-storages code https://bitbucket.org/david/django-storages/src/f153a70ba254dc129d9403546809a02256ef75b5/storages/backends/s3boto.py?at=default#cl-465 , it seems that it keeps some sort of local cache of file metadata, and returns 0 if the file isn't in the cache - I'm pretty sure this is invalid behaviour within django-storages.

**Comment by ser1us** [comment]
Thanks for checking, you're completely right. For the records: It seems to work fine after I removed the ```AWS_PRELOAD_METADATA``` environment setting.

Thanks again! Much appreciated.
