### ISSUE TITLE
How do I tag with multiple word tags

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1438]
I looked at this issue https://github.com/torchbox/wagtail/issues/916, but I can't find a solution to my problem.

I want to do multiple word tags: Like `Fred Flinstone`, `Caveman`
However I get `Fred` `Flinstone` `Caveman`. The moment I type space a tag is identified.

If I use double quotes, I get double quotes appearing in the tag.

**Comment by SalahAdDin** [comment]
I have understood that in the last django-taggit version had fixed this problem, and is possible use multiple words in a tag, but, i don't know is real.

**Comment by lee-kagiso** [comment]
I am upgraded to the latest, and it didn't make a difference, the change log also made no mention of any such improvement

**Comment by Ricemast** [comment]
@lee-kagiso Using double quotes (`"`) to surround your multiword tag should work just fine. It only shows those quotes in the WT admin interface, they are not saved in the DB nor will they be shown when you render them.

![screen shot 2015-07-06 at 11 18 23](https://cloud.githubusercontent.com/assets/3462749/8520267/c1948a76-23d0-11e5-9bda-e059e85e60a8.png)
![screen shot 2015-07-06 at 11 18 03](https://cloud.githubusercontent.com/assets/3462749/8520271/c8b068de-23d0-11e5-891d-1a35aa7832e5.png)
![screen shot 2015-07-06 at 11 17 46](https://cloud.githubusercontent.com/assets/3462749/8520275/cb5123bc-23d0-11e5-8748-164608f7b114.png)

**Comment by lee-kagiso** [comment]
@Ricemast thanks!

**Comment by SalahAdDin** [comment]
But, i think that don't should be neccessary put the "" for put a multiword tag.
