### ISSUE TITLE
'Ten minute' tutorial potentially confusing relating to Wagtail versions

### ISSUE THREAD

**Issue by seddonym** [torchbox/wagtail#1439]
Here's what I did:

- From https://wagtail.io/developers/, I followed the link to the Ten Minute Guide at http://docs.wagtail.io/en/latest/getting_started/tutorial.html
- I ran `pip install wagtail` and followed the tutorial.
- I experienced a few issues but hit a wall in the related items section.  It look a while to realise that the InlinePanel API had changed, and that the tutorial is for a different version than is currently installing using pip (Wagtail 0.8.8).

Obviously if you visit the Wagtail docs direct, it does lead to the correct version, but it seems reasonable that other developers may take the same path I took!

My suggestion would be either to remove / qualify the link from the 'Developers' page, or perhaps adjust the documentation itself to make it clear that it needs to be Wagtail 1.x.

Hope useful feedback!

**Comment by gasman** [comment]
No longer an issue now that 1.0 is the current version installed by pip.
