### ISSUE TITLE
Rebuild documentation with Django 1.8

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#1451]
`@cached_property` attributes did not correctly carry across their docstrings until Django 1.8, which caused `autodoc` to fall over. [The docs for `Page.specific`](https://wagtail.readthedocs.org/en/v1.0rc1/reference/pages/model_reference.html?highlight=specific#wagtail.wagtailcore.models.Page.specific) are a good example.

Rebuilding the documentation with Django 1.8 or higher fixes the problem.

**Comment by kaedroho** [comment]
Thanks!
