### ISSUE TITLE
Image as link 

### ISSUE THREAD

**Issue by iho** [torchbox/wagtail#1472]
Hello everyone! 
I am sorry, but how do this with wagtail? 
```
<a href="https://www.google.com.ua/">
<img border="0"  src="https://www.google.com.ua/images/srpr/logo11w.png">
</a>
```
I need it for advertising snippet.

**Comment by gasman** [comment]
Hi @iho - please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
