### ISSUE TITLE
CSS Issues in Admin

### ISSUE THREAD

**Issue by joshourisman** [torchbox/wagtail#1477]
There appears to be some CSS issues for the admin in rc2 (that were also present in at least b2). I'm attaching a screenshot, so you can see what I mean.

![wagtail_-_exploring_root](https://cloud.githubusercontent.com/assets/39895/8526310/eb8ab546-23d3-11e5-8678-a6be4711d20b.png)

**Comment by davecranwell** [comment]
I'm sure I've seen this before and it turned out to be due to a misconfigured site setup or similar. @gasman does this ring a bell? ISTR you identified it last time.

**Comment by gasman** [comment]
@davecranwell We've had similar layout glitches when updating the CSS and failing to run `npm run build` - is that what you're thinking of? (That wouldn't affect a release package with the CSS prebuilt, of course.)

**Comment by davecranwell** [comment]
hmm, no that wasn't it. There's some oddness going on in this screenshot, I think. For example why does the Root have a page status of "LIVE"? The status indicator should be hidden completely if the parent page is root.

**Comment by davecranwell** [comment]
@joshourisman Have you altered the Page table in some way to force "Root" to be a true page?

You'll note that in this template we've deliberately hidden the page status tag - shown in your screenshot - for pages which are the Root (`is_root`) but somehow your Root page is not identified as the actual root.

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/pages/listing/_list.html#L29

While Root must technically be a page for internal reasons, it should never be a true page with a URL, accessible on the front end. It looks like your Root page might be, which I think is having knock-on effects with other parts of the UI.

**Comment by joshourisman** [comment]
I just dropped my Postgres database, and ran migrate to recreate everything from scratch. I still see exactly the same thing. Page.objects.get(id=1).is_root() returns True, as well.

**Comment by joshourisman** [comment]
This may be relevant: the template linked to above (wagtailadmin/pages/listing/_list.html) does not exist in the version of Wagtail that I installed (`pip install wagtail==1.0rc2`), which is not consistent with what's on github for the v1.0rc2 tag.

**Comment by joshourisman** [comment]
Yeah, just checked the tarball on PyPI, and the packaged 1.0rc2 is not the same as what's tagged as 1.0rc2 on GitHub.

**Comment by joshourisman** [comment]
Ugh, nevermind, my mistake; Octotree had switched me back over to the master branch…

**Comment by davecranwell** [comment]
Glad you found the problem :) Does this mean the state of your tree is a result of Octotree? Could we close this issue?

**Comment by joshourisman** [comment]
No, sorry; Octotree is a Chrome extension for browsing GitHub repos. Generally awesome, but unreliably supports branches, leading me to unintentionally switch to the master branch when viewing the wagtail code on GitHub, which is why I thought the distributed tarball was different. I'll delete the comments about that stuff, to avoid confusion.

The problem persists with my wagtail install. Running 1.0rc2 with a completely fresh database. Since dropping the database I've done nothing other than `./manage.py migrate` and `./manage.py createsuperuser`.

**Comment by joshourisman** [comment]
It looks to me like the template is just incorrect: https://github.com/torchbox/wagtail/blob/v1.0rc2/wagtail/wagtailadmin/templates/wagtailadmin/pages/list.html#L46-50

That will display the 'live' tag regardless of whether or not the parent page is_root. All that changes is whether or not it's a link.

**Comment by davecranwell** [comment]
Ah yes you're right. I thought a recent refactor of the listing template had already addressed this, but that work hasn't made it into rc2. The fixes will be in 1.1 at this rate, currently speculated for release at the end of August.

**Comment by davecranwell** [comment]
Hi @joshourisman I believe this has now been fixed with https://github.com/torchbox/wagtail/pull/1611 Please could you have another look?

**Comment by alexgleason** [comment]
I was also experiencing this issue and am no longer seeing it on the current master branch.

**Comment by gasman** [comment]
Thanks for the confirmation @alexgleason!

**Comment by joshourisman** [comment]
A little late to the party, but confirming that this fixes the problem for me as well.
