### ISSUE TITLE
Login attempts result in different behaviour for users known by django but with insufficient permissions

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1486]
1. create a new user in wagtail,
2. assigned it to a group which has no admin access
3. try to log into wagtail admin as that user

The result is a redirect back to the login without any feedback whatsoever.

I'd expect the user to receive the same error response as someone logging in with completely unknown credentials. A difference in results indicates to anyone probing the site maliciously, that a set of tested credentials matches a real user.

**Comment by timheap** [comment]
@gasman just came across this while giving a demo to @praekelt. An error message would help quite a lot here.
