### ISSUE TITLE
Include requestor IP in preview dummy_request?

### ISSUE THREAD

**Issue by jasonm** [torchbox/wagtail#1502]
When `wagtailcore.models.Page.dummy_request` issues a dummy `WSGIRequest` to compute preview content, should it defensively include a reasonable `REMOTE_ADDR` header in case there are middleware installed which expect an IP address?  Or should middleware always defensively handle the case where no requestor IP is provided?

Related to: https://github.com/Miserlou/django-easy-timezones/issues/6

I _think_ it's the responsibility of the middleware library to be defensive in this case, but curious if any Wagtail devs think it's worth including a valid `REMOTE_ADDR` in the request.

**Comment by gasman** [comment]
Yes, I think it would be a good idea to add `REMOTE_ADDR` to the dummy request object, even if it is bad form for middleware (and other code) to rely on its presence - anything that makes the preview rendering more representative of a real page request is a good thing.

I'd suggest updating `dummy_request` to accept an *optional* `original_request` kwarg, and have the preview views pass the incoming request object to it - we can then cherry-pick `REMOTE_ADDR` from there, if available (along with any other headers that might be useful - user-agent, possibly?)

**Comment by sterago** [comment]
I have noticed that the missing `REMOTE_ADDR` header in the dummy request also causes an issue with django's debug context processor, as it relies on this value to determine whether or not it should expose the `debug` context variable to the templates:
https://github.com/django/django/blob/5153a3bfdcec82324d67ff79862384288cf6afe6/django/template/context_processors.py#L41

so adding `REMOTE_ADDR` to the dummy request should fix this issue as well.

**Comment by gasman** [comment]
As per https://groups.google.com/d/msg/wagtail/dp8y1l5T3L8/MXLWOZPjCgAJ, it would also make sense to copy the original request's Cookie header, so that any session-dependent behaviour on the page (e.g. user authentication) would be performed as the logged-in user. (This would cause the Wagtail userbar to display, which we probably don't want - but that's easily fixed by checking the `request.is_preview` flag.)

**Comment by coredumperror** [comment]
I've just run into this problem myself (we use a middleware to restrict access to on-campus users), and was planning to make a PR with precisely the fix suggested here. So I'll go ahead and do that. :)

**Comment by gasman** [comment]
Implemented in #2550.
