### ISSUE TITLE
Date picker widget appears behind streamfield block menu

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1510]
This is just a case of incorrect z-index. If you have a date field immediately before a streamfield, the date picker that appears when the date field is focused, is cut off by the streamfield menu below it.

**Comment by davecranwell** [comment]
Use SCSS maps to rewrite all use of z-index https://css-tricks.com/handling-z-index/

**Comment by gasman** [comment]
Fixed in #1869
