### ISSUE TITLE
update_index deleting all mappings inside the index

### ISSUE THREAD

**Issue by dchaplinsky** [torchbox/wagtail#1514]
Including those that doesn't belongs to wagtail.

I'm using elasticsearch in my project to provide search across DB (not only news pages). 
And when I hit update_index wagtail is dropping whole index, including my own mappings for my collections.

I'm not very happy with idea to have two different indexes for the same project. Is there a solution for that?

**Comment by kaedroho** [comment]
@dchaplinsky 
Out of interest, why are multiple indexes in the same project a problem for you?

The index that Wagtail creates is given wagtail-specific configuration which may change (and this could possibly break any mappings/behaviour that your application dependends on). For this reason, I only recommend using the index Wagtail creates for models that are managed by Wagtail (any model can be managed by Wagtail: http://docs.wagtail.io/en/v1.0/topics/search/indexing.html#indexing-custom-models).

**Comment by kaedroho** [comment]
Closing this as I think creating separate indices is the way to go. No Elasticsearch provider I've seen charges extra for splitting up your data into multiple indices (unless doing so increases the overrall volume of data).

Also, some refactoring in Elasticsearch 2.0 means that we may have to make Wagtail use multiple indices too (see: https://www.elastic.co/blog/great-mapping-refactoring#conflicting-mappings).
