### ISSUE TITLE
wagtailimage_tag: alt value not exist

### ISSUE THREAD

**Issue by einstein13** [torchbox/wagtail#1517]
I am using wagtail 1.0.rc1 and when I use in template {% image image_object as img %}, there is no value (or empty string) {{ img.alt }}.
According to the wagtail documentation: http://wagtail.readthedocs.org/en/v0.8.8/core_components/images/index.html#more-control-over-the-img-tag there should be such a value. Currently it is possible to go back: {{image_object.title }}, but that is not the correct solution here

**Comment by gasman** [comment]
Hi @einstein13 - thanks for reporting. This looks like a documentation error - the Rendition object does not provide an 'alt' property, so going back to the original image object (`{{ image_object.title }}`) is in fact the correct way of doing this, in the current version.

Having said that, it would be easy enough to add an 'alt' property, and that would make the API a bit nicer - so I'll put that on the wishlist for the next release.
