### ISSUE TITLE
stream.js not being added as form media

### ISSUE THREAD

**Issue by joshourisman** [torchbox/wagtail#1522]
This is a bit of a weird one. I created a fairly simple Page subclass (MixedMediaPage — full code below) that includes a StreamField. When I attempt to create a MixedMediaPage in the admin, the StreamField fails to work, due to a javascript error (`Uncaught ReferenceError: StreamBlock is not defined`). As far as I can tell, the problem is that the `stream.js` file is simply not loaded on the page. As a result, `window.StreamBlock` is not set, and therefore the StreamField simply fails to work.

I have StreamFields on several other page classes that work without issue, and I've been unable to find anything that I'm doing differently with this one that would explain the issue. I thought that maybe it was because I'm only using ImageChooserBlock and EmbedBlock here, which do not some from wagtailcore.blocks, but even when I replace that StreamField wholesale with one that works in another page class, it still has the same error.

    from django.db import models
    from modelcluster.fields import ParentalKey
    from modelcluster.tags import ClusterTaggableManager
    from taggit.models import TaggedItemBase
    from wagtail.wagtailadmin.edit_handlers import FieldPanel, StreamFieldPanel
    from wagtail.wagtailcore.fields import StreamField
    from wagtail.wagtailcore.models import Page
    from wagtail.wagtailembeds.blocks import EmbedBlock
    from wagtail.wagtailimages.blocks import ImageChooserBlock

    class MixedMediaHomePage(Page):
        subpage_types = ['MixedMediaPage']
        parent_page_types = []

    class MixedMediaTag(TaggedItemBase):
        content_object = ParentalKey('MixedMediaPage', related_name='tagged_items')

    class MixedMediaPage(Page):
        caption = models.TextField()

        media = StreamField([
            ('image', ImageChooserBlock()),
            ('video', EmbedBlock()),
        ])
        tags = ClusterTaggableManager(through=MixedMediaTag, blank=True)

        content_panels = Page.content_panels + [
            FieldPanel('caption', classname='full'),
            StreamFieldPanel('media'),
            FieldPanel('tags', classname='full'),
        ]

        parent_page_types = ['MixedMediaHomePage']

**Comment by gasman** [comment]
I'll bet it's because your field is named 'media', which clashes with the form media property - does it work if you rename it to something else?

**Comment by joshourisman** [comment]
Oh wow, I bet that's it. Should have thought of that. Testing…

**Comment by joshourisman** [comment]
That was it. Dumb mistake, thanks!
