### ISSUE TITLE
Reduce use of similar-size image renditions used in admin

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1523]
We appear to have two renditions used when displaying images in a list: max-165x165 and max-130x130

Apparently this is problematic for image-heavy sites with external image servers, where renditions have to be pre-rendered (rather than on demand). We can't stop developers requesting lots of image renditions for the front end, but we can play a small part by at least limiting unnecessary image renditions in wagtail admin.

These two renditions should be reduced to only the larger one, resized with css or width/height attr to create the smaller of the two renditions.

**Comment by gasman** [comment]
Fixed in #1822
