### ISSUE TITLE
Wagtail API & REST framework

### ISSUE THREAD

**Issue by tomchristie** [torchbox/wagtail#1524]
Just opening the conversation here...

Would there be any interest in considering implementing the Wagtail API in Django REST framework, with a view to:

* Making it more readily customizable by other developers.
* Making it faster for other developers to get up to speed on (built and structured within a common framework that many folks will be used to working with)
* Making it easier for other devs to add in various authentication/permission policies. (eg using third party auth options for REST framework)
* Optionally make use of some of the functionality that REST framework provides. Eg the browsable API and the upcoming admin style browsable API.

What's the general view on this?

**Comment by kaedroho** [comment]
I'm in favour of replacing the custom code with REST framework. I had a look at it when I wrote the initial implementation but couldn't think of an easy way to get it to work with multi-table inheritance (which Wagtail uses for its ``Page`` model).

**Comment by tomchristie** [comment]
> I had a look at it when I wrote the initial implementation but couldn't think of an easy way to get it to work with multi-table inheritance at the time

Gotcha. Having dynamic serializers for an endpoint probably wouldn't be terribly awkward, so if you did go for it then I'd err on the side of designing your API how you want it to look, and making REST framework fit in around that.

I'd be happy to have some involvement in this if it is something you wanted to do.

**Comment by tomdyson** [comment]
Thanks, @tomchristie, we'd really appreciate your help on this. What's the best way to get started?

**Comment by tomchristie** [comment]
I've some thoughts on approaching this incrementally. Will aim to catch up on this next week, ideally with a PR to demonstrate.

**Comment by tomchristie** [comment]
There ya go.
