### ISSUE TITLE
`wagtail start` should accept a second argument for destination directory

### ISSUE THREAD

**Issue by mixxorz** [torchbox/wagtail#1526]
Similar to `django-admin.py`.

```bash
$ wagtail start my_project my-project
```
```bash
$ mkdir my-project
$ cd my-project/
$ wagtail start my_project .
```

I'll put in a PR later today for this. I haven't looked at the code but this should be simple enough to implement. I'll also add tests if you're testing the `wagtail start` command. :grinning:

**Comment by kaedroho** [comment]
PR Merged, thanks!

**Comment by mixxorz** [comment]
Thanks for merging! :wine_glass: :sunglasses:
