### ISSUE TITLE
Add `url` link that points to the home page?

### ISSUE THREAD

**Issue by bnjmn** [torchbox/wagtail#1530]
How do I add a `url` link to the home page in a template? I'm not sure what the view function name is, or if there is even a distinct one, so I can't get the built-in `url` template tag to work. I've also tried the `wagtail` tag for `pageurl` but can't seem to guarantee reference to the home page in all templates. 

Also, I'd like this to work for any page including static pages made using `TemplateView` (in `django.views.generic`). I'd like to do something like this:

```
{% extends 'base.html' %}
<h1>Hello World</h1>
<p>Go to <a href="{% url 'home_page' %}">Home Page</a></p>
```
I find it a little strange since the homepage is required and basically generated as a fixture in the database but there doesn't seem to be an easy way to access it without querying for the homepage using the `id` that was created for me. What is the `wagtail` way of making this work? 

Thanks for any help. Keep up the great work!

**Comment by gasman** [comment]
Hi @bnjmn - please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
