### ISSUE TITLE
The project template should list INSTALLED_APPS in precedence order

### ISSUE THREAD

**Issue by pjdelport** [torchbox/wagtail#1536]
Currently, the [project template's INSTALLED_APPS](https://github.com/torchbox/wagtail/blob/v1.0/wagtail/project_template/project_name/settings/base.py#L26-L52) lists the default apps from most generic to most specific, but this is the inverse of the order Django expects them in: apps listed earlier override the resources of apps listed later.

A better default value for this setting might be:

```python
INSTALLED_APPS = [
    'home',
    'search',

    'wagtail.wagtailforms',
    'wagtail.wagtailredirects',
    'wagtail.wagtailembeds',
    'wagtail.wagtailsites',
    'wagtail.wagtailusers',
    'wagtail.wagtailsnippets',
    'wagtail.wagtaildocs',
    'wagtail.wagtailimages',
    'wagtail.wagtailsearch',
    'wagtail.wagtailadmin',
    'wagtail.wagtailcore',

    'modelcluster',
    'compressor',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```

**Comment by gasman** [comment]
Does the current ordering cause any actual problems? If not, I would prefer to stick to the more familiar arrangement (see for example https://docs.djangoproject.com/en/1.8/intro/tutorial01/#activating-models ), as that avoids the impression that Wagtail is doing anything non-standard.

**Comment by pjdelport** [comment]
It will at least cause problems as soon as users try to override any templates the way many other Django apps expect them to: instead of working, the templates will just silently get ignored, which is a frustrating failure mode for newcomers to have to struggle with.

Fixing this should not give any impression that Wagtail is being non-standard: the Django docs ([link](https://docs.djangoproject.com/en/1.8/ref/templates/api/#django.template.loaders.app_directories.Loader)) are quite specific about the order INSTALLED_APPS should be listed in:

> The order of `INSTALLED_APPS` is significant! For example, if you want to customize the Django admin, you might choose to override the standard `admin/base_site.html` template, from django.contrib.admin, with your own `admin/base_site.html` in `myproject.polls`. You must then make sure that your `myproject.polls` comes before `django.contrib.admin` in `INSTALLED_APPS`, otherwise `django.contrib.admin`’s will be loaded first and yours will be ignored.

I think the current version of the polls tutorial is just broken, and should be fixed. The tutorials [next page](https://docs.djangoproject.com/en/1.8/intro/tutorial02/#customize-the-admin-index-page), in fact, covers overriding the admin's base template, which won't actually work until the example's `INSTALLED_APPS` is fixed like the above.

**Comment by timheap** [comment]
I second this. Having apps installed in the order noted by @pjdelport is the only way for overrides to work in the expected way. It is how I expect projects to work, and is how I structure my projects. I was surprised when Wagtail did *not* endorse this way in a new project, not the other way around.

**Comment by gasman** [comment]
OK, fair enough! Would be happy to accept a patch for this.

**Comment by pjdelport** [comment]
I went ahead and filed a Django documentation bug for this too, by the way: [#25153](https://code.djangoproject.com/ticket/25153)

**Comment by pjdelport** [comment]
@gasman: PRed. :)

**Comment by kaedroho** [comment]
Merged, thanks!
