### ISSUE TITLE
permission_required decorators redirect to a broken URL

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1539]
When a user attempts to access a view that is guarded by a `permission_required` decorator, and the user does not have the required permission, they are redirected to a broken URL of the form `http://localhost:8000/admin/images/django.contrib.auth.views.login?next=/admin/images/`.

To reproduce (on wagtaildemo):
* create a group with no permissions apart from 'can log into Wagtail admin'
* create a user in that group and no others
* log in as that user
* visit `/admin/images/`

**Comment by gasman** [comment]
Having made some initial steps towards introducing class-based views to wagtailadmin in this branch https://github.com/gasman/wagtail/tree/feature/collections3 , I've discovered that `permission_required` decorators are quite horrible to integrate into CBVs, and so I've come up with an alternative mixin-based implementation here https://github.com/gasman/wagtail/commit/feb4c08ae116f2cfb62535d4d37b0e51aacbe884 .

As a nice side effect, this implementation doesn't suffer from this issue (because it's not tied to the `LOGIN_URL` setting). So, we "just" need to convert the rest of the wagtail admin to CBVs, and this will be fixed :-)

**Comment by kaedroho** [comment]
Django 1.9 introduces a mixin like that, might be useful as reference: https://docs.djangoproject.com/en/dev/topics/auth/default/#redirecting-unauthorized-requests-in-class-based-views
