### ISSUE TITLE
Don't display the huge block selection box if a StreamField can contain only one type of block

### ISSUE THREAD

**Issue by LiquidPL** [torchbox/wagtail#1549]
The plus button that shows the block selection box in a StreamField should just add the block if only one type of them can be added.

**Comment by SalahAdDin** [comment]
A screenshot please :D

**Comment by alexgleason** [comment]
Can we discuss what should happen when the page first loads? I'm tempted to just insert one block, but if that block has required fields and the whole StreamField is required, the user would have do delete the block to proceed. For now I've left it so you must choose the first block by clicking it, then subsequent additions are automatically added.

**Comment by gasman** [comment]
@alexgleason That sounds sensible enough, yep. It might be slightly better to say "If (and only if) the StreamField is required, insert an initial block" - but that's certainly not a showstopper, and off the top of my head I'm not sure if we actually enforce required=True for StreamFields in any meaningful way at the moment.
