### ISSUE TITLE
Image upload failed with wagtail 1.0

### ISSUE THREAD

**Issue by mistguy** [torchbox/wagtail#1550]
I installed wagtail in two machines, one for development and one for deployment.
However, I cannot upload images with deployment machine and all it says is "Sorry, upload failed"

Here is my `pip freeze` in deployment machine:

    backports.ssl-match-hostname==3.4.0.2
    Beaker==1.5.4
    beautifulsoup4==4.4.0
    blivet==0.61.0.26
    Brlapi==0.6.0
    chardet==2.0.1
    configobj==4.7.2
    configshell-fb==1.1.14
    coverage==3.6b3
    cupshelpers==1.0
    decorator==3.4.0
    di==0.3
    Django==1.8.3
    django-appconf==1.0.1
    django-compressor==1.5
    django-modelcluster==0.6.2
    django-sendfile==0.3.9
    django-taggit==0.16.2
    django-treebeard==3.0
    dnspython==1.11.1
    ethtool==0.8
    firstboot==19.5
    freeipa==2.0.0a0
    fros==1.0
    glusterfs-api==3.6.0.29
    html5lib==0.999999
    iniparse==0.4
    initial-setup==0.3.9.23
    ipaplatform==4.1.0
    ipapython==4.1.0
    IPy==0.75
    javapackages==1.0.0
    kerberos==1.1
    kitchen==1.1.1
    kmod==0.1
    langtable==0.0.13
    lxml==3.2.1
    Mako==0.8.1
    MarkupSafe==0.11
    matplotlib==1.2.0
    netaddr==0.7.5
    nfsometer==1.7
    NFStest==1.0.8
    nose==1.3.0
    numpy==1.7.1
    Paste==1.7.5.1
    phonopy==1.9.5
    Pillow==2.9.0
    policycoreutils-default-encoding==0.1
    pyasn1==0.1.6
    pycups==1.9.63
    pycurl==7.19.0
    pygobject==3.8.2
    pygpgme==0.3
    pyinotify==0.9.4
    pykickstart==1.99.43.17
    pyliblzma==0.5.3
    pyOpenSSL==0.13.1
    pyparsing==1.5.6
    pyparted==3.9
    python-augeas==0.4.1
    python-dateutil==1.5
    python-default-encoding==0.1
    python-dmidecode==3.10.13
    python-ldap==2.4.15
    python-meh==0.25.2
    python-nss==0.16.0
    python-yubico==1.2.1
    pytz==2015.4
    pyudev==0.15
    pyusb==1.0.0b1
    pyxattr==0.5.1
    PyYAML==3.10
    qrcode==5.0.1
    requests==2.7.0
    rtslib-fb==2.1.50
    scipy==0.12.1
    seobject==0.1
    sepolicy==1.1
    setroubleshoot==1.1
    six==1.9.0
    slip==0.4.0
    slip.dbus==0.4.0
    SSSDConfig==1.12.2
    targetcli-fb===2.1.fb37
    Tempita==0.5.1
    Unidecode==0.4.18
    urlgrabber==3.10
    urwid==1.1.1
    wagtail==1.0
    Willow==0.2.1
    yum-langpacks==0.4.2
    yum-metadata-parser==1.1.4

The problem is that the only error message is `"POST /admin/images/multiple/add/ HTTP/1.1" 500 20338` and though I successfully uploaded images in development machine, I cannot find out what happened in deployment machine.

BTW: I can upload documents in deployment machine.

**Comment by mistguy** [comment]
Ok, it was because I didn't install libjpeg-devel

**Comment by SalahAdDin** [comment]
For remember.

**Comment by BobStein** [comment]
I also had "Sorry, upload failed." for images and documents. The solution was to set directory permissions so that ubuntu apache could create the media directory.  

    chgrp -R www-data SITE_DIRECTORY
    chmod -R g+w SITE_DIRECTORY

Details at http://stackoverflow.com/questions/1682440/permission-denied-error-with-django-while-uploading-a-file/7704732#7704732
