### ISSUE TITLE
Dynamic subpage_types

### ISSUE THREAD

**Issue by jungornti** [torchbox/wagtail#1552]
Hello.
We are creating news site with wagtail.

Our model structure is following:

    Index page
        Category
            Article
            Article

Category page is defined like this:

    class CategoryPage(Page):                                            

        subpage_types = ['articles.ArticlePage', 'articles.CategoryPage']

Categories may be nested and should contain only categories or only articles (leaf category node should contain only articles). How can we achieve this? Current realisation allows categories to be nested along with articles (category may have article and category childs toghether). I think we can achieve this by making subpage_types property of the page.

**Comment by gasman** [comment]
As mentioned in https://github.com/torchbox/wagtail/issues/194#issuecomment-46441728, I'm not keen on making the subpage rules configurable dynamically, because I think it's useful to be able to run the rules in reverse ("where can I add a page of type ArticlePage?")

**Comment by jungornti** [comment]
Okay, thank you.
