### ISSUE TITLE
Access (render) images from the Wagtail API

### ISSUE THREAD

**Issue by bgryszko** [torchbox/wagtail#1557]
Hey, thanks for an awesome library! 

I'm wondering if there is a way to render image just by using actual REST API? As I'm unable to access file path from current implementation.

**Comment by gasman** [comment]
Hi @bgryszko - please use the [Google Group](https://groups.google.com/forum/#!forum/wagtail) for support requests.

**Comment by bgryszko** [comment]
Thanks @gasman, and sorry posting question here. Just if anyone stepped here while looking for solution, I've resolved it by serving images with tweaked `https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/views/frontend.py` to my needs.
