### ISSUE TITLE
related names back to front

### ISSUE THREAD

**Issue by emg36** [torchbox/wagtail#1560]
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L1191

group and page related names are round the wrong way

**Comment by gasman** [comment]
Hi @emg36 - I'm pretty sure the current arrangement is correct. `related_name` adds a property to the related model, so this gives us `group.page_permissions` (for finding out which pages this group has permission on) and `page.group_permissions` (for finding out which groups have permission over this page).
