### ISSUE TITLE
Documentation of tabbed interface definition mixes old and new syntaxes

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1562]
These pages still show the old style (`Model.content_panels = []`)
http://docs.wagtail.io/en/latest/reference/contrib/forms.html?highlight=content_panels
http://docs.wagtail.io/en/latest/topics/streamfield.html?highlight=content_panels
http://docs.wagtail.io/en/latest/reference/pages/model_recipes.html?highlight=content_panels
http://docs.wagtail.io/en/latest/topics/snippets.html?highlight=content_panels

**Comment by gasman** [comment]
All fixed in various PRs from @richbrennan, I believe!
