### ISSUE TITLE
Change page type with saving

### ISSUE THREAD

**Issue by InvDeath** [torchbox/wagtail#1563]
When I change content (fields value as admin) of my page the type of this page changes to. http://prntscr.com/7ytjra

**Comment by gasman** [comment]
Hi @InvDeath,
Unfortunately there's not enough information here for us to investigate this issue. If you are able to reproduce this problem consistently, please reopen this ticket with a minimal code sample that demonstrates the problem, and an exact sequence of steps for reproducing it. Thanks!
