### ISSUE TITLE
Compress related error -  'admin/js/urlify.js' could not be found in the COMPRESS_ROOT

### ISSUE THREAD

**Issue by jorge-marques** [torchbox/wagtail#1566]
Hi, I'm getting the following error when trying to edit a page in the admin:

    UncompressableFileError at /admin/pages/2/edit/
    'admin/js/urlify.js' could not be found in the COMPRESS_ROOT

In my settings file I have:

    COMPRESS_PRECOMPILERS = (
        ('text/x-scss', 'django_libsass.SassCompiler'),
    )

Removing this setting makes the page work normally.
However, I'm also using the precompiler for my frontend, and it does not compile the .scss unless I have this defined.

**Comment by gasman** [comment]
duplicated by #1567
