### ISSUE TITLE
Compress related error -  'admin/js/urlify.js' could not be found in the COMPRESS_ROOT

### ISSUE THREAD

**Issue by jorge-marques** [torchbox/wagtail#1567]
Hi, I'm getting the following error when trying to edit a page in the admin:

    UncompressableFileError at /admin/pages/2/edit/
    'admin/js/urlify.js' could not be found in the COMPRESS_ROOT

In my settings file I have:

    COMPRESS_PRECOMPILERS = (
        ('text/x-scss', 'django_libsass.SassCompiler'),
    )

Removing this setting makes the page work normally.
However, I'm also using the precompiler for my frontend, and it does not compile the .scss unless I have this defined.

I'm using Django 1.8.2 and wagtail 1.0

**Comment by jorge-marques** [comment]
Sorry, not sure how I ended up creating a new issue. Could have sworn I was just making an edit.

**Comment by gasman** [comment]
It looks like you need to add `'django.contrib.admin'` to your INSTALLED_APPS.

(Ideally we wouldn't depend on this, and I'm not sure why enabling django_libsass causes this to fail. However, it's already on our todo list to drop urlify.js as part of #1443, so this will be solved soon enough.)
