### ISSUE TITLE
Prevent Children for Page 

### ISSUE THREAD

**Issue by wide-awake** [torchbox/wagtail#1568]
I need my page instance to be the last, "bottom" of the tree. Yet it is not possible to do something like this:
```
class MyLastPage(Page):
    # ...

    class Meta:
        can_have_children = False
```

Did you plan to add similar functionality soon? Or can you point me, where i can wrote it myself?

**Comment by gasman** [comment]
This can be done by setting `subpage_types` to an empty list:

    class MyLastPage(Page):
        # ...

        subpage_types = []

(note that it's still possible to move pages from elsewhere - this is being addressed in #638)
