### ISSUE TITLE
In documentation "create_revision" should be "save_revision"

### ISSUE THREAD

**Issue by JHSaunders** [torchbox/wagtail#1582]
In version 1.0 (and probably longer) the method to create a PageRevision is page.save_revision(), not page.create_revision(). The docs (http://docs.wagtail.io/en/v1.0/reference/pages/model_reference.html) refer to a create_revision function, which does not exist. Nor is the save_revision function documented in the model reference. This is a pretty critical system to understand if you are programmatically creating content (such as for migrations from other systems).

**Comment by JHSaunders** [comment]
This relates to #1101.

**Comment by kaedroho** [comment]
Thanks! Typo fixed.

The other issues you reported are covered by other tickets, so I'll close this one.

 - #1437 - Reference docs for internal models
 - #1101 - Topic docs for programmatically creating content
