### ISSUE TITLE
Page Organization Documentation

### ISSUE THREAD

**Issue by gmeans** [torchbox/wagtail#1583]
I spent a couple of hours stumbling with a url issue for a page due to not being clear on how pages should be organized within the admin interface.

I think it would help to mention that all pages need to either be set as the default page for a site, or children of a default page for a site. Otherwise you see the 'Live' button being grayed out, and in my case, get weird results from the .url and .full_url methods.

It also caused us some confusion when we discussed the possibility of A/B testing home page designs. 

- Should each home page design exist in root? That's not possible since switching the default home page for a site makes the children of the original "Not associated with the website".

In a future release it might be more intuitive to merge the Explorer and Site interfaces since you have to have a Site w/ a Root Page and content organized beneath it. Perhaps make the parent node a "hidden" page so that content is organized beneath a "site" vs. a Page.

Just some thoughts. Great CMS!

**Comment by wildekin** [comment]
I completely agree, just recently having struggled with this building my first wagtail project.

I setup a blog index, inside that a post model. If I want to make a new post, I have to click explorer > homepage > blog

My first instinct was to put the blog as a child in the root so it was visible in the first explorer level. Then the url didn't work

Is there any documentation on how to change the left hand menu to include links into various levels of the site? So I can just have Blog post below explorer? It just seems really convoluted to have to access the explorer > homepage to do everything

**Comment by SalahAdDin** [comment]
Well, i have the same problem, but happen when i put the root as home page, this doesn't work.
I asked here for my problem, and try many things for solve it, and read the docs.

Will be great if the docs will be more clear :D

**Comment by gasman** [comment]
I think that what would really help here is some extra signposting within the Explorer interface. Explaining the behaviour in the docs is a good start, but if people don't have to look at the docs at all, that's even better...

I propose adding some help text above the page listing (in either the 'information' or 'warning' style), whenever there is no site record associated with the location being browsed. The message would differ depending on 1) whether this the root level or not 2) whether the user has 'add site' permission, or just 'add page'. (If the user doesn't have permission to add pages at that location, I would say we don't need a message at all.)

Suggested text - feel free to suggest improvements:

**Root level, 'add site' permission - 'info' message**

> The root level is where you can add new sites to your Wagtail installation. Pages created here will not be available at any URL until they are associated with a site through the Settings -> Sites area. To add pages to an existing site, create them as children of the homepage.

**Root level, no 'add site' permission - 'info' message**

> Pages created here will not be available at any URL. To add pages to an existing site, create them as children of the homepage.

**Non-root level, 'add site' permission - 'warning' message**

> There is no site record for this location. Pages created here will not be available at any URL until a site is configured through the Settings -> Sites area.

**Non-root level, no 'add site' permission - 'warning' message**

> There is no site record for this location. Pages created here will not be available at any URL.

**Comment by SalahAdDin** [comment]
It's great @gasman, tank you :D

**Comment by gasman** [comment]
Signposting messages implemented in #1612.
