### ISSUE TITLE
Backwards compatibility for EditorsPick model move

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1588]
This was previously referenced from the project template and it has now been moved to its own module:
https://github.com/torchbox/wagtail/blob/stable/1.0.x/wagtail/project_template/search/views.py#L24

Anyone who created their site on 1.0 and upgraded to 1.1 will get this error: ``ImportError: cannot import name 'EditorsPick'``. It's an obvious fix, but annoying as everyone will get it.

Ideally, we should come up with a backwards-compatible fix which shows a ``DeprecationWarning`` and remove it completely in 1.3.

**Comment by gasman** [comment]
+1 - I didn't realise we were missing this. We definitely want this to go through the proper deprecation timeline.

**Comment by gasman** [comment]
What was the conclusion on this? Did we decide that it was better to let this fail in an obvious way, rather than put in hacks to accommodate references to a non-existent wagtailsearch.EditorsPick model?

**Comment by gasman** [comment]
Closing as discussed - there's no clean way to preserve backwards compatibility when moving a model between apps. The release notes now cover the changes that need to be made when upgrading.

**Comment by fdemmer** [comment]
link to the release notes for the lazy: http://docs.wagtail.io/en/v1.1/releases/1.1.html?highlight=editorspick#promoted-search-results-no-longer-in-wagtailsearch
