### ISSUE TITLE
Text wrap on image does not work as expected

### ISSUE THREAD

**Issue by itsMagondu** [torchbox/wagtail#1599]
Hi. Thanks for the amazing app. Loving it so far.

I have an issue where if I add an image and align it to the left as seen below, it works on the richtext editor but breaks on the frontend. Is this something that is broken or should it be a feature request? `float: left;` on the <img> fixes this however those adding content cannot use this

 - Wagtail admin interface using richtext
![wagtail-backend](https://cloud.githubusercontent.com/assets/1202275/9228740/816d64ee-4122-11e5-87c1-216062b6d032.png)

 - My frontend
![wagtail-frontend](https://cloud.githubusercontent.com/assets/1202275/9228741/818c9828-4122-11e5-9284-eb632bf08e9c.png)

Thanks

**Comment by davecranwell** [comment]
Wagtail does not generate any CSS for your front end, it only adds the classes to the elements. It's up to the author to write this CSS. 

The documentation provides some example CSS in one related area: http://wagtail.readthedocs.org/en/v1.0/topics/writing_templates.html?highlight=responsive#responsive-embeds however no example CSS is provided for supporting the three default image alignments. This is a documentation omission if anything - Wagtail itself would never generate the CSS you need.

**Comment by itsMagondu** [comment]
Thanks. I will add the CSS on my end. However the richtext editor is confusing too since it does the aligning as seen on the images above.
