### ISSUE TITLE
'Title' column heading misaligned in explorer for users without 'publish' permission

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1608]
For users without publish permission, the 'order' column of the explorer is omitted. This results in the 'title' column heading being pushed too far to the left:
<img width="1173" alt="screen shot 2015-08-14 at 13 26 09" src="https://cloud.githubusercontent.com/assets/85097/9273275/3d3ac9c8-428b-11e5-9a02-dcfdd71482f8.png">

Rather than adding a special case in the CSS to give it an extra margin, I think it would be cleaner to consistently include the 'order' column all the time (and leave it blank for users without the relevant permission) - that way we avoid additional special-casing further down the line (e.g. https://github.com/torchbox/wagtail/issues/1583#issuecomment-131078851 - adding a row to contain a help message will require `<td colspan="5">` or `<td colspan="6">`). This involves some rewiring of the table logic, though.

**Comment by davecranwell** [comment]
Agree with this approach. Will action.

**Comment by kaedroho** [comment]
PR: https://github.com/torchbox/wagtail/pull/1611
