### ISSUE TITLE
Page reordering interface displays "Page of ." in the footer

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1609]
<img width="984" alt="screen shot 2015-08-14 at 13 57 31" src="https://cloud.githubusercontent.com/assets/85097/9273365/7781d83c-428c-11e5-82bf-bc7a6726c1de.png">

**Comment by Vorlif** [comment]
Hi @gasman -  can you close the issue? The problem should be resolved with #1496.

**Comment by gasman** [comment]
@Vorlif Ah, yes - thanks for pointing that out!
