### ISSUE TITLE
Locking a page makes it possible to unpublish a page without a method to undo

### ISSUE THREAD

**Issue by creativedutchmen** [torchbox/wagtail#1615]
When a page is locked, it is still possible for moderators (and maybe editors, I did not check) to unpublish the page.
However, there is no way to publish the page again, because the only way to publish a page is in the edit screen.

In my opinion a locked page should be just that: locked. Meaning no changes can be made, including unpublishing.

**Comment by tomdyson** [comment]
We think you're right. We'll review locking behaviour (in the absence of any PRs).
