### ISSUE TITLE
Always get "This field cannot be blank" despite input

### ISSUE THREAD

**Issue by pymarco** [torchbox/wagtail#1617]
I have create a new wagtail site. I log in to admin and edit the home page (which has no title by default). I enter a title and click "Publish". The form does not go through and there are validation errors for title field and slug field. This is very frustrating. I can't understand why this would be happening.

Is this a bug?

**Comment by Vorlif** [comment]
Is your page model a child of the Page class?

```
class YourPage(Page):
    ...
```
Then are 'title' and 'slug' a part of the Page class and are required.
You have to therefore display in the admin interface to fill them.

To display the page variables in the admin interface add the the page panels to YourPage panels.

```
class YourPage(Page):
    ...

    content_panels = Page.content_panels + [
        ...
    ]
```

Can you otherwise send a small example?

Flori

**Comment by pymarco** [comment]
Hi Flori,

Thank you for responding. I am a little confused by what you wrote. Just to confirm both page and slug fields do display in the admin. I enter data in the title field, and slug is autopopulated. Despite this I get field is blank validation error. 

I have reproduced this locally with the most basic example, the home app provided by wagtail without modification

```

**Comment by Vorlif** [comment]
Hi Pymarco,

I had your mistake first misinterpreted.
I just tested it and got no validation error.
Unfortunately, I can not help you here.

Which version of Wagtail you use? 1.0?
Which browser / version?

**Comment by pymarco** [comment]
Thanks

Wagtail 1.0
FF 40
Chromium 43

served with "runserver"

Really disheartening, I'm so excited to actually use Wagtail

**Comment by Vorlif** [comment]
Quite rightly. Wagtail is very cool.
But now I'm confused. This is a strange issue.

Which python version?

**Comment by pymarco** [comment]
Python 2.7.6

It must be something I change in this one project I created. Because I just created a fresh one and the homepage's title defaults to "Homepage". But for the project I am having trouble with the title is blank. I just diffed both project's home app and they are identical.

**Comment by pymarco** [comment]
Ok, I think I've figured out what has happened. I had added wagtail_modeltranslations app which added a migration to wagtailcore/migrations. Then I removed wagtail_modeltranslations but the migrations it had created were left behind. I will close.

**Comment by Vorlif** [comment]
Okay. Good to know.

**Comment by ChiragKanzariya** [comment]
> I have create a new wagtail site. I log in to admin and edit the home page (which has no title by default). I enter a title and click "Publish". The form does not go through and there are validation errors for title field and slug field. This is very frustrating. I can't understand why this would be happening.
> 
> Is this a bug?

You can just fill form in admin panel because there, title field is required field there in admin side. 
If you want to fix this bug than you have to remove title field from admin panel and that's it. You can solved your error

**Comment by even311379** [comment]
My solution was delete all migration files, and make migrations again.
Then, it's good to go.
