### ISSUE TITLE
The search bar only searches for pages

### ISSUE THREAD

**Issue by creativedutchmen** [torchbox/wagtail#1638]
The search bar in the navigation on the left only searches for pages by default. When a page is found, the option to search in other sections (images, documents) is shown. However, this functionality is hidden when no page is found.

To me, this sounds backwards. No pages are found, so chances are the user wasn't searching for a page in the first place. Displaying other areas to be searched would be very helpful.

The same holds for images and documents: if there is a match, the other sections are shown. If there is no match, they are hidden. In my opinion they should be shown at all times, making search more user friendly.

**Comment by gasman** [comment]
Makes sense - thanks for the suggestion!

**Comment by alexgleason** [comment]
Do snippets get searched too?

**Comment by gasman** [comment]
Implemented in #1800
