### ISSUE TITLE
Make snippet_type parameter of SnippetChooserPanel optional

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1639]
http://docs.wagtail.io/en/v1.0/reference/pages/editing_api.html#wagtail.wagtailadmin.edit_handers.wagtail.wagtailsnippets.edit_handlers.SnippetChooserPanel

Specifying a snippet model as the second argument of SnippetChooserPanel should not be necessary - it should be possible to pick that up from the foreign key, as we now do for PageChooserPanel.

**Comment by kaedroho** [comment]
This appears to be implemented in: https://github.com/torchbox/wagtail/pull/1375

**Comment by gasman** [comment]
Doh!
