### ISSUE TITLE
Add a system check to verify that Pillow / Wand has JPEG / PNG / GIF support compiled in

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1644]
(moved from https://github.com/torchbox/wagtaildemo/issues/12)

It's easy to miss the fact that libjpeg/zlib should be installed prior to installing Pillow, and this will result in a build of Pillow without JPEG/PNG support, and hard-to-identify issues with images not displaying.

We should add a system check on server startup to warn if the image library in use (Pillow or Wand) is missing support for these formats.

**Comment by FlipperPA** [comment]
Quick question, by server startup do you just mean on runserver start up only, or also a hook into gunicorn / uwsgi / mod_wsgi? By the look of the closed issue, it looks like runserver only, but wanted to check before diving in.

**Comment by gasman** [comment]
@FlipperPA That's a good point... I was imagining that we'd use Django's system check framework <https://docs.djangoproject.com/en/1.8/topics/checks/> for this, to display a warning on the console - but that's not so useful for server-level issues like this, where everything might be perfectly fine in development and only be broken on the live server, where those warnings won't be seen. (Since we've mostly seen this coming up in the context of new users installing wagtaildemo, I hadn't considered the case of live server deployments at all. But catching the issue there is just as important, if not more...)

Perhaps, then, it would be more appropriate to display a warning bar on the admin homepage when the user is logged in as a superuser.

**Comment by gasman** [comment]
I've implemented the first half of this in #1718 - this adds the system check, but doesn't yet display a message on the admin dashboard.

**Comment by gasman** [comment]
Pillow 3.x makes it hard to get this wrong now - at this point I don't think it's worth the trouble of prettifying the error message.
