### ISSUE TITLE
"Your most recent edits" listing excludes pages that another user has subsequently edited

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1646]
https://github.com/torchbox/wagtail/pull/1231#issuecomment-135470115

The "Your most recent edits" listing on the admin dashboard only includes pages whose latest revision was created by the current user. If Alice edits a page, then Bob edits the same page, it falls off Alice's list even if it's the one she edited most recently.

**Comment by kaedroho** [comment]
Perhaps could be done as part of: https://github.com/torchbox/wagtail/issues/496

**Comment by mjec** [comment]
Unless anyone has a better idea I think best fix might be going back to a raw query but moving the `user_id` check to within the subquery:

        self.last_edits = PageRevision.objects.raw(
            """
            select wp.* FROM
                wagtailcore_pagerevision wp JOIN (
                    SELECT max(created_at) as max_created_at, page_id FROM wagtailcore_pagerevision where user_id = %s group by page_id
                ) as max_rev on max_rev.max_created_at = wp.created_at order by wp.created_at desc
            """, [request.user.id])[:5]

**Comment by kaedroho** [comment]
Thanks @mjec. I'm happy to go back to a raw query if it fixes the logic.

**Comment by khink** [comment]
All this needs is a test, i'm going to work on it.

**Comment by dirtycoder** [comment]
@gasman, @kaedroho I think I have an alternative solution for this, but maybe it's not very elegant. :wink: 

What about adding an additional boolean field to the `PageRevision` to mark it as the latest user revision on that `Page`?
I made a quick test with this `latest_user_revision` and the impact on the performance was none, but I tried it with a small database, 20k pages and 20k revisions.
I will generate more pages and revision to test it with a bigger database.
Also, with this it will not be necessary to go back to the raw query.

**Comment by gasman** [comment]
@dirtycoder I'm not really keen on adding more "moving parts" to the database just to serve this one panel - I'd much rather find a way that works within the current database structure. (It doesn't seem like this should be a hard query to write efficiently, as long as all the lookups are done in the right order and the appropriate indexes are in place.)

**Comment by dirtycoder** [comment]
Sure!

An index on the `created_at` improved the situation by a good margin, removing the seq scan for the max `created_at` in the subquery. But not as much as the current, and incorrect, query.

But as my database is small I'm just analyzing the query plan.
I'll probably take another look at it during the weekend.

**Comment by dirtycoder** [comment]
Sure!

An index on the `created_at` improved the situation by a good margin, removing the seq scan for the max `created_at` in the subquery. But not as much as the current, and incorrect, query.

But as my database is small I'm just analyzing the query plan.
I'll probably take another look at it during the weekend.

**Comment by dirtycoder** [comment]
Sure!

An index on the `created_at` improved the situation by a good margin, removing the seq scan for the max `created_at` in the subquery. But not as much as the current, and incorrect, query.

But as my database is small I'm just analyzing the query plan.
I'll probably take another look at it during the weekend.
