### ISSUE TITLE
Development instructions unclear about which wagtaildemo in contributing docs

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1651]
In the contributing docs, it says:

> So in the directory containing wagtaildemo, run:

The problem being that there are two wagtaildemo directories by default: the one git clone creates, and the one inside of the repo.

https://github.com/torchbox/wagtail/blob/master/docs/contributing/developing.rst#using-the-demo-site--vagrant

**Comment by gasman** [comment]
Hi @alexgleason - thanks for pointing this out. Would it fix things if we said "in the directory containing the wagtaildemo repo"?

**Comment by alexgleason** [comment]
Yep! That's definitely more clear.
