### ISSUE TITLE
Allow the creation of pages that are not backed by a table

### ISSUE THREAD

**Issue by jorge-marques** [torchbox/wagtail#1653]
Is there any way to create a page that is not backed by a table?
I have a couple of pages that don't need any additional fields besides the ones provided by the Page model.

**Comment by gasman** [comment]
Hi @jorge-marques - please use the Wagtail Google group https://groups.google.com/forum/#!forum/wagtail for support queries.

**Comment by jorge-marques** [comment]
Hi @gasman.
I've rephrased the issue, hopefully it's more adequate for github now.
I believe the example I provided makes some sense, at least conceptually. I'm trying to understand if this use case was anticipated by the wagtail developers. I believe this could be a useful feature/optimization.
If you still feel this is not the place for this discussion, please close the issue again and I'll try the support or maybe the developer group.

**Comment by gasman** [comment]
It's possible to create page types that have no additional fields - the HomePage class provided for a fresh project is an example: https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/home/models.py
IIRC, this creates a table consisting only of a primary key, which isn't very pretty, but it does the job. Do you see any practical advantage to being able to define a model with no table at all?

**Comment by kaedroho** [comment]
Preventing Django from creating that table would be tricky. Things might get complicated if you decide to add a field to the empty model, which would mean that the table would also need to be created and records inserted for every existing instance of that page type. I imagine there would be many edge-cases that we would need to consider as well.

Perhaps you could use a proxy model instead? https://docs.djangoproject.com/en/1.8/topics/db/models/#proxy-models

**Comment by jorge-marques** [comment]
@gasman I suppose it's not really a big deal. I have a website that's mostly static, but has a couple of managed page types. I found it easier to create wagtail pages for the "static" pages than to mix and match "manual" routes with wagtail managed pages. It would just be neater for my current use case, but the issue mentioned by @kaedroho is better avoided. It's no big deal.

@kaedroho, regarding the use of a proxy model, wagtail does not seem to pick it up, but maybe I'm doing something wrong:

    class MyPage(Page):
        is_abstract = False
    
        class Meta:
            proxy = True
            verbose_name = 'My Page'
