### ISSUE TITLE
Snippets Admin Error

### ISSUE THREAD

**Issue by saeschdivara** [torchbox/wagtail#1664]
Hi I am new to wagtail so I tried an example from the documentation with the following code:

``` python
from __future__ import unicode_literals

from django.db import models

from wagtail.wagtailcore.models import Page

from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel
from wagtail.wagtailsnippets.models import register_snippet


@register_snippet
class Advert(models.Model):
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)

    panels = [
        FieldPanel('url'),
        FieldPanel('text'),
    ]

    def __unicode__(self):
        return self.text


class HomePage(Page):
    advert = models.ForeignKey(
        'Advert',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

HomePage.content_panels = [
    SnippetChooserPanel('advert', Advert)
]
```

And I got the following error:
![bildschirmfoto vom 2015-09-04 07 49 26](https://cloud.githubusercontent.com/assets/4942808/9677392/984b38a8-52d9-11e5-88fd-a40ec407e390.png)
![bildschirmfoto vom 2015-09-04 07 49 41](https://cloud.githubusercontent.com/assets/4942808/9677393/984ed274-52d9-11e5-8c77-ceffd799c43a.png)

**Comment by gasman** [comment]
Hi @saeschdivara - I'm unable to replicate this error. Your `HomePage.content_panels` definition is missing the 'title' field, which is likely to cause problems, but even so, I can't recreate the same error that you show here.

Please can you provide an exact sequence of steps for producing this, starting from a new Wagtail project (as produced by `wagtail start`)?

(I'll close this ticket for now, but please re-open if you can provide this information)

**Comment by saeschdivara** [comment]
Ok, I have not found out yet, why it doesn't work but it seems that a 3rd party package has something to do with my error
