### ISSUE TITLE
Sanitize content pasted from MS Word

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1669]
We recently ran into an issue where content writers are pasting content from MS Word (in fact they always write their content in Word as they are worried of losing it, given the lack of autosave on the admin UI, it is how they have always done it, they are comfortable with Word etc. etc.), and MS Word specific tags are getting introduced:

eg:

```html
<p class="MsoNormal"><span><b>Original request:</b></span><br></p><p class="MsoNormal"><span lang="EN-US" style="font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-ansi-language:EN-US">Goeie dag</span><o:p></o:p></p>

<u1:p></u1:p>

<p class="MsoNormal"><span lang="EN-US" style="font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-ansi-language:EN-US"><u1:p>&nbsp;</u1:p></span><o:p></o:p></p>
```

Currently the Wagtail whitelister fails on these tags, a better solution might be to just strip them out using a library such as https://pypi.python.org/pypi/htmllaundry/?

**Comment by gasman** [comment]
Have you customised the whitelister rules at all (using the `construct_whitelister_element_rules` hook)? I can't see how this markup could possibly pass the default whitelister rules - if I try to replicate this by pasting this code into the rich text field's hidden text area, and saving the page, the invalid attributes/elements are stripped as expected:

    <p><b>Original request:</b><br></p><p>Goeie dag</p>
    <p>&nbsp;</p>

**Comment by lee-kagiso** [comment]
No we haven't tried doing that, I don't actually know what happened
directly, but they somehow managed to pass it in without it getting
stripped out

**Comment by gasman** [comment]
OK - will close this as unable to replicate, but please reopen if you're able to provide a set of steps that reproduces this.

**Comment by lee-kagiso** [comment]
So today I finally worked out it was the html comments causing all the issue as
they weren't getting stripped out.

I see https://github.com/torchbox/wagtail/pull/1821 fixes it
