### ISSUE TITLE
UnicodeEncodeError when generating gravatar for user with an email in an internationalized domain name

### ISSUE THREAD

**Issue by LiquidPL** [torchbox/wagtail#1670]
Hello,
When I'm trying to add an user with an email using an IDN, the following UnicodeEncodeError is raised:
http://dpaste.com/2G6KVBN

**Comment by kaedroho** [comment]
Thanks for spotting

Looks like ``b(email.lower())`` to ``email.lower().encode('utf-8')`` should fix this..

**Comment by gasman** [comment]
@kaedroho That's assuming that Gravatar is also using utf-8 when calculating hashes - annoyingly https://en.gravatar.com/site/implement/hash/ doesn't specify. However, in the worst case, that just means it'll fail to find the user's avatar on Gravatar, which is far preferable to the admin breaking completely :-)

**Comment by davecranwell** [comment]
Would hope we find some time to make #319 a reality soon, reducing dependence on gravatar.

**Comment by gasman** [comment]
Fixed in 13c8e4da583b1178974c48d822fbaa411de1f755, with test added in d1ef42fe9b7d0f91d75b4ba0133a75d0066b6683
