### ISSUE TITLE
One should be able to add a redirect unique per site

### ISSUE THREAD

**Issue by colinfrankb** [torchbox/wagtail#1672]
#### Context

I have two sites, in my sites section. I have a redirect with a `old_path`  equal to `/post/news/`
I login to my 2nd site and try to add a redirect with the same `old_path`. It fails saying `Redirect with this Redirect from already exists.`

the reason is because of this line of code
```
class Redirect(models.Model):
    old_path = models.CharField(verbose_name=_("Redirect from"), max_length=255, unique=True, db_index=True)
```

the class is a unique constraint on old_path and not doing a composite constraint on site_id as well, something like

```
class Meta:
    unique_together = (
         ('old_path', 'site_id'),
    )
```

**Comment by kaedroho** [comment]
@colinfrankb Thanks for pointing this out. I think this is definitely something that should be fixed

**Comment by colinfrankb** [comment]
You're welcome, glad I could contribute :+1:

**Comment by timorieber** [comment]
Related to #1163

**Comment by juyrjola** [comment]
A similar bug is biting us, as well. We'd like to have per-site redirects, but currently there appears to be no way to have `Redirect.site` be anything else but `None`.
