### ISSUE TITLE
Page with image cannot be saved

### ISSUE THREAD

**Issue by saeschdivara** [torchbox/wagtail#1674]
I tried the following:

```python
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext as _

from wagtail.wagtailcore.models import Page

from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel
from wagtail.wagtailsnippets.models import register_snippet


class HomePage(Page):
    big_image = models.ImageField(_('Big Image'), upload_to='home_page/big_image')



HomePage.content_panels = [
    FieldPanel('big_image'),
]
```

But when I try to save the page as draft, it always tells me that I my field is required (even though I had a file selected)

Am I doing something wrong?

**Comment by kaedroho** [comment]
Please use the google group for support queries: https://groups.google.com/forum/#!forum/wagtail

To answer your question though. I think the issue may be that you've missed out the ``title`` field from ``content_panels``:

```python
HomePage.content_panels = [
    FieldPanel('title', classname="full title"),
    FieldPanel('big_image'),
]
```

Also, I noticed that you're adding image upload straight into the homepage. Could I recommend that you instead use a ``ForeignKey`` to ``wagtailimages.Image`` and make it selectable using an ``ImageChooserPanel``. This will allow editors to select images out of the images library and also allow wagtail to dynamically resize images for the template using the ``{% image %}`` tag (http://docs.wagtail.io/en/v1.0/topics/images/using_in_templates.html)

**Comment by saeschdivara** [comment]
Ok, thanks, it worked.
But it is not ```python wagtailimages.Image ``` but  ```python wagtailimages.models.Image ```
