### ISSUE TITLE
Optionally scope images to a particular site

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1699]
Some of the images we have are licenced for use by a particular site only.
Currently other sites can still select those images from the image library.

**Comment by tomdyson** [comment]
Hi Lee, this is being addressed in the forthcoming 'Collections' feature - see

https://github.com/torchbox/wagtail/wiki/Collections-RFC 

and

https://groups.google.com/forum/#!topic/wagtail-developers/kE-aDrOIzRI
