### ISSUE TITLE
Previewing a Page, uses wrong Site

### ISSUE THREAD

**Issue by colinfrankb** [torchbox/wagtail#1703]
Having two sites which are linked to two different Root Pages respectively, when Previewing a page under a root page, the wrong Site instance is attached to the request, ultimately resulting in our sites displaying the wrong css.

`response = page.serve_preview(page.dummy_request(), preview_mode)`

On serving a request to preview a page, a dummy request is made looking like the following

```
request = WSGIRequest({
            'REQUEST_METHOD': 'GET',
            'PATH_INFO': path,
            'SERVER_NAME': hostname,
            'SERVER_PORT': port,
            'wsgi.input': StringIO(),
        })
```

then the middleware is run, but in the SiteMiddleware, and subsequently the Site model, it looks for a different key in the request

`hostname = request.META['HTTP_HOST'].split(':')[0]`

This results in the default Site been chosen

**Comment by kaedroho** [comment]
Thanks for reporting @colinfrankb

**Comment by colinfrankb** [comment]
You're welcome!
