### ISSUE TITLE
Method 'reject_moderation' is not working correctly

### ISSUE THREAD

**Issue by tiagofmc** [torchbox/wagtail#1711]
When we give a specific group permissions to add/edit a certain page and the admin needs to approve or reject the revision (page moderation), if the admin rejects the revision the page will always have 'published + draft' status. 

After you reject the revision, if you edit that page it shows the content from the revision page. Even I change the status of the page with attribute 'has_unpublished_changes' to False, it doesn't work.
However, if I delete the PageRevision object it works fine, but I don't store the revisions made.

**Comment by gasman** [comment]
This is the intended behaviour. Rejecting a submission doesn't mean reverting to the last published state - it means that the editor is being asked to make further changes before submitting it again.

Rolling back to a previous revision is covered by #640 - I think this should always be a separate action to rejecting a submission, though.
