### ISSUE TITLE
Document libjpeg-dev as a required package for image uploads

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1715]
See: #1525, #1550, #1385

I also just had to debug this problem. The solution is simple, just install libjpeg (`sudo apt-get install libjpeg-dev` on Ubuntu) then reinstall Pillow. http://stackoverflow.com/a/10109941

It's not obvious to the user that this package is needed, and no error is prominently shown in the Wagtail UI other than "Sorry, file upload failed."

**Comment by gasman** [comment]
Have now updated the text at http://docs.wagtail.io/en/v1.1/getting_started/index.html to state the requirement for libjpeg / zlib more clearly: 16020af2131d310ecc0a0f23188ff767200e7377

Adding a more informative warning message on server startup is covered by #1644.

**Comment by alexgleason** [comment]
Thanks!
