### ISSUE TITLE
SCSS formatting inconsistently follows coding guidelines

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1726]
I've noticed that in some spots, spaces aren't used before `{` or after `:` characters despite this being part of the [CSS coding guidelines](http://docs.wagtail.io/en/v1.1/contributing/css_guidelines.html). I don't think it's that big of a deal, but it's confusing as a contributor as to whether I should conform my code to the rest of the document or to follow the guidelines. An example of this is #1725, where the stylesheet doesn't include spaces and if I followed the guidelines it would make the code inconsistent, so in this case I chose to actually not follow the guidelines.

**Comment by kaedroho** [comment]
Thanks! I think it would be nice to have automated checks like we have for Python/JS.

Happy to set this up on Drone/Travis if someone cleans up the code (and sets up a style checker).

**Comment by gasman** [comment]
Fixed in #1737
