### ISSUE TITLE
Consider using Bourbon for admin front-end

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1727]
[Bourbon](http://bourbon.io/) is a SCSS mixin library. Looking through Wagtail's mixins, it seems that what it's accomplishing is very similar to what Bourbon already does, except Bourbon is a specialized project, has more features, and using it would be a formalized way of writing code.

Bourbon also provides [Neat](http://neat.bourbon.io/), an add-on to Bourbon for creating grid layouts. I use these two in conjunction to develop websites and am very happy with the results.

I think we should consider using this for the Wagtail admin since it would create a greater separation of effort while ultimately benefiting both projects.

**Comment by davecranwell** [comment]
Interesting idea, Alex. We'll discuss this internally.

**Comment by gasman** [comment]
Closing as per discussion on #1731
