### ISSUE TITLE
Elasticsearch 2

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1734]
Beta 1 of Elasticsearch 2.0 has been released: https://www.elastic.co/blog/elasticsearch-2-0-0-beta1-released

Would be good to have Wagtail support for it soon

**Comment by auvipy** [comment]
will es2 be stable b4 1.2 release?

**Comment by kaedroho** [comment]
Elasticsearch 2.0 is now released https://www.elastic.co/blog/elasticsearch-2-0-0-released

There's still not much progress on porting Wagtail to it. It looks like there may be significant changes required due to the mapping refactor

**Comment by kaedroho** [comment]
I've made some cleanup to the Elasticsearch backend in #2005. This might make it easier to implement ES 2.0 support as a subclass of the existing module, just swapping out the bits that are different.

**Comment by ironhouzi** [comment]
Not sure how soon you'll be deploying 1.4, but it would be nice to have correct information about what ES version is recommended: http://docs.wagtail.io/en/v1.3.1/topics/search/backends.html#elasticsearch-backend

**Comment by jimr** [comment]
Any word on the likelihood of this landing in 1.5? It's been pushed back from 1.2 -> 1.3 -> 1.4 -> 1.5 so far...

**Comment by kaedroho** [comment]
I've made some progress with this today: #2568 #2570

Hopefully It'll be in a state to start testing tomorrow, but I doubt it'll be looked at before the 1.5 release

**Comment by kaedroho** [comment]
Elasticsearch 2 support now on master
