### ISSUE TITLE
Unable to use models with a StreamField inside Inline Panels

### ISSUE THREAD

**Issue by cpsimpson** [torchbox/wagtail#1735]
I'm running into an error when I try to add a related model that has a StreamField defined.  Whenever I try to go to the admin page to edit or create a page of this type I get a "'NoneType' object is not iterable" error.  
Below are the (simplified) models in question for a better idea of what we are trying to do. ChapteredArticlePage is the type of page I am trying to create when I run into the error:

```python
class ChapteredArticlePage(Page):
    excerpt = RichTextField(blank=True, default="")
   body = BodyField()


ChapteredArticlePage.content_panels = Page.content_panels + [
    FieldPanel('excerpt'),
    StreamFieldPanel('body'),
    InlinePanel('chapters', label="Chapters"),
]


class Chapter(models.Model):
    heading = models.CharField(max_length=512, blank=True)
    body = BodyField()

    content_panels = [
        FieldPanel('heading'),
        StreamFieldPanel('body'),
    ]

    class Meta:
        abstract = True


class ArticleChapter(Orderable, Chapter):
    page = ParentalKey(ChapteredArticlePage, related_name='chapters')


class BodyField(StreamField):
    def __init__(self, block_types=None, **kwargs):
        block_types = [
            ('Heading', HeadingBlock()),
            ('Paragraph', ParagraphBlock()),
            ('Image', ImageBlock()),
            ('Embed', EmbedBlock(icon="site")),
            ('List', blocks.ListBlock(
                blocks.RichTextBlock(label="item"), icon="list-ul")
             ),
        ]

        super(BodyField, self).__init__(block_types, **kwargs)
```

(omitting the block class code, because it doesn't seem to matter what types of blocks are included for the error to occur). 

This was discussed on the support forum: https://groups.google.com/forum/#!searchin/wagtail/Streamfield/wagtail/L8nTkFZ2BeM/2o-pJwRNBgAJ

**Comment by thenewguy** [comment]
I've encountered this as well

**Comment by richardhewett** [comment]
I have also run into this although it only seems to happen with more complex block structures given to the ``StreamField`` when using the ``StreamField`` in related models.

This works even in related models

``item = StreamField(blocks.CharBlock())``

However as soon as you try to expand it to use a more complex structure it fails

``item = StreamField(blocks.StructBlock([
        ('image', ImageChooserBlock()),
        ('link', blocks.URLBlock(required=False))])``

Now I managed to debug the ``render_form`` method and noticed that ``value`` being passed was ``None`` rather than say an empty array so I put a null check in and initialised ``value`` to ``[]``. This then loaded the edit page view for my page and I saw the related model displayed via the inline panel.

Only issue here now is that when you try to select one of the blocks assigned to the ``StreamField`` the UI just closes down rather than open up to display an editable field as it would do normally.

**Comment by mattmcmanus** [comment]
I also have run into this. The scenario I'm working on involves having pages with InlinePanels consisting of "Sections" that have a title and a SteamField body. 

Here is a simplified run down of the models. I'm new to both Python and Wagtail so I fear my ability to assist is limited, but I will spend a little more time on this.

```python
class ProtocolProcessStreamBlock(StreamBlock):
    # 6 fields

class Section(models.Model):
    title = models.CharField(max_length=255)
    body = StreamField(ProtocolProcessStreamBlock())
    panels = [
        FieldPanel('title'),
        StreamFieldPanel('body'),
    ]

    class Meta:
        abstract = True

class ProtocolProcessSection(Orderable, Section):
    page = ParentalKey('ProtocolProcessPage', related_name='section')

class ProtocolProcessPage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('section', label="Protocol Process Section"),
    ]
```

**Comment by ltakens** [comment]
I've also run into the 'NoneType object is not iterable' error when I tried to add a page in the admin interface. My page model also had an InlinePanel for a related model containing a StreamField.
After fixing this trying to iterate over the non iterable (empty) object I was able to add my page. Now, the StreamField widgets inside the InlinePanel failed..

**Comment by jaydensmith** [comment]
Any indication on when this will be fixed?

**Comment by jodth07** [comment]
I am running into the same problem. looking forward to it being worked on.

**Comment by Gagaro** [comment]
I started to work on this issue and fixed the NoneType error. I still have a few issue with the media not being included and another issue with the JS not working.

my work is there https://github.com/Gagaro/wagtail/tree/fix-inline-streamfield

**Comment by Gagaro** [comment]
I also fixed the media files missing. I'm not sure about possible side-effects though, this will need further review.

**Comment by Gagaro** [comment]
The JS is fixed as well (html_declarations weren't included). I'll test this to ensure this work and prepare the PR.
