### ISSUE TITLE
StreamField blocks jitter when you add a new one

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1738]
This occurs on the master branch. Add a new block such as a ListBlock or StructBlock, and it will start raised up too high then jitter down into place once the animation completes. Doesn't occur on 1.1 release.

**Comment by gasman** [comment]
Hi @alexgleason - I'm not seeing this on current master, when testing against wagtaildemo and adding an 'aligned image' block (I chose that one because it's just a plain unstyled StructBlock) to a blog page. Is this still occurring for you?

**Comment by gasman** [comment]
Closing, presumed fixed - please reopen if you have more info on how to replicate.
