### ISSUE TITLE
Deleting `models.PROTECT` Images, throws ProtectionError

### ISSUE THREAD

**Issue by colinfrankb** [torchbox/wagtail#1748]
When a Page model has a foreign key to an Image model and its `on_delete` is set to `PROTECT`
Trying to delete the image from the image module throws the uncaught `ProtectionError` exception.

Is it possible that this ProtectionError exception can be handled with an error message?

**Comment by gasman** [comment]
Hi @colinfrankb,
This has previously been requested in #1602 - will close this one as a duplicate.

**Comment by colinfrankb** [comment]
Thanks @gasman
