### ISSUE TITLE
Orderable bug

### ISSUE THREAD

**Issue by EduardoNogueira** [torchbox/wagtail#1749]
We have a orderable inline class and we define the "Meta" in it, when we change the order of the inlines and save the page, the new order is ignored.

**Comment by gasman** [comment]
Can you give a code example, please?

**Comment by EduardoNogueira** [comment]
# coding: utf-8

from django.db import models
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail_modeltranslation.models import TranslationMixin, SnippetsTranslationMixin
from base.models import GenericIndexPageMixin
from modelcluster.fields import ParentalKey


class Fair(SnippetsTranslationMixin, Orderable):
    page = ParentalKey(
        'fairs.FairListIndex', related_name='fairs_list')

    name = models.CharField('Nome', null=True, blank=True, max_length=100)
    description = RichTextField('Descrição', null=True, blank=True)

class Meta:
        verbose_name = u"Lista de Mercados e Feiras"

Fair.panels = [
    FieldPanel('name'),
    FieldPanel('description'),
]


class FairListIndex(TranslationMixin, GenericIndexPageMixin, Page):

    subpage_types = []
    parent_page_types = ['base.AreaIndexPage']

    class Meta:
        verbose_name = u"Lista de Mercados e Feiras"

FairListIndex.content_panels = [
    MultiFieldPanel([
        FieldPanel('title'),
    ], heading=u'Título'),
    MultiFieldPanel([
        FieldPanel('header_title'),
        ImageChooserPanel('himage'),
    ], heading=u'Título de Cabeçalho'),
    InlinePanel('fairs_list', label="Feiras e Mercados"),
]

**Comment by EduardoNogueira** [comment]
Something like this:

```
# coding: utf-8

from django.db import models
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail_modeltranslation.models import TranslationMixin, SnippetsTranslationMixin
from base.models import GenericIndexPageMixin
from modelcluster.fields import ParentalKey


class Fair(SnippetsTranslationMixin, Orderable):
    page = ParentalKey(
        'fairs.FairListIndex', related_name='fairs_list')

    name = models.CharField('Nome', null=True, blank=True, max_length=100)
    description = RichTextField('Descrição', null=True, blank=True)

    class Meta:
        verbose_name = u"Feira"

Fair.panels = [
    FieldPanel('name'),
    FieldPanel('description'),
]


class FairListIndex(TranslationMixin, GenericIndexPageMixin, Page):

    subpage_types = []
    parent_page_types = ['base.AreaIndexPage']

    class Meta:
        verbose_name = u"Lista de Mercados e Feiras"

FairListIndex.content_panels = [
    MultiFieldPanel([
        FieldPanel('title'),
    ], heading=u'Título'),
    MultiFieldPanel([
        FieldPanel('header_title'),
        ImageChooserPanel('himage'),
    ], heading=u'Título de Cabeçalho'),
    InlinePanel('fairs_list', label="Feiras e Mercados"),
]

```

**Comment by gasman** [comment]
Thanks! It sounds like the `ordering = ['sort_order']` set on the 'Orderable' parent class (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L1121-L1123) is being overwritten when you provide your own `Meta` class. We'll investigate this further.

**Comment by mmedal** [comment]
If it is indeed `ordering = ['sort_order']` being overwritten, isn't it working as intended? As described in the [Django docs](https://docs.djangoproject.com/en/1.8/topics/db/models/#meta-inheritance), wouldn't you would extend the Meta class to preserve the ordering?

    class Meta(Orderable.Meta):
        verbose_name = u"Feira"

**Comment by gasman** [comment]
Thanks @mmedal! I think you're right - this is indeed consistent with standard Django behaviour, and extending Orderable.Meta is the appropriate fix.

**Comment by kaedroho** [comment]
Docs required?
