### ISSUE TITLE
Padding on embedded video?

### ISSUE THREAD

**Issue by gmeans** [torchbox/wagtail#1750]
We're using a Rich Text field and the user embedded a YouTube video into the body. On the frontend we're seeing a padding-bottom of 56% added which is causing a large amount of whitespace on the site.

I believe I can override the template within my project, but I was curious why embeds is adding padding at all? Is there a way to disable this?

Thanks!

**Comment by gasman** [comment]
Hi @gmeans - this is covered by #1495 (which I'll reopen shortly, as I think it's about time we fixed this properly...)
