### ISSUE TITLE
EMBEDLY_KEY should be renamed to WAGTAILEMBEDS_EMBEDLY_KEY

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1757]
Related to #1756

I think this should be renamed to make it consistent with other Wagtail settings.

**Comment by davecranwell** [comment]
I'd rather us take the #1546 / #723 approach personally, but I don't know the technicalities of that approach. It certainly _seems_ aesthetically far superior.

**Comment by davecranwell** [comment]
e

**Comment by davecranwell** [comment]
(Ignore that accidental closure!)

**Comment by zerolab** [comment]
Fixed by #1799 which is now merged.
