### ISSUE TITLE
[RFC] Wagtail admin API

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1760]
Looking to get some feedback on this new feature that I think would help us to greatly improve the maintainability of parts of the admin interface and may lead to user interface improvements in the future.

The initial proposal can be found here: https://groups.google.com/forum/#!topic/wagtail-developers/dNQ9LEaenyI

## Background

We've recently been discussing refactoring parts of the Wagtail admin interface to give better separation between Python and JS. This will help us to simplify the modal workflow system that is currently very difficult to modify.

We've also discussed making the explorer and search interfaces more JavaScript driven.

## Why an API?

In order to implement these features, we need a place where the new interfaces can fetch data from. I propose creating an REST API for this.

The main advantage of creating an API is that we can drive all these interfaces from a single place, so we can concentrate on creating a single rock-solid API and all the new interfaces will benefit from it. Unit testing APIs is also easier as JSON is much easier to parse and check than HTML.

## Why not "Wagtail API"?

The ``wagtailapi`` module (introduced in 1.0) is focused on serving content out to external clients without admin access. For the admin interface, we need more features such as browsing draft pages and seeing permissions/page state. For the modal-workflow refactor we also need access to snippets, which ``wagtailapi`` doesn't support.

The Admin API will be very similar and share a lot of code with the existing API.

## The API

The API will be heavily based on the existing ``wagtailapi`` module and will include some features that I'd like to see in v2. The new API will not be versioned and may change in backwards-incompatible ways between Wagtail releases. So the API can change to suit needs of new Wagtail features when needed.

To save time I'll just mention the differences from the ``wagtailapi`` module:

**1) Authentication**

Like the rest of the admin interface, the new API will use Django's auth module and session cookie for authentication. The same user permissions that exist in the admin interface will be applied to the admin API.

**2) Draft and private pages**

All pages, including draft and private pages, are visible in the API. There will be three new fields added, "status" (string), "has_page_view_restriction" (boolean) and "has_children" (boolean) so the existing UI can be replicated. All these fields will be in "meta"

**3) Selecting multiple page types** (``wagtailapi`` v2 feature)

The ``?type=`` filter will be able to take a comma-separated list of page types. This is required for the page chooser modal.

**4) Image thumbnails**

A ``thumbnail_url`` field will be added to the images endpoint containing the URL of the ``max-165x165`` rendition.

~~**5) child_of/descendant_of filters take special "root" value representing the root page**~~

For example, ``?child_of=root`` will get the children of the root page

**6) html_url, slug, first_published_at, updated_at fields on pages** (``wagtailapi`` v2 feature)

All live pages will be given a html_url if they are in a site, linking to where they exist on the frontend

The slug, first_published_at, updated_at fields will be taken straight from the modal

html_url, first_published_at, updated_at will appear in the "meta" section. slug will appear alongside other data fields.

**7) ``parent`` field on page listings**

The parent link will be added to the page listing.

## Implementation

The new API will be built using Django REST Framework and reuse parts of the existing ``wagtailapi`` module.

The core part of the API will be implemented in Wagtail admin. All endpoints will be implemented in their respective module (except for pages which will be implemented in ``wagtailadmin``) and endpoints will be registered with a hook.

Initially, endpoints will be implemented for pages, images, documents and snippets.

The URL of the endpoints will be of the form ``/admin/api/{pages,images,documents}/``. The snippet API URL will contain a model name: ``/admin/api/snippets/app_name.ModelName/``.

Some refactoring is required in the ``wagtailapi`` module to allow it to be reused in this way. Also, as it's currently a contrib module, we need to think about how we're going to restructure it so core modules don't have to depend on a contrib module.

**Comment by JoshBarr** [comment]
Hey Karl,

This is looking really good. An admin API would definitely help clean up the contract between server-side and client-side code, and make modals and pickers easier to develop. :+1: 

There's a few admin-specific fields that would be useful for the explorer implementation, such as the list of available child/parent page types for each node, and the publish status. 

If this API requires auth, do you think it would be worth extending it to support OAuth as well? I can imagine cases in a service architecture where we might want to POST new pages or documents into Wagtail from another service. (i'm thinking of [flagpost.nz](http://flagpost.nz) which has a module that scrapes ~10,000 nodes from another site and creates Wagtail pages for them).

**Comment by SalahAdDin** [comment]
Use rest?

**Comment by tomdyson** [comment]
Thanks for writing this up, @kaedroho. I'm strongly in favour. 

> as it's currently a contrib module, we need to think about how we're going to restructure it so core modules don't have to depend on a contrib module.

Is there any reason not to move `wagtailapi` into core?

@JoshBarr we definitely want to support POSTing new pages etc into Wagtail from another service but - as I understand it - that would form part of the planned `wagtailapi` improvements, not @kaedroho's proposed `wagtailadminapi`.

**Comment by gasman** [comment]
Sounds good to me!

I think we'd also need the API to return the list of available actions the user can perform on each object (e.g. for pages: edit, publish, lock/unlock, add subpage, move, copy and so on), so that we're not duplicating that business logic in the view. The existing explorer views also depend on the concept of 'can descend' to decide whether to include the link to navigate into a page; it's kind of borderline whether this is business logic (in which case it should also be returned by the API as a can_descend flag) or purely a view-level construct (in which case the view layer should make that decision itself, and the API needs to include the relevant information such as 'does this page have any subpages').

Re moving `wagtailapi` from contrib to core - I imagine we'd start by moving the implementation internals into somewhere like `wagtail.wagtailcore.api`, and making `wagtail.contrib.wagtailapi` effectively just a wrapper that provides a urlconf and whatever else users need to add a public-facing API. (The contrib app might later get phased out in favour of using the wagtailcore.api stuff directly - but we don't have to make that decision yet.)

**Comment by kaedroho** [comment]
> There's a few admin-specific fields that would be useful for the explorer implementation, such as the list of available child/parent page types for each node, and the publish status. 

Perhaps to start with, we can just provide a URL to the "add subpage" view as a field (and omit it if no subpage types are available). That'll be enough to replicate the current UI, we could probably come up with something better if we decide to change that bit of UI altogether.

As for status, I've currently added a "status" field as a string. Thinking about it though, we would probably want at least two fields for this: one for the JavaScript to read and one to display to the user (that's translated), or perhaps we could implement translations in the JS?

> If this API requires auth, do you think it would be worth extending it to support OAuth as well? I can imagine cases in a service architecture where we might want to POST new pages or documents into Wagtail from another service.

Initially, the admin API won't be able to create pages. We do plan on adding support for writing to the main ``wagtailapi`` module though (which would probably support OAuth). I think the admin API should be focused on the needs of the admin interface and anything external should use the standard ``wagtailapi`` module.

> Use rest?

Yep, that's the plan! :)

**Comment by wide-awake** [comment]
Sounds great to me!

**Comment by kaedroho** [comment]
WIP PR can be found at https://github.com/kaedroho/wagtail/pull/30

**Comment by SalahAdDin** [comment]
Why don't user rest framework?

**Comment by gasman** [comment]
@SalahAdDin We are using it:

> The new API will be built using Django REST Framework and reuse parts of the existing `wagtailapi` module.

**Comment by SalahAdDin** [comment]
Ah, thanks, it's a great thing!

**Comment by kaedroho** [comment]
Admin API merged into Wagtail 1.6
