### ISSUE TITLE
Wagtail with SSL (error at preview page)

### ISSUE THREAD

**Issue by girishkumarkh** [torchbox/wagtail#1762]
Hi guys,

I am running wagtail==0.8.4 with django-sslify for redirecting redirecting http request --> https request. everything with the site works fine expect the preview page. where I've been spit out the following error while at DEBUG=True:

Exception at /cmsdashboard/pages/10/edit/preview/ Couldn't create request mock object - request middleware returned a response Request Method: POST Request URL: 

```
Exception at /cmsdashboard/pages/10/edit/preview/ Couldn't create request mock object - request middleware returned a response Request Method: POST Request URL: 
```

any ideas ?

**Comment by kaedroho** [comment]
In settings => sites, is the hostname set correctly and the port set to 443?

**Comment by girishkumarkh** [comment]
Can't believe, I've missed that :sob: I've updated to wagtail==0.8.10 with default port set to 443. All working fine now! Thanks @kaedroho
