### ISSUE TITLE
Template Syntax Error: Invalid filter: richtext

### ISSUE THREAD

**Issue by mdw7326** [torchbox/wagtail#1775]
Following the tutorial [here](http://wagtail.readthedocs.org/en/v1.1/getting_started/index.html) and running Django 1.8.5 with Python 3.4.3, I get the above error when adding `{{ self.body|richtext }}` to my home_page.html template. I followed the instructions exactly a couple of times and keep getting this. I manged to make it work by using the `safe` filter instead (i.e. `{{ self.body|safe }}`, however this can allow all kinds of stuff in the template... I apologize if this is actually a noobish mistake on my part, but in that case at least the docs should be updated.

**Comment by mdw7326** [comment]
I am stupid.

**Comment by kaedroho** [comment]
Looks like an easy mistake to make, thanks for reporting! As this is the most read part of the documentation, it's important that we iron out any issues.

Perhaps we should highlight the changes in bold, or improve the explanation?

**Comment by mdw7326** [comment]
I guess the assumption I made that got me in to trouble was that the filters were already being taken care of behind the scene, having never used custom template filters before. So I think a sentence like "Be sure to load the custom wagtail filters in your template before using them" might help.

**Comment by tomdyson** [comment]
Thanks for the feedback, @mdw7326, and for addressing it, @JoshBarr.

**Comment by teddyward** [comment]
It's been 5 years since this happened, but I appreciate the time and effort that you all put into documentation and following up on GH issues, since finding this on Google was a great time saver for me today ❤️
