### ISSUE TITLE
Cleanup body_class in default homepage template?

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1781]
I think the default body class in the homepage template could be clarified

Currently, it's: ``{% block body_class %}template-{{ self.get_verbose_name|slugify }}{% endblock %}``

https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/home/templates/home/home_page.html#L3

I propose we change it to: ``{% block body_class %}template-homepage{% endblock %}``

I think this is much easier on the eyes, and easier to decipher.

**Comment by davecranwell** [comment]
Agreed. I think need to decipher is actually a need to safely discard everything, which is always the second approach when using generated code. Removing opinionated code and making things obvious is a :+1: from me.

**Comment by kaedroho** [comment]
Closed by #1784
