### ISSUE TITLE
Multiple Document Upload

### ISSUE THREAD

**Issue by kunambi** [torchbox/wagtail#1788]
A client has around 300 PDF documents that we need to upload to a newly installed Wagtail site. It'd be really helpful if it'd be possible to bulk upload those, just like images. Tried to find any references if there's been any decisions against this type of request, but couldn't find any.

This is very much related to #234.

TYIA.

**Comment by davecranwell** [comment]
:+1:  Sounds good

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kunambi** [comment]
Is there an update or an ETA? Would love seeing this implemented.

**Comment by kaedroho** [comment]
Looks like this has already been done and will be released in 1.4! https://github.com/torchbox/wagtail/pull/1892

**Comment by kunambi** [comment]
:+1: !
