### ISSUE TITLE
ImageChooserPanel - Show Transparency

### ISSUE THREAD

**Issue by jorge-marques** [torchbox/wagtail#1798]
I'd like to propose adding the show-transparency css class to the img tag generated by the ImageChooserPanel. I have some images that are basically white outlines against a transparent background and they're invisible in the chooser.

**Comment by davecranwell** [comment]
Agreed, that would be good. Similarly the images inserted into rich text editor if possible.

Note to self: The checkerboard transparency style needs adding to the styleguide.

**Comment by rmartins90** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:
