### ISSUE TITLE
wagtailsearch.views.frontend needs updating to use non-deprecated search method

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#1808]
Currently using Page.search, which is deprecated in Wagtail 1.2 - should be updated to use the QuerySet-based mechanism instead.

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsearch/views/frontend.py#L41

**Comment by anurag-ks** [comment]
Is the "QuerySet-based mechanism" already defined, or should it be done ?

**Comment by gasman** [comment]
@anurag-ks The new QuerySet mechanism is already implemented, in #1478. But actually this is taken care of now - I had a free moment to fix this tonight (#1811) :-)
