### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by rcorzogutierrez** [torchbox/wagtail#1840]
Include the possibility of a default theme

**Comment by gasman** [comment]
Hi @rcorzogutierrez - thanks for the suggestion. However, it needs a lot more detail before it's something we can act on.

In Wagtail, developers are expected to define their own page structures - unlike a system such as Wordpress which uses one fixed page model. This makes it very difficult to come up with a theming system that fits everyone's needs.

**Comment by robmoorman** [comment]
@rcorzogutierrez this might be helpful https://github.com/moorinteractive/wagtail-themes
