### ISSUE TITLE
Unable to add users with IDN email addresses

### ISSUE THREAD

**Issue by kylestratis** [torchbox/wagtail#1855]
With issue #1670 fixes being made to support unicode emails for gravatars, I was doing some testing and noticed that adding users with IDN emails will not allow adding the user. I'm not sure if this is intended or not (I'm just getting my feet wet with wagtail), but considering the gravatar support for IDN emails, I assume we should be able to add users with IDN email address. 

For my testing, I used the following Greek email address (I found it on wikipedia, so there shouldn't be privacy issues): θσερ@εχαμπλε.ψομ

[Here are two images](http://imgur.com/a/uUSTs) recreating my steps, along with the error message that occurs at the Roles view when clicking 'Add User.' They are also attached below, because redundancy. 

![1-add_user](https://cloud.githubusercontent.com/assets/4088051/10654445/70db70ce-7838-11e5-96a7-5fc01b206277.png)
![2-roles](https://cloud.githubusercontent.com/assets/4088051/10654444/70db3e06-7838-11e5-8d51-0aba9837b163.png)

**Comment by gasman** [comment]
The field here is simply an `<input type="email">` element with no custom validation at our end, so the behaviour here is entirely up to the browser. In my tests, Chrome and Firefox both accept Unicode in the domain portion but not the username, and I think this is the format that we're seeing 'in the wild' right now (#1670 refers to "an email using an IDN").

The more general question of "what characters should be allowed in an email address, and how should browsers handle them" seems to be a horrible mess (see https://html.spec.whatwg.org/multipage/forms.html#e-mail-state-(type=email), https://www.w3.org/Bugs/Public/show_bug.cgi?id=18162, https://bugzilla.mozilla.org/show_bug.cgi?id=618876) - but I think we can safely say it's not our problem. Either the browsers are getting it right, or it's a browser bug :-)
