### ISSUE TITLE
page.copy(copy_revisions=False) copies revisions

### ISSUE THREAD

**Issue by buff3r** [torchbox/wagtail#1858]
Using a fresh wagtail checkout I added a test to wagtail.wagtailcore.tests.test_page_model.TestCopyPage, which is failing:

        christmas_event = EventPage.objects.get(url_path='/home/events/christmas/')

        christmas_event.save_revision()

        # Copy it
        new_christmas_event = christmas_event.copy(copy_revisions=False)

        # Check that the revisions were not copied
        self.assertEqual(new_christmas_event.revisions.count(), 0)

**Comment by gasman** [comment]
Hi @buff3r,
One revision is always created on copy, regardless of the `copy_revisions` setting - see https://github.com/torchbox/wagtail/blob/5285a9a915be3ad078de9f064ffc14f19f950e72/wagtail/wagtailcore/models.py#L827-L831
