### ISSUE TITLE
Deleting an inline child object from the database makes page un-saveable

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#188]
When a child object of a page (linked via ParentalKey) is deleted from the database (typically because it contains a foreign key to an image / document / page with on_delete=CASCADE), it will remain in the content_json field of the PageRevision table and therefore still appear when the page is edited. It preserves its original ID, and since this no longer exists in the database, the ID field throws a "this is not one of the available choices" validation error. (Unfortunately, the ID is a hidden field, so the specific validation error won't be shown - the user will just see a generic 'there were errors on this page' message, with no indication of where the error is.)

The fix would be for django-modelcluster to check the object IDs when deserializing the cluster, and drop any objects that have a non-blank ID that does not exist in the database.

**Comment by kaedroho** [comment]
Should this be moved to https://github.com/torchbox/django-modelcluster?

**Comment by gasman** [comment]
I can't replicate this now. The page revision JSON does indeed include the 'dead' child object, but when this gets deserialised (via `PageRevision.as_page_object`), we run `from_json` with `check_fks=True` (modelcluster's default setting), which filters it out. The `check_fks` flag has worked in this way ever since the initial release of django-modelcluster, so I'm not sure why this would ever have failed in the way described...
