### ISSUE TITLE
Rendering model states takes too long

### ISSUE THREAD

**Issue by rmartins90** [torchbox/wagtail#1895]
On Wagtail 1.2rc1 and Django 1.8.5:
It's just me or there's something wrong with Rendering model states process on migrate command?
I don't know what kind of info I could provide to debug.

**Comment by gasman** [comment]
How long does it take, exactly? Is this on a new project, or an existing one - and if it's an existing one, how many migrations does your project have?

**Comment by timheap** [comment]
This might be related to a known (and now fixed) bug in Django: https://code.djangoproject.com/ticket/24743

**Comment by gasman** [comment]
Closing as a presumed Django issue - please re-open if you have information to suggest that this is Wagtail-specific.
