### ISSUE TITLE
Paste from Word brings in unwanted xml tags

### ISSUE THREAD

**Issue by zylene** [torchbox/wagtail#1916]
We are using wagtail version 1.1 for a sizeable website and we really like it but we have run into a problem with the hallo.js editor not stripping out unwanted tags.

When we paste into the rich-text editor directly from Word (as many content editors may do) the paste brings in XML from the word document.  Although not displayed, it is visible in the view source and also in the database of course.  We have been diligently working with the editors to change the way they paste the code in the meantime, but we thought this would be filtered out as invalid HTML?  

for example: 
<code>
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Normal</w:View>
  <w:Zoom>0</w:Zoom>
  <w:TrackMoves></w:TrackMoves>
  <w:TrackFormatting></w:TrackFormatting>
  <w:PunctuationKerning></w:PunctuationKerning>
  <w:ValidateAgainstSchemas></w:ValidateAgainstSchemas>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:DoNotPromoteQF></w:DoNotPromoteQF>
  <w:LidThemeOther>EN-US</w:LidThemeOther>
  <w:LidThemeAsian>JA</w:LidThemeAsian>
</code>

This seems similar to issue 1669 which was closed as unreproducible. (https://github.com/torchbox/wagtail/issues/1669)

**Comment by gasman** [comment]
Hi @zylene - this should be fixed in 1.2 by #1821.
