### ISSUE TITLE
Naming convention of appending "Page" to each model in docs

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1927]
"[Page models](http://docs.wagtail.io/en/v1.2/topics/pages.html)" in the docs says:

> **Tip:**
> To keep track of `Page` models and avoid class name clashes, it can be helpful to suffix model class names with “Page” e.g BlogPage, ListingIndexPage.

Can this be explained further, possibly linked to a more detailed article?

I don't totally get it. Does Django not allow a built in way to avoid name clashes in the database? It seems like the current method is to guess on naming your models so nothing clashes. Even then, having a model called `blog_page` in the DB isn't totally foolproof since another app could have that. Wouldn't you prefer something more like `wagtail_blog`? I think Django allows you to set that manually when you create a model.

It seems redundant to create a class with `class BlogPage(Page)`. I feel like this could be a problem if the only reason we're appending "Page" is to avoid a technical issue rather than focusing on best naming conventions and clean code.

**Comment by gasman** [comment]
Further background to this: #503

**Comment by alexgleason** [comment]
Thanks. So as @kaedroho says:

https://github.com/torchbox/wagtail/issues/503#issuecomment-50123069
> I'm not sure how this could be solved at the moment. But I would recommend suffixing your page types with "Page" to prevent clashes like this happening.

So what I'm getting from this is that the only reason to append "Page" is to prevent this error.

How should we handle that in the docs? In that case it seems like the docs should be more assertive in telling you to use -Page. It's not even a tip so much as it is a warning. Like,

> **Warning:**
> Due to a bug in Wagtail (No. 503[link]) it is advised that you append "Page" to the end of your model names to avoid errors.

**Comment by davecranwell** [comment]
I think that could imply only the exact word "Page" will do, which is untrue - it's just a namespace.

**Comment by alexgleason** [comment]
So this doesn't get lost, this phrasing was found to be agreeable.

> **Notice:**
> Ensure that none of your field names are the same as your class names. This will cause errors due to the way Django handles relations[link to more info]. In our examples we have avoided this by appending "Page" to the name of each model names.
