### ISSUE TITLE
Use sendfile for serving image renditions in image serve view

### ISSUE THREAD

**Issue by prydie** [torchbox/wagtail#1942]
Currently #1913 implements `'serve'` and `'redirect'` behaviours. It would be useful to add `'sendfile'` to this list to enable serving by the webserver without the additional HTTP request required by `'redirect'`.

**Comment by kaedroho** [comment]
Good idea @prydie! I think it might be worth making this the behaviour of the default 'serve' mode.

We've implemented this for docs so the implementation should be very similar to https://github.com/torchbox/wagtail/commits/master/wagtail/wagtaildocs/views/serve.py

Also, to whoever implements this, please implement it on top of #1913 or wait until that's merged first before starting work.

**Comment by gasman** [comment]
Implemented in #2459
