### ISSUE TITLE
Refactor scss in admin

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1948]
Copying from a closed PR from September 23rd (#1731), this is a list of unused mixins:

* @mixin filter($filter...)
* @mixin transition-delay($delay...)
* @mixin notransition()
* @mixin content-box()
* @mixin table-column($x, $padding:$padding, $grid-columns:$grid-columns)
* @mixin push($offset:1, $grid-columns:$grid-columns)
* @mixin push-padding($offset:1, $grid-columns:$grid-columns)
* @mixin pull($offset:1, $grid-columns:$grid-columns)
* @mixin pull-padding($offset:1, $grid-columns:$grid-columns)

**Comment by davecranwell** [comment]
All the mixins related to prefixing should be removed in favour of gulp-autoprefixer which is _already_ part of the Gulp compilation task, but seems to have gone unnoticed.

The grid related ones should remain. We may not use them, but then we don't use "cols-7" or "cols-11" similarly. They should remain as part of a reasonably feature-rich grid framework that others can use.

**Comment by gasman** [comment]
Fixed in #1964
