### ISSUE TITLE
Prefetching tags does not seem to work.

### ISSUE THREAD

**Issue by jorge-marques** [torchbox/wagtail#1953]
Prefetching tags does not seem to work.

I have a ClusterTaggableManager called "categories" in one of my pages.

Doing something like:

`MyPage.objects.all().prefetch_related('categories')` throws an exception:

    TypeError
    get_query_set() takes 1 positional argument but 2 were given

I believe this is supported using the plain TaggableManager in django-taggit.

**Comment by kaedroho** [comment]
Could you provide more traceback? Also, could you let us know what versions of the following packages you have installed:
 - Wagtail
 - Django
 - django-modelcluster
 - django-taggit

**Comment by gasman** [comment]
Closing due to lack of update - please reopen if you can provide the requested info.
