### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by ciloeweb** [torchbox/wagtail#1955]
I have the problem when try to connect google storage: this is the error

TooManyAuthHandlerReadyToAuthenticate at /admin/images/
2 AuthHandlers ['ComputeAuth', 'HmacAuthV1Handler'] ready to authenticate for requested_capability ['s3'], only 1 expected. This happens if you import multiple pluging.Plugin implementations that declare support for the requested_capability.

I add settings.py 

DEFAULT_FILE_STORAGE = 'django_google_storage.storage.GoogleStorage'
GS_ACCESS_KEY_ID = 'key'
GS_SECRET_ACCESS_KEY = "key"
GS_STORAGE_BUCKET_NAME = 'bucketname'

I don't know what is the problem.

Thanks!

**Comment by gasman** [comment]
Hi @ciloeweb - please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support requests.
