### ISSUE TITLE
wagtail plus non-wagtail

### ISSUE THREAD

**Issue by Eraldo** [torchbox/wagtail#2008]
How can I use the power of CBVs in combination with Wagtail.

I love the fact that wagtail does separate admin from cms. And that content and design are loosely coupled. Nice!

I want to use Wagtail as the CMS for the basic site. Users on that site create content without the CMS and for that content, I would like to use django's tools and views. For example the CBVs like CreateView, UpdateView, etc.

Imagine a page where there is an introduction text that is handled via wagtail (so the page is a wagtail page) then on that site there is a list of books and authors (for examples sake).

Is there a way to combine these two worlds in a nice manner? Or do I need to manually put lists and logic a post checks and all these things in the serve method?

I guess I am still not sure how to create a wagtail powered project that is not wagtail-only.
(I guess that is similar to what django-cms tries to achieve via apphooks)

I also thought of using a stock class based django view and adding a wagtail snippets for things like the introduction text. Then I would not have breadcrumbs .. and updating the info page would require knowing the name of the snippet and finding the right one within the cms. So loosing most of what wagtail is designed to do basically. Hm. Not so sexy.

I would however love to use wagtail.
Are there any best practises or concepts that I am not yet aware of?

**Comment by gasman** [comment]
Hi @Eraldo - please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
