### ISSUE TITLE
Reusable Text Tokens

### ISSUE THREAD

**Issue by harrislapiroff** [torchbox/wagtail#2013]
Would Wagtail be interested in adopting this as a feature? It's something I'm planning to develop for a couple of our projects, but I'd structure it for wagtail contrib and put in a PR if Torchbox would be interested in merging it into core:

1. A model `Tokens` (for now) that is a simple key (`SlugField`) value (`CharField`) structure.
2. A template tag that lets you display or access the value of any token `{% token "company-name" %}`.
3. An extension to the rich text editor that lets you embed tokens. (This might be the trickiest part, both technically and conceptually.) Probably also a corresponding template filter that lets you evaluate tokens on the template end.

A couple use cases:

* A CMS user has a piece of data that is used across your site but changes frequently. (Like your university's tuition.) Use a token to store and update that data.
* A developer wants to develop generic site templates that can be reused for multiple sites without much modification of the templates. Use tokens to render global values like `company-name` and `contact-address` and let the user fill in the values.

Is this something that would be interesting to Wagtail devs? Is it a feature Wagtail already supports that I've somehow overlooked?

**Comment by gasman** [comment]
Hi @harrislapiroff - this sounds quite similar to the 'settings' module added in Wagtail 1.2: http://docs.wagtail.io/en/v1.2/reference/contrib/settings.html . Would that fit your requirements?

**Comment by harrislapiroff** [comment]
Ah ha, yes, I had missed that! Thank you! It's different from my idea, but maybe better. I'll try it out and see how it feels.

**Comment by gasman** [comment]
Good to hear! Will close this for now, but please reopen if you find that there's any functionality you need which isn't covered by settings.
