### ISSUE TITLE
Documentation fails to build under Django 1.9

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2014]
Output of `make html` when starting from a clean state (`make clean`):

    sphinx-build -b html -d _build/doctrees   . _build/html
    Running Sphinx v1.3.1
    making output directory...
    Initializing Spelling Checker
    loading pickled environment... not yet created
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 106 source files that are out of date
    updating environment: 106 added, 0 changed, 0 removed
    reading sources... [100%] topics/writing_templates
    /home/vagrant/wagtail/docs/reference/contrib/routablepage.rst:103: WARNING: autodoc: failed to import module 'wagtail.contrib.wagtailroutablepage.models'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
        __import__(self.modname)
      File "/home/vagrant/wagtail/wagtail/contrib/wagtailroutablepage/models.py", line 7, in <module>
        from wagtail.wagtailcore.models import Page
      File "/home/vagrant/wagtail/wagtail/wagtailcore/models.py", line 8, in <module>
        from modelcluster.models import ClusterableModel, get_all_child_relations
      File "/home/vagrant/libs/django-modelcluster/modelcluster/models.py", line 152, in <module>
        class ClusterableModel(models.Model):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
        self.check_apps_ready()
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
    /home/vagrant/wagtail/docs/reference/contrib/routablepage.rst:104: WARNING: autodoc: failed to import class 'RoutablePageMixin' from module 'wagtail.contrib.wagtailroutablepage'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
        return getattr(obj, name, *defargs)
    AttributeError: 'module' object has no attribute 'RoutablePageMixin'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
        obj = self.get_attr(obj, part)
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
        return safe_getattr(obj, name, *defargs)
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
        raise AttributeError(name)
    AttributeError: RoutablePageMixin
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:5: WARNING: autodoc: failed to import module 'wagtail.wagtailcore.models'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
        __import__(self.modname)
      File "/home/vagrant/wagtail/wagtail/wagtailcore/models.py", line 8, in <module>
        from modelcluster.models import ClusterableModel, get_all_child_relations
      File "/home/vagrant/libs/django-modelcluster/modelcluster/models.py", line 152, in <module>
        class ClusterableModel(models.Model):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
        self.check_apps_ready()
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:90: WARNING: don't know which module to import for autodocumenting 'specific' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:92: WARNING: don't know which module to import for autodocumenting 'specific_class' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:94: WARNING: don't know which module to import for autodocumenting 'url' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:96: WARNING: don't know which module to import for autodocumenting 'full_url' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:98: WARNING: don't know which module to import for autodocumenting 'route' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:100: WARNING: don't know which module to import for autodocumenting 'serve' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:102: WARNING: don't know which module to import for autodocumenting 'get_context' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:104: WARNING: don't know which module to import for autodocumenting 'get_template' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:106: WARNING: don't know which module to import for autodocumenting 'preview_modes' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:108: WARNING: don't know which module to import for autodocumenting 'serve_preview' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:110: WARNING: don't know which module to import for autodocumenting 'get_ancestors' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:112: WARNING: don't know which module to import for autodocumenting 'get_descendants' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:114: WARNING: don't know which module to import for autodocumenting 'get_siblings' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:152: WARNING: don't know which module to import for autodocumenting 'can_exist_under' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:154: WARNING: don't know which module to import for autodocumenting 'can_create_at' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:156: WARNING: don't know which module to import for autodocumenting 'can_move_to' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:215: WARNING: don't know which module to import for autodocumenting 'find_for_request' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:217: WARNING: don't know which module to import for autodocumenting 'root_url' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:227: WARNING: don't know which module to import for autodocumenting 'get_site_root_paths' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:301: WARNING: don't know which module to import for autodocumenting 'as_page_object' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:305: WARNING: don't know which module to import for autodocumenting 'approve_moderation' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:309: WARNING: don't know which module to import for autodocumenting 'reject_moderation' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:313: WARNING: don't know which module to import for autodocumenting 'is_latest_revision' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/model_reference.rst:317: WARNING: don't know which module to import for autodocumenting 'publish' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    /home/vagrant/wagtail/docs/reference/pages/queryset_reference.rst:34: WARNING: autodoc: failed to import module 'wagtail.wagtailcore.query'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
        __import__(self.modname)
      File "/home/vagrant/wagtail/wagtail/wagtailcore/query.py", line 5, in <module>
        from django.contrib.contenttypes.models import ContentType
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
        class ContentType(models.Model):
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
        app_config = apps.get_containing_app_config(module)
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
        self.check_apps_ready()
      File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
        raise AppRegistryNotReady("Apps aren't loaded yet.")
    django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
    /home/vagrant/wagtail/docs/reference/pages/queryset_reference.rst:35: WARNING: don't know which module to import for autodocumenting 'PageQuerySet' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    writing output... [100%] topics/writing_templates
    /home/vagrant/wagtail/docs/releases/0.6.rst:28: WARNING: undefined label: routablepageurl_template_tag (if the link has no caption the label must precede a section header)
    generating indices... genindex py-modindex
    writing additional pages... search
    copying images... [  1%] editor_manual/administrator_tasks/../../_static/images/screen38_promoted_results_copying images... [  4%] editor_manual/finding_your_way_around/../../_static/images/screen05_explorer_pagecopying images... [  6%] editor_manual/administrator_tasks/../../_static/images/screen38.5_popular_search_copying images... [  7%] editor_manual/new_pages/../../_static/images/screen26_reordering_multiple_items.pcopying images... [ 10%] editor_manual/finding_your_way_around/../../_static/images/screen06_explorer_pagecopying images... [ 12%] editor_manual/administrator_tasks/../../_static/images/screen35_users_menu_item.pcopying images... [ 18%] editor_manual/administrator_tasks/../../_static/images/screen36_users_interface.pcopying images... [ 23%] editor_manual/new_pages/../../_static/images/screen11.1.5_streamfield_richtext.pncopying images... [ 25%] editor_manual/finding_your_way_around/../../_static/images/screen03_explorer_menucopying images... [ 31%] editor_manual/documents_images_snippets/../../_static/images/screen32_image_edit_copying images... [ 40%] editor_manual/finding_your_way_around/../../_static/images/screen04_search_screencopying images... [ 42%] editor_manual/finding_your_way_around/../../_static/images/screen07_explorer_pagecopying images... [ 45%] editor_manual/documents_images_snippets/../../_static/images/screen33_snippet_mencopying images... [ 51%] editor_manual/documents_images_snippets/../../_static/images/screen29_documents_pcopying images... [ 62%] editor_manual/finding_your_way_around/../../_static/images/screen08.5_reorder_pagcopying images... [ 65%] editor_manual/finding_your_way_around/../../_static/images/screen02_dashboard_edicopying images... [ 78%] editor_manual/documents_images_snippets/../../_static/images/screen34_snippet_usecopying images... [ 81%] editor_manual/documents_images_snippets/../../_static/images/screen31_images_pagecopying images... [ 87%] editor_manual/finding_your_way_around/../../_static/images/screen08_add_page_buttcopying images... [ 90%] editor_manual/administrator_tasks/../../_static/images/screen39_add_promoted_resucopying images... [ 93%] editor_manual/administrator_tasks/../../_static/images/screen37_promoted_menu_itecopying images... [ 96%] editor_manual/new_pages/../../_static/images/screen16_selecting_image_from_librarcopying images... [ 98%] editor_manual/new_pages/../../_static/images/screen11.9_streamfield_reordering.pncopying images... [100%] editor_manual/documents_images_snippets/../../_static/images/screen30_documents_edit_page.png
    copying static files... done
    copying extra files... done
    dumping search index in English (code: en) ... done
    dumping object inventory... done
    build succeeded, 30 warnings.

**Comment by kaedroho** [comment]
Is this using the Django 1.9 branch?

**Comment by gasman** [comment]
Yup.

**Comment by gasman** [comment]
Can confirm that the docs now build successfully with 8ddd9ee537649383b0ecc43c6769d37c582bda1c applied.

**Comment by luizluan** [comment]
Thank You
