### ISSUE TITLE
on_delete action needs to be set on all ForeignKeys

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2019]
We currently get a lot of deprecation warnings about this When running on Django 1.9. We need to add on_delete actions to every ForeignKey, ParentalKey and OneToOneField in Wagtail. This also needs to be done in all the migrations as well.

**Comment by kaedroho** [comment]
#2024 could probably be solved at the same time

**Comment by gasman** [comment]
Fixed in #2065
