### ISSUE TITLE
wagtailsearch urls need to be namespaced

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2021]
Wagtail search URLs aren't like the rest of Wagtail:
- https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsearch/urls/admin.py#L6-L7
- https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsearch/wagtail_hooks.py#L10

We're currently just prefixing them the old-fashioned way with ``wagtailsearch_``, we should use Django namespaces instead

**Comment by CorneliusIV** [comment]
I have been wanting to help out. So I would like to do this. 
One question is this just for the admin URL's or the frontend URL's as well?

**Comment by kaedroho** [comment]
Thanks @CorneliusIV! This only applies to the admin URLs.

Here's what was done to do this to the wagtaildocs module: https://github.com/torchbox/wagtail/commit/b3ba30eb006b403754ae0154cd00e1c663a836ae
