### ISSUE TITLE
"Hello" part of notification emails doesn't fall back to username

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2037]
Relevant code: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/notifications/base_notification.html#L2
Introduced in: https://github.com/torchbox/wagtail/pull/1973

If the user doesn't have a name set, I think this should fallback to the username, if one is set (or simply just say "Hello" without a space afterwards). It currently says ``Hello ,``

Looks like an easy fix

**Comment by gasman** [comment]
Fixed in #2046
