### ISSUE TITLE
loaddata adds data to db but doesn't show up in admin

### ISSUE THREAD

**Issue by alan-unravel** [torchbox/wagtail#2060]
Any insights into this would be greatly appreciated!

**Comment by kaedroho** [comment]
Please post support requests to the [support group](https://groups.google.com/forum/#!forum/wagtail). GitHub issues are for discussing development of Wagtail itself.

When you post there, could you give some extra detail (what you're moving, are you moving to a fresh db, where do you expect it to appear) and any examples you can provide would be very useful for us to work out what's happening and help you solve it.
