### ISSUE TITLE
Wagtail CMS grid at DjangoPackages

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtail#2071]
Hello guys! I'm just released https://github.com/MechanisM/wagtail-constance
And also created Wagtail CMS grid at https://www.djangopackages.com/grids/g/wagtail-cms/ 
I think it would be great to have a list of all available apps built for wagtail.

**Comment by gasman** [comment]
Nice! I've added it to the wiki page at https://github.com/torchbox/wagtail/wiki/Contributed-apps-and-website-code. Having a grid on djangopackages.com is a good idea too - I would suggest announcing it on [the Google group](https://groups.google.com/forum/#!forum/wagtail).
