### ISSUE TITLE
Manage some tables in database in Wagtail admin interface

### ISSUE THREAD

**Issue by KhumpuW** [torchbox/wagtail#2076]
If I want some tables in DB to be manageable in Wagtail, Could I do that?
maybe the same way that you can manage data by Form Builder that auto appear in admin interface when you have more than one form?

**Comment by kaedroho** [comment]
Hi @KhumpuW 

Please use the [support group](https://groups.google.com/forum/#!forum/wagtail) for help with using Wagtail.

But to answer you question, you can use [wagtailmodeladmin](https://github.com/rkhleics/wagtailmodeladmin) for that (and this will be merged into Wagtail core soon).

**Comment by SalahAdDin** [comment]
Yes, or you can use django-admin instead.
