### ISSUE TITLE
Can't  add new Home Page

### ISSUE THREAD

**Issue by danielblink** [torchbox/wagtail#2077]
IntegrityError at /admin/pages/add/home/homepage/1/
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`myblog`.`wagtailcore_page`, CONSTRAINT `wagtailcore_p_content_type_id_534ebab2_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`))')
    Request Method:	POST
    Request URL:	http://www.bilibara.com:8080/admin/pages/add/home/homepage/1/
    Django Version:	1.8.6
    Exception Type:	IntegrityError
    Exception Value:	
    (1452, 'Cannot add or update a child row: a foreign key constraint fails (`myblog`.`wagtailcore_page`, CONSTRAINT `wagtailcore_p_content_type_id_534ebab2_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`))')
    Exception Location:	/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
    Python Executable:	/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/bin/uwsgi
    Python Version:	2.7.10
    Python Path:	
    ['.',
     '',
     '/home/myblog',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python27.zip',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/plat-linux2',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/lib-tk',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/lib-old',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/lib-dynload',
     '/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7',
     '/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/plat-linux2',
     '/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/lib-tk',
     '/root/.pythonbrew/venvs/Python-2.7.10/venv_py2.7.10/lib/python2.7/site-packages']
    Server time:	周三, 30 十二月 2015 08:27:16 +0000

**Comment by SalahAdDin** [comment]
I think that will be better come back to core app without other features.

**Comment by gasman** [comment]
Hi @danielblink - I'm afraid there's not enough information here to determine whether this is a bug in Wagtail. We would need to see a minimal set of steps for reproducing this error, starting from a fresh project and including any details of code added, commands run and so on.

From the error message, it looks like your database is missing some updates - try running `python manage.py makemigrations` and `python manage.py migrate`. However, we can't provide tech support here - I would suggest asking on the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail) instead.
