### ISSUE TITLE
migrations fails with local postgres database

### ISSUE THREAD

**Issue by sytch** [torchbox/wagtail#2083]
i'm trying to setup wagtail with a local postgres database.

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'test_db',
        'USER': 'test_user',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': 5432,
        'CONN_MAX_AGE': 600,  # number of seconds database connections should persist for
    }
}
```

while running ```./manage.py migrate``` the following error occurs:

```
django.db.utils.ProgrammingError: relation "wagtailimages_filter_spec_42ad6e02_like" already exists
psycopg2.ProgrammingError: relation "wagtailimages_filter_spec_42ad6e02_like" already exists
```

Wagtail 1.2 / 1.3
Python 2.7.10 / 3.4.3
PostgreSQL 9.4.4

**Comment by gasman** [comment]
Hi @sytch - this is caused by a bug in the latest point release of Django: https://code.djangoproject.com/ticket/26034

We're looking at workarounds, but for now, I'd suggest using Django 1.9 or 1.8.7.

**Comment by sytch** [comment]
it worked, thanks!

**Comment by xintellion** [comment]
I'm getting the same error:
wagtail 1.10.1
python 3.6.1
Postgres 9.5.5
django 1.11.2

 Applying wagtailimages.0005_make_filter_spec_unique...
psycopg2.ProgrammingError: relation "wagtailimages_filter_spec_42ad6e02_like" already exists

For now I commented out uniqueness in wagtailimages.0005_make_filter_spec_unique to get my database tables created.

    dependencies = [
        ('wagtailimages', '0004_make_focal_point_key_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='spec',
            # field=models.CharField(unique=True, max_length=255),
            field=models.CharField(max_length=255),
            preserve_default=True,
        ),
    ]

**Comment by gasman** [comment]
@xintellion Are you able to reproduce this on a fresh Wagtail project? If so, please open a new issue describing the exact steps leading up to this error. Thanks!
