### ISSUE TITLE
Wagtail userbar link text cutted off.

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtail#2097]
I'm used wagtail mostly in english and wasn't noticed, but when I switched to russian, I see that link for "Edit"(in russian is "Редактировать") is cutted off.
![2016-01-10 22-52-44 window](https://cloud.githubusercontent.com/assets/121781/12223594/021f4c9c-b7ed-11e5-9738-f1e48e074415.png)

**Comment by kaedroho** [comment]
Thanks for reporting!

**Comment by davecranwell** [comment]
I believe this is addressed by https://github.com/torchbox/wagtail/pull/2201
