### ISSUE TITLE
Problem with MySQL 5.7 for initial migration.

### ISSUE THREAD

**Issue by CodeCrow** [torchbox/wagtail#2105]
The initial migration for wagtail images fails on line 17 of 0004_make_focal_point_key_not_nullable.

This can be fixed with the following:

```sql
DELETE FROM wagtailimages_rendition WHERE CONCAT(image_id, '-', filter_id) IN (
    SELECT CONCAT(image_id, '-', filter_id) FROM (SELECT DISTINCT * FROM wagtailimages_rendition) AS x
    WHERE focal_point_key IS NULL 
    GROUP BY image_id, filter_id HAVING COUNT(*) > 1
) AND focal_point_key IS NULL
```

**Comment by kaedroho** [comment]
Thanks for reporting @CodeCrow

**Comment by guydav** [comment]
I ran into the same problem today - this is the exact error message that this results in:

django.db.utils.OperationalError: (1093, "You can't specify target table 'wagtailimages_rendition' for update in FROM clause")

Adding it here so it comes up in google searches more easily.

**Comment by robmoggach** [comment]
same here with mysql (my guess is it's the mysql query/statement)- here's the offending query:

        schema_editor.execute("""
            DELETE FROM `wagtailimages_rendition` WHERE CONCAT(image_id, '-', filter_id) IN (
                SELECT CONCAT(image_id, '-', filter_id)
                FROM (SELECT * FROM `wagtailimages_rendition`) AS x
                WHERE `focal_point_key` IS NULL
                GROUP BY image_id, filter_id
                HAVING COUNT(*) > 1
            ) AND `focal_point_key` IS NULL
        """)
