### ISSUE TITLE
  getattr(): attribute name must be string

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#2114]
Hi guys

I have a problem with Django 1.9.1 and Wagtail 1.3.1
![typeerror at -admin-pages-3-edit- - mozilla firefox_019](https://cloud.githubusercontent.com/assets/5034215/12345601/fa0d31b6-bb18-11e5-9c5f-134cef17e65d.png)
![typeerror at -admin-pages-3-edit- - mozilla firefox_020](https://cloud.githubusercontent.com/assets/5034215/12345602/fa0ddbfc-bb18-11e5-956b-1cbfa9b6f916.png)

I was working with wagtail 1.0 and django 1.8.5 and hasn't problem with it but now i have this problem. And i don't know why :'(

This happen whe i try edit any page... i applied all migrations in the system.

Can anyone help me?

**Comment by gasman** [comment]
Hi @SalahAdDin,
As we have told you several times before - **Github issues are the wrong place to ask for technical support with Wagtail**. Please use the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail), where there is a larger community of people available to help.

Github issues are for the development of Wagtail only - responding to support queries here takes time away from developing Wagtail. If you continue to ignore our requests, we will have no alternative but to block you from contributing to the Github project.

**Comment by rhodges** [comment]
For anyone who found this while Googling the problem looking for the solution, please see https://groups.google.com/forum/#!topic/wagtail/d2Mhkf-gT5U
