### ISSUE TITLE
RedirectMiddleware should check request has site attr before using it

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#2120]
`wagtail.wagtailredirects.middleware.RedirectMiddleware` should check for `request.site` existing before accessing it.  If a middleware installed before `wagtail.wagtailcore.middleware.SiteMiddleware` returns a response then the RedirectMiddleware causes a 500 error.

```
Internal Server Error: /page/foo
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/wagtail/wagtailredirects/middleware.py", line 22, in process_response
    redirect = models.Redirect.get_for_site(request.site).get(old_path=path)
AttributeError: 'WSGIRequest' object has no attribute 'site'
```

Per [docs](https://docs.djangoproject.com/en/1.9/topics/http/middleware/#process-response):

> Unlike the process_request() and process_view() methods, the process_response() method is 
> always called, even if the process_request() and process_view() methods of the same middleware 
> class were skipped (because an earlier middleware method returned an HttpResponse). In 
> particular, this means that your process_response() method cannot rely on setup done in 
> process_request().

**Comment by kaedroho** [comment]
Thanks for the report!
