### ISSUE TITLE
ValueError: Cannot query "ContentType object": Must be "ContentType" instance. with Travis

### ISSUE THREAD

**Issue by albertoconnor** [torchbox/wagtail#2128]
I understand this is an obscure issue, and it is really unlikely a change like this will land, but here goes.

When we run our tests on travis we get the following error:

`ValueError: Cannot query "ContentType object": Must be "ContentType" instance.`

Here is an example of a failing job:

https://travis-ci.org/OpenCanada/website/jobs/94555871

When we run the test on dev or in product we can't replicate issue. In the past we have fixed by using `pk` instead of instance in data migrations in our own code. In this case it is in wagtail's code and I was able to get the Travis builds to work again with this fork:

https://github.com/albertoconnor/wagtail/commit/3211997f54fbe316a668f216cb4e08743419d61a

This leads to a maintenance issue on our part, and I am about to test this with Wagtail 1.3.1, and assuming it still is an issue I will be updating my fork. If it is possible a change like this could land in Wagtail it would make our lives slightly easier and should be functionally the same.

We can't explain why this is only an issue with Travis and would understand if more investigation would be required.

**Comment by gasman** [comment]
Hi @albertoconnor - is the Travis link correct? That one doesn't seem to match the error described...

**Comment by albertoconnor** [comment]
You are right it isn't correct:

https://travis-ci.org/OpenCanada/website/jobs/90819522

**Comment by albertoconnor** [comment]
In a strange twist, it looks like wagtail 1.3.1 is working:

https://travis-ci.org/OpenCanada/website/jobs/103412147

Might have something to do with how the order of migrations actually get resolved. Feel free to close for now at least.

**Comment by gasman** [comment]
This looks rather similar to https://groups.google.com/d/msg/wagtail/oesji9HJ4ZQ/9DEtBUaSCQAJ - a bug in Django 1.8 that was fixed in 1.8.1. Perhaps updating your dependencies indirectly caused Django to a non-broken version...?

Will close until this is confirmed as reproducible on latest Django/Wagtail, then. (Wagtail 1.4 will drop Django 1.7 support, and specifically require Django 1.8.1 or above.) Thanks for the report!
