### ISSUE TITLE
Redirect doesn't work with urls having a trailing slash

### ISSUE THREAD

**Issue by dperetti** [torchbox/wagtail#2138]
We cannot enter a redirect url with a trailing slash since https://github.com/torchbox/wagtail/issues/1350 (which consisted in normalizing the path, thus removing the trailing slash).

That's fine but then I guess every incoming request needs to be normalized before searching for matching redirects.

**Comment by kaedroho** [comment]
> That's fine but then I guess every incoming request needs to be normalized before searching for matching redirects. 

Looks like that's already the case: https://github.com/torchbox/wagtail/blob/13c6904598cc43eb15991bcda1073b82cf0070b4/wagtail/wagtailredirects/middleware.py

**Comment by dperetti** [comment]
Thank you for pointing this out !  I just found out that **the redirect only works when the response is 404** !
I was trying to override the "purchase" item of my top menu in order to redirect to the payment platform, which I agree is a very specific case. Would have been handy though !
