### ISSUE TITLE
Create a live demo site

### ISSUE THREAD

**Issue by bufke** [torchbox/wagtail#214]
Here is one I made but I won't be updating it and make no promises it will continue to exist. username and password are demo

http://bsc-wagtail-demo.herokuapp.com/

If someone wants access to the heroku app to maintain it let me know.

**Comment by kaedroho** [comment]
This is currently being addressed in https://github.com/torchbox/wagtaildemo/pull/44.

I'd like to create a little app that launches instances of wagtaildemo on a Docker server so people can play around with it without needing to sign up for Heroku. That's something I'll probably have a go at on a weekend sometime though.

**Comment by SalahAdDin** [comment]
I think the same, is a good idea.

**Comment by kaedroho** [comment]
http://demo.wagtail.io

**Comment by SalahAdDin** [comment]
:+1:
