### ISSUE TITLE
image tags not saving after upload

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#2142]
![large](https://cloud.githubusercontent.com/assets/5364807/12511222/8396423a-c107-11e5-8f8f-77787e52add7.png)
Hi,

We're experiencing a bug when an image is uploaded and you can tag it straight away, the tags don't get saved, Our users need to go into images, then click on the image, and add tags a second time for them to stick.

i have a feeling we had this before but it was fixed? but I could be wrong.

Thanks

Joss

**Comment by timheap** [comment]
I can confirm this. Steps to reproduce:

* Select 'Images' from the admin side bar.
* Press 'Add an image' button in the header.
* Drag-drop/click to upload an image or three to upload. Number or method do not seem to matter here.
* Once they have uploaded, add a tag to one of the images, and hit 'Update'.
* Navigate back to 'Images', and select the newly uploaded image.
* On the edit page, note the lack of tags.

You can successfully tag images from edit page, but not from the inline quick editor.

**Comment by timheap** [comment]
Looking in to it a bit more, it seems that tags entered are not POSTed to the backend from the multiuploader page, but are POSTed properly from the regular edit page.

**Comment by timheap** [comment]
Alright, I tracked it down. That was an annoying bug...

It seems that tagit is getting initialised twice for this one input. Once through the `<script>` tag appended to the AdminTagWidget output, and once from [add-multiple.js](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/static_src/wagtailimages/js/add-multiple.js#L109-L110). This double up, combined with the generic nature of the `.tag_field input` selector, ultimately means that the generated input for the first tagit instance is turned in to another tagit instance, and the tags entered in to the new tagit instance are not saved to the real input. Thus, no tags.

**Comment by hermey** [comment]
hier oder dort?


On Sun, 24 Jan 2016 18:29:52 -0800, Tim Heap <notifications@github.com>
wrote :

**Comment by tomdyson** [comment]
Thanks for the report @jossingram and for the fix @timheap!
