### ISSUE TITLE
Feature request: LTS version

### ISSUE THREAD

**Issue by stevejalim** [torchbox/wagtail#2148]
Hi folks

Not sure if/where this is on the roadmap, but it would be good if there were a long-term-support version of Wagtail, in addition to the usual releases.

For example, we've got something built with 1.0, but bringing it up to date with 1.3 is breaking our build, due to various backwards incompatible changes. We're upgrading, in case there's ever a security release we need, but it's more work than anticipated.

Given how rapidly Wagtail is growing, I think there might be a case for an LTS version where security  fixes are backported but newer features are not included. What do you think @gasman @tomdyson @kaedroho? 

Cheers
Steve

**Comment by shredding** [comment]
Preferably in sync with Django LTS ...

**Comment by tomdyson** [comment]
Wagtail 0.8 was our last LTS-ish version. I like the idea of syncing with Django LTS, although it looks like the next LTS isn't scheduled until April 2017: https://www.djangoproject.com/download/. Wagtail 1.0 was the first to support the last Django LTS (1.8) but I think it will be too much of a burden to backport security fixes until 2017. We could make Wagtail 1.4 LTS - what do others think?

**Comment by stevejalim** [comment]
Yes, I was going to suggest syncing with Django's LTS pattern in general.

However, given that Django 1.8 LTS is around till at least 2018, an non-'ish' Wagtail LTS release sooner rather than later would be really welcome. Thanks for being open to it.

**Comment by auvipy** [comment]
making wagtail 1.4 lts could be a very good idea.

**Comment by gasman** [comment]
1.4 has now been released as a LTS branch.
