### ISSUE TITLE
Wagtail API missing configuration variables

### ISSUE THREAD

**Issue by negletios** [torchbox/wagtail#2156]
On 1.3.1 there are some configuration variables for Wagtail API like WAGTAILAPI_SEARCH_ENABLED and WAGTAILAPI_MAX_RESULTS.

I cannot see where  WAGTAILAPI_MAX_RESULTS is used on the wagtailapi code. And even so it has no effect on my testing enviroment. Either I put 1 or 100 its the same thing on the response.

I think somehow there is the documentation for the feature, but it is not implemented yet.

**Comment by alexgleason** [comment]
Indeed, these settings only appear in the documentation and not the codebase. https://github.com/torchbox/wagtail/search?utf8=%E2%9C%93&q=WAGTAILAPI_MAX_RESULTS

**Comment by kaedroho** [comment]
Oops, documentation error. the name is actually ``WAGTAILAPI_LIMIT_MAX`` (https://github.com/torchbox/wagtail/blob/master/wagtail/contrib/wagtailapi/pagination.py#L13). Thanks for spotting!
