### ISSUE TITLE
AbstractDocument is fairly restrictive

### ISSUE THREAD

**Issue by jschneier** [torchbox/wagtail#2168]
Hi I'm playing around with the master branch (please release 1.4! :p) and in particular the new overridable custom document model.

Thus far I've found it to be fairly restrictive. For example, I want to remove tags from it, however this then breaks because `popular_tags(cls)` no longer exists (I removed `TagSearchable`). It would be nice if this could be relaxed a little more, in much the same way that the Django `AbstractUser` and `AbstractBaseUser` provide minimal and easily overridable implementations.

**Comment by alexgleason** [comment]
Thanks for pointing this out. I added the code the allow abstract documents, which was based on the code for abstract images. So if there's any restrictions here it may make sense to also explore them for images.

It may also make sense to let each of these modules share some code (#2035)

**Comment by jschneier** [comment]
After playing around with this some more I think the current implementation is actually pretty good, tagging would be the only thing I'm not sure about. Going to close this for now :)
