### ISSUE TITLE
--no-data flag for update_index command

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2171]
Sites that want to run unit tests with Elasticsearch need to make sure the schema is installed in Elasticsearch before running the tests. Otherwise, Elasticsearch will try to guess the schema.

You can't run ``update_index`` on a CI server as there is usually no database available. So we need a command that installs the schema but doesn't attempt to read from the database.

I'm thinking adding a ``--no-data`` flag to the ``update_index`` command would be the best way to get this. It will be run just before running the tests:

```shell
python manage.py update_index --no-data
python manage.py test
```

**Comment by gasman** [comment]
Fixed in #2383
