### ISSUE TITLE
[Error] 'send_notification' when submitting page for moderation

### ISSUE THREAD

**Issue by tiagofmc** [torchbox/wagtail#2173]
I have a page that can be created/edited by two groups of users, lets call them Editors and Admin.
When I try submit a page for moderation with both groups, it gives me this error:

> more than one row returned by a subquery used as an expression

I investigated a little further and I found the problem in method 'send_notification' in wagtail/wagtailadmin. 
The problem is on line 66 of function 'users_with_page_permission'. 
`return User.objects.filter(is_active=True).filter(q).distinct()`

When running this code in debug, I tried replacing 'q' by this: 
`User.objects.filter(is_active=True).filter(groups__page_permission=perm)`
, which is half of the query attributed to 'q'. The 'is_superuser' added after the declaration works fine on its own.
And it gives me another error:

> *** ValueError: Cannot use QuerySet for "grouppagepermission": Use a QuerySet for "Group".

I printed the 'perm' variable to see its value:

`[<GroupPagePermission: GroupPagePermission object>, <GroupPagePermission: GroupPagePermission object>]`

The content of the 'perm' list: 
`{'page_id': 1, 'group_id': 1, '_state': <django.db.models.base.ModelState object at 0x1153cf2d0>, 'id': 3, 'permission_type': u'publish'}`

`{'page_id': 3, 'group_id': 4, '_state': <django.db.models.base.ModelState object at 0x1153cf8d0>, 'id': 8, 'permission_type': u'publish'}`

Any idea how to solve this problem?
Thanks in advance.

**Comment by nek4life** [comment]
How bizarre we just encountered the same issue not more than an hour ago as well. I've tracked the code back to essentially the same place you have outlined above. 

Wagtail Version 1.3.1

```
Request Method: POST
Request URL: http:///blogs/admin/pages/36/edit/
Django Version: 1.9.1
Python Executable: /usr/bin/uwsgi
Python Version: 3.4.2
Python Path: ['.', '', '/var/www//burtonblogs', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/var/www//venv/lib/python3.4/site-packages']
Server time: Fri, 29 Jan 2016 13:27:11 -0500
Installed Applications:
['burton_blogs.videos',
'burton_blogs.search',
'burton_blogs.blogs',
'burton_blogs.core',
'burton_blogs.apps.BurtonBlogsConfig',
'wagtail.wagtailforms',
'wagtail.wagtailredirects',
'wagtail.wagtailembeds',
'wagtail.wagtailsites',
'wagtail.wagtailusers',
'wagtail.wagtailsnippets',
'wagtail.wagtaildocs',
'wagtail.wagtailimages',
'wagtail.wagtailsearch',
'wagtail.wagtailadmin',
'wagtail.wagtailcore',
'wagtail.contrib.wagtailroutablepage',
'wagtail.contrib.wagtailstyleguide',
'modelcluster',
'compressor',
'taggit',
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.middleware.security.SecurityMiddleware',
'wagtail.wagtailcore.middleware.SiteMiddleware',
'wagtail.wagtailredirects.middleware.RedirectMiddleware')


Traceback:  

File "/var/www//venv/lib/python3.4/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
  
    
      The above exception (more than one row returned by a subquery used as an expression
) was the direct cause of the following exception:
    
  

File "/var/www//venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/var/www//venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www//venv/lib/python3.4/site-packages/django/views/decorators/cache.py" in _cache_controlled
  43.             response = viewfunc(request, *args, **kw)

File "/var/www//venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/var/www//venv/lib/python3.4/site-packages/wagtail/wagtailadmin/views/pages.py" in edit
  272.                 send_notification(page.get_latest_revision().id, 'submitted', request.user.id)

File "/var/www//venv/lib/python3.4/site-packages/wagtail/wagtailadmin/utils.py" in send_notification
  156.         recipient for recipient in recipients

File "/var/www//venv/lib/python3.4/site-packages/django/db/models/query.py" in __iter__
  258.         self._fetch_all()

File "/var/www//vev/lib/python3.4/site-packages/django/db/models/query.py" in _fetch_all
  1074.             self._result_cache = list(self.iterator())

File "/var/www//venv/lib/python3.4/site-packages/django/db/models/query.py" in __iter__
  52.         results = compiler.execute_sql()

File "/var/www//venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
  848.             cursor.execute(sql, params)

File "/var/www//venv/lib/python3.4/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/var/www//venv/lib/python3.4/site-packages/django/db/utils.py" in __exit__
  95.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/var/www//venv/lib/python3.4/site-packages/django/utils/six.py" in reraise
  685.             raise value.with_traceback(tb)

File "/var/www//venv/lib/python3.4/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/pages/36/edit/
Exception Value: more than one row returned by a subquery used as an expression
```

**Comment by gasman** [comment]
This was reported and fixed earlier today, in #2169.

**Comment by nek4life** [comment]
@gasman Hey Matt,

What determines if one is a moderator? Is it the can publish any page permission? I'm trying to figure out how to fix this error without running wagtail from the master branch.

**Comment by gasman** [comment]
@nek4life Yes, any user with publish permission for the relevant page is considered a moderator.

(I would suggest using a nightly build from http://wagtailnightly.kaed.uk/, but it looks like they stopped building in November - any idea what happened there, @kaedroho?)

**Comment by nek4life** [comment]
Perfect disabling the publish permission on one of the groups fixed the issue. I'm not sure why it was turned on in both groups in the first place, I'll have to inquire with the other site admins, but nevertheless thank you for all the help! I will probably just stick to the current release unless it's decided both groups need to publish, but in that case I feel as though they should just move everyone to the same group and be done with it.
