### ISSUE TITLE
Image/document modal not showing when DEBUG = False

### ISSUE THREAD

**Issue by Fonz001** [torchbox/wagtail#2176]
On my production server the image modal is nog showing when DEBUG is disabled. Its seems to be a client-side javascript issue. 

There are no network errors. But the admin interface starts with the console error: 

`747bc443edaf.js:272 Uncaught TypeError: $(...) is not a function(anonymous function)`

When I click on "select an image" :

`VM10084:1 Uncaught SyntaxError: Unexpected token`

When I enable DEBUG, the issue can no longer be reproduced. Both of the errors do not occur.

Not an urgent issue, but it would be nice to be able to turn off DEBUG

**Comment by alexgleason** [comment]
The difference between debug being on or off is that in production, Wagtail will minify, concatenate, and cache the javascript files. In development, Wagtail will serve each file as a separate HTTP request.

So maybe something is going wrong when the files get concatenated and minified. Do you have any custom javascript files that would cause a problem if concatenated? eg one that doesn't contain a semi colon or bracket where it should.

Check for errors in you console when in debug, too.

**Comment by gasman** [comment]
@Fonz001 What version of Wagtail are you using?

**Comment by Fonz001** [comment]
Hi!

@alexgleason Your solution worked, a missing semicolon in custom javascript! Thanks guys! +1
