### ISSUE TITLE
Update jQuery for wagtailadmin from 1.10.1 to 1.10.2 to fix iframe bug

### ISSUE THREAD

**Issue by Rayil** [torchbox/wagtail#2186]
If you use an iframe linking to a Wagtail site, jQuery won't load in Internet Explorer. The jQuery bug is found here: https://bugs.jquery.com/ticket/13980, and was fixed in 1.10.2: http://blog.jquery.com/2013/07/03/jquery-1-10-2-and-2-0-3-released/.

`wagtailadmin/templates/wagtailadmin/admin_base.html` references the jQuery file located at `wagtailadmin/static_src/wagtailadmin/js/vendor/jquery-1.10.3.js`. I'm unsure why the file name is 1.10.3, but the actual file is jQuery 1.10.1.

**Comment by davecranwell** [comment]
We should probably upgrade to 2.x if we can. We'd only want 1.x if we supported <=IE8, which we don't. It's possible another plugin we're using requires 1.x but that seems unlikely.

**Comment by tomdyson** [comment]
Agreed, we should upgrade to 2.x. Shall we do the 1.10.3 fix in the meantime?

**Comment by JoshBarr** [comment]
jQuery 2 was released in 2013, and has the same API as jQuery 1.9 onwards. In theory, if anything works now, it should work with jQuery 2, but be faster.

**Comment by gasman** [comment]
Upgraded to 2.2.1 in #2303.

**Comment by SalahAdDin** [comment]
:+1:
