### ISSUE TITLE
Wagtail userbar iframe empty

### ISSUE THREAD

**Issue by benebun** [torchbox/wagtail#2193]
We had to disable the userbar because it loaded an empty iframe (and made the UI inaccessible as discussed also in #2164)

The iframe is empty because:
- we redirect /admin to https
- when editors visit the frontend via http this redirect interferes with the loading of the userbar so it displays an empty iframe that invisibly overlaps the UI of the website.

An alternative workaround instead of disabling the userbar entirely would probably be to use https also on the frontend but that seems overkill.

**Comment by JoshBarr** [comment]
Given that you've already paid for the certificate, and browsers (Chrome/FF) are looking to block unencrypted sites (or display warnings), is there a reason not to serve the frontend over HTTPS, at least for your admins? 

We can definitely help with the empty ifrsme though, by checking the resources are accessible over the current protocol before injecting the admin bar.

**Comment by nek4life** [comment]
I have the same issue. We redirect the admin portion only. We do this because unfortunately we have 3rd party javascript integrations that do not support https at this time making it impossible for us to run the entire site under https. The weird thing is that the bar does load, however the images do not display so we are able to click on the toolbar if you know where it is, but you cannot see it. This would be great to fix so the userbar is usable while securing the admin portion of the site.

**Comment by benebun** [comment]
> Given that you've already paid for the certificate

Nope, we/the client hasn't paid for a certificate, we use a self-signed one for the admin, which can be explained to the client but of course wouldn't work for the frontend with a public audience.

It's not a big deal for us atm, right now we rather disable the userbar as an additional feature until we/the client is forced to buy a certificate for the frontend when, like you say, browsers display warnings or SEO is more of an issue.

**Comment by benebun** [comment]
> The weird thing is that the bar does load, however the images do not display so we are able to click on the toolbar if you know where it is, but you cannot see it.
@nek4life interesting, for us it was different: when checking the iframe in the developer tools it was completely empty.

**Comment by davecranwell** [comment]
The wagtail userbar no longer uses an iframe at all, thanks to https://github.com/torchbox/wagtail/pull/2201
