### ISSUE TITLE
Wagtail userbar click to take user to Explorer section containing current page

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#2195]
I tend to only need the wagtail userbar for one of two reasons:

1. edit the current page
2. manage pages around it

There's no button for the second option. Clicking the wagtail logo itself takes you to the dashboard, but is the dashboard _ever_ that helpful as a landing page from the userbar?

I therefore propose that clicking the wagtail takes you to the Explorer, into the section containing the page you're currently on.

**Comment by nek4life** [comment]
+1 This would be great for jumping to an index page and I agree that's exactly what I would like to do many times.

**Comment by JoshBarr** [comment]
Solved in #2201.
