### ISSUE TITLE
Right click->Paste in RichText area doesnt work (IE11)

### ISSUE THREAD

**Issue by jonnyscholes** [torchbox/wagtail#2210]
Wagtail version: 1.3.1
Browser: Internet Explorer 10/11
OS: Windows 10

What should happen: When pasting via right click into RichText field it should show up and then save correctly.

What happens: After pasting via right click the text appears but after saving and coming back to the page the pasted text is no longer present. If the field has no length requirements the page saves successfully. If it does then the page errors and highlights the field in question - but the field is empty.

Inspecting the request I can see that the content is never sent - so the backend receives an empty field and responds appropriately.

**Comment by jonnyscholes** [comment]
Looking into hallojs I found a PR from 2014 that reports this issue (and apparently fixes - although I'm not convinced). https://github.com/bergie/hallo/pull/219

**Comment by gasman** [comment]
Fixed in #2605
