### ISSUE TITLE
Lack of cancel button on 'unpublish' or 'delete' pages

### ISSUE THREAD

**Issue by heymonkeyriot** [torchbox/wagtail#2213]
If an editor clicks on `delete` or `unpublish` they're taken to new screens. Neither screen gives the option to `cancel` their decision.

**Unpublish screen**
![image](https://cloud.githubusercontent.com/assets/11335309/12910243/ba7e5ab0-cf00-11e5-9a8b-789cf98672f5.png)

**Delete screen**
![image](https://cloud.githubusercontent.com/assets/11335309/12910222/8d746ca8-cf00-11e5-9920-6767840a8743.png)

The only way for the user to go back to the edit screen is to hit the `back` button or for them to re-find it via the explorer. It's an issue as it's quite easy to hit delete when you mean to hit publish (I've done it a few times at least) and once on the page the messaging is set-up around the idea that you do either want to delete or unpublish the page. In the long run it's probably preferable to allow the user to delete/ unpublish directly from the edit page, since moving to a new page removes any streamfield ordering (c/f #475 ), but that would be a great deal more complex to implement.

Below is an attempt to add the option of cancelling the action for users. I also tried to increase the consistency between the two screens (on unpublish the user is currently asked a question, and given the choice of an answer, on the delete screen it's a narrative with two actions). Below both consistently ask the question that the user has clicked on, with unpublish being hierarchically secondary on the delete screen.

![image](https://cloud.githubusercontent.com/assets/11335309/12910332/c3dc9ada-cf01-11e5-81b1-a9ed3c05c0dd.png)

![image](https://cloud.githubusercontent.com/assets/11335309/12910551/83d0f722-cf03-11e5-98c9-ecdd1712c895.png)

Do others feel this would be an improvement?

**Comment by davecranwell** [comment]
Having the option to not-do it is an improvement I think, although I see no reason for the "alternate unpublish" option to not also be a button.

This whole delete interface is traditionally the domain of a modal window so I wonder whether that would be another/better solution. A hybrid alternative might be to centrally aligned the buttons, and the main question, in the centre of the screen. We might benefit from the ubiquity of centralised "[Do This] or [Don't]" interfaces if we adopted a similar layout.

**Comment by alexgleason** [comment]
There's a good A List Apart article about avoiding warnings. http://alistapart.com/article/neveruseawarning

If you're on Android, you can see this in the Gmail app. Try deleting one of your email threads and see how it disappears immediately with a black confirmation box that lets you undo it.

Note that I first saw this in elementary OS's human interface guidelines (HIG) http://elementary.io/docs/human-interface-guidelines#always-provide-an-undo I highly recommend looking through it. I know this is for an operating system and not a CMS but they have some great ideas and it works very well as a reference for good UX.

**Comment by davecranwell** [comment]
I like those ideas. How easy would it be to "undo" the deletion of a page, I wonder?

**Comment by gasman** [comment]
@davecranwell It certainly makes it a bigger job than a UI change, but probably not an insurmountable task. Obviously it requires the deleted pages to be kept in the database, so we'd need to add a new flag to indicate 'deleted' status, and update the admin UI (and other places, e.g. the API?) to hide them. All existing front-end code (menus etc) *should* already be filtering pages to `live=True`, so hopefully no changes required there.

(There are probably other messy edge cases that arise from keeping deleted items in the database - on_delete actions on foreign keys will no longer apply, for example. And if/when we implement #1602, what happens if you try to delete an image that's linked from a deleted page?)

**Comment by alexgleason** [comment]
^ That's what I was thinking, too. Theoretically having this new status could also allow for a "trash bin" functionality like WordPress where you can view, restore, or permanently delete the items (there's no undo for this action!) In WordPress the trash bin is emptied automatically after 30 days.

**Comment by davecranwell** [comment]
Should this be something we roll out one entity at a time e.g pages first, then images, docs, snippets etc, or should this be all-or-nothing? It would create dangerously inconsistent UX to do this for pages but not, say, images. However the larger the task, the less likely we are to prioritise it, I expect.

**Comment by alexgleason** [comment]
I think it could be rolled out at once, but it's not something that can be done entirely on the front-end. Pages, images, and documents would all require separate changes to be made to them individually.

I just looked at the way it's set up. For documents and images there's no concept of "unpublishing" them. This makes sense, I'm just pointing out the difference. They directly call Django's native [Model.delete()](https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.delete) function inside of a view when you click "delete" in the admin. We may want to abstract that out into a separate function like Pages, as described below:

Pages have a [custom delete function](https://github.com/torchbox/wagtail/blob/0cf59107a717c8396a7d5313672900e41ea653f0/wagtail/wagtailcore/models.py#L444) right inside of the model that would need to be changed to work more like [unpublish](https://github.com/torchbox/wagtail/blob/0cf59107a717c8396a7d5313672900e41ea653f0/wagtail/wagtailcore/models.py#L653), then add a "deleted" state to it as Matthew says.

On the front-end, the "delete" buttons for documents/images/pages are just a input type="submit" button inside an HTML form. There's a hidden input csrf token that gets posted and causes the delete.

For a page, the URL is like: `/admin/pages/42/delete/`
And for a document: `/admin/documents/delete/5/`

Posting csrf data to these URLs would delete them. (BTW: just noticed the inconsistent URLs structures)

**Comment by m1kola** [comment]
Fixed in #2830

**Comment by ababic** [comment]
Just a thought, guys. Should this be reflected in the ModelAdmin 'delete' view also?

**Comment by m1kola** [comment]
> Just a thought, guys. Should this be reflected in the ModelAdmin 'delete' view also?

I think It's a good idea to have consistent behaviour. Could you, please, create a PR / issue?
