### ISSUE TITLE
Why enforce django-compressor?

### ISSUE THREAD

**Issue by peterlauri** [torchbox/wagtail#2226]
I was just trying to deploy wagtail to our already existing django project. It kind of got stuck a bit due to the compressor app, that doesn't play well with our deployment on AWS and using whitenoise. Is there a specific reason why static file compression is build-in in wagtail? And why not let this be a part of the deployment process of the specific project? Of course, in a wagtail-only deployment, this isn't a problem, but when one try to fit wagtail into an already existing project, this can be a problem.

My solution around this is to just use the setting **COMPRESS_ENABLED = False**, and all works. But that makes me cry :)

**Comment by m1kola** [comment]
Hi @peterlauri! [Wagtail 1.4 no longer depends](http://docs.wagtail.io/en/latest/releases/1.4.html#removed-django-compressor-dependency) on django-compressor. You just need to upgrade to 1.4 version when it will be released ;)

**Comment by gasman** [comment]
Covered by #2132.

**Comment by peterlauri** [comment]
Sweet! I should have read the planned release... So I wasn't the first one that thought about this, good :)
