### ISSUE TITLE
Create Page Models dynamically.

### ISSUE THREAD

**Issue by istinspring** [torchbox/wagtail#2235]
Hello, i'm pretty new with wagtall and trying to use it as CMS for a bunch of slightly different content catalogs. What i want to do is to generate Page Models dynamically for each site according to some configuration data. I know it's possible to do with django models:

```
attrs = {
    'name': models.CharField(max_length=32),
    '__module__': 'myapp.models'
}
Animal = type("Animal", (models.Model,), attrs)
```

Can i do the same for wagtall Page Models?

**Comment by gasman** [comment]
Hi @istinspring - please use the [Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
