### ISSUE TITLE
Date picker widget should highlight current date at all times

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#2239]
When the datepicker opens on an clean date field, the modals opens on the current month, with the current day highlighted in the salmon colour.

Once a date is selected, assuming that date isn't today, the picker will never again colour-code the current date if re-opened. It will show the date selected in the field, but not the current date. As someone rarely aware of the actual date, I find this endlessly frustrating.

There's one other idiosyncrasy worth addressing when this issue is handled: When the picker is opened on a clean field, the current date e.g 15, is highlighted, but the number 15 remains highlighted in each of the months you choose, regardless of the actual current month. I can't work out why this would be useful and again this causes confusion.

**Comment by timheap** [comment]
Fixed by #2260
