### ISSUE TITLE
HTML in notification e-mail

### ISSUE THREAD

**Issue by mikedingjan** [torchbox/wagtail#2245]
For a upcoming project we would like to implement HTML e-mails for notifications. Before sending a PR I would like to discuss the "best way" for doing this.

My proposal:
To keep backwards compatibility it's good to have a setting which enables HTML e-mail (default=False) when this setting is set to True the send_email function should attach a extra html_message kwarg which will contain the original message (already a HTML file). the text message will then be a stripped ``django.utils.html.strip_tags`` alternative of the already loaded message.

Any thoughts on this?

**Comment by mikedingjan** [comment]
Something like this: 

https://github.com/mikedingjan/wagtail/commit/77d3e9146f1200d030d65f0f71a46ac2df9dd556

**Comment by gasman** [comment]
Sounds good to me, although not sure about using `strip_tags` - we wouldn't want to end up with link text with no corresponding links. If HTML email is going to be an optional setting then we'll be keeping the plain text versions around anyway - any reason not to just use those?

**Comment by mikedingjan** [comment]
Good one, ``strip_tags`` might not be the best approach for this. I'll look into another solution for this.

**Comment by davecranwell** [comment]
Shall we ditch this older ticket https://github.com/torchbox/wagtail/issues/662 in favour of this one, or continue this in #662?

**Comment by mikedingjan** [comment]
One possible solution for this is using a regex which replaces all HTML tags without the a tags, that would be something like ``<(?!\/?a(?=>|\s.*>))\/?.*?>``. personally I don't like this because it isn't easy maintainable.

A other solution could be creating our own implementation of ``strip_tags`` which would then skip the a tag..

On the other hand how bad is it that the text version of the e-mail doesn't have links? HTML e-mail is widely supported these days.

Any thoughts?

**Comment by mikedingjan** [comment]
Another solution would be splitting up the templates between a HTML and TXT version, in my opinion this is the nicer one. Django default implementation also works like this. The subject will also be stored in a separate txt file, like django.

**Comment by tomdyson** [comment]
Hi @mikedingjan! I think splitting up the templates is the way to go.

**Comment by mikedingjan** [comment]
Cool, I will start implementing that

**Comment by gasman** [comment]
> On the other hand how bad is it that the text version of the e-mail doesn't have links? HTML e-mail is widely supported these days.

I'd say the links are pretty much the sole reason for the notification email to exist in the first place - if we aren't dealing with them gracefully, then we could just as well hard-code the plain-text version to "`blah blah blah nobody will see this`" and save ourselves a job ;-)

+1 for splitting up templates. Having a single-line template just for the subject line seems a bit clunky to me, but all the alternatives I can think of (e.g. a NotificationEmail class with `html`, `plaintext` and `subject` methods, where `html` and `plaintext` use templates but `subject` doesn't) are over-engineered, so let's go with that.

**Comment by gasman** [comment]
Implemented in #2253
