### ISSUE TITLE
Incorrect label alignment on select boxes

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2246]
Labels on select boxes are top-aligned rather than centred as on other field types:

![screen shot 2016-02-17 at 11 03 55](https://cloud.githubusercontent.com/assets/85097/13107646/8c7e46fe-d566-11e5-9971-068b1f204cc4.png)

This is especially conspicuous when collections (#2243) are in use, as they add a new dropdown to the image/document views.

**Comment by m1kola** [comment]
Seems like we should review labels for all types on different languages.

Same page with `LANGUAGE_CODE = 'de'` looks like shown below.
<img width="259" alt="screen shot 2016-02-17 at 23 44 14" src="https://cloud.githubusercontent.com/assets/509198/13124076/7639606c-d5d0-11e5-91a1-a62f980d2670.png">

**Comment by gasman** [comment]
Fixed in #2294
