### ISSUE TITLE
Display Wagtail version number inside of admin

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2248]
It's useful to see at a glance what version of Wagtail you're working on when moving across multiple projects.

This could be a faint indicator in the corner, or even an "About" menu similar to "Help > About" menus often seen in applications.

**Comment by gasman** [comment]
The version number appears as title text when you hover over the wagtail logo. Do we need something more discoverable, perhaps...?

**Comment by alexgleason** [comment]
Ahh, nice! Thanks.

Yes, I think it might be helpful to display it at the very bottom of the "Settings" menu?

![screenshot from 2016-02-17 11 35 25](https://cloud.githubusercontent.com/assets/3639540/13116709/e00702da-d56a-11e5-9470-700842b34c9c.png)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Implemented in #2769
