### ISSUE TITLE
Remove col* classes from FieldRowPanel

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2257]
``FieldRowPanel`` currently requires the developer to set ``col*`` classes on all of the child panels. As described in: http://docs.wagtail.io/en/v1.3.1/reference/pages/panels.html#fieldrowpanel

I think it would be a neater if these classes were added automatically (based on the total number of fields specified), so a developer only has to specify the fields.

**Comment by davecranwell** [comment]
There would still be some need to specify the widths wouldn't there? The kind of columnar layout you want couldn't be divined from the child fields alone could it?

For example if you had three fields: a checkbox, and two text inputs. Imagine that the checkbox toggles the output of the other two fields into the page. You _might_ assume that if there are three fields in a row, they should each be `col-4` (i.e each 4 cols of the possible 12), but a checkbox might not need 4 cols and the text inputs might each require far more.

Perhaps if the classes were assumed (evenly dividing the number of fields between 12), but still allowed to be overridden, that might be nice.

**Comment by gasman** [comment]
Fixed in #2346
