### ISSUE TITLE
Inconsistency in help text appearance

### ISSUE THREAD

**Issue by heymonkeyriot** [torchbox/wagtail#2263]
Help text for non-streamfield blocks appear to the right hand side of the field on hover with an icon. Help text on a block within streamfield is always visible, and doesn't have an icon.

**Comment by davecranwell** [comment]
@heymonkeyriot https://github.com/torchbox/wagtail/issues/1442 is worth a read for some background on this.

I'd like to either consistently place the help text somewhere (which might result in removal of these "full bleed" - `classname="full"` - designed fields we have such as the page Title) or to remove it altogether on account of it's low usage.

**Comment by heymonkeyriot** [comment]
Thanks Dave. I think the issue would be better tracked on the already open issue. 

For what its worth, I think the help text should definitely have a consistent location. It's also important to have. I think it's currently underused but is important as a way of giving advice to editors. Anyhow, will respond at more length on the other ticket.
