### ISSUE TITLE
Settings menu items unclickable in Firefox 46.0a2 (Developer Edition)

### ISSUE THREAD

**Issue by johnfraney** [torchbox/wagtail#2286]
The settings menu opens properly, but its menu items aren't accepting mouse clicks. The elements obscured by the menu accept the mouse hover and click actions instead. Only occurs in desktop mode (the mobile/responsive menu works as expected).

To reproduce:
1. Click Settings in the Wagtail menu
2. Click any of the Settings menu items (Users, Groups, Sites...)
3. The element underneath the settings menu will register the click and the settings menu will close

This bug does not occur in Firefox 44.

Environment:
- Arch Linux
- Wagtail 1.3.1
- Firefox 46.0a2 (Developer Edition)

**Comment by akx** [comment]
@juhakujala resolved this by removing `z-index: 1` from `.nav-main li` in the CSS, fwiw.

**Comment by gasman** [comment]
That would be this line here, I assume... https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/static_src/wagtailadmin/scss/core.scss#L447

@davecranwell, does the above fix sound acceptable to you?

**Comment by akx** [comment]
This will also be fixed in #2091: https://github.com/torchbox/wagtail/pull/2091/files#diff-d09d601d3959762ba04c5269294cdc3bL433

**Comment by gasman** [comment]
@akx Ah, good spot! In that case, I have no qualms about applying the suggested fix as a one-off (since #2091 isn't ready to merge just yet) - I'll do that now.

**Comment by johnfraney** [comment]
Great work, you guys. (I tried increasing the `z-index` to solve the issue and it didn't work. So close!)

**Comment by gasman** [comment]
Fixed in a67c971f4fd687ed7b937de210d29f5fb9c61244
