### ISSUE TITLE
Registered settings do not activate when selected

### ISSUE THREAD

**Issue by mgd020** [torchbox/wagtail#2307]
The active class is applied when the request.path begins with the `MenuItem.url`.
The MenuItem.url for a setting is `{app_label}/{model_name}/`
The request.path for a setting is `{pk}/{app_label}/{model_name}/`
The fix is to move `pk` to the end of the url like this `{app_label}/{model_name}/{pk}`
I have a PR for this.

**Comment by gasman** [comment]
Fixed in #2308
