### ISSUE TITLE
Error running "npm install"

### ISSUE THREAD

**Issue by timorieber** [torchbox/wagtail#2313]
Running `npm install` (bash on ubuntu 14.04) resulted in the following error:

> wagtail@1.0.0 install /path/to/wagtail
> pushd ./client; npm install; popd
> sh: 1: pushd: not found

Due to this issue I wasn't able to build the static assets for the wagtail admin UI. It took me a while to figure out what was causing the problem. As stated in http://stackoverflow.com/questions/5193048/bin-sh-pushd-not-found/5193092#5193092 `pushd` is a builtin function in bash, but node uses `sh` by default.

I finally changed
`"install": "pushd ./client; npm install; popd",`
to
`"install": "bash -c 'pushd ./client; npm install; popd'",`
in `package.json`.

I have no idea how to fix this issue for all operating systems, as I think my workaround will only work on linux.

**Comment by gasman** [comment]
Reported separately here: https://groups.google.com/d/msg/wagtail/iWl9IVd87Cg/VjbWA2ZEAwAJ . I think it's worth fixing this for 1.4, to avoid anyone else getting caught out by it - @JoshBarr / @justinvdm, please could you take a look? (I guess `cd ./client; npm install; cd ..` would be a more portable alternative, assuming the `npm install` doesn't do any further directory changing of its own...)

**Comment by timorieber** [comment]
Ah, ok. Never used `pushd` and `popd` before. `cd` should do the trick, except node changes directories itself as mentioned in https://github.com/torchbox/wagtail/issues/2313#issuecomment-192991512.

**Comment by gasman** [comment]
Fixed in #2314
