### ISSUE TITLE
User bar list spacing can be hijacked 

### ISSUE THREAD

**Issue by tomdyson** [torchbox/wagtail#2327]
There's extra spacing between the list items in my user bar / edit bird - see attached screenshot. My site uses http://getskeleton.com/ which includes the line:

```css
li {
  margin-bottom: 1rem; }
```

Can the user bar's CSS be scoped to avoid clashes like these?

<img width="731" alt="edit-bird-screenshot" src="https://cloud.githubusercontent.com/assets/15543/13642274/bf4af6fa-e613-11e5-9c1b-799d80ca9a3e.png">

**Comment by davecranwell** [comment]
It appears to have also inherited the font.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by JoshBarr** [comment]
My cunning plan is to not use list items at all. We'll go for generic spans or divs, and add more traps into the CSS. On modern browsers we can reset `all: initial` before applying any styling, which should help.

**Comment by gasman** [comment]
Hopefully fixed in #2341. @tomdyson, I've put up a custom build at http://playground.torchboxapps.com/matthew/wagtail/wagtail-1.4rc1-userbarfix.tar.gz with @JoshBarr's fix - please can you try this version (use this URL in place of `wagtail==1.4rc1` in your requirements file), and confirm whether this has fixed the styling?

**Comment by tomdyson** [comment]
WFM! Thanks, @JoshBarr.

<img width="680" alt="edit-bird-fixed" src="https://cloud.githubusercontent.com/assets/15543/13700241/ad454a22-e777-11e5-8a53-2cc2f79bbaf5.png">

**Comment by alexgleason** [comment]
Awesome! Also, I just reread my post, sorry if I sounded condescending. It was meant to be a general statement and not a jab at whoever programmed the new userbar.
