### ISSUE TITLE
Site.find_for_request should use request methods instead of request headers

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#2331]
Is there a reason that [Site.find_for_request()](https://github.com/torchbox/wagtail/blob/stable/1.3.x/wagtail/wagtailcore/models.py#L104) inspects request headers directly instead of using `request.get_host()`?  It does not look like wagtail respects `USE_X_FORWARDED_HOST` due to how it looks up the request site.

**Comment by gasman** [comment]
I don't think so - I think that might just have been me being unaware of `get_host`...

**Comment by gasman** [comment]
Duplicated by #2358 (closing this one as the other has a corresponding pull request)
