### ISSUE TITLE
Allow configurable site logo

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2337]
Wagtail instances should be able to have a configurable "site logo" associated with them. When present, the logo should replace the Wagtail bird in the admin dashboard and appear on the login screen. Related #2309 

Here's an example of what this looks like in Craft CMS where the client's logo is displayed on the login screen:

![screenshot from 2016-03-10 13 48 41](https://cloud.githubusercontent.com/assets/3639540/13680670/ab4f376a-e6c7-11e5-9fea-d6a42763e042.png)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by heymonkeyriot** [comment]
I think we could run in to difficulties trying to replace the logo in the admin UI (given it's aspect ratio) and I think would need a little more thinking to allow a client logo to work effectively in the admin UI. Makes a lot of sense on the login screen though to have an if statement to show the logo else it just shows the website title.

**Comment by alexgleason** [comment]
>"things that should be specified in the codebase, not the database"

Thanks! This makes sense. Initially I assumed there would be value in the site manager to update their logo. But I can't think of a realistic case for this.

Updated my issue title and text to abstract the implementation side out of this.

**Comment by gasman** [comment]
Closing as (as far as I can tell...) this functionality is exactly covered by http://docs.wagtail.io/en/v1.3.1/advanced_topics/customisation/branding.html.

**Comment by alexgleason** [comment]
Oh, you're right! Thanks.

**Comment by SalahAdDin** [comment]
First we need to wait about if will be a new login screen or now, and the we can branding loging screen, but, have loging screen a branding logo tag?

**Comment by JoshBarr** [comment]
@SalahAdDin yes, the plan is to make custom logos for the login screen into a `{% block %}` in the login template which developers can override on a per-project basis.

**Comment by SalahAdDin** [comment]
Great idea! :+1:
