### ISSUE TITLE
Shouldn't wagtail.contrib.settings.models.BaseSetting be called BaseSettings?

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#2348]
This is a fairly minor gripe, but I'm confused about why this class has a singular name, rather than a plural name, even though it represents the base model for a _collection of settings_. I know that it's convention to name database models in the singular (e.g. Page vs Pages), but a Page is a singular thing, while a BaseSetting represents all the settings for a singular Site.

**Comment by gasman** [comment]
This is the sort of naming problem that you can't really solve perfectly, and need to make a tradeoff between code clarity and logical correctness - for example, if we called the individual model 'settings' then you'd have the question of what to call an array of 'settings' objects. (I don't know if that particular situation is likely to ever come up, but I wouldn't want to count on us never running into similar problems.) Either way, changing the name at this point would involve going through a deprecation process, and I think the pain of that would outweigh any marginal benefits of making the change.
