### ISSUE TITLE
Not all admin pages call custom CSS hook

### ISSUE THREAD

**Issue by danni** [torchbox/wagtail#2363]
If you've registered a custom CSS hook (`insert_editor_css`) not all admin pages call it to be triggered.

**Comment by danni** [comment]
I've noticed some pages include:

```
{% block extra_css %}
    {% include "wagtailadmin/pages/_editor_css.html" %}
{% endblock %}
{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
{% endblock %}
```

Should this go into `admin_base`?

**Comment by danni** [comment]
Okay, I've now realised that's because it's meant to be for edit pages only, in which case how is one expected to add custom CSS more generally (i.e. to add additional icons to the interface when writing custom object types to the left hand menu).

**Comment by tomdyson** [comment]
Hi @danni. Yes, the `insert_editor_css` hook only fires on edit pages. Wagtail 1.4 has a new `insert_global_admin_css` hook which should do what you need:

http://docs.wagtail.io/en/latest/reference/hooks.html#insert-global-admin-css
