### ISSUE TITLE
WAGTAILIMAGES_BACKENDS

### ISSUE THREAD

**Issue by nordbit** [torchbox/wagtail#2368]
.. is removed from code. How to force Wagtail to use Wand as default image resizer engine? Wand is really far better for creating high quality thumbnalis, Pillow is quick and less resource hungry, but quality of thumbnails generated by Wand are significally better .

**Comment by kaedroho** [comment]
Simplest way to do this would be to uninstall Pillow, which would make Wagtail use Wand instead.

Please use the [support group](https://groups.google.com/forum/#!forum/wagtail). for future support questions.

**Comment by nordbit** [comment]
Really?
```
  File "/srv/wag/lib/python3.4/site-packages/wagtail/wagtailimages/fields.py", line 3, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

```
