### ISSUE TITLE
React in templates

### ISSUE THREAD

**Issue by voylinux** [torchbox/wagtail#2377]
Hi, new developer in Wagtail community:

For a web project I am going working on for my personal web, I want to create a Page model wich will (at least is my idea) render from the server side with React using something like [python-react](https://github.com/markfinger/python-react).

I think if this works well could take Wagtail templates to a next level for frontend developers as me.

I am using [Puput](https://github.com/APSL/puput) from the people in [APLS](https://github.com/apsl) and Wagtail as my code base.

@marctc commented you have already being moving to React like in #2275 amd I wonder if work in this a  project exclusive feature or if it would be interesting for wagtail community to work on this as new way to render templates or something.

**Comment by voylinux** [comment]
Maybe the whole thing is not ready to serve full pages yet (not sure) but I found some very interesting work about this in [https://github.com/jonashagstedt/django-jsx](https://github.com/jonashagstedt/django-jsx).

Wich are your thoughts about trying something of this for the idea?
How about wrapping template components in React components?

**Comment by robmoorman** [comment]
I think you should leave this choice up to the developers, you don't want to force people working with React templates.

The feature you mentioned is for the admin; where React (more) components will communicatie with the new admin API.

Maybe it's a good idea to split up your admin and frontend application with Django settings. In that way you can leave the admin as it is and for your frontend application you can set an alternative render engine like [python-react](https://github.com/markfinger/python-react#django-integration).

And what about the idea running your application with [Redux](https://github.com/reactjs/redux) and communicatie a REST API which represent your Wagtail pages. I've seen an implementation this way and it works very well!

**Comment by auvipy** [comment]
@robmoorman do you have any demo code to show the djano rest and redux based single page apps?

**Comment by robmoorman** [comment]
@auvipy not for public sharing, I can provide a stripped version of it or even better some boilerplate code, no problem! I'll send it over later this week.

**Comment by voylinux** [comment]
I like the aproach of a headless CMS, but maybe this is beyond the scope of wagtail. It would be two apps. Wagtail as an API and a node app as frontend.

**Comment by auvipy** [comment]
@robmoorman boilerplate demo would be great too.

**Comment by gasman** [comment]
Is there anything that needs to be changed/added within Wagtail in order to accomplish this? If not, I suggest we close this ticket and move the general discussion to the Wagtail google group.

**Comment by voylinux** [comment]
@gasman Probably you are right.
