### ISSUE TITLE
The construct_explorer_page_queryset hook is not invoked when building the Explorer menu

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#2384]
Maybe I'm just missing something, but it seems like the `construct_explorer_page_queryset` hook has a critical limitation that hamstrings it into near uselessness: it doesn't change the contents of the Explorer fly-out menu in the sidebar. Clicking that Explorer link still shows the entire page tree to the user, including Pages denied to the user by `construct_explorer_page_queryset`. And since users aren't prevented from navigating to pages hidden by that hook, that makes the sidebar menu a "back door" into parts of the Page Explorer they shouldn't be allowed into.

I've managed to get around this for my own site by replicating the code invoked through the `wagtailadmin_explorer_nav` view, and changing the menu to call my custom view. It uses a modified version of `wagtailcore.models.get_navigation_menu_items()`, which prevents non-superusers from seeing anything in the fly-out menu besides the descendants of the active Site's root_page. Here's the relevant snippet:

```
def get_navigation_menu_items(request):
    # Get all pages that appear in the navigation menu: ones which have children,
    # or are at the top-level (this rule required so that an empty site out-of-the-box has a working menu)
    pages = Page.objects.filter(Q(depth=2) | Q(numchild__gt=0)).order_by('path')

    if not request.user.is_superuser:
        # Display only the pages which are within the direct family line of the active Site's root page.
        pages = (
            Page.objects.descendant_of(request.site.root_page)
            | Page.objects.ancestor_of(request.site.root_page, inclusive=True)
        ).filter(numchild__gt=0).order_by('path')
```

Obviously this isn't appropriate for every site, but I think a hook much like `construct_explorer_page_queryset` needs to be provided that allows site creators to do something similar. Perhaps `construct_explorer_menu_queryset`? This menu is identical on every page, so it needn't be as complex at the existing hook. Though the docs will have to carefully inform users of the correct way to form an alternate queryset. The rest of  `get_navigation_menu_items()` makes pretty strict assumptions about what must appear in the `pages` queryset. For instance, it appears that the queryset must include an unbroken line of ancestors all the way up to the Root page (Page.id=1), or it'll crash.

I think that a suggestion that @tomdyson made to me last week during our talk about multi-tenancy may be an even better solution than a hook, though: adding a "View" permission to the permissions settable on Pages. That should obviate the need for a hook, *and* plug the additional loophole of being able to see a page that's not navigable just by typing its Explorer URL into the address bar. But hashing that out is something for another issue.

**Comment by fozcode** [comment]
I found that the hook did affect the Explorer menu when viewing/editing a page, but not when the user is at the admin home page.  This made it useless for me too so I ended up removing the Explorer menu completely.

**Comment by gasman** [comment]
@fozcode This hook shouldn't be affecting the explorer menu under any circumstances - if it does, that would be a very weird bug. If you're able to investigate further and provide steps for reproducing the problem, that would be much appreciated!

@coredumperror As you mention, I think it would be particularly fiddly to support customising the explorer menu queryset (either through `construct_explorer_page_queryset`, or a new equivalent hook) given the more complex construction of that query. I think the proposed view/choose permission (along with the second tweak I proposed in https://github.com/torchbox/wagtail/issues/359#issuecomment-47642464) would be the way to go here - hopefully I'll have chance to jot down some thoughts about the workings of this in the next week or so.

**Comment by fozcode** [comment]
@gasman Apologies - I just re-tested what I thought I'd tried previously, and you are correct there is no link between the output from this hook and the content of the Explorer menu. Whatever I saw must have been something unrelated.

**Comment by gasman** [comment]
Closing this now, as it sounds like we're pretty much settled on the permission model as discussed in #2401 as the solution to this.
