### ISSUE TITLE
Why is Filter a model in wagtailimages ?

### ISSUE THREAD

**Issue by Gagaro** [torchbox/wagtail#2387]
Hello,

I posted this in the dev group but no there seems to be no one reading this (https://groups.google.com/forum/#!topic/wagtail-developers/cSRtU-xN4ZE).

The Filter class being a model seems to be useless. It really only add a request to the database each time an image is rendered.

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/models.py#L441

This could easily be changed to a CharField including the spec.

Filter should take its spec in the init and set self.spec there. Then each Filter.objects.get_or_create(spec=spec) or Filter.objects.get(spec=spec) should be replaced by Filter(spec). No more request, and still the same behaviour.

Unless I am missing something. Am I?

I'm willing to do the PR if this is correct.

Thanks.

**Comment by gasman** [comment]
Hi @Gagaro - sorry for the lack of response on the mailing list. It hasn't been forgotten - I've just been too busy to reply this week (and I think I'm the only person in a position to respond, as the person who made the original design decision to make Filter a model).

I'll close this ticket, as the mailing list is really the best place for this discussion.

**Comment by Gagaro** [comment]
Thanks for the answer, I was afraid no one was actually reading it. I'll stay patient while waiting your answer then :smiley:.
