### ISSUE TITLE
KeyError in admin when editing group permissions

### ISSUE THREAD

**Issue by jtebert** [torchbox/wagtail#2389]
There seems to be a bug in the admin when editing permissions for groups (Wagtail 1.4.1).

To reproduce the error:

- Go to Admin -> Settings -> Groups -> Add a Group
- Select "Add a page permission"
- There is a delete button, but clicking it does nothing (problem 1)
- If you do not select a page with "Choose a Page", and proceed to "Save", there is a Python KeyError, for 'page' because there was no page selected (problem 2)

**Comment by gasman** [comment]
Problem 2 confirmed on Wagtail 1.4.3. The delete button is working fine for me though...
