### ISSUE TITLE
staticfiles vs static

### ISSUE THREAD

**Issue by dilrajsachdev** [torchbox/wagtail#2390]
In most of the wagtail templates, ` {% load static %}` used, which is fine till now. 
But now I switch using S3 storages with custom URLs, with this it is producing full URLs

If I use `{% load staticfiles %}` then I can get full custom S3 URLs.

Any suggestions to work it out ?

Thanks

**Comment by robmoorman** [comment]
Are you using [django-s3-storage](https://github.com/etianen/django-s3-storage)?

If so, check out the `AWS_S3_PUBLIC_URL_STATIC` and `AWS_S3_BUCKET_NAME_STATIC` settings.

Off-topic: put CloudFront in front of the S3 buckets ;)

**Comment by gasman** [comment]
We switched from `{% load static %}` to `{% load staticfiles %}` in Wagtail 1.4 - see https://github.com/torchbox/wagtail/pull/2192.

**Comment by dilrajsachdev** [comment]
I am using django-storages and also using CloudFront
Thanks for the update
