### ISSUE TITLE
Userbar use of rem conflicts with implementation styles

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#2393]
![screen shot 2016-03-23 at 10 26 07](https://cloud.githubusercontent.com/assets/352835/13982382/b3ee1926-f0e1-11e5-8975-57d3cd694350.png)

The Userbar font size is fixed at 14px, but the padding is set in rem, which in the case of the site in the screenshot above, is 16px, resulting in the odd padding above.

I think this is one case where em (or at least px) are preferable.

**Comment by alexgleason** [comment]
THANK YOU I've been wondering about that inconsistency! Makes perfect sense.

I've recently started using rems and it's pretty interesting how powerful they are, yet you *want* to use them interchangeably with pixels. Sometimes you have the intention of increasing the size of things when the text size increases, but sometimes you want things to remain static.

It's really interesting and a fun challenge to design sites in such a way that they can look right at any font size. And you also want to make sure you do what the user expects. For instance, if someone is visually impaired, maybe it makes sense to enlarge a logo with text in it when they increase the font size. Etc.

**Comment by JoshBarr** [comment]
Yep, will change to `em`s to inherit all sizing from the font-size.
