### ISSUE TITLE
Preview window automatically closes when the pages has validation errors

### ISSUE THREAD

**Issue by jaroel** [torchbox/wagtail#2395]
The preview button should run validation first, before trying to open the preview window

**Comment by gasman** [comment]
I don't think this is possible - the window has to open immediately on user input, or else it will be blocked by popup blockers. At least some of the validation needs to happen on the server side (for example, checking the slug for uniqueness), so it's not possible to validate and then open the window during the execution of the event handler.

There's discussion on other issues about whether the popup window is the best way to do previews, so at some point we may drop this mechanism completely.
