### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'parent_page' when adding or modifying page

### ISSUE THREAD

**Issue by ironhouzi** [torchbox/wagtail#2398]
Upgraded to 1.4.1 and ran locally. When adding a page or modifying (save draft, or publish) an existing page, I always get the above mentioned error.

Details:
https://gist.github.com/ironhouzi/82b1cb85152350f9982d

Not sure what else I can provide, so please let me know if any pertinent information is missing.

**Comment by gasman** [comment]
Have you used the `edit_handler` property on the page model to customise the tabbed interface? If so, please see #2267 (in particular, the workaround detailed in https://github.com/torchbox/wagtail/issues/2267#issuecomment-198375724).

**Comment by ironhouzi** [comment]
Thank you for the swift reply and pardon me for not reading that issue thoroughly enough.

I will wait for 1.4.2 instead of applying the workaround. Any idea when 1.4.2 will be released?
