### ISSUE TITLE
Error when using TabbedInterface with "edit_handler"

### ISSUE THREAD

**Issue by dszmaj** [torchbox/wagtail#2400]
Could I do something to solve this for know?

> Environment:
> 
> 
> Request Method: POST
> Request URL: http://127.0.0.1:8000/pl/admin/pages/3/edit/
> 
> Django Version: 1.9.4
> Python Version: 3.5.0
> Installed Applications:
> ['home',
>  'search',
>  'wagtail.wagtailforms',
>  'wagtail.wagtailredirects',
>  'wagtail.wagtailembeds',
>  'wagtail.wagtailsites',
>  'wagtail.wagtailusers',
>  'wagtail.wagtailsnippets',
>  'wagtail.wagtaildocs',
>  'wagtail.wagtailimages',
>  'wagtail.wagtailsearch',
>  'wagtail.wagtailadmin',
>  'wagtail.wagtailcore',
>  'modelcluster',
>  'taggit',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles']
> Installed Middleware:
> ['django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'wagtail.wagtailcore.middleware.SiteMiddleware',
>  'wagtail.wagtailredirects.middleware.RedirectMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
>   149.                     response = self.process_exception_by_middleware(e, request)
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
>   147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/django/views/decorators/cache.py" in _cache_controlled
>   43.             response = viewfunc(request, *args, **kw)
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py" in decorated_view
>   22.             return view_func(request, *args, **kwargs)
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailadmin/views/pages.py" in edit
>   273.                           parent_page=parent)
> 
> File "/home/dominik/.virtualenvs/wagtail/lib/python3.5/site-packages/modelcluster/forms.py" in __init__
>   208.         super(ClusterForm, self).__init__(data, files, instance=instance, prefix=prefix, **kwargs)
> 
> Exception Type: TypeError at /pl/admin/pages/3/edit/
> Exception Value: __init__() got an unexpected keyword argument 'parent_page'
>

**Comment by gasman** [comment]
Hi @dszmaj - please see #2267, particularly the workaround detailed in https://github.com/torchbox/wagtail/issues/2267#issuecomment-198377909.
