### ISSUE TITLE
Unnecessary padding for messages

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2408]
Currently in `master` we have unnecessary padding for messages. I can't reproduce this bug on `stable/1.4.x` branch and on `v1.4.1` tag.

![screen shot 2016-03-28 at 14 34 59](https://cloud.githubusercontent.com/assets/509198/14077706/1d855908-f4f7-11e5-8d8d-11e38b6a94f9.png)

**Comment by gasman** [comment]
Fixed in #2442
