### ISSUE TITLE
Duplicate existing page / copy existing page's contents into new page

### ISSUE THREAD

**Issue by BrendanBerkley** [torchbox/wagtail#2431]
I'm not the most technical Wagtail dev you'll ever meet, so I apologize if this has been addressed already.

I'm interesting in using the Wagtail forms, and I can see a use case where a user will want to create a pretty involved form and then will want to create a similar form later and just change a couple of fields.

Is there a mechanism in place to do something like this? I'm envisioning a "Duplicate" or "Copy" button in line with "Add Child Page".

If such a thing doesn't exist, would it be relatively simple to roll my own version of something like that?

**Comment by tomdyson** [comment]
Hi Brendan - are you aware of the 'copy' feature? It's available in the page listing, when you hover over a page:

<img width="546" alt="screenshot 2016-04-01 19 59 24" src="https://cloud.githubusercontent.com/assets/15543/14217147/494ea102-f844-11e5-9ee9-5765b5cab1bf.png">

**Comment by BrendanBerkley** [comment]
:facepalm: 

Thanks for taking the time to answer this.

**Comment by Wrufesh** [comment]
How can I do the same thing programmatically. I want to do so because I have a django model Foreignkey field and want to change it in a new copy.

**Comment by gasman** [comment]
Hi @Wrufesh - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
