### ISSUE TITLE
Create a custom FieldBlock for programming code.

### ISSUE THREAD

**Issue by rockink** [torchbox/wagtail#2432]
So, I wanted to create a custom code. I couldn't do so. I cam up with this, but I couldn't make it work.

`class CodeBlock(FieldBlock):
    def __init__(self, required=True, help_text=None, **kwargs):
        self.field = forms.Textarea(required=required, help_text=help_text)
        super(CodeBlock, self).__init__(**kwargs)
`

So, my plan was to modify the text that I received from CodeBlock, and modify it before saving it. How do I do that? 

I intent to use it for StreamField like this:

    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
        ('code',blocks.CodeBlock())
    ])

**Comment by gasman** [comment]
Hi @rockink - please use the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
