### ISSUE TITLE
Migrations fail on clean database

### ISSUE THREAD

**Issue by colinfrankb** [torchbox/wagtail#2440]
Hey there,

Just upgraded to Wagtail 1.4.2

I get the following error when I run all the migrations on a clean database

```
self = <django.db.backends.utils.CursorWrapper object at 0x10e9b7be0>
sql = 'INSERT INTO "wagtailcore_page" ("path", "depth", "numchild", "title", "slug", "live", "has_unpublished_changes", "url... VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "wagtailcore_page"."id"'
params = ('0001', 1, 1, 'Root', 'root', True, ...)

    def execute(self, sql, params=None):
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)
E               django.db.utils.IntegrityError: duplicate key value violates unique constraint "wagtailcore_page_path_key"
E               DETAIL:  Key (path)=(0001) already exists.

venv/lib/python3.4/site-packages/django/db/backends/utils.py:64: IntegrityError
```

this seems to be the migration that causing the problem

`venv/lib/python3.4/site-packages/wagtail/wagtailcore/migrations/0001_squashed_0016_change_page_url_path_to_text_field.py:33: in initial_data`

**Comment by colinfrankb** [comment]
Hey there, I found that this error only occurs when you have multiple database connections setup.

If that is not relevant, I will close the issue

**Comment by gasman** [comment]
Hi @colinfrankb - if this only occurs with multiple databases, it sounds like this is effectively a duplicate of #2234. Does that sound right?

(We'd like to support multiple databases cleanly, but that tends towards more of an enhancement than a bugfix...)

**Comment by colinfrankb** [comment]
Hey @gasman 

Yes that sounds exactly like the problem.

Closing this issue
