### ISSUE TITLE
Can't upload images with 1.4

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#2446]
Since upgrading to 1.4 I can't upload images anymore.

I keep seeing this in the console:

```bash
Forbidden (CSRF token missing or incorrect.): /admin/images/multiple/add/
[05/Apr/2016 11:17:46] "POST /admin/images/multiple/add/ HTTP/1.1" 403 2274
```

**Comment by gasman** [comment]
Hi @lee-kagiso - this is working fine for me on a new install of wagtaildemo using Wagtail 1.4.3. Please can you try clearing your browser cache / cookies, and ensure that `'django.middleware.csrf.CsrfViewMiddleware'` is included in `MIDDLEWARE_CLASSES` in your settings file?

**Comment by lee-kagiso** [comment]
I have tried Firefox Private Browsing and another browser, and got a colleague to confirm on their machine.

Here is our middleware.

```python
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'wagtail.wagtailcore.middleware.SiteMiddleware',
    'wagtail.wagtailredirects.middleware.RedirectMiddleware',
)
```

**Comment by gasman** [comment]
Please can you try bringing up a new Wagtail 1.4.3 instance (either [wagtaildemo](https://github.com/torchbox/wagtaildemo) or just a fresh `wagtail start` installation) and see if the problem occurs there? That'll help us establish whether this is a browser issue, or something specific to your project.

**Comment by Proper-Job** [comment]
@lee-kagiso Have you restarted gunicorn or mod_wsgi or runserver or whatever you're using?

**Comment by lee-kagiso** [comment]
A colleague confirmed that they had no problem on a new project.
Yes I restarted the django webserver.

**Comment by Proper-Job** [comment]
@lee-kagiso Did you perhaps put a StreamField into a FieldPanel instead of a StreamFieldPanel?  I remember having something odd like that happening to me once and I'd made a mistake like that.  I don't it was the same error, though.

**Comment by lee-kagiso** [comment]
No I just checked, and we are only using StreamFieldPanels

**Comment by gasman** [comment]
Closing as unable to reproduce - evidently this is being caused by some kind of configuration / customisation specific to this project. Please reopen if you're able to reproduce this on a new Wagtail project.

**Comment by Proper-Job** [comment]
@lee-kagiso If you're on python 3 you might try to delete the __pycache__.  I did have problems uploading images once, and I don't remember what I did to make it go away.  That only happened on the development server, though.

**Comment by lee-kagiso** [comment]
Thanks, I just tried your tip to delete the pycache, still no luck...

**Comment by lee-kagiso** [comment]
Django Debug Toolbar profiling middelware was breaking things... 

https://django-debug-toolbar.readthedocs.org/en/1.4/tips.html#middleware-isn-t-working-correctly

**Comment by Proper-Job** [comment]
Good catch.
