### ISSUE TITLE
Asset creation workflow

### ISSUE THREAD

**Issue by sixpearls** [torchbox/wagtail#245]
I've been thinking about this, and I think there's something worth discussion. As I see it, there are 4 types of wagtail related models:

1. Page subclasses, which are any distinct website page (it has a URL).
2. Snippet-registered models, which are _attached_ to a page
3. And helper models (eg, M2M through models) which don't have their own admin area--they show up as inlines or not at all
4. Assets, which are used within fields on a page (currently ships with Images, Documents, Embeds. Redirects seem similar, but perhaps another category)

So far, #s 1-3 are beautiful and joyous to work with as both a developer and user. In contrast, support for creating new assets is completely absent. The only asset I know I would want to add is a gallery (collection of images, with over-writable/selectable embed templates). I could copy and paste a bunch of the ``wagtailimage`` and ``wagtaildocs`` code, but I think it would behoove the project to simplify the process for developers. The shipped assets should be re-factored to take advantage of the new developer tools. This was already started in the move to allow hallo plugins (1ecc215759142e6cafdacb185bbfd3f8e9cd3185), and I think the project should keep moving in that direction.

**Comment by davecranwell** [comment]
Is there any way we can move this ticket on or is it just a case of closing it in favour of #634?

**Comment by gasman** [comment]
#634 doesn't really supersede this ticket - it's just a spinoff from the comment about embed choosers, which (if I'm not mistaken) was only tangentially related to @sixpearls's original suggestion.

StreamField (#823) will address the issue of including references to arbitrary models within richtext/mixed content, without the need to jump through whitelisting/expansion hoops - we'd do that by making the snippet chooser one of our fundamental block types. At that point, I *think* the only thing remaining on this ticket would be the question of whether snippet models are "first-class" enough, or whether we ought to do more to support custom model types that live at the top-level menu.

While I won't promise that StreamField will be the magic bullet that solves everything, I think it'll make it much clearer to see what further work needs to be done here - so in the interests of un-clogging the backlog of tickets, I'll close this one with the intention of possibly opening new ones post-StreamField.

**Comment by sixpearls** [comment]
This issue is actually essentially proposing the same thing as #891 (with the sample refactoring of #890) and is closely related to #634, #858.

The basic idea was to make it clear how to take an arbitrary model "asset", and (1) add CRUD pages to the admin and (2) add a good chooser interface for every type of field it might be useful (ForeignKeys and ManyToMany relationships, the richtextfield interface, and now the StreamField interface). Bonus points if the current Image, Document, and Embed assets were re-factored to use the new workflow.

So between the above identified issues, every aspect is being covered. I guess at this point the only value this issue has is in pointing out how the new features are related. Since that's done, by all means keep this one closed!
