### ISSUE TITLE
Image tags widget

### ISSUE THREAD

**Issue by davejacobs** [torchbox/wagtail#2450]
I know that M2M relationships and choosers are a work in progress, but is there any way of currently re-using the image tags widget for my pages?

<img width="452" alt="screen shot 2016-04-05 at 11 47 09 am" src="https://cloud.githubusercontent.com/assets/10695/14294160/7fcb761e-fb24-11e5-91f3-b97c560296e6.png">

**Comment by gasman** [comment]
Hi @davejacobs - please use the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by davejacobs** [comment]
Ah okay cool, thanks.
