### ISSUE TITLE
Resized PNG image files not retaining transparency

### ISSUE THREAD

**Issue by Matt-Deacalion** [torchbox/wagtail#2464]
I have the following image uploaded within a `wagtailimages.Image` instance:
![mu-foundation](https://cloud.githubusercontent.com/assets/1128480/14396269/8a37239e-fdce-11e5-9106-3db671f4c057.png)

When I use this template code:
`{% image organisation.logo width-250 %}`

The following image is generated:
![mu-foundation width-250](https://cloud.githubusercontent.com/assets/1128480/14396291/a50f716c-fdce-11e5-9c88-c53333e9ecdf.png)

I'm unable to make it retain the transparent pixels.

Edit: I'm running version **1.4.3**

**Comment by chimeno** [comment]
What version of Willow do you use? 
There was a bug with Willow 0.2, try updating if it's the case.

**Comment by SalahAdDin** [comment]
@chimeno The last wagtail version update the Willow package.

**Comment by Matt-Deacalion** [comment]
@chimeno I'm using `0.3`, I tried `0.2.2` that version doesn't seem compatible with the latest version of Wagtail.

**Comment by kaedroho** [comment]
Fixed by https://github.com/torchbox/Willow/issues/38. This fix will be released in Willow 0.3.1 and 0.4.x
