### ISSUE TITLE
Provide page in the context of StreamField blocks

### ISSUE THREAD

**Issue by timorieber** [torchbox/wagtail#2469]
I came across the limitation that the page is missing in the context of related StreamField blocks when rendering the blocks template several times. A typical use case is when you need to implement an intro block, where the page title and author should be displayed.

So far I was not able to solve this as a complete StreamField block. My implementation is a StreamField block anyway, but not using the blocks rendering mechanism. Instead I check for this block type and call a template with `{% include %}` and the necessary data as parameters.

The hurdle occurs in the majority of cases when you need to display data from builtin fields of Wagtails `Page` model. Otherwise you would be able to design it like it should be.

This issue is opened in addition to #1743 to clearly separate the discussion between the different requirements to have `request` and `page` available in the template context. I fully agree with https://github.com/torchbox/wagtail/issues/1743#issuecomment-144029475, though.

**Comment by BertrandBordage** [comment]
I agree, and the parent block (if any) would also be extremely useful in a lot of cases.

**Comment by gsstver** [comment]
I solved this case in one project. It's very useful.

**Comment by gasman** [comment]
See updates on https://github.com/torchbox/wagtail/issues/1743#issuecomment-224543332 for a suggested way forward here, which should (hopefully...) be intuitive and consistent with Django's `{% include %}` tag. In the proposed solution, the entire template context is (by default) passed to the block template, so this will cater for both `page` and `request`.

**Comment by mgd020** [comment]
Workaround: https://gist.github.com/mgd020/d841f8016024707b11b490b82ec648f0

**Comment by m1kola** [comment]
This issue and issue #1743 were partially solved in #2786. But the feature still needs some work (see #2823 and #2824).

**Comment by gasman** [comment]
Closing this now, as the specific issue described here is fixed by #2786 (even if there is further work to do on the feature as a whole).
