### ISSUE TITLE
Wagtail 1.4.x breaks image conversion

### ISSUE THREAD

**Issue by miscellainiac** [torchbox/wagtail#2472]
Hi, I've been diving into the source code for wagtail trying to figure out why code we had written to create circle-cropped image renditions no longer works in wagtail 1.4.x when it worked fine in 1.3.x and earlier. There is definitely some re-work on our part that needs to be done, but I think I've got a good handle on most of that now.

The piece that is missing can be found here: https://github.com/torchbox/wagtail/blob/stable/1.3.x/wagtail/wagtailimages/models.py
vs.
https://github.com/torchbox/wagtail/blob/stable/1.4.x/wagtail/wagtailimages/models.py

Around line 388; in the run of the Filter, in wagtail 1.3.x the output format of the image rendition was determined AFTER all the operations on it had been performed, which allowed us to apply an alpha layer and save any image as a PNG, simply by changing the `original_format`.

In wagtail 1.4.x however, the original image format is stored BEFORE any operations are performed and then used to save the image. So it doesn't matter what our custom operations tell wagtail the file should be saved as, any image rendition will always be saved as in the same format as the original image.

**Comment by kaedroho** [comment]
Hi @miscellainiac Before 1.4 the internal image operations/willow APIs were considered "unstable", so I wouldn't consider this a bug (but as of Wagtail 1.4 and Willow 0.3 they are stable and will no longer be changed without our standard deprecation process).

The fact that the ``original_format`` could be used to change the output format was just a side-effect of how the code was implemented. But I'd like to implement an official way of doing this by adding a ``get_properties`` method to image operations (see https://github.com/torchbox/wagtail/pull/1847#issuecomment-157857150).
