### ISSUE TITLE
Modeladmin needs fixing for non-superusers

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2477]
flake8 currently failing on https://github.com/torchbox/wagtail/blob/master/wagtail/contrib/modeladmin/helpers.py#L182 due to the missing import of UserPagePermissionsProxy, which suggests that that particular code path needs fixing / testing...

**Comment by coredumperror** [comment]
Yup, I'm seeing that too with my latest PR commits in #2463.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kaedroho** [comment]
Fixed by #2479. It was tested by the way, it must've been a bad rebase. sorry about that.
