### ISSUE TITLE
Animated Gifs not really supported?

### ISSUE THREAD

**Issue by frankwiles** [torchbox/wagtail#2505]
The [docs mention](http://docs.wagtail.io/en/v1.4.3/advanced_topics/images/animated_gifs.html) that after installing Wand, Wagtail will support animated GIFs. This does not seem to be the case any longer.

After installing `Wand==0.4.2` with `wagtail==1.4.3` and restarting no behavior changes.  Animated GIFs are still converted to PNGs.

I took the liberty of digging into the codebase and find no mention of Wand except in the docs and a referenced to another seemingly removed setting `WAGTAILIMAGES_BACKENDS`

**Comment by frankwiles** [comment]
Ok so turns out this is a problem with library versions and not a bug in Wagtial, Willow, or even Wang.  The system(s) in question was lacking the right imagemagick libraries!!!! Grrrr

**Comment by kurtw** [comment]
@frankwiles I would love some context into what you ran into. I ran into the exact same things you did. When you say systems in question, do you mean Wand?

**Comment by ghostwords** [comment]
You need to explicitly install ImageMagick. This is noted in [Wand's installation instructions](http://docs.wand-py.org/en/0.4.2/guide/install.html), but not [Wagtail's](http://docs.wagtail.io/en/v1.4.3/advanced_topics/images/animated_gifs.html).

**Comment by frankwiles** [comment]
Actually it turned out I had ImageMagick installed on my laptop, just not a new enough version.  So when I saw the same behavior local as I did on the server in question, I assumed (incorrectly) it was a problem with Wagtail or maybe Wand.  Upgrading and/or installing ImageMagick and libmagic did hte trick as @ghostwords mentioned.
