### ISSUE TITLE
Broken styles for some buttons on dashboard

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2512]
**Steps to reproduce:**
1. Open any page and make some changes
2. Submit the page for moderation
3. Go to the dashboard
3. Put cursor on a title of the page in "pages awaiting moderation" section

**Result:**
<img width="315" alt="screen shot 2016-04-25 at 17 55 23" src="https://cloud.githubusercontent.com/assets/509198/14788143/52dfe77a-0b0f-11e6-8971-58940f200614.png">

**Expected result:**
<img width="294" alt="screen shot 2016-04-25 at 18 03 28" src="https://cloud.githubusercontent.com/assets/509198/14788314/ff750402-0b0f-11e6-8c6a-00ad1d45f3f2.png">

**Comment by gasman** [comment]
Bug introduced in ba4983ca2118e9e9e15df8ef738682a975e5c625. Looks like it's happening because the `.button-secondary` class (which sets the text to blue) is now lower precedence than `input[type=button]` (which sets text to white). @JoshBarr, please could you take a look?

**Comment by JoshBarr** [comment]
The solution is to refactor Wagtail's view code to expect an explicit `button` class on buttons, and remove the styling hooks from the attribute selectors, eg `input[type=button], input[type=submit]`.

**Comment by gasman** [comment]
Fixed in #2524
