### ISSUE TITLE
enableDirtyFormCheck function doesn't take into account keyboard shortcuts

### ISSUE THREAD

**Issue by ptink** [torchbox/wagtail#2516]
The function in wagtailadmin/core.js that raises a warning if the user attempts to navigate away from the page without saving does not understand that if the keyboard shortcut is used to (e.g.) save draft, the $trigger for the event is the currently focused element, and not the actual submit button. This means that if a user edits the page and then uses ctrl+s to save, a warning pops up saying "Are you sure you want to leave the page?" Which is confusing and defeats the purpose of a shortcut .

**Comment by tomdyson** [comment]
Thanks for the report, @ptink. Is this something you could help with?

**Comment by gasman** [comment]
Fixed in #2526
