### ISSUE TITLE
gulp-sass dependency management is too brittle

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2522]
Related: #2518. While it's a good thing that we were able to track down and fix an issue with our SASS, it did mean that we were blocked for most of a day in setting up a new developer with a Wagtail installation, and I'd like to be sure that we aren't bitten by this again in future. Now that I've dug into the details, it seems that the sequence of events was:

* The SASS project decided that version 3.3.0 was a good time to change the variable scoping rules of the language. (To be fair, they did document it under a heading labelled ["Backwards Incompatibilities – Must Read!"](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#backwards_incompatibilities__must_read_2)...)
* libsass implemented the corresponding change ("Variables in control flow should not be accessible in outer scopes") in [version 3.3.3](https://github.com/sass/libsass/releases/tag/3.3.3), which, despite supposedly being a patch release, is apparently ["massive"](https://github.com/sass/node-sass/releases/tag/v3.5.1) and "the latest and most awesome LibSass release ever".
* node-sass released [version 3.5.1](https://github.com/sass/node-sass/releases/tag/v3.5.1) 6 days ago (previous was 3.4.2), followed by a flurry of follow-up releases, bringing it up to date with libsass 3.3.6.
* gulp-sass [depends](https://github.com/dlmanning/gulp-sass/blob/v2.3.1/package.json#L25) on `"node-sass": "^3.4.2"`, i.e. any 3.x.x release. In other words, it trusts node-sass to do semantic versioning correctly, which it doesn't.
* As a result, gulp-sass was quite happy to install a backwards-incompatible version of node-sass / libsass with no warning.

Since most Wagtail developers just want the SASS compilation to work and aren't bothered about having bleeding-edge versions, I think it makes sense to pin our NPM dependencies at exact versions. I gather [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) is the standard way of doing that, but by default it doesn't consider the `devDependencies` list, which is where gulp-sass is currently listed. Given that Wagtail end-users don't touch npm at all, I'm not clear on what the distinction between `devDependencies` and `dependencies` is here - would it make sense to move everything to `dependencies`? (ping @JoshBarr)

**Comment by JoshBarr** [comment]
`devDependencies` is definitely the right place for tooling that's not required at runtime. 

`npm shrinkwrap --dev` will correctly pin our dev dependencies. Agree we don't really need to use bleeding edge versions generally. Would have expected this to be a 4.X release with a major breaking change like that!

**Comment by gasman** [comment]
@JoshBarr Thanks - I tried `npm shrinkwrap --dev` here https://github.com/gasman/wagtail/tree/cleanup/npm-shrinkwrap, but was getting all kinds of issues with missing packages when bringing up a new Vagrant box, so I figured I was on the wrong track. Will persevere with that then :-)

**Comment by vincentaudebert** [comment]
@gasman I tried it too and I had some "extraneous" errors linked to packages I installed in previous branches.
I think the easiest is to nuke your `node_modules` folder, run `npm install` and then `npm shrinkwrap --dev`

**Comment by gasman** [comment]
We've hopefully got a working shrinkwrap config now, in 6b6866345e6413fd28cbf0a20a7a7ae5d575bc27. No idea what I did differently this time, other than catching npm at a moment when all the packages were collectively behaving themselves! We'll see if it still works in a week's time :-)
