### ISSUE TITLE
Much of the example code in the docs uses 2-space indentation, which is not PEP8.

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#2530]
This has bitten me several times when copy-pasting code from the docs into my projects, as we use 4-space indentation (as PEP8 requires).

Should this be fixed? I'd be happy to do the grunt work, but it'd require perhaps hundreds of changes to the documentation code. I wasn't sure it'd be a good idea to start such a large PR without first getting the go-ahead.

**Comment by gasman** [comment]
Have just had a quick scan through the docs, and could only see a small fraction that doesn't use 4-space indentation (most of it template / CSS code rather than Python). Definitely happy for those to be fixed, so a PR would be very welcome!

**Comment by coredumperror** [comment]
I guess I've happened run into an unusual concentration of 2-space Python code (I think a lot of the hook example code may be 2-space), which made me think more of the example code was problematic than it really is.

I'll get to work on that.

**Comment by gasman** [comment]
Fixed in #2532
