### ISSUE TITLE
Cannot Edit A Redirect When Set To Just A Forward Slash

### ISSUE THREAD

**Issue by AtomicSpark** [torchbox/wagtail#2533]
I attempted to redirect from the site root to an existing page. E.g. _example.com/_ to _example.com/blog/_. I assumed "Redirect from:" should be set to "/", as all other redirects start with a forward slash. The redirect is successfully added, however, the FROM column field is blank and you cannot click on the redirect to edit it. It also doesn't appear to be functional.

Taking a look at the [following code](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailredirects/models.py#L55-L68), one can see that it strips any extra white space and removes a trailing slash. If the string is set to only a forward slash, the string is now empty. This doesn't seem to explain why multiple slashes would be set to an empty string, but that's as far as I looked into this issue.

How do we prevent the user from creating a redirect with an empty `old_path`?

If supported, how do we properly redirect from the site root?

**Comment by gasman** [comment]
Hi @AtomicSpark,

Redirects only take effect on URLs that don't exist as pages (i.e. would return a 404 if the redirect wasn't there), so setting one on the root URL generally won't work. (Actually, it probably will work if you leave your site root page unpublished, but that's not a particularly obvious way of doing it...) We should probably add in a check to disallow an empty 'from' URL, yep.

A better way of achieving what you want to do is to set up a 'redirect' page type, as described here: http://www.coactivate.org/projects/ejucovy/blog/2014/05/10/wagtail-notes-managing-redirects-as-pages/
