### ISSUE TITLE
Setting `MESSAGE_TAGS` makes messages in Wagtail loose their styles

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#2551]
I've set `MESSAGE_TAGS` in my project to use the relevant CSS classes for my project, following a BEM naming scheme:

```python
MESSAGE_TAGS = {
    messages.DEBUG: 'messages__debug',
    messages.INFO: 'messages__info',
    messages.SUCCESS: 'messages__success',
    messages.WARNING: 'messages__warning',
    messages.ERROR: 'messages__error',
}
```

Unfortunately, Wagtail implicitly relies on this setting not being changed. If it is changed, the flash messages loose their colours.

Wagtail should either document that this setting is required to be set to its defaults, or it should work regardless of how this setting is set.

**Comment by SalahAdDin** [comment]
What is `MESSAGE_TAGS`? In the documentation there isn't information about it.

**Comment by timheap** [comment]
`MESSAGE_TAGS` is a Django setting. You can read more about it in the Django docs: https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-MESSAGE_TAGS
