### ISSUE TITLE
Get Wagtail version

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2557]
Currently the way is with

```python
from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION
```

But maybe a function like Django has is a more elegant way, as it doesn't depend on the version number existing in any particular file. I'm afraid someone could move that, and it isn't a documented feature.

Or am I over thinking it? I know the version is shown on hover for the logo in the admin screen, but I haven't checked to see how it's pulled out. Maybe documenting it and agreeing it should remain there would work, also.

**Comment by kapito** [comment]
It should be quite easy to make a command or alias along the lines of 'wagtail getversion' which outputs the response from `from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION`.

http://ubuntuforums.org/showthread.php?t=1554459 may be relevant here, however when trying to execute `from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION` I get "from: can't read /var/mail/wagtail.wagtailcore". Do you know what I'm doing wrong?

**Comment by alexgleason** [comment]
Hi @kapito, you're running the command I shared above inside of your terminal emulator. However, it's Python code and must be run in a Python environment.

Assuming you have [Python](https://www.python.org/downloads/) and [Wagtail](https://wagtail.io/developers/) installed on your local machine, you can run `python` inside of your terminal to enter the Python interpreter. You should see `>>>` before your cursor.

Then you can type:

```python
from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION
```

This will import the version number under the name `WAGTAIL_VERSON`, then you can type:

```python
print(WAGTAIL_VERSON)
```

to print the version number. Use ctrl+D to exit the Python interpreter.

**Comment by kapito** [comment]
Ah, my apologies! Thanks for clarifying. I agree that's quite a lengthy process. Unfortunately I'm not sure exactly how to implement it, but one option is to create a python file (or maybe it could go in setup.py?) which has the code you mentioned:

`from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION`
`print("Your current Wagtail version is " + WAGTAIL_VERSON)`

If I save this as getversion.py, I can use `python getversion.py` to run the script, or create an alias with `alias wagtail_version='cd ~/vagrant-wagtail-develop/wagtail/;python getversion.py'` (of course the path will be different for normal wagtail as opposed to vagrant-wagtail-develop). I can now run the script from any directory in the terminal with `wagtail_version`.

It's not perfect, but I feel it's better than the current method. :)

**Comment by alexgleason** [comment]
@kapito My concern is more of an organizational one. Wagtail contains multiple apps, such as `wagtailcore`, `wagtailadmin`, `wagtailembeds`, `wagtailforms`, etc... Currently we're getting the version number by checking inside of one file (`__init__.py`) inside of one of the apps (`wagtailcore`). But I question if that's the right way.

Django lets you do:

```python
import django
print(django.VERSION)
```

This seems a lot cleaner.

**Comment by gasman** [comment]
I don't really see any problems with the current `from wagtail.wagtailcore import __version__ as WAGTAIL_VERSION` approach, or what we'd practically gain from changing it. It may not be the most elegant thing in the world, but I wouldn't want to get bogged down in fixing things that aren't broken :-)

**Comment by vladox** [comment]
Is there a way to display the current version number in the web admin interface?

**Comment by gasman** [comment]
@vladox It's shown when hovering over the Wagtail logo.

**Comment by pmneve** [comment]
Not working currently.

**Comment by gasman** [comment]
@pmneve What isn't working? Retrieving the version number in code, or seeing it in the admin interface? The latter was changed a few versions ago, for accessibility reasons - it's now available under the Settings menu.

**Comment by pmneve** [comment]
Hover over logo not working. will look again in Settings.  Thanks!

**Comment by pmneve** [comment]
Ah!. There it is right at the bottom!  Too many windows open on my screens.  Thank you!
