### ISSUE TITLE
Support regular expressions (regex) in Settings... Redirects

### ISSUE THREAD

**Issue by dprothero** [torchbox/wagtail#2559]
It would be great if Redirects supported regular expressions (regex). For example, you could redirect something like:

`/error-codes/(.*)`
to:
`/docs/library/errors/$1`

So that something like `/error-codes/1234` would redirect to `/docs/library/errors/1234`

Interested in feedback on this feature. I may look at creating a PR for it.

**Comment by gasman** [comment]
Hi @dprothero,
It's not something I'd go for, to be honest... I'm keen to avoid the anti-pattern of making programmers click through an admin interface when they could do the job much better and more flexibly by writing actual code. If you can write a regexp, then you *are* a programmer, and you're far better off writing a urls.py rule (where you can commit it to version control, write tests for it, copy it between installations and so on).

**Comment by dprothero** [comment]
Completely valid reasoning, thanks.
