### ISSUE TITLE
'Preview' button on creating a page is missing button style

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2582]
Presumably missed in #2524:

<img width="449" alt="screen shot 2016-05-09 at 21 46 57" src="https://cloud.githubusercontent.com/assets/85097/15127704/ae802402-162f-11e6-8cbe-aa727e39598a.png">

I'm concerned there may be others that were missed - I think we'll need to systematically step through all templates to be sure.

**Comment by m1kola** [comment]
I can't reproduce issues with preview button on current master, but I found another issue with "Save" button for snippets. I'm working on fix.

`modeladmin`, probably have the same issues as snippets.

**Comment by m1kola** [comment]
#2611 should fix issues with preview button on page create view and with save buttion for snippets (create and edit view).

Now I'm going to check `modeladmin`.

**Comment by m1kola** [comment]
Sorry, I forgot to leave comment here. PR #2611 was updated: issue with buttons in `modeladmin` were fixed.

**Comment by gasman** [comment]
I'm pretty confident that #2622 has now caught all remaining unstyled buttons.
