### ISSUE TITLE
wagtailsearch post_delete_signal_handler does not delete from backend

### ISSUE THREAD

**Issue by riceyrice** [torchbox/wagtail#2594]
Hi there, we are finding that the `post_delete_signal_handler()` calls `get_indexed_instance()` which filters to objects that exist in the database (i.e. pk in those returned by `get_indexed_obects()`. As the deleted object no longer exists, the call to `backend.delete()` is never made, so deleted items remain in the index, which causes discrepancies between the count of search results and the actual search results.

Perhaps the check on `get_indexed_objects()` is redundant in this case, or the signal handler should instead be on the `pre_delete` signal?

Thanks,
Stephen

**Comment by kaedroho** [comment]
Thanks for spotting!

We should only need the id of the page in order to delete it from the index so I think we could reimplement this without needing get_indexed_instance.

**Comment by gasman** [comment]
Fixed in cd783ebc38f8a821e268d2b16e89d96e01fe7ad5 as part of #2407 - but since the fix is also dependent on a wider refactor that's too big to backport to 1.4.x, I'm moving this to the 1.5 milestone.
