### ISSUE TITLE
Internet Explorer shows Stay on Page / Leave Page dialog when saving/publishing

### ISSUE THREAD

**Issue by riceyrice** [torchbox/wagtail#2604]
The onbeforeunload event to prevent data loss in the event of navigating away does not seem to be ignoring correct navigation i.e. Save, Publish, etc.
Tested Wagtail 1.4.4 in IE11/Win8.1

**Comment by riceyrice** [comment]
On trying to get a more precise reason bug report I think I have fix in #2606.

**Comment by gasman** [comment]
Both the pre- and post-#2606 versions of the code seem to be suffering from this issue in Firefox 46 for me. Investigating...

**Comment by gasman** [comment]
`var $trigger = $(event.explicitOriginalTarget || document.activeElement);` seems to do the trick across IE, FF and Chrome. Will go with that...

**Comment by gasman** [comment]
Fixed in #2606
