### ISSUE TITLE
Page Chooser cannot navigate to child pages in Internet Explorer

### ISSUE THREAD

**Issue by riceyrice** [torchbox/wagtail#2608]
When choosing a page chooser e.g. a `PageChooserBlock` in a `StreamField`, using IE11/Win8.1, the list of pages at root appears OK, with an AJAX request to e.g.:
`/admin/choose-page/?page_type=wagtailcore.page`
Clicking a right-hand triangle to navigate to a child page shows the correct list of pages:
`/admin/choose-page/3/?page_type=wagtailcore.page`
However, as soon as this list appears the modal immediately submits an empty search:
`/admin/choose-page/search/?page_type=wagtailcore.page&q=&results_only=true`
There is no text in the search box, so the page list is replaced with "There are 0 results"
So pages can be found by searching but not by browsing.

**Comment by gasman** [comment]
Thanks for the report! Have created a fix for this in #2615 (which also makes the UX a bit nicer on other browsers, as it's now possible to get back to the browse view after searching).
