### ISSUE TITLE
Minor formatting problems when encapsulating RichTextField or InlinePanel inside a MultiFieldPanel

### ISSUE THREAD

**Issue by jeffrey-hearn** [torchbox/wagtail#261]
I came across this problem when trying to make RichTextField and InlinePanel both collapsible by placing them in a MultiFieldPanel. The hallo.js toolbar overflows the input field, which is now indented and part of a fieldset. The InlinePanel works fine, but lacks a heading.

Arguably, the InlinePanel subforms should also be indented like the rest of the fieldset, but I think that space is well used by the subforms. Perhaps they could be placed in a container element of some type, like a well or a pair of horizontal rules. This could also be solved by convention, by recommending that InlinePanels be given their own MultiFieldPanel (which can be given a heading).

```python
STUFF = [
	ImageChooserPanel('splash_image'),
	DocumentChooserPanel('free_download'),
	PageChooserPanel('related_page'),
	InlinePanel( UseAllTheFieldsPage, 'carousel_items', label="Carousel items" ),
]

MORESTUFF = [
	FieldPanel('title', classname="title full"),
	FieldPanel('body', classname=""),
]

UseAllTheFieldsPage.content_panels = [
	MultiFieldPanel(MORESTUFF, heading="General stuff", classname="collapsible collapsed"),
	MultiFieldPanel(STUFF, heading="Chooser Junk", classname="collapsible collapsed"),
]
```
![richtextfield](https://cloud.githubusercontent.com/assets/3364400/3073298/6cd2069a-e2e4-11e3-89c4-f87812f4919c.png)
![inline-panel](https://cloud.githubusercontent.com/assets/3364400/3073300/717da42e-e2e4-11e3-890e-92bd568a2b22.png)

**Comment by kaedroho** [comment]
This looks similar to: https://github.com/torchbox/wagtail/issues/100

Many tweaks have been made to the display of Inline panels since this ticket was created. Does this problem still exist?

**Comment by gasman** [comment]
Presumed fixed as per https://github.com/torchbox/wagtail/issues/261#issuecomment-55579694
