### ISSUE TITLE
update_index for Elasticsearch throwing an error

### ISSUE THREAD

**Issue by octobertech** [torchbox/wagtail#2628]
Just installed and playing with Wagtail on my windows pc - looks and works great though pages not working out of the box as on mezzanine.
When trying to connect Elasticsearch and doing update_index command in console it throwing an error:
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [title] has unsupported parameters: [index_analyzer : endengram_analyzer]')

I believe [title] here is page's title...

**Comment by kaedroho** [comment]
It looks like you're using Elasticsearch 2.x Wagtail currently only supports Elasticsearch 1.x.

Support for ES 2.x is coming soon though, see https://github.com/torchbox/wagtail/issues/1734 for progress.

**Comment by octobertech** [comment]
Oh yeah it was the latest 2.3 now installed the 1.7 and it seems to work well. Thank you!
