### ISSUE TITLE
Better widget for ManyToMany fields

### ISSUE THREAD

**Issue by melinath** [torchbox/wagtail#2635]
The current M2M widget is all right for a small number of items, but it would be nice to have an autosuggest field instead.

**Comment by gasman** [comment]
Covered by #231

**Comment by melinath** [comment]
I opened a separate ticket because that seemed like it dealt explicitly with many-to-many throughs and wasn't considering simple M2Ms. But seeing as you're the one who actually knows what's going on I will defer to your knowledge. :-)

**Comment by alexgleason** [comment]
Hi @melinath, we appreciate the feedback. :) It looks like @gasman is referring to [this comment](https://github.com/torchbox/wagtail/issues/231#issuecomment-82302069) where "a better UI widget" is mentioned. It would be valuable to make note of including a search feature, which I agree would be an improvement.

I'm guessing that isn't possible yet, though, until #231 is covered.

Thanks! Please let us know if you have any more ideas.

**Comment by dperetti** [comment]
[django-ajax-select](http://django-ajax-selects.readthedocs.org/en/latest/Install.html) is a beautiful implementation of an auto-suggest field.
I was able to make it work in Wagtail admin with a simple :
`        FieldPanel('people', widget=AutoCompleteSelectMultipleWidget('people')), `
... then I was bitten by issue #231...

**Comment by Clarity-89** [comment]
@dperetti do you have any sample app done with Wagtail and django-ajax-selects? I'm using it to select an m2m value but for some reason it doesn't get saved to the db.
