### ISSUE TITLE
Firefox bug

### ISSUE THREAD

**Issue by MagdaN** [torchbox/wagtail#2642]
I am using Firefox 46.0.1 on a Mac (El Capitan) and I get the following error: When I am logged in and see the wagtail admin page and I click on the Explorer Link, the Explorer tab just opens for a really short time, so that I am not able to click on anything in the tab, meaning I can't use the functionality at all.

Wagtail version is 1.3.1. 

Works fine in Chrome and Safari.

**Comment by gasman** [comment]
Hi @MagdaN - this was fixed in Wagtail 1.4.4: #2549, #2555.

**Comment by MagdaN** [comment]
@gasman: OK Thanks!
