### ISSUE TITLE
Hallo link editor attempts to edit document links as page links

### ISSUE THREAD

**Issue by riceyrice** [torchbox/wagtail#2654]
Testing 1.5rc1- link editor checks for presence of `data-id` attribute when deciding whether to edit an existing page link which means it picks up document links and passes the value of this attribute to the chooser where it is wrongly interpreted as a document ID. It should check that `data-linktype` is `'page'`.

**Comment by riceyrice** [comment]
Possible fix in #2661

**Comment by gasman** [comment]
Fixed in #2661
