### ISSUE TITLE
Table block doesn't save alignment data

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2655]
Here's an example of what table JSON data looks like (from a StreamField form submission):

```
body-10-value:{"data":[["hello","world","sup"],["hii","yoooo",null],[null,null,null]],"first_row_is_table_header":false,"first_col_is_header":false}
```

However, you can right-click any cell, and choose Alignment > Left / Right / Center, among some vertical options, too. This data also needs to be saved into the JSON so it can be templated.

It's probably too late for every cell to have its own "options" attribute, so I'm guessing alignment will need to be passed in as a map, like

```
"alignments": [{"cell": "0,1", "alignment": "left"}, {"cell": "2,2", "alignment": "center"}]
```

etc

**Comment by gasman** [comment]
I guess there's a question here, which ties in with the whole content vs presentation thing, about whether alignment is really part of the data model. It probably depends on the context: for a pure data table, such as one that gets rendered as a graph on the front-end, it doesn't belong there (and we should probably disable the alignment options entirely in that case); for a table displayed to the user, it might make sense to set alignments on a per-column or row basis. I can't think of a legitimate use for setting arbitrary alignment on a per-cell basis - I suspect that's heading too far into the domain of using tables for layout, which we want to avoid.

**Comment by AtomicSpark** [comment]
Although it is implemented in the handsontable code and currently non-functioning in Wagtail, HTML align attributes are depreciated in HTML5 and [should not be used](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#attr-align). I vote that we disable align features in handsontable if possible, before this turns into a Wagtail image debate on whether or not we inject surprise CSS into templates.

**Comment by alexgleason** [comment]
Very good points. I vote to disable alignment entirely.

**Comment by Proper-Job** [comment]
I'm working on https://github.com/torchbox/wagtail/issues/2687 anyway right now and I'll do a PR for this.

**Comment by Proper-Job** [comment]
https://github.com/torchbox/wagtail/pull/2701

**Comment by robslotboom** [comment]
I agree with this but why not replace the html alignement attributes by alignment classes.
