### ISSUE TITLE
Tags search doesn't work by default in 1.5

### ISSUE THREAD

**Issue by muhammad-saleh** [torchbox/wagtail#2658]
Dears,
I updated Wagtail to v1.5 and thought that the tag search should be working now
But unfortunately it didn't

What I did is:
- I added a new image (dog.jpg)
- Gave this image some tags (animal, jungle, nature)
- Tried to search for 'animal'

Result was 0 results

I don't have elasticsearch but I'm not really sure about the behavior if elasticsearch is installed or not but I expected this feature to work in both cases

I will try today with elastic search but it would be really great to have this working out of the box

**Comment by gasman** [comment]
Hi @muhammad-saleh - this is covered by #278.
