### ISSUE TITLE
Document link href attribute is 'undefined' and shown in tooltip in editor

### ISSUE THREAD

**Issue by riceyrice** [torchbox/wagtail#2660]
Document links are inserted with a href attribute of 'undefined'. This isn't really a problem as the data-id attribute contains the document identification, but it does mean the new tooltip functionality shows the word 'undefined' when hovering over document links.

Not sure what the href _should_ be, possibly the tooltip behaviour should change depending on data-linktype?

**Comment by riceyrice** [comment]
Actually this behaviour differs for newly inserted document links and already present document links loaded from the database, which do have a href set, so perhaps the required fix is to the code that inserts the link. The doclink button code looks for a url attribute on the object returned by the chooser but this is not present.

**Comment by m1kola** [comment]
Fixed in #2682

Thanks!
