### ISSUE TITLE
Richtext editor not working in site settings in 1.5

### ISSUE THREAD

**Issue by seb-b** [torchbox/wagtail#2664]
I have a site settings with a richtext field. The richtext editor doesn't seem to initialise. I can't save new values to the field either. No errors in the console. Downgrading to 1.4 fixes the problem

Model definition:
```
@register_setting(icon='site')
class SiteSettings(BaseSetting):
   footer_content = RichTextField()
   
  panels = [
    FieldPanel('footer_content'),
  ]
```

Screenshot of the admin interface with no richtext controls
![image](https://cloud.githubusercontent.com/assets/1635388/15729983/2b45be00-28ac-11e6-956a-d5fd0d2a78fe.png)

**Comment by m1kola** [comment]
Fixed in #2675
