### ISSUE TITLE
It's no longer possible to scroll down the Explorer menu

### ISSUE THREAD

**Issue by iaindillingham** [torchbox/wagtail#2678]
It's no longer possible to scroll down the Explorer menu. This is problematic when an item in the Explorer menu has more children than can fit on the screen. The additional children are inaccessible!

The original issue is described in #2520 and fixed in #2525 ([this commit][1]). However, the fix changes the ``position`` of ``.explorer`` from ``absolute`` to ``fixed``, which seems to be the problem.

A temporary solution is to add a new CSS file to the administration interface -- using the [``insert_global_admin_css``][2] hook -- that sets ``position: absolute;``.

[1]: https://github.com/torchbox/wagtail/pull/2525/commits/06590e2c092aac400b2b491ed9fcbd4ea60d49b8
[2]: http://docs.wagtail.io/en/v1.5/reference/hooks.html#insert-global-admin-css

**Comment by gasman** [comment]
Thanks for the report! I've now reverted the fix from #2525, because inability to access menu items is a more severe bug than the original cosmetic issue. Reverted in 64132728d151803cbf739ea78aeff3ffd87f8a0e (master) and 1814579a77ef5db72e4ab7da03365c33580ebfef (1.5.x).
