### ISSUE TITLE
After blog creation in tutorial, blog does not show up in Wagtail Admin

### ISSUE THREAD

**Issue by tmcothran** [torchbox/wagtail#2685]
I've followed the "Getting Started" section in the official documentation. However, when I get to the step where you create the blog, the blog does not show up in Wagtail's admin. Only the home application shows up. I registered the blog in the base settings, ran makemigrations and migrate. The only step I didn't follow exactly from the tutorial is that rather than naming the project "mysite" I called it "personal_page." I've gone over the steps a few times, and I don't *think* it's a mistake on my part.

**Comment by MechanisM** [comment]
Please, use wagtail support google group for such questions.

**Comment by tmcothran** [comment]
OK/
