### ISSUE TITLE
API v2 URL filtering

### ISSUE THREAD

**Issue by nwaxiomatic** [torchbox/wagtail#2696]
Hi I was wondering if the url path filtering was finished, or what its current status is.

I would like to make a generic frontend router that just searches for the relevant path and displays the page that way, but this is not possible currently.

**Comment by nwaxiomatic** [comment]
it seems you only need to add 'url_path' to PagesAPIEndpoint.extra_meta_fields to get this behavior.

**Comment by gasman** [comment]
Hi @nwaxiomatic,
If this is a bug report or feature request, please open a new issue describing the specific change you'd like to see. If it's a query, I'd suggest directing it to the [Wagtail Developers Google group](https://groups.google.com/forum/#!forum/wagtail-developers) (although the lead developer of the API is currently on holiday).
