### ISSUE TITLE
Preview redirects to login view for login_required Pages (even though user is logged in)

### ISSUE THREAD

**Issue by gkoller** [torchbox/wagtail#2698]
_Wagtail version: 1.5.2_

Pages that inherit from a class:

```python
class LoginRequiredPage(Page):
    class Meta:
        proxy = True

    @method_decorator(login_required)
    def serve(self, request, *args, **kwargs):
        return super(LoginRequiredPage, self).serve(request, *args, **kwargs)
```
can't be previewed. 

The problem stems from the dummy request creation in: `wagtail.wagtailadmin.views.pages.preview_on_edit`:

```python
response = page.serve_preview(page.dummy_request(), preview_mode)
```

That dummy request does not carry over the currently logged in user. As a result the dummy request is associated with an anonymous user. This forces the `login_required` decorator on LoginRequiredPage.serve to be triggered resulting in a redirect to the login view. 

I'm not sure how to fix this. Maybe a solution would be to pass in the user object to the call `dummy_request` and somehow associated it with the newly created `WSGIRequest`.

**Comment by gasman** [comment]
Hi @gkoller - this is being addressed by #2550.
