### ISSUE TITLE
Bug: Images Pagination doesn't keep GET parameters, e.g. current Collection

### ISSUE THREAD

**Issue by hamsterbacke23** [torchbox/wagtail#2700]
Wagtail Version 1.5.2

Steps to reproduce:
- Create some collections
- Have enough images to have a pagination
- Select collection on admin/images/
- Click on 'next page' 

Result: Collection selectfield and displayed images default back to 'all collections'
Should be: collection selectfield is the same as before, images are filtered correctly on the second and following pages as well

**Comment by bbusenius** [comment]
We've run into this as well. It's causing some problems for our editors since we have some image collections that are rather large.

**Comment by gasman** [comment]
Fixed in #2986
