### ISSUE TITLE
wrong static path for wagtail.contrib.modeladmin

### ISSUE THREAD

**Issue by ronniestevens** [torchbox/wagtail#2703]
I added wagtail.contrib.modeladmin to my base.py, and run 'manage.py collectstatic', but the static files are in 'static/wagtailmodeladmin/css', while the app searches these in 'static/modeladmin/css'. Creating the latter manually resolves the issue.
Wagtail 1.5.2.

**Comment by gasman** [comment]
Thanks for the report! Fixed in f143e3d63dd8b0ea80907764432e5b9eb2415829.
