### ISSUE TITLE
'Remove link' functionality in rich text editor not working

### ISSUE THREAD

**Issue by jimr** [torchbox/wagtail#2704]
**Expected behaviour**: clicking 'remove link' on a link in a `RichTextBlock` should remove the anchor and persist the change on save.
**Observed behaviour**: clicking 'remove link' removes the anchor but doesn't persist the change on save.

I'm not sure what's going on, but if you click inside the linked word, or select the linked word and click 'remove link' it appears to be removed immediately, but comes back on 'save draft'. If you select the linked text and delete it and click save, the text of the anchor tag is re-inserted into the rich text block on save.

I've set up a clean Wagtail 1.5.2 project (using `wagtail start`) and added a `StreamField` with a `RichTextBlock` to check this isn't something we've accidentally introduced in our project.

![unlink](https://cloud.githubusercontent.com/assets/212743/15966349/b379994e-2f1a-11e6-962a-a3924e72a2be.gif)

**Comment by loicteixeira** [comment]
It is probably the same issue as #2637, the remove link button does not flag the field as modified. I would bet that if you issue any other action (like a single keystroke) in the field, it will save properly.

The remove button will have to flag the field as modified the [same way the add button does](https://github.com/torchbox/wagtail/blob/90bd6bdf11ee06756c317ffeb5026f32a07adcde/wagtail/wagtailadmin/static_src/wagtailadmin/js/hallo-plugins/hallo-wagtaillink.js#L108).

**Comment by gasman** [comment]
Fix implemented in #2715.

**Comment by jimr** [comment]
Fix looks good, thanks @gasman . Should I open a separate issue about the link href appearing in the rich text body after deleting the linked text? Is that even considered a bug?

**Comment by gasman** [comment]
@jimr I'm not aware of that one - that sounds like a different bug to this one. Yep, please open a new issue with more details.

**Comment by jimr** [comment]
@gasman blink and you'd miss it, but that's what I'm showing at the end of the video on this issue. I'll open a separate issue anyway since it's unrelated.
