### ISSUE TITLE
Rich text editor list implementation broken by H1 buttons etc.

### ISSUE THREAD

**Issue by nimasmi** [torchbox/wagtail#2708]
Steps to reproduce:

1. Create a list in the rich text editor.
1. Highlight some text in the list, and use the H3 button.
1. Observe HTML is now:

```
<ol>
    <li>List item 1</li>
</ol>
<h3>
    <ol>
        <li>List item 2</li>
    </ol>
</h3>
<ol>
    <li>List item 3</li>
</ol>
<p>
</p>
```

Pressing more heading buttons can create even more messed up HTML: `<h3><p><h4><h2><ol><li>List item 2</li></ol></h2></h4></p></h3>`, anyone?

**Comment by gasman** [comment]
This is hallo.js's behaviour rather than ours, and there's not much we can do about it other than switch to an alternative editor (which probably will happen soonish - #2409)

**Comment by nimasmi** [comment]
I suspected as much. I'd already said to the person who reported it "This is wagtail's behaviour rather than mine". Thanks anyway.
