### ISSUE TITLE
Allow alternative menu title by adding an optional 'menu title' field to the base Page model

### ISSUE THREAD

**Issue by nfletton** [torchbox/wagtail#2710]
On several occasions I've wanted to display a page's title in the menu differently to the value of the builtin Page.title field. However that's not as easy as you might expect.

Based on the Wagtail Demo of building a menu, you can't add a field to your custom models for the purpose since the .get_children() method of treebeard only returns the base Page model objects and not the custom model objects. That makes sense not least for performance reasons.

I'm aware there are various discussions related to the broader architecture that touch on menus and an approach for building menus using snippets (https://gist.github.com/bgrace/a5216b4059007924a75c) but for this simple use case of allowing an alternative menu title, an extra field would allow a little more flexibilty with the current page tree architecuture for little cost. Maybe I'm missing something and that's plausable.

**Comment by SalahAdDin** [comment]
Very interesting.

**Comment by zerolab** [comment]
See #836 for implementation suggestions and possible alternatives (the Puput reference)

**Comment by nfletton** [comment]
Thanks @zerolab . I'll take a look.

**Comment by gasman** [comment]
The AbstractPage model described in #836 would be the best long-term fix for this. I suspect that adding a new core field of this kind, at this point in Wagtail's existence, would cause as many problems as it solves: disruption to existing projects if it's enabled by default, extra hoops to jump through to set it up if it isn't.

In the meantime, I think `.get_children().specific()` ought to work acceptably for fetching the custom model objects, as it only performs one extra query for each distinct page type in the queryset.

**Comment by nfletton** [comment]
Thanks for the .specific() pointer @gasman
