### ISSUE TITLE
HTML_EXTENSION_RE

### ISSUE THREAD

**Issue by kakulukia** [torchbox/wagtail#2744]
Im using jade templates with the awesome pyjade compiler, BUT there is a hardcoded constraint whih wants to have html templates in wagtail/wagtailforms/models.py

:(

a better version for that regex could be
HTML_EXTENSION_RE = re.compile(r"(.*)\.[a-z]{3,4}$")

Please don't enforce the use of HTML templates!

**Comment by kakulukia** [comment]
here is the matching PR
https://github.com/torchbox/wagtail/pull/2745

**Comment by zerolab** [comment]
Closed in 334bebc
