### ISSUE TITLE
Install Error on windows

### ISSUE THREAD

**Issue by evolvews** [torchbox/wagtail#2781]
First, Great job, loving wagtail for our projects!

Only issue I have had so far:
Can't install version >= 1.5 on windows using pip.
FileNotFoundError: [Errno 2] No such file or directory: 
'\\env\\Lib\\site-packages\\wagtail\\tests\\testapp\\migrations\\__pycache__\\0005_customrichblockfieldpage_customrichtextfieldpage_defaultrichblockfieldpage_defaultrichtextfieldpage.cpython-35.pyc'

**Comment by gasman** [comment]
This is working fine for me. From a clean Windows 7 VM (IE11 Win7 VirtualBox from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), I've done the following steps:

* Go to https://www.python.org/downloads/ , download and run Python 3.5.2 installer
* Tick 'Add Python 3.5 to PATH', then 'Install now'
* then on the command line:

    pip install wagtail
    wagtail start testproject
    cd testproject
    python ./manage.py migrate
    python ./manage.py runserver

Visiting http://127.0.0.1:8000/ then gives me the "Welcome to your new Wagtail site!" page as expected.

Can you give me the exact steps you're running to reach the above error message, please?

**Comment by gasman** [comment]
I'll close this issue for now, as we need more details before we can investigate further - we'll be happy to reopen if you can provide the requested info. Thanks!

**Comment by evolvews** [comment]
Confirmed that this works, this ended up being an issue with the path/filename path length on windows. the filename:
`0005_customrichblockfieldpage_customrichtextfieldpage_defaultrichblockfieldpage_defaultrichtextfieldpage.py `
was putting me over the limit in the virtualenv I was installing into. Thanks for the reply..
