### ISSUE TITLE
ModelAdmin remove Add button

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#2787]
Is it possible to globally disable the add button like one can do with the regular admin UI as per 
http://stackoverflow.com/questions/20297321/how-to-remove-add-button-in-django-admin-for-specific-model ?

```py
class MyAdmin(admin.ModelAdmin):
    def has_add_permission(self, request):
        return False
```

**Comment by gasman** [comment]
Hi @lee-kagiso,
(Please don't use Github issues for questions - if you have a feature request and you're not sure if it exists already, please ask on the [Wagtail support](https://groups.google.com/forum/#!forum/wagtail) Google group first)

The add button is shown / hidden depending on the user's permission level, as set in Settings -> Groups; I can't really see a need for adding another mechanism to override that.

**Comment by alramalho** [comment]
I've found the need to do this as the default choose parent template was timing out due to a lot of possible parents (combinations of >2000 in X)
Since the only way in my admin interface to add a page without having previously specified a parent I've decided to do the following workaround:

```python
class MyAdmin(admin.ModelAdmin):
    index_template_name = 'wagtailadmin/index_without_add_button.html'
```

Where my ` wagtailadmin/index_without_add_button.html` is 

```liquid
{% extends "modeladmin/index.html" %}

{% block extra_js %}
    <script type="text/javascript">
    window.onload = function() {
        document.getElementsByClassName('actionbutton')[0].remove()
    };
    </script>
{% endblock %}

```

Would like some more robust solution here as this is hardly tied to Wagtails implementation, and it fugly.
Nevertheless, I'm sharing this here if somebody needs a quick bandage for this.

Still appreciate any better ways to fix my problem explained above

**Comment by manisar2** [comment]
In another use case, I'm providing a model admin for a **site setting** on a multi-site Wagtail.
After all the sites are exhausted (i.e. an instance of this setting is created for each site), I would want to disable / hide the 'add' button as _saving_ anyway fails after hitting the add button.

**Comment by allcaps** [comment]
This worked for me:

```
from wagtail.contrib.modeladmin.helpers import PagePermissionHelper


class FooPagePermissionHelper(PagePermissionHelper):
    def user_can_create(self, user):
        return False


class FooPageAdmin(ModelAdmin):
    model = FooPage
    ...
    permission_helper_class = FooPagePermissionHelper


modeladmin_register(FooPageAdmin)
```

**Comment by DouglasMcKey** [comment]
You can remove the add button from the list view by using the button helper when setting up your Wagtail Admin. See an example below.


```
from wagtail.contrib.modeladmin.helpers import ButtonHelper


class WagtailHomePageCarouselButtonHelper(ButtonHelper):
    def add_button(self, classnames_add=None, classnames_exclude=None):
        return None


class WagtailHomePageCarouselAdmin(ModelAdmin):
    model = HomePageCarousel
    menu_icon = "image"
    menu_label = "Main Carousel"
    list_display = ["home_page", "get_image_count"]
    search_fields = ["home_page"]
    button_helper_class = WagtailHomePageCarouselButtonHelper
```

I only ever want one instance in this model. When there are no instances, Wagtail prompts the following:

`No Home Page Carousels have been created yet. Why not add one.`

Once I have created the first instance. There is never an add button. 

Solves my requirement.
