### ISSUE TITLE
Hallo.js - Plugins activated but content not saved

### ISSUE THREAD

**Issue by msi2** [torchbox/wagtail#2795]
Hi all,

I'm running on Wagtail 1.3.1, Django 1.7.11.

I have activated hallohtml and hallojustify plugins and they appear in toolbar (without icons but buttons are here).

The buttons can be used and the modifications are seen in the textarea (I mean that I can center a field for example and I see it).

When I publish the page, the modifications made by either hallojustify or hallohtml are not saved whereas I can still use the bold/italic buttons and save the content. It looks like the html is cleaned up...

I should miss something but...

`@hooks.register('insert_editor_js')
def editor_js():
    js_files = [
    ]
    js_includes = format_html_join('\n', '<script src="{0}{1}"></script>',
        ((settings.STATIC_URL, filename) for filename in js_files)
    )

    return js_includes + format_html(
            """
            <script>
              registerHalloPlugin('hallojustify');
              registerHalloPlugin('hallohtml');
            </script>
            """
        )`

**Comment by gasman** [comment]
Answered in http://stackoverflow.com/questions/38096682/wagtail-hallo-js-adding-plugins-but-modified-content-is-not-saved/38097833#38097833 - please don't use Github issues for support queries.
