### ISSUE TITLE
Add ability to organize images in subdirectories

### ISSUE THREAD

**Issue by simonsmiley** [torchbox/wagtail#2800]
It would be nice to be able to organize images in subdirectories. Something like what django-filer allows.

My usecase is image galleries. Without this, it's really hard to organize.

**Comment by gasman** [comment]
Hi @simonsmiley - the 'Collections' feature added in Wagtail 1.4 allows this: http://docs.wagtail.io/en/v1.5.2/releases/1.4.html#collections-for-image-document-organisation

**Comment by simonsmiley** [comment]
It would still be nice to be able to create a hierarchy instead of them being flat

**Comment by tomdyson** [comment]
@simonsmiley have you seen https://github.com/anteatersa/Wagtail-Image-Folders ?

**Comment by simonsmiley** [comment]
No I haven't... I guess I always searched using the wrong keywords...
Thanks, Now I'll definitely give wagtail a try!
