### ISSUE TITLE
Adding of version number in the admin makes account / logout unclickable

### ISSUE THREAD

**Issue by jjanssen** [torchbox/wagtail#2802]
After the implementation of showing the version number in the admin (#2769) the account and logout link are no longer clickable when the settings menu is closed (at least in Chrome).  

![2016-06-30_09-54-43](https://cloud.githubusercontent.com/assets/287422/16480972/3537ea2e-3ea9-11e6-991e-ff7f79469c62.gif)

**Comment by tomdyson** [comment]
@chrxr could you look at this, please?

**Comment by jjanssen** [comment]
While testing my enhancements to the account settings. I also noted it shows the version number on top of the account settings in IE9.

![image](https://cloud.githubusercontent.com/assets/287422/16489832/7b9e293c-3ed7-11e6-88f0-e416e2bbb3c0.png)

**Comment by gasman** [comment]
Fixed in #2813.
