### ISSUE TITLE
Callable choices for ChoiceBlock

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2809]
Would be nice to have support of callable `choices` for `ChoiceBlock`.

Django's [`ChoiceField`](https://docs.djangoproject.com/en/1.8/ref/forms/fields/#choicefield) supports callable values for `choices` argument since version 1.8.

**Comment by nkuttler** [comment]
What is needed for this? Should I write some code and create a pull request? I really need this.

**Comment by m1kola** [comment]
Hi @nkuttler.

We already have a pull request for this issue (see #2812). It would be great if you can do the code review and/or testing for your use case.
