### ISSUE TITLE
Minor issues with styles of buttons

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2818]
1. In some choosers the edit buttons are higher than other buttons. Document chooser in stream field, for example.

    <img width="348" alt="screen shot 2016-07-04 at 18 14 22" src="https://cloud.githubusercontent.com/assets/509198/16565158/2b47e956-4214-11e6-9a26-a500eab33d7c.png">

2. Ugly left borders in buttons with icons. **Small** version of this button have the same issue.

    <img width="467" alt="screen shot 2016-07-04 at 18 43 54" src="https://cloud.githubusercontent.com/assets/509198/16565633/4a0c7ade-4217-11e6-9cd0-30218c6f3933.png">

**Comment by m1kola** [comment]
It seems to me that the first bug is not actual anymore: I can't reproduce it on fresh copy of `master` branch.

The second bug I can reproduce on Chrome (currently I use 51.0.2704.103 on Mac OS): I can't reproduce it on FireFox (46.0.1).

**Comment by gasman** [comment]
Fixed in #2819.
