### ISSUE TITLE
Add/edit pages you own

### ISSUE THREAD

**Issue by EduardoNogueira** [torchbox/wagtail#2831]
How can I give permissions to add/edit pages you own to a group on the most recent versions of wagtail?
I think this option disappeared in one of the last releases.

**Comment by gasman** [comment]
Hi @EduardoNogueira - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

This option is still available as the 'Add' column under 'Page permissions' - there wasn't space for the full label in the new layout.

**Comment by EduardoNogueira** [comment]
Tks for the answer! @gasman
