### ISSUE TITLE
Add custom field_type to FormBuilder

### ISSUE THREAD

**Issue by johnwiseheart** [torchbox/wagtail#2835]
I'd like to add a field to the form builder that allows a user to pay for something using paypal.

The easiest way I see to do this, would be if there was a way to give FormBuilder a custom field_type, which references other models elsewhere in my project. Currently I don't see a way to add a custom field_type like this.

**Comment by m1kola** [comment]
Hi @johnwiseheart,

I don't think that you need to add a new field type to `FormBuilder` for your task. It seems to me that you just can extend your page model (the one which was inherited from the `AbstractForm` or `AbstractEmailForm` models) with required fields / methods.

Useful docs:
* [Form builder](http://docs.wagtail.io/en/v1.5.2/reference/contrib/forms.html)
* [Page models](http://docs.wagtail.io/en/v1.5.2/topics/pages.html)

If you really want to add a new field type to `FormBuilder`, you create your own form builder class and override default `FormBuilder` using `form_builder` attribute in `AbstractForm`/`AbstractEmailForm`-derived models.

But keep in mind that `form_builder` attribute is not documented, so it may be changed in future.

**Comment by johnwiseheart** [comment]
The issue is that I want the user to be able to optionally add a payment to
a form, so it would need to be in the form builder itself, as far as I can
tell. I will have a look and see whether extending the page model works as
I'm hoping, but may have to override the builder otherwise.

**Comment by m1kola** [comment]
At the moment I see only one reason why do you need to add a new field type to `FormBuilder`: you need to do that, if you want to save some value from your "payment field" in a DB and be able to export this value to CSV.

If you don't want to save value / input in the DB and if you don't need an export, you can add this functionality on the page model level.

Also there is pull request (#2617, needs some work) that allows you to add an extra data to the DB and to the CSV export.
