### ISSUE TITLE
Circular dependency import errors

### ISSUE THREAD

**Issue by Eraldo** [torchbox/wagtail#2839]
# Context

Imagine 2 django apps:

**news app**
`models.py`: `NewsPage` with a stream field that allows to add `EventTeaserBlock` blocks.
`blocks.py`: `NewsTeaserBlock`

**events app**
`models.py`: `EventPage` with a stream field that allows to add `NewsTeaserBlock` blocks.
`blocks.py`: `EventTeaserBlock`

# Challenge

⚡ As soon as I import one of these apps, it in turn tries to import the other and I get caught in a circular import.

Example:
1. Loading `news` app imports `NewsPage` from `news/models.py` which finds the `StreamField` and there it tries to load `EventTeaserBlock` which finds a `News` model and thus triggers loading the `events` app -- Which in turn loads the `EventsPage` which has a `StreamField` using `NewsTeaserBlock` and this is where the circle is complete!

# Request

Putting everything in one monolithic app might work, but I do not want to go that path.
Splitting the apps to have an `events_blocks` app and an `events_pages` app might also work.. that again ist not how `django` intends `apps` to work: I would expect a `news` app to include it's pages and blocks.

Any ideas/hints/suggestions on how to solve this?

**Comment by gasman** [comment]
Hi @Eraldo - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.
