### ISSUE TITLE
html5lib 0.99999999 broken

### ISSUE THREAD

**Issue by prydie** [torchbox/wagtail#2843]
wagtails `setup.py` includes the following version spec for `html5lib`:

```
    "html5lib>=0.999,<1",
```

This matches version 0.99999999 which causes an exception on import in Wagtail due to https://github.com/html5lib/html5lib-python/issues/276.

More info at: http://stackoverflow.com/a/38392288/374052

**Comment by patoroco** [comment]
It depends on beautifulsoup, and it's already reported: https://bugs.launchpad.net/beautifulsoup/+bug/1603299

From now, we're forcing version to `html5lib==0.9999999` in our requirements file for our project.
