### ISSUE TITLE
problem creating new page

### ISSUE THREAD

**Issue by kuso** [torchbox/wagtail#2861]
Hi guys,

  I just setup a fresh installation of wagtail and was trying to create a new page.  But I am having trouble finding the following page as described in the documentation.  Apparently any page I try to create is of the 'Home Page' type.  I would like to create page of some other types.  Can somebody help me?

![screen09_page_type_selection](https://cloud.githubusercontent.com/assets/147306/17013394/d6cc0dd6-4f50-11e6-8966-0d79ce05f634.png)

**Comment by Proper-Job** [comment]
@kuso support queries should go into this group: https://groups.google.com/forum/#!forum/wagtail
Having said that, did you create model objects that inherit from Page?  When you  create a new page, wagtail allows you to choose from Page subclasses within your installed apps.

**Comment by kuso** [comment]
Okay, I got it working now after subclassing from Page.  Sorry about the misplacement of the question.
