### ISSUE TITLE
DB search backend indexes JSON encoded streamfields

### ISSUE THREAD

**Issue by thwd-duda** [torchbox/wagtail#2862]
For example, iif the french word `pépinières` appears in a WYSIWYG stream field, it will be indexed for search as `p\u00e9pini\u00e8res`. This is bad because the search term `pépinières` will not yield that result. If you search for `p\u00e9pini\u00e8res` instead, the match is found.

**Comment by kaedroho** [comment]
Thanks for reporting this @thwd-duda!

The database search backend was developed to make search at least return something if you couldn't run Elasticsearch locally for development. However, it isn't designed to be a "proper" search engine which always returns the most relevant results. It doesn't have ranking, stemming or the ability to search body text either so it's not a good option for a production search engine anyway.

For now, if you want good quality search in Wagtail, use Elasticsearch.

There are plans to add support for PostgreSQL FTS and Whoosh in the future which would be a great improvement on the current DB search.
