### ISSUE TITLE
Button class on login screen has the icon-spinner by default

### ISSUE THREAD

**Issue by sebworks** [torchbox/wagtail#2863]
It appears that the sign-in button has the `icon-spinner` class by default. This results in the spinner appearing, although you haven't clicked on the `Sign in` button.

```
<button type="submit" class="button-longrunning" tabindex="3" data-clicked-text="Signing in...">
     <span class="icon icon-spinner"></span>
     <em>Sign in</em>
</button>
```

<img width="241" alt="screen shot 2016-07-21 at 11 46 18 pm" src="https://cloud.githubusercontent.com/assets/1696212/17046075/9189220c-4f9d-11e6-84c2-863104b8add2.png">

**Comment by gasman** [comment]
Hi @sebworks,
The "sign in" button should look like this, so my guess is that your CSS has not properly loaded:

![screen shot 2016-07-22 at 09 14 08](https://cloud.githubusercontent.com/assets/85097/17050803/dd5fbdc2-4fec-11e6-8c4c-5f306b39bcd5.png)

Please check in your browser's Developer Tools (under Network) that all CSS files are being served correctly.

**Comment by sebworks** [comment]
@gasman, is the button font-size in `login.css` being intentionally overridden? I notice the `Sign In` button is significantly smaller.

<img width="542" alt="screen shot 2016-07-26 at 9 04 41 am" src="https://cloud.githubusercontent.com/assets/1696212/17138808/0e5db336-5310-11e6-8fd1-f1eb0a84c855.png">

**Comment by gasman** [comment]
Ah, good catch! Looks like the 'large button' style wasn't reinstated when the CSS was tweaked in cc7a936cd5f3c00bf3c808332d639739d066d992. Will work on a fix now...

**Comment by sebworks** [comment]
I think you can just provide specificity like:

`button.button`
