### ISSUE TITLE
Error while publishing a page with future go_live_at date set

### ISSUE THREAD

**Issue by asa511** [torchbox/wagtail#2865]
(using wagtail 1.5.3 / Python 3.4 / Django 1.9.7 / postgresql)

I am unable to publish a page with go_live_at date set to a future date. The following error occurs:

```
 File "/home/xxx/.virtualenvs/xxx/lib/python3.4/site-packages/wagtail/wagtailadmin/views/pages.py", line 323, in edit
    if page.go_live_at and page.go_live_at > timezone.now():
TypeError: can't compare offset-naive and offset-aware datetimes

```
Perhaps it was working fine before I upgraded from 1.2 to 1.5.3 but I am not very sure.

**Comment by gasman** [comment]
Hi @asa511 - I'm not able to replicate this on a new project created with Wagtail 1.5.3 / Python 3.4 / Django 1.9.7 / Postgresql, so I suspect this is something specific to your project's settings. (However, I also tried changing the most obvious candidates - setting `USE_TZ = False` and setting `TIME_ZONE` to something other than `UTC` - and still couldn't replicate the error...)

Please can you try creating a new project with `wagtail start myproject`, and see if it still shows the error - if not, try copying settings over from the affected project until you find one that triggers the error.

**Comment by gasman** [comment]
Closing as unable to replicate - we'll be happy to reopen if you can provide the requested info. Thanks!
