### ISSUE TITLE
RoutablePageMixin + i18n + Preview = not working

### ISSUE THREAD

**Issue by soar** [torchbox/wagtail#2866]
Today I've found strange issue. I have some page class:

```python
class BlogPage(Page):
    ...
```

And `urls.py`:

```python
urlpatterns = [
    url(r'^djangoadmin/', admin.site.urls),
    url(r'^wagtailadmin/', include(wagtailadmin_urls)),
    url(r'^doc/', include(wagtaildocs_urls)),
]

urlpatterns += i18n_patterns(
    url(r'', include(wagtail_urls)),
)
```

When I click "Preview" button in admin page, I see following requests:

```
[25/Jul/2016 13:29:19] "GET /wagtailadmin/pages/preview/ HTTP/1.1" 200 10327
[25/Jul/2016 13:29:20] "GET /wagtailadmin/pages/preview_loading/ HTTP/1.1" 200 9844
[25/Jul/2016 13:29:23] "POST /wagtailadmin/pages/19/edit/preview/ HTTP/1.1" 200 9594
```

And all works fine. But now I want to modify my page class:

```python
class BlogPage(RoutablePageMixin, Page):

    @route(r'^tag/(\w+)/$', name='tag')
    def tag(self, request, tag):
    ...
```

Wagtail admin is still working. But when I open same page and click "Preview" - I see 404 page:

```
Page not found (404)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/ru/wagtailadmin/pages/19/edit/preview/
Raised by: 	wagtail.wagtailcore.views.serve
```

You can notice, that language tag appears in URI, but it shouldn't - i18n isn't enabled for admin pages. And now there are following requests:

```
[25/Jul/2016 13:35:52] "GET /wagtailadmin/pages/19/edit/ HTTP/1.1" 200 173884
[25/Jul/2016 13:35:58] "GET /wagtailadmin/pages/preview/ HTTP/1.1" 200 10326
[25/Jul/2016 13:35:59] "GET /wagtailadmin/pages/preview_loading/ HTTP/1.1" 200 9844
Not Found: /wagtailadmin/pages/19/edit/preview/
[2016-07-25 13:36:01.700] [WARNING   ] [django.request] [base/get_response] [p:320956|t:311696] || Not Found: /wagtailadmin/pages/19/edit/preview/
[25/Jul/2016 13:36:01] "POST /wagtailadmin/pages/19/edit/preview/ HTTP/1.1" 302 0
Not Found: /ru/wagtailadmin/pages/19/edit/preview/
[2016-07-25 13:36:01.755] [WARNING   ] [django.request] [base/get_response] [p:320956|t:324092] || Not Found: /ru/wagtailadmin/pages/19/edit/preview/
[25/Jul/2016 13:36:01] "GET /ru/wagtailadmin/pages/19/edit/preview/ HTTP/1.1" 404 1741
```

I've also tried to remove any routes:

```python
class BlogPage(RoutablePageMixin, Page):
    ... (only fields here)
```

And requests are now:

```
[25/Jul/2016 13:37:17] "GET /wagtailadmin/pages/preview/ HTTP/1.1" 200 10327
[25/Jul/2016 13:37:18] "GET /wagtailadmin/pages/preview_loading/ HTTP/1.1" 200 9844
Not Found: /wagtailadmin/pages/19/edit/preview/
[2016-07-25 13:37:20.804] [WARNING   ] [django.request] [base/get_response] [p:322080|t:319612] || Not Found: /wagtailadmin/pages/19/edit/preview/
[25/Jul/2016 13:37:20] "POST /wagtailadmin/pages/19/edit/preview/ HTTP/1.1" 200 2084
```

**Comment by kaedroho** [comment]
I think you're missing the "main" view on the routable page, this must be defined when you switch to using the ``RoutablePageMixin``.

Try adding the following to your model:

```python
from django.template import TemplateResponse


    @route(r'^$')
    def main_events(self, request):
        return TemplateResponse(request, self.get_template(), self.get_context())
```

**Comment by soar** [comment]
@kaedroho but in [documentation](http://docs.wagtail.io/en/v1.5.3/reference/contrib/routablepage.html#module-wagtail.contrib.wagtailroutablepage) you can see:

> A Page using RoutablePageMixin exists within the page tree like any other page, but URL paths underneath it are checked against a list of patterns. If none of the patterns match, control is passed to subpages as usual (or failing that, a 404 error is thrown).

So, I think, if defined routes doesn't match query - should be used default algorithm for Page class. Without any additional coding. Am I wrong?

**Comment by kaedroho** [comment]
That bit of documentation is about how it behaves if a subroute doesn't exist. (eg, using your configuration above, ``/tag/my-tag/`` will render the ``tag`` view but ``/foo/`` will attempt to lookup a subpage called foo and serve that)

In order to make ``RoutablePageMixin`` work, we had to override the method that is usually used to render the page so you have to define a new one if you want previewing to work again.

**Comment by soar** [comment]
I understand. Thank you.

**Comment by nutztherookie** [comment]
Based on this, I'd argue that in 99% the main-route is a sensible default and could be included in the `RoutablePageMixin`.
```python
    @route(r'^$')
    def main(self, request):
        return TemplateResponse(request, self.get_template(), self.get_context())
```

This can still be overridden and it declutters all classes inheriting RoutablePageMixin. 
(Granted the method name must match.)

**Comment by gasman** [comment]
@nutztherookie Sounds like a good idea to me - please feel free to open that as a new issue.

(Are you sure the method name needs to match? As far as I can tell, non-matching names would just result in two routes being defined for `r'^$'` inside the urlconf, and hopefully we have the inheritance set up so that the one defined in the subclass matches first - if not, I'm sure that can be fixed!)

**Comment by nutztherookie** [comment]
Hey @gasman , I wasn't sure about this either so I tested it quickly and I tink the base-route was taken first. I will check again more thoroughly and create a PR :)

**Comment by nutztherookie** [comment]
not sure if referencing this issue automatically triggers you guys to get this update so: I created a PR: #3344  :)
