### ISSUE TITLE
An edit button appears on the users listing

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2898]
In Wagtail 1.6rc1 an edit button appears on the users listing like it shown on the screenshot below. 

In Wagtail 1.5 we don't have any buttons on this listing.

<img width="405" alt="screen shot 2016-08-08 at 16 38 00" src="https://cloud.githubusercontent.com/assets/509198/17481902/e6b8d464-5d87-11e6-919a-b9e7cba76cf0.png">

**Comment by gasman** [comment]
This was added in #2523 (see also https://github.com/torchbox/wagtail/issues/2371#issuecomment-214624673). If you have the appropriate permission, there should be a 'delete' button there too - is that not the case?

**Comment by m1kola** [comment]
Cool! I have tried to find any PRs using `edit` and `button` keywords and found nothing relevant. That's why I've decided that the button had been added accidentally.

Thanks!
