### ISSUE TITLE
Saving fails when using custom image

### ISSUE THREAD

**Issue by mronoffon** [torchbox/wagtail#2911]
Saving 'normal' images (wagtailimages.Image) is no problem, but when i use 
WAGTAILIMAGES_IMAGE_MODEL ("core.APPImage" - mine), I get the following error: "Select a 
valid choice. That choice is not one of the available choices."  The code originates from the 
example, so there "shouldn't" be any syntax errors.  Im using wagtail 1.5.3, with django 1.9.9. 

Thanks in advance

**Comment by gasman** [comment]
Hi @mronoffon - I'm afraid there's not enough detail here to investigate this. Please can you provide a minimal code example and steps for reproducing this issue?

**Comment by mronoffon** [comment]
Hi,

This code was copied and modified from your example:

# Custom image
class APPImage(AbstractImage):
    caption = models.CharField(max_length=255, blank=True)
    alt_text = models.CharField(max_length=255, blank=True)
    awards = models.TextField(blank=True)
    featured = models.TextField(blank=True)

    admin_form_fields = Image.admin_form_fields + (
        'caption',
        'alt_text',
        'awards',
        'featured',
    )

    @property
    def full_url(self):
        return self.get_rendition('original').url

    @property
    def caption_text(self):
        return self.caption


class APPRendition(AbstractRendition):
    image = models.ForeignKey('APPImage', related_name='renditions')

    class Meta:
        unique_together = (
            ('image', 'filter', 'focal_point_key'),
        )

# Receive the pre_delete signal and delete the file associated with the model instance.
@receiver(pre_delete, sender=APPImage)
def image_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.file.delete(False)

@receiver(pre_save, sender=APPImage)
def image_feature_detection(sender, instance, **kwargs):
    # Make sure the image doesn't already have a focal point
    if not instance.has_focal_point():
        # Set the focal point
        instance.set_focal_point(instance.get_suggested_focal_point())

@receiver(pre_delete, sender=APPRendition)
def rendition_delete(sender, instance, **kwargs):
    instance.file.delete(False)

----
Now, when WAGTAILIMAGES_IMAGE_MODEL is NOT in use, the 'save' process works.  If I enable
the WAGTAILIMAGES_IMAGE_MODEL='core.APPImage' and attempt to save an entry, I get the 
following error: "Select a valid choice. That choice is not one of the available choices."

I can't see anything else that would cause this error message to appear.

**Comment by gasman** [comment]
I'm unable to reproduce this on a fresh Wagtail install, although I had to remove the feature detection code as I don't have OpenCV set up here. (This is why I need a _minimal_ code example - if you can confirm whether the feature detection is or isn't a necessary part of the failure case, then that gives us a better idea of where to look for the bug.)

Here are the steps I took:

* Create new project

		mkvirtualenv customimagetest
		pip install "Wagtail==1.5.3" "Django==1.9.9"
		wagtail start customimagetest
		cd customimagetest
		./manage.py startapp core

* Edit `core/models.py` to the following:

        from __future__ import unicode_literals

        from django.db import models
        from django.db.models.signals import pre_delete, pre_save
        from django.dispatch import receiver

        from wagtail.wagtailimages.models import Image, AbstractImage, AbstractRendition

        class APPImage(AbstractImage):
            caption = models.CharField(max_length=255, blank=True)
            alt_text = models.CharField(max_length=255, blank=True)
            awards = models.TextField(blank=True)
            featured = models.TextField(blank=True)

            admin_form_fields = Image.admin_form_fields + (
                'caption',
                'alt_text',
                'awards',
                'featured',
            )

            @property
            def full_url(self):
                return self.get_rendition('original').url

            @property
            def caption_text(self):
                return self.caption


        class APPRendition(AbstractRendition):
            image = models.ForeignKey('APPImage', related_name='renditions')

            class Meta:
                unique_together = (
                    ('image', 'filter', 'focal_point_key'),
                )

        # Receive the pre_delete signal and delete the file associated with the model instance.
        @receiver(pre_delete, sender=APPImage)
        def image_delete(sender, instance, **kwargs):
            # Pass false so FileField doesn't save the model.
            instance.file.delete(False)

        @receiver(pre_delete, sender=APPRendition)
        def rendition_delete(sender, instance, **kwargs):
            instance.file.delete(False)

* Edit customimagetest/settings/base.py, add 'core' to INSTALLED_APPS and set `WAGTAILIMAGES_IMAGE_MODEL = 'core.APPImage'`

* Set up database

		./manage.py makemigrations
		./manage.py migrate
		./manage.py createsuperuser
		./manage.py runserver 0.0.0.0:8000

* Log in to http://localhost:8000/admin/
* Go to Images -> Add an Image, and upload an image file
* Click 'update' (without making any changes to the form)
* Form submits with no error

**Comment by marctc** [comment]
This is a Puput related issue. It can be closed.

cheers

**Comment by gasman** [comment]
@marctc Thanks for the confirmation!
