### ISSUE TITLE
Introduce a ModelChooserBlock rather than SnippetChooserBlock

### ISSUE THREAD

**Issue by heymonkeyriot** [torchbox/wagtail#2912]
Now that Wagtail comes with ModelAdmin within core we're using models (rather than models with snippet decorators) much more regularly. This gives us flexibility over where we place them in the menu and whether contextually they should be grouped together.

One problem though is that, if they need to be referenced from a page model it isn't possible to use the SnippetChooserBlock, which means we get a fairly utilitarian dropdown list of options, rather than the nice UI that comes as part of the SnippetChooserBlock.

It'd be great if we could abstract back to some akin to a ModelChooserBlock. Or would that interfere with some other functionality?

**Comment by gasman** [comment]
Covered by #1806.
