### ISSUE TITLE
Sites: Incorrect matching of subdomain

### ISSUE THREAD

**Issue by bufke** [torchbox/wagtail#2921]
Hello, as far as I understand wagtail sites should match based on domain. So foo.com and bar.com might be different sites. If I have the same page in both sites - wagtail will attempt to match the site or use the default if that fails. So if I go to foo.com and see a slugurl link it might point to foo.com/page1 but bar.com will have bar.com/page1 even though page 1 is actually the same site.

This appears to fail when subdomain are used however. We get false matches. It can be reproduced like this

1. Create a site "localhost"
2. Create a second site "test.localhost"
3. Go to a page that has a slugurl link by going to localhost (may require editing /ect/hosts to ensure this resolves to wagtail).

I would expect the link to be "localhost/page1" however it is "test.localhost/page1"

Adding multiple sub domains does not work around the issue - for example admin.test.localhost would still match localhost. If I change the "localhost" part of the domain it will work as intended. For example the site "altlocalhost" would yeild links like "altlocalhost/page1"

A more production like scenario would be 

A default site of mygreatsite.com
A admin only site of admin.mygreatsite.com
The homepage is the same in both sites.

When I go to mygreatsite.com I end up with links to admin.mygreatsite.com.

**Comment by bufke** [comment]
Nevermind - after inspecting more the site in the request object is detected correctly. My problem is that slugurl uses the Page's relative_url function which calls get_url_parts. This doesn't even consider the current site. My work flow appears just unsupported. Having a page in multiple sites just don't work.

**Comment by gasman** [comment]
Yep - `slugurl` will just use the first page it finds with a matching slug, anywhere in the page tree - regardless of whether it matches the current site. If there are multiple pages with that slug, it's indeterminate which one will be used.

Out of curiosity - do you have a specific reason for wanting to use `slugurl` here, rather than just hard-coding the URL path into the template? It seems to me that if you're hard-coding a slug, and you have specific expectations about where it's meant to exist in the tree, then that's effectively the same thing as hard-coding a URL.

**Comment by bufke** [comment]
slugurl has some advantages over a hard coded url. Let's say I moved my page somewhere else in the tree, but still wanted a link that's in the home page template to work. slugurl would still function as intended while a hard coded url wouldn't. 

That said it's not ideal. If I changed the slug my slugurl would break. Ideally everything would be more data driven and controlled in wagtail (like having the page link in the home page model). Sometimes it's just faster to throw in a slugurl in a template and be done with it.

For my above problem - I think I'm just to just change Page.relative_url to only ever return relative urls. I don't need to cross between sites ever in this particular case.

**Comment by bufke** [comment]
I don't have time at this second - but would you ever want to support slugurl with pages in multiple sites? Page.get_url_parts would need to get passed the current site and attempt to match that site if possible - but fallback to existing behaviour if current_site is not passed in.

At a higher level - slugurl would attempt to keep you on the current site when possible.

**Comment by madisvain** [comment]
I found myself having the same issue. Solved it currently like this:

```python
from django import template

from wagtail.wagtailcore.models import Page

register = template.Library()


@register.simple_tag(takes_context=True)
def site_slugurl(context, slug):
    """Returns the URL for the page that has the given slug."""
    pages = Page.objects.filter(slug=slug)

    if not pages:
        return None

    try:
        current_site = context['request'].site
    except (KeyError, AttributeError):
        # request.site not available in the current context; fall back on page.url
        return pages.first().url

    for page in pages:
        if page.get_site() == current_site:
            return page.relative_url(current_site)
        else:
            continue
```

But this fore sure is not a very clean solution. Will look into this a bit more if this can be fetched with a database query more efficiently.
