### ISSUE TITLE
Middleware Problem with Django 1.10

### ISSUE THREAD

**Issue by imthecritic** [torchbox/wagtail#2924]
While upgrading and changing to the new style of middleware for Django 1.10  (changing "MIDDLEWARE_CLASSES" to "MIDDLEWARE") in my basey.py, I ran into this problem:

>   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "/home/ubuntu/workspace/test4/xsite/wsgi.py", line 18, in <module>
>     application = get_wsgi_application()
>   File "/home/ubuntu/workspace/test4/env/lib/python3.4/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
>     return WSGIHandler()
>   File "/home/ubuntu/workspace/test4/env/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
>     self.load_middleware()
>   File "/home/ubuntu/workspace/test4/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 82, in load_middleware
>     mw_instance = middleware(handler)
> TypeError: object() takes no parameters

I was able to fix the problem by changing the RedirectMiddleware and SiteMiddleware classes to take MiddlewareMixin instead of object. 

Now the class in /wagtail/wagtailcore/middleware.py looks like:

...
from django.utils.deprecation import MiddlewareMixin

class SiteMiddleware(MiddlewareMixin):
...

And the class in /wagtail/wagtailredirects/middleware.py looks like:
...
...
from django.utils.deprecation import MiddlewareMixin

class RedirectMiddleware(MiddlewareMixin):
...

**Comment by gasman** [comment]
Hi @imthecritic - a pull request for this is in progress at #2922.

**Comment by gasman** [comment]
Fixed in #2922
