### ISSUE TITLE
Page subclasses fail to use PageManager on current Django stable/1.10.x

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#2933]
As reported by @pjstevns, Django commit https://github.com/django/django/commit/21f18e5372fe86090a82b696f3208e56c6a2aa80 breaks the behaviour of the `objects` manager on subclasses of `Page` - it now gets set to a plain `django.db.models.manager.Manager` instance instead `PageManager`, causing numerous test failures anywhere that the custom PageManager / PageQuerySet methods are used.

A minimal models.py that reproduces the change of behaviour:

```python
from __future__ import absolute_import, unicode_literals

from django.db import models
from django.utils import six
from treebeard.mp_tree import MP_Node, MP_NodeQuerySet


class PageQuerySet(MP_NodeQuerySet):
    pass


class BasePageManager(models.Manager):
    def get_queryset(self):
        return PageQuerySet(self.model).order_by('path')

PageManager = BasePageManager.from_queryset(PageQuerySet)


class PageBase(models.base.ModelBase):
    """Metaclass for Page"""
    def __init__(cls, name, bases, dct):
        super(PageBase, cls).__init__(name, bases, dct)

        # Override the default `objects` attribute with a `PageManager`.
        # Managers are not inherited by MTI child models, so `Page` subclasses
        # will get a plain `Manager` instead of a `PageManager`.
        # If the developer has set their own custom `Manager` subclass, do not
        # clobber it.
        if not cls._meta.abstract and type(cls.objects) is models.Manager:
            PageManager().contribute_to_class(cls, 'objects')


class Page(six.with_metaclass(PageBase, MP_Node, models.Model)):
    title = models.CharField(max_length=255)
    objects = PageManager()


class EventPage(Page):
    date = models.DateField()
```

Pre-https://github.com/django/django/commit/21f18e5372fe86090a82b696f3208e56c6a2aa80 behaviour:
```
>>> from core.models import Page, EventPage
>>> EventPage.objects
<django.db.models.manager.BasePageManagerFromPageQuerySet object at 0xb66eacec>
```

New behaviour:
```
>>> from core.models import Page, EventPage
>>> EventPage.objects
<django.db.models.manager.Manager object at 0xb64c670c>
```

The inheritance situation here is quite complicated: `Model` is subclassed as treebeard's `MP_Node` (abstract), which sets the manager `MP_NodeManager`. `MP_Node` is subclassed as `Page` (concrete), which sets `PageManager`. `Page` is then subclassed as `EventPage` (MTI), and the `PageBase` metaclass attempts to force the use of PageManager on that too.

Interestingly, if I take `MP_Node` out of the chain, the regression happens further back in time in https://github.com/django/django/commit/ed0ff913c648b16c4471fc9a9441d1ee48cb5420 - which points to the possibility that this was an intended change of behaviour for 1.10 but the change was masked by https://code.djangoproject.com/ticket/27073.

(cc @timgraham in case this is a legitimate Django 1.10.1 regression, rather than Wagtail misbehaving - I'll do some more unpicking to try and figure out which...)

**Comment by timgraham** [comment]
Better to \cc @loic if you need some expertise about the intentions of these changes.

**Comment by gasman** [comment]
Thanks @timgraham.

I'm now 99% certain this can be chalked up to bad behaviour on Wagtail's part :-) We're relying on metaclass hacking to ensure that MTI subclasses of the `Page` model retain the custom manager defined on `Page` - https://github.com/django/django/pull/6175 breaks this ability (although it seems that certain quirky inheritance patterns can mask this and cause our custom manager to appear after all, which is why we didn't spot this on 1.10).

I now realise that I can achieve what I need by introducing an abstract superclass of `Page` and setting the manager there instead. So, since the metaclass hack _is_ avoidable, I think it's entirely reasonable for Django to not support it across versions.

The minimal test case I ended up with, for the record:

```python
from __future__ import absolute_import, unicode_literals

from django.db import models
from django.utils import six


class CustomManager(models.Manager):
    pass


class ManagedModelBase(models.base.ModelBase):
    def __init__(cls, name, bases, dct):
        super(ManagedModelBase, cls).__init__(name, bases, dct)
        CustomManager().contribute_to_class(cls, 'objects')


class Page(six.with_metaclass(ManagedModelBase, models.Model)):
    pass


class EventPage(Page):
    pass
```

```
# old behaviour
>>> from core.models import EventPage
>>> EventPage.objects
<core.models.CustomManager object at 0xb6663f6c>

# new behaviour
>>> from core.models import EventPage
>>> EventPage.objects
<django.db.models.manager.Manager object at 0xb63ff5ec>
```
