### ISSUE TITLE
RichTextField

### ISSUE THREAD

**Issue by mronoffon** [torchbox/wagtail#2946]
Is RichTextField deprecated (or slated for deprecation)?  According to the demo: https://github.com/torchbox/wagtail-torchbox/blob/master/tbx/core/models.py#L340

Outside of StreamField, is there a simpler but similar widget to use?

thank you

**Comment by gasman** [comment]
Hi @mronoffon - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

(The wagtail-torchbox repo is simply the Torchbox website built on Wagtail - it's not part of the Wagtail project itself, and nothing in there should be taken as a statement of official policy or best practice about Wagtail.)

**Comment by SalahAdDin** [comment]
@mronoffon Until now i'm using `RichTextField` without problems.
