### ISSUE TITLE
Strings had not been marked for translation on password form

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2950]
Strings had not been marked for translation on password form. They can be found in this template: [`wagtail/wagtailcore/templates/wagtailcore/password_required.html`](https://github.com/torchbox/wagtail/blob/9b81d3b6670c4d7a313f802f000fae1259100b56/wagtail/wagtailcore/templates/wagtailcore/password_required.html)

How to reach this form from the UI:

> Users with publish permission on a page can set it to be private by clicking the ‘Privacy’ control in the top right corner of the page explorer or editing interface, and setting a password. Users visiting this page, or any of its subpages, will be prompted to enter a password before they can view the page.

[More docs](http://docs.wagtail.io/en/v1.6/advanced_topics/privacy.html#private-pages).

**Comment by gasman** [comment]
Fixed in #2955
