### ISSUE TITLE
StreamField items without input fields appear blank in the admin editor

### ISSUE THREAD

**Issue by dwasyl** [torchbox/wagtail#2961]
This is just a usability thing, but when a StreamField includes a block that has no field inputs and is added to a pages streamfield it appears as a blank space in the streamfield panel. However, when the user hovers over the block it highlights and the title appears in the tab on the right side.

Perhaps there are other ways to include blocks like this in pages, but it has proven useful to define a few StructBlocks that just represent a template and database lookup that can be inserted on multiple pages/anywhere on the layout.

Maybe items with no input fields could by default display the StreamField item name? Just something to visually indicate there is an object there.

**Comment by gasman** [comment]
Thanks for the suggestion, @dwasyl!
It would probably be more logically correct for us to have a specific block type to cover blocks that simply "exist" and don't have any configuration options, rather than using a StructBlock with no fields for that purpose. Definitely worth improving the in-form rendering either way, though.

**Comment by dwasyl** [comment]
@gasman That would probably be a better solution, but in the meantime StructBlocks exist just fine without any fields and it does no harm. It just starts to look a little odd when you add a blank row into a streamfield.

I find some of these little things go a long way with end users.

**Comment by benoitvogel** [comment]
Since the new StaticBlock (#3154) has been merged, I assume this issue can be closed now.

**Comment by gasman** [comment]
Yep, good point - thanks @benoitvogel!
