### ISSUE TITLE
Group Permissions: persistent value on checkbox

### ISSUE THREAD

**Issue by lboaretto** [torchbox/wagtail#2962]
When I select "Can access Wagtail admin" checkbox, the value does not persist.

The same on "Object Permissions" (Redirect, User, Site, Group).

Wagtail 1.6.1
Django 1.10
Python 2.7.9

**Comment by gasman** [comment]
Confirmed - looks like this is a regression with Django 1.10. Thanks for the report!

**Comment by gasman** [comment]
The bug appears on this commit:
https://github.com/django/django/commit/ded502024191053475bac811d365ac29dca1db61
https://code.djangoproject.com/ticket/17657

**Comment by m1kola** [comment]
Fixed in #2966

Thanks for the report!
