### ISSUE TITLE
Chrome "Are you sure you want to leave the page?" dialog when saving a page

### ISSUE THREAD

**Issue by ptink** [torchbox/wagtail#2965]
We've noticed that in the latest version ("52.0.2743.116 m") of Chrome on Windows it prompts the user on whether they are sure they want to leave the page when saving- which can be confusing and result in a loss of work. The bug does not occur in Firefox or in the latest versions of chrome on linux/mac. Not tested in IE.

**Comment by gasman** [comment]
Hi @ptink,
I'm unable to replicate this when testing against wagtaildemo - please can you give specific steps for reproducing this issue? It may depend on details like whether you're submitting the form by clicking the button or pressing enter, or which field was focused at the time, so please be as specific as possible.

(Also, can I confirm that you're running the latest version of Wagtail? There were a few bugfixes to this behaviour in 1.6.)

**Comment by iamwithnail** [comment]
I had the same issue in 1.5 on Chrome on Android, i'm just updating the install, so will see if it's fixed in the new release and detail if not.

**Comment by ptink** [comment]
Appears this was an issue with v1.5 of Wagtail, v1.6 doesn't have this behaviour! In terms of recreating it was clicking the button rather than pressing enter, though the solution for us has simply been to upgrade Wagtail now.

**Comment by gasman** [comment]
Thanks for confirming!
