### ISSUE TITLE
Include more expansive iconset in core

### ISSUE THREAD

**Issue by ebertti** [torchbox/wagtail#2970]
http://fontawesome.io/icons/

- One Font, 634 Icons
- No JavaScript Required
- Infinite Scalability
- Free, as in Speech
- CSS Control
- Perfect on Retina Displays
- Plays Well with Others
- Desktop Friendly
- Accessibility-minded

**Comment by MechanisM** [comment]
https://github.com/alexgleason/wagtailfontawesome

**Comment by alexgleason** [comment]
The plugin above achieves Font Awesome support.

But I think there's a discussion to be had about including a more expansive iconset in core, be it Font Awesome or one of the many others. Or a combination.

* http://fontawesome.io/icons/
* http://ionicons.com/
* https://octicons.github.com/

**Comment by SalahAdDin** [comment]
Torchbox can expand his iconset, i think that will be a better and unique solution.

**Comment by timheap** [comment]
I think bundling an icon font in Wagtail would be annoying to maintain, as the release cycles for Wagtail and Font Awesome do not line up, and old Wagtails would be stuck with old versions of Font Awesome. However, if Wagtail depended upon wagtailfontawesome (or some similar package), these issues would disappear, while still effectively shipping an expanded icon library with Wagtail.

**Comment by alexgleason** [comment]
IMO it's the least of our worries if the latest version of Wagtail doesn't always include the 10 random new icons Font Awesome added recently. The existing iconset has worked in 95% of the blocks I've built.

**Comment by gasman** [comment]
Let's continue the discussion at #2349, as this conversation is covering much the same ground as the earlier one.
