### ISSUE TITLE
Admin interface not very readable: too low contrast and too small fonts

### ISSUE THREAD

**Issue by strindhaug** [torchbox/wagtail#2976]
A lot of the text in the admin interface is very hard to read.

First the font sizes are ridiculously small, the stylesheet sets the body font size to 80% which (assuming a default font size of 16px, which almost all browsers have) gives a base font size of 12.8px
In the men this is further reduced by setting font size to 0.95em which gives a font size of 12.2 px which is very small but if you have good vision is at the lower edge of being legible. 
(When I write stylesheets I usually never reduce the base font size, and i only go as low as 90% or 85% for "small print" e.g. legalese and other stuff in the footer that nobody wants to read anyway)

But for that size to be barely readable it needs a lot of contrast, but the text is very low contrast as well: light gray on dark gray.

But then the font weight is only 300 making it's strokes only some subpixels wide further reducing the contrast so the actual text color is only about `#777777` (The brightest pixel i could find in a screenshot was `#919191` which is still way to low contrast: http://webaim.org/resources/contrastchecker/?fcolor=919191&bcolor=333333 )

(Light text on dark background usually requires a slightly heavier font than normal to be just as readable anyway.)

If one uses a dark gray or dark colored background, the text should pretty much be 100% brightness, or if the font is light gray the backround should be 0% brightness, if the color of both the text and background is moved towards 50% brightness the contrast will be to low for some people and on some monitors.

**Comment by strindhaug** [comment]
![skjermbilde fra 2016-09-05 11-16-58](https://cloud.githubusercontent.com/assets/2144849/18243733/cca34e52-735c-11e6-8f41-195698c51e5f.png)

How the menu appears on my computer at 100% zoom (unscaled)
Notice how the text color is visually several steps darker than the icon (that have the same color in css) because the strokes are less than 1px wide.

(I notice that the screenshots [like this one](https://camo.githubusercontent.com/ac10c25f513eaed55138d01f402c0f1d9482bdc6/687474703a2f2f692e696d6775722e636f6d2f55354d4461306c2e6a7067) seem to be zoomed in to about 125% zoom for some reason?)

**Comment by gasman** [comment]
Hi @strindhaug - thanks for the report! We'll discuss this at our core dev team meeting this week. (I think we could certainly lighten the text colour a bit - increasing the font size might be a harder sell...)

(I think the screenshots are the way they are because they were captured from a Retina screen on a Mac, resulting in them being uploaded at 200% resolution - presumably Imgur/Github scaled them back down to 125%. I guess we've probably been over-reliant on retina screens in general when designing Wagtail, where the contrast issue is much less noticeable...)

**Comment by strindhaug** [comment]
I've started working on a fork trying to improve contrast and legibility a bit, I'll create a PR once it's ready.
I won't increase the font-size, since you can compensate by zooming, but I think changing the font weight from 300 to normal for the smallest fonts is necessary.

**Comment by strindhaug** [comment]
I do still believe the base font size on the body should be 100% (e.g. respecting the browser default, or user preferences if they have changed it) and not 80% as it is now, but I didn't change this in my PR since it could cause layout issues where dimensions is specified in px based on the assumption of 12.8px font size.

**Comment by gasman** [comment]
Fixed in #2985
