### ISSUE TITLE
Internationalization - Linking pages

### ISSUE THREAD

**Issue by nux17** [torchbox/wagtail#2981]
I've read this [doc page](http://wagtail.readthedocs.io/en/v1.6.2/advanced_topics/i18n/duplicate_tree.html), referring to how linking pages together.

But how is this linking done? I don't see anything spawning on the admin interface. There is some lack of documentation on this part.

**Comment by gasman** [comment]
Hi @nux17,
The `french_link`, `spanish_link` fields need to be added to the page's `content_panels`, like any other field. I'll add this to the example in the documentation now...
