### ISSUE TITLE
modeladmin's ChooseParentView and DeleteView don't call get_context_data

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2984]
modeladmin's ChooseParentView and DeleteView view classes override the ``get()`` method but do not call ``get_context_data()`` which makes modifying them slightly tricker and inconsistent with the other view classes.

ChooseParentView: https://github.com/torchbox/wagtail/blob/master/wagtail/contrib/modeladmin/views.py#L728-L731
DeleteView: https://github.com/torchbox/wagtail/blob/28c8ae3ab99dd1b0b22bb334835c9e823b060cae/wagtail/contrib/modeladmin/views.py#L772-L774

**Comment by gasman** [comment]
Fixed in #3060
