### ISSUE TITLE
Link interface in Rich Text Editor does not allow anchors

### ISSUE THREAD

**Issue by polimekanos** [torchbox/wagtail#2988]
It would be great to allow links to anchors e.g. '#artists' to the Rich Text Link interface. I am working on a project that includes footnotes. However, I can't add links to anchors such as ‘[[3](#anchor)]’ using the 'external link' feature as this will create an error – valid url must be added.

**Comment by gasman** [comment]
Hi @polimekanos - there's an existing ticket for this at #1049.
