### ISSUE TITLE
FieldPanel classname='title' and slug generation

### ISSUE THREAD

**Issue by robslotboom** [torchbox/wagtail#2990]
The documentation says:

FieldPanel
The CSS class title can be used to mark a field as the source for auto-generated slug strings.

This isn’t the case. Adding classname="title" to a FieldPanel for another field than title will not trigger the creation of the slug.

Ommitting it from the FieldPanel for the title field still triggers the creation of a slug.

**Comment by gasman** [comment]
Thanks for the report! Have corrected the documentation in 8aa316c575f36a42ff2a8f1bbfc2046519efc099 - the 'title' class was never intended to control the slug behaviour, and it looks like that misconception has been in place in the docs for a rather long time :-/
