### ISSUE TITLE
Conflicting migrations: 0030_auto_20160810_1340, 0029_unicode_slugfield_dj19 in wagtailcore

### ISSUE THREAD

**Issue by dborisog** [torchbox/wagtail#3000]
### Issue Summary

Conflicting migrations: 0030_auto_20160810_1340, 0029_unicode_slugfield_dj19 in wagtailcore

### Steps to Reproduce

For some time I've been prototyping a web-site, started with Wagtail 1.5.3 working with SQLite.

Yesterday I shifted to Wagtail 1.6.2, my site was running OK.

Today I decided to move from SQLite to PostgreSQL, I haven't been interested in any data from SQLite nor in migratations for this DB, so I've cleaned all 'migrations' folders; created and setup PostgreSQL db;  manage.py check was OK.

I was able to migrate my model afterwards I had the named migrations deleted from wagtailcore\migrations.

However,
> python manage.py migrate
> CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0030_auto_20160810_1340, 0029_unicode_slugfield_dj19 in wagtailcore). To fix them run 'python manage.py makemigrations --merge'

> python manage.py makemigrations --merge
> Merging wagtailcore
>   Branch 0030_auto_20160810_1340
>     - Alter field owner on page
>     - Alter field owner on page
>   Branch 0029_unicode_slugfield_dj19
>     - Alter field slug on page
> 
> Merging will only work if the operations printed above do not conflict
> with each other (working on different fields or models)
> Do you want to merge these migration branches? [y/N] n

### Technical details

* Python version: Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
* Django version: 1.10.1
* Wagtail version: 1.6.2
* Browser version: irrelevant

The following packages installed in my virtualenvironment.
> pip freeze
> beautifulsoup4==4.5.1
> Django==1.10.1
> django-appconf==1.0.2
> django-compressor==2.0
> django-debug-toolbar==1.5
> django-el-pagination==2.1.1
> django-modelcluster==2.0
> django-taggit==0.18.3
> django-treebeard==4.0.1
> djangorestframework==3.4.6
> html5lib==0.999999
> Pillow==3.3.1
> psycopg2==2.6.2
> puput==0.6
> pytz==2016.6.1
> rcssmin==1.0.6
> requests==2.10.0
> rjsmin==1.0.12
> six==1.10.0
> sqlparse==0.2.0
> tapioca-disqus==0.1.2
> tapioca-wrapper==0.5.3
> Unidecode==0.4.19
> wagtail==1.6.2
> Willow==0.3.1

**Comment by gasman** [comment]
The `0030_auto_20160810_1340` migration is not something that's part of wagtailcore (see https://github.com/torchbox/wagtail/tree/v1.6.2/wagtail/wagtailcore/migrations) - so apparently it must have been added in a previous `./manage.py makemigrations` command. Unfortunately there's not enough detail here to know how that happened, or how to reproduce it. I would recommend uninstalling and reinstalling the wagtail package, to ensure that the stray migration is cleared out.

**Comment by dborisog** [comment]
Thank you.

Tried to recover deleted files to share the content; unfortunately, was able to find .pyc files only, unable to read the meaning from name, and has not found these files in virtualenvs I created around the time of this project.

Manual deletion of these files, in combination with uninstall with admin rights and new installation worked.

**Comment by dborisog** [comment]
@gasman , I unwillingly replicated the bug. Though I'm not sure it is related to your team I would like to share the migrations.

> wagtailcore\migrations\0029_unicode_slugfield_dj19.py

```
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models
from django import VERSION as DJANGO_VERSION


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = []
    if DJANGO_VERSION >= (1, 9):
        operations += [
            migrations.AlterField(
                model_name='page',
                name='slug',
                field=models.SlugField(allow_unicode=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255, verbose_name='slug'),
            ),
        ]
```

> \wagtailcore\migrations\0030_auto_20160916_1817.py

```
# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255, verbose_name='slug'),
        ),
    ]
```

The latter migration has happened after I've tried to makemigrations for (infoportugal) wagtail-modeltranslation https://github.com/infoportugal/wagtail-modeltranslation/


> python manage.py makemigrations
> \site-packages\django\utils\six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
>  return meta(name, bases, d)

> Migrations for 'wagtailcore':
>  0030_auto_20160916_1817.py:
>    - Alter field slug on page


The following packages are installed in my virtualenv.

> pip freeze
> beautifulsoup4==4.5.1
> bleach==1.4.2
> Django==1.9.9
> django-appconf==1.0.2
> django-compressor==2.0
> django-debug-toolbar==1.5
> django-el-pagination==2.1.1
> django-markdownx==1.6.3
> django-modelcluster==2.0
> django-taggit==0.18.3
> django-treebeard==4.0.1
> djangorestframework==3.4.6
> html5lib==0.999999
> Markdown==2.6.2
> Pillow==3.3.1
> psycopg2==2.6.2
> puput==0.6
> pytz==2016.6.1
> rcssmin==1.0.6
> requests==2.10.0
> rjsmin==1.0.12
> six==1.10.0
> sqlparse==0.2.0
> tapioca-disqus==0.1.2
> tapioca-wrapper==0.5.3
> Unidecode==0.4.19
> wagtail==1.5.3
> wagtail-modeltranslation==0.5.0a0
> Willow==0.3.1

**Comment by gasman** [comment]
Thanks, that's useful to know! It looks like wagtail-modeltranslation is doing some kind of redefinition of the Page.slug field, and hasn't yet been updated to match the Wagtail 1.6 definition (with the allow_unicode=True parameter).

**Comment by dborisog** [comment]
Just one note, this comes from Wagtail 1.5.3 and Django 1.9.9 and 'private' version of wagtail-modeltranslation, which has the following errors with Wagtail 1.6 / Django 1.10 
https://github.com/infoportugal/wagtail-modeltranslation/issues/84

I haven't tried to quickfix these errors, and I mostly unfamiliar with Wagtail & Django, so I don't know nor can't make valid assumptions if the "bug" is still relevant for Wagtail 1.6 

In general, however, I find the situation of a 'minor' app initiating changes in a major one quite surprising. But again, not sure if it is natural for Django architecture.
