### ISSUE TITLE
Feature request: add bulk actions and date hierarchy to ModelAdmin contrib app

### ISSUE THREAD

**Issue by lboaretto** [torchbox/wagtail#3006]
Date-based drilldown navigation helps the editor to find some page: [Date hierarchy](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.date_hierarchy)

[Bulk Actions](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/actions/) helps to publish/unpublish, export, delete...

**Comment by gasman** [comment]
Can you give more details of this suggestion, please?

**Comment by lboaretto** [comment]
I think that this will require some work on UI/design.

**Comment by gasman** [comment]
Thanks for the suggestion - we'll keep it in mind for future development. As it stands this isn't a good fit for a Github issue, as it really corresponds to two separate pieces of work, and would need to be specified in more detail before someone can go ahead and implement it - so I'll close this now.
