### ISSUE TITLE
Documentation for Wagtail UI Styleguide does not explain how to access it

### ISSUE THREAD

**Issue by harrislapiroff** [torchbox/wagtail#3009]
### Issue Summary

The [documentation for Wagtail UI Styleguide](http://docs.wagtail.io/en/v1.6.2/contributing/styleguide.html) does not explain how to access the styleguide once it is installed. I had to look into the code to find it.

We should add a sentence that explains that it can be accessed at $WAGTAILADMINURL/styleguide/ or in the admin navigation under Settings.

**Comment by SalahAdDin** [comment]
But, all live this is easy, adding `wagtail.contrib.styleguide` enable the option menu inside admin section, if i don't wrong.

**Comment by gasman** [comment]
@harrislapiroff Good point, thanks! Originally we had it as a top-level menu item, so there was no need to document it - then it moved to Settings, and it didn't occur to us to update the documentation. Will add a line accordingly...

**Comment by harrislapiroff** [comment]
Thanks, @gasman! Looks great. :)
