### ISSUE TITLE
One of Elasticsearch 2 builds fails permanently

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#3018]
Build with `TOXENV=py35-dj110-postgres-elasticsearch2 INSTALL_ELASTICSEARCH2=YES` fails permanently

```
$ if [[ -n "$INSTALL_ELASTICSEARCH2" ]]; then ./scripts/travis/install_elasticsearch2.sh; fi
sudo: must be setuid root
sudo: must be setuid root
sudo: must be setuid root
sudo: must be setuid root
sudo: must be setuid root
The command "if [[ -n "$INSTALL_ELASTICSEARCH2" ]]; then ./scripts/travis/install_elasticsearch2.sh; fi" failed and exited with 1 during .
```

Example: https://travis-ci.org/torchbox/wagtail/jobs/161611317

**Comment by zerolab** [comment]
That is because Travis is set up to use the container infra which does not allow sudo.
https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

So https://github.com/torchbox/wagtail/blob/master/scripts/travis/install_elasticsearch2.sh must be updated to not use sudo

**Comment by kaedroho** [comment]
Should be fixed now. There was a missing ``sudo: true`` in the build matrix
