### ISSUE TITLE
Why does DbWhitelister unilaterally convert <div> to <p>?

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#3054]
While working on an importer to bring the content from my shop's old sites into our new Wagtail-based solution, I discovered a rather disturbing "feature" in the `DbWhitelister` class. The `clean_tag_node()` function forcibly converts all `<div>`s to `<p>`s, with no option whatsoever to avoid this via hook (`construct_whitelister_element_rules` has no effect). The offending lines are as follows:

    if tag.name == 'div':
        tag.name = 'p'

Why does it do this? Would it be possible to add an option to skip that step? This completely breaks some kinds of imported content from our old sites.

I get that your philosophy regarding `RichTextField` is that it's not a full-featured WYSIWYG HTML editor. But as far as I know, there isn't an "`HTMLField`", so I know of no clean way around the extreme restrictions placed upon `RichTextField`.

**Comment by coredumperror** [comment]
After discussing this issue with my colleagues, we realized that this div->p conversion should be impossible to trigger under normal circumstances, anyway. Without the custom Hallo plugin that I'm using to add an "Edit HTML" button to the WYSIWYG, it's impossible for user to input a `<div>` into the RichTextField's content. So those offending lines shouldn't ever trigger, making these existence pretty dubious.

**Comment by gasman** [comment]
Hi @coredumperror,
As I recall, converting from `<div>` to `<p>` was necessary to ensure that text pasted in from outside sources (e.g. Word documents) consistently uses `<p>` tags. Without this, it's impossible to style body text reliably - any CSS rules that apply a particular margin or line height to `p` elements will be ignored if the text is wrapped in a `div` instead.

As of Wagtail 1.6, it ought to be possible to define an HTML editor field that doesn't apply whitelisting, without having to hack Wagtail internals, via the following steps:

* Create a copy (or subclass) of [`HalloRichTextArea`](https://github.com/torchbox/wagtail/blob/f00fe21da2e1c7a0ef6d1225f019437091067124/wagtail/wagtailadmin/rich_text.py#L15) that doesn't call `DbWhitelister.clean` in `value_from_datadict`
* Add a `WAGTAILADMIN_RICH_TEXT_EDITORS` setting to your settings file:

        WAGTAILADMIN_RICH_TEXT_EDITORS = {
            'default': {
                'WIDGET': 'wagtail.wagtailadmin.rich_text.HalloRichTextArea'
            },
            'html': {
                'WIDGET': 'myapp.HtmlArea'
            }
        }

* Define your rich text field as `RichTextField(editor='html')`.

**Comment by coredumperror** [comment]
> As I recall, converting from <div> to <p> was necessary to ensure that text pasted in from outside sources (e.g. Word documents) consistently uses <p> tags.

This seems dubious... Does Word actually create `<div>`s from pasted content? From my (limited) experience with it, Word seems rather obsessed with `<p>`s. Besides, wouldn't it usually be the javascript's job to do this kind of cleanup?

> As of Wagtail 1.6, it ought to be possible to define an HTML editor field that doesn't apply whitelisting

That'd be super cool... if only we weren't stuck on our branch of Wagtail 1.5 that has all the changes I made for multi-tenancy.

**Comment by nmckey** [comment]
Hi gasman - thanks so much for the above solution. 

I was encountering the same problem trying to insert custom <div> tags into a RichTextField.  Would it be worth mentioning this in the whitelisting documentation? I spent quite a while thinking it was something wrong with my implementation of the hook and throwing my time at a red herring. 

It turns out one of my colleagues went through exactly the same thing so it's not just coredumperror and myself.

Happy to contribute some text if this will make things easier. 

White listing docs
http://docs.wagtail.io/en/v1.9/reference/hooks.html#construct-whitelister-element-rules

**Comment by gasman** [comment]
@nmckey I'd rather not have this in the official docs - disabling the whitelister and permitting arbitrary HTML is very much discouraged, and in any case there's a significant rewrite of Wagtail's rich text capabilities coming up soon (which will do a better job of allowing specific custom tags without opening it up to allow absolutely anything).

**Comment by nmckey** [comment]
OK -the solution above was not my preferred method either, however the client had insisted upon it as they had the same functionality in another wagtail site they used. 

I would much rather have allowed divs to be whitelisted - so hopefully that will be implemented in the rewrite. Just thought by adding a note to the documentation that divs are currently excluded from the whitelister might save others some time.

Thanks
