### ISSUE TITLE
Padding in embed_frontend.html

### ISSUE THREAD

**Issue by Gagaro** [torchbox/wagtail#3059]
Hi,

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/templates/wagtailembeds/embed_frontend.html#L1

Why is there a `padding-bottom` in this template? It's causing huge empty zone in my template with youtube videos.

Thanks.

**Comment by jjanssen** [comment]
Seems related to #1495

**Comment by Gagaro** [comment]
Thanks, I missed the doc AND the issue..

I'll continue the conversation there 👍 .
