### ISSUE TITLE
Feature request: make StreamField available in Snippets

### ISSUE THREAD

**Issue by soar** [torchbox/wagtail#3063]
Now Snippets editor allows using only basic Django Fields - `CharField`, `URLField`, etc. But Wagtail has rich set of extended Fields named Blocks - `blocks.RichTextBlock`, `TableBlock` etc. When I made my own Page type - I've done custom `MarkdownBlock` which includes Markdown/HTML editor.

Why don't allow to use this blocks in Snippets editor page? 

Now Snippet definition is very similar to Page definition, for example:

```python
from wagtail.wagtailcore.fields import RichTextField, StreamField

@register_snippet
class LinkSnippet(index.Indexed, models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()

    # This works now:
    description = RichTextField()
    # but this - not:
    description = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
    ])

    panels = [
        FieldPanel('title'),
        FieldPanel('url'),
    ]

    search_fiels = [
        index.SearchField('title', partial_match=True),
    ]

    def __str__(self):
        return "LinkSnippet :: {0!s}".format(self.title)
```

When I try to add StreamField as in example above - I see StreamField-interface, but "+" buttons do nothing. Looks like this will be simple-to-do feature, but ability to use StreamField and custom block types could make Snippets much better.

**Comment by gasman** [comment]
Hi @soar - As far as I know, there are several Wagtail users successfully using StreamFields in snippets with no problems (see for example: https://groups.google.com/d/msg/wagtail/128ysb0XWPg/cL7Dm9GkEgAJ). Did you remember to add `StreamFieldPanel('description')` to the `panels` definition?

**Comment by soar** [comment]
Yes, there are no python errors, I can add StreamField. But there are UI-related bugs, as I described above - "+" button does nothing:

![2016-10-10_00-16-09](https://cloud.githubusercontent.com/assets/30570/19223704/caaab486-8e7e-11e6-8327-3d77f4084903.png)

And in debugger I see errors:

```
TypeError: blockOpts is undefined[Подробнее]  stream.js:87:1
	window.StreamBlock/</sequence<.onInitializeMember http://127.0.0.1:8000/static/wagtailadmin/js/blocks/stream.js:87:1
	postInsertMember http://127.0.0.1:8000/static/wagtailadmin/js/blocks/sequence.js:95:17
	window.Sequence/self.insertMemberAtStart http://127.0.0.1:8000/static/wagtailadmin/js/blocks/sequence.js:196:13
	window.StreamBlock/</<.onChooseBlock http://127.0.0.1:8000/static/wagtailadmin/js/blocks/stream.js:140:21
	StreamBlockMenu/</< http://127.0.0.1:8000/static/wagtailadmin/js/blocks/stream.js:60:41
	jQuery.event.dispatch http://127.0.0.1:8000/static/wagtailadmin/js/vendor/jquery-2.2.1.js:4731:16
	jQuery.event.add/elemData.handle http://127.0.0.1:8000/static/wagtailadmin/js/vendor/jquery-2.2.1.js:4544:6
```

I've trying field definition from my example (which works in Page) and from your example too - still not working.

I have Django 1.10.2 + Wagtail 1.6.3.
Checked with Firefox Developer Edition 51.0a2 (2016-10-08) and Google Chrome 53.0.2785.143.

**Comment by gasman** [comment]
Are you SURE you used `StreamFieldPanel`, not `FieldPanel`?

When I test with the following models.py, everything is working fine:

	from __future__ import absolute_import, unicode_literals

	from django.db import models

	from wagtail.wagtailadmin.edit_handlers import StreamFieldPanel, FieldPanel
	from wagtail.wagtailcore import blocks
	from wagtail.wagtailcore.fields import RichTextField, StreamField
	from wagtail.wagtailimages.blocks import ImageChooserBlock
	from wagtail.wagtailsearch import index
	from wagtail.wagtailsnippets.models import register_snippet


	@register_snippet
	class LinkSnippet(index.Indexed, models.Model):
	    title = models.CharField(max_length=255)
	    url = models.URLField()

	    description = StreamField([
	        ('heading', blocks.CharBlock(classname="full title")),
	        ('paragraph', blocks.RichTextBlock()),
	        ('image', ImageChooserBlock()),
	    ])

	    panels = [
	        FieldPanel('title'),
	        FieldPanel('url'),
	        StreamFieldPanel('description'),
	    ]

	    search_fiels = [
	        index.SearchField('title', partial_match=True),
	    ]

	    def __str__(self):
	        return "LinkSnippet :: {0!s}".format(self.title)

If I change the line `StreamFieldPanel('description'),` to `FieldPanel('description'),` I get the same error that you report above.

**Comment by soar** [comment]
I'm sorry for your time @gasman - this is really my mistake :-(
