### ISSUE TITLE
Preview page using JqueryUI Dialog instead of popup

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#307]
I think it would be more user friendly if the preview popup became a modal window instead of an actual new window/tab.  It would also address the concerns mentioned here: https://github.com/torchbox/wagtail/issues/168

Jquery UI is already used, so it makes sense to go with that.  Opening a dialog instead of a popup when the preview button is clicked should be trivial.

This would provide a clean look, not open a new tab, and should prevent any confusion about whether the content was saved or not since the preview will no longer appear to navigate to a new page.

**Comment by davecranwell** [comment]
We'll continue to consider this as we make ongoing improvements to the interface. However for the time being we don't have plans to investigate this further. We're trying to close tickets which have no obvious or agreed path towards completion, so we'll close this but please feel free to discuss alternative methods on the Google Group
