### ISSUE TITLE
Some Page model attribures are defined elsewhere

### ISSUE THREAD

**Issue by jaap3** [torchbox/wagtail#3078]
Some of the Page model's attributes are defined outside of the Page main definition module. This causes confusing errors that in some cases mask the actual exception.

Yesterday we spent some time debugging a strange `AttributeError` which in the end was caused by a missing `import` statement.

In our case we had `INSTALLED_APPS` set to something like this:

```
INSTALLED_APPS = [
    'mypages',

    'wagtail.wagtailforms',
    'wagtail.wagtailredirects',
    'wagtail.wagtailembeds',
    'wagtail.wagtailsites',
    'wagtail.wagtailusers',
    'wagtail.wagtailsnippets',
    'wagtail.wagtaildocs',
    'wagtail.wagtailimages',
    'wagtail.wagtailsearch',
    'wagtail.wagtailadmin',
    'wagtail.wagtailcore',
]
```

And then in `mypages.models` defined a model using a `FieldPanel`.

```
from django.db import models
from wagtail.wagtailcore.models import Page

class MyPage(Page):
    content_panels = Page.content_panels + [
        FieldPanel('date'),
    ]
```

This code caused a `AttributeError` to be raised, telling us that `Page.content_panels` didn't exists.

After a while we decided to change the order of `INSTALLED_APPS` so the `wagtail` modules came before our custom apps. This revealed the actual error, we forgot to import the `FieldPanel` class from `wagtail.wagtailadmin.edit_handlers`.

From what I've gathered it was a conscious decision to define some of the Page's attributes in `edit_handlers`, but from our perspective it's very confusing to have a different error depending on which order you've listed the wagtail modules in `INSTALLED_APPS`.

One resolution would be to define `content_panels` and other fields in `wagtail.core.models` with sane defaults (e.g. an empty list, None etc.) and then override them in `edit_handlers`.

/cc @ramonakira

**Comment by gasman** [comment]
Hi @jaap3,

Setting an empty `content_panels` / `promote_panels` attribute in wagtailcore.models sounds like a good solution to me. Those attributes don't 'logically' belong in wagtailcore, since they're related to the editor interface which is the responsibility of wagtailadmin - but I think it's acceptable to add them to prevent a misleading error message. A pull request for that would be very welcome!
