### ISSUE TITLE
Uploading PNG causes Willow TypeError

### ISSUE THREAD

**Issue by atelic** [torchbox/wagtail#3105]
### Issue Summary

After uploading a new image, the `/admin/images` page returns a `TypeError: save_as_jpeg() got an unexpected keyword argument 'progressive'`

![screen shot 2016-10-24 at 2 22 24 pm](https://cloud.githubusercontent.com/assets/8905795/19658315/7a099a60-99f5-11e6-8bbc-233436b831f9.png)

[Full traceback here](https://gist.github.com/atelic/ca562a8b351b21db4360564cf6996606)
### Steps to Reproduce

1. Log into the admin site
2. Go to images and click Add an image
3. Upload a new image and click back on the Images panel
4. The error will appear.

I would expect that it would show the list of all images like normal here. When debugging I ran across this:

```
   463
   464                    import ipdb; ipdb.set_trace
-->465                    return willow.save_as_jpeg(output, quality=quality, progressive=True, optimize=True)
   466                elif output_format == 'png':
ipdb> import pydoc
ipdb> print(pydoc.render_doc(willow.save_as_jpeg).splitlines()[2])
save_as_jpeg(f, quality=85) method of willow.plugins.pillow.PillowImage instance
```

It looks like the version of `willow` that is being called does not have the kwargs that this file expects even though I have `0.3.1` installed. 
### Technical details

* Python version: `3.5.2`
* Django version: `1.10.2`
* Wagtail version: `1.7`
* **Willow** version: `0.3.1`
* Browser version: Chrome 53 on OS X 10.12

**Comment by gasman** [comment]
Hi @atelic,
You need to upgrade to Willow 0.4 - Wagtail 1.7 does not support earlier versions of Willow (see https://github.com/torchbox/wagtail/blob/master/setup.py#L33).

**Comment by atelic** [comment]
Thanks, @gasman I missed this. Sorry for the noise
