### ISSUE TITLE
'ListBlock' object has no attribute 'child_blocks'

### ISSUE THREAD

**Issue by AliLozano** [torchbox/wagtail#3122]
Hi,

I'm have a StreamField with a List of unique StreamBlock, I can use `StreamField(['foo', FooBlock()])` but I think it is for multiple type of blocks, I see the other option is `StreamField(ListBlock(FooBlock()))`  that in the form works like I want, but when I'm going to save, it give me this error: `'ListBlock' object has no attribute 'child_blocks'`

I'm doing something bad or its a bug?. 

Thanks a lot.

**Comment by gasman** [comment]
Hi @AliLozano,
StreamField only supports StreamBlock (either explicitly as in `StreamField(StreamBlock(...))` or implicitly via `StreamField([('name', SomeBlock()), ...])`) as the top-level block type. There's an existing proposal to add new field types such as ListBlock here: #2048

**Comment by AliLozano** [comment]
Thanks @gasman
