### ISSUE TITLE
Elasticsearch 5 support

### ISSUE THREAD

**Issue by qwIvan** [torchbox/wagtail#3130]
When I execute `./manage.py update_index --settings=web6c.settings.production`, I was get some Exception.

> The [string] type is removed in 5.0 and automatic upgrade failed because parameters [index_analyzer, boost] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [name]

But I never used elasticsearch.

> Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in ha
ndle
    self.update_backend(backend_name, schema_only=options['schema_only'])
  File "/usr/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 77, in upd
ate_backend
    index.add_model(model)
  File "/usr/lib/python3.5/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 513, in add_model
    index=self.name, doc_type=mapping.get_document_type(), body=mapping.get_mapping()
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 282, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/lib/python3.5/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 124, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'The [string] type is removed in 5.0 and automatic upgrade failed because parameters [index_analyzer, boost] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [name]')

**Comment by danreeves** [comment]
I'm also getting this error, trying to set up a new project with Elasticsearch 5

<details>
with
```
Django==1.10.2
wagtail==1.7
elasticsearch==5.0.0
```
 `wagtail.wagtailsearch.backends.elasticsearch2`

I'm getting

```
$ ./manage.py update_index
Updating backend: default
default: Rebuilding index eta__wagtailcore_page
DELETE /eta__wagtailcore_page [status:404 request:0.251s]
PUT /eta__wagtailcore_page/_mapping/wagtailcore_page_home_homepage?update_all_types=true [status:400 request:0.062s]
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in handle
    self.update_backend(backend_name, schema_only=options['schema_only'])
  File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 77, in update_backend
    index.add_model(model)
  File "/usr/local/lib/python3.4/site-packages/wagtail/wagtailsearch/backends/elasticsearch2.py", line 114, in add_model
    update_all_types=True
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/indices.py", line 283, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'The [string] type is removed in 5.0 and automatic upgrade failed because parameters [boost] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [title]')
```
</details>

**Comment by gasman** [comment]
As per http://docs.wagtail.io/en/v1.7/topics/search/backends.html#wagtailsearch-backends-elasticsearch , only Elasticsearch 1.x and 2.x are currently supported. Will leave this ticket open as a feature request to support later versions.

**Comment by qwIvan** [comment]
through the official demo
https://github.com/torchbox/wagtaildemo

I try to using
`pip install 'elasticsearch==1.2.0'`
and elasticsearch 1.4.4, it's worked.

**Comment by kaedroho** [comment]
Looks like it won't be as difficult to support Elasticsearch 5 as it was to add support for Elasticsearch 2.

Just did a quick experiment to see what we need to change (https://github.com/kaedroho/wagtail/tree/elasticsearch-5), we would need to add a new ``elasticsearch5`` module as the ``fielddata_fields`` and ``text`` changes are not compatible with Elasticsearch 2

**Comment by qwIvan** [comment]
I using
`pip install elasticsearch==5.0.0`
and elasticsearch 2.4.1 is resolved.

**Comment by MechanisM** [comment]
I think that name `elasticsearch` in modules should rely on latest available `elasticsearch` version(currently 5.0, or at least latest supported by wagtail version), and there shouldn't be module names like `elasticsearch5`. It is better to rename old `elasticsearch` to `elasticsearch1` than to have latest one as `elasticsearch5`(unless there is bigger version number in current stable version). Everything can be described in docs. It is normal practice out there, that all installs rely on latest available stable version. If needed older one - then need to come with specific actions like adding version numbers etc, but by default module name `elasticsearch` should return latest stable one...

**Comment by kaedroho** [comment]
> I think that name elasticsearch in modules should rely on latest available elasticsearch version(currently 5.0, or at least latest supported by wagtail version)

I disagree with this, new major Elasticsearch versions are not compatible with previous ones. If somebody was to update Wagtail, they will need to update their Elasticsearch server at the exact same time of their search will break.

With pip, you do not usually just let it install the latest version of each package. You will normally pin the dependency to a specific version in requirements.txt, so you know they are compatible with your project. The naming scheme here is a similar idea to that, it lets you specify the version of Elasticsearch you have installed, and Wagtail won't try to guess it for you.

I know that the module names are inconsistent. I would be in favour of adding an ``elasticsearch1`` module to improve that. But I'm against making a module that supports a different version of Elasticsearch depending on what version of Wagtail you're using.

**Comment by MechanisM** [comment]
> I think apt does something similar to this. There are many packages with the major version number at the end python3 for example.

Yeah, `apt` offers also adding info which packages are conflicting, and which packages can be replaced("offer functionality of".. like `nginx` can kinda replace `apache2`)

As for `python3` - I meant that when I entering `apt install python3` - it doesn't tries to offer me `python3.2` or `python3.4` it installs me latest available from python3 - 3.5+
And currently if I'm adding `elasticsearch` backend to `wagtail`, it means not latest one, it refers to 1st one.

About `elasticsearch` module name again, I didn't meant to make this module to support all `elasticsearch` versions, I just meant that module name `elasticsearch` should refer to lastet supported by `wagtail` version of `elasticsearch`.
If people are new to wagtail and starting from scratch - they just add `elasticsearch`(not *1 not *2 not even *5)
If people updating their old `wagtail` installation - they always should read update manuals, changelog, how to migrate to new version etc. If they need specific `elasticsearch` only then they adding version numbers like `elasticsearch1` or *2 *5
If ppl are not so quick enough or too much lazy to migrate to newer `elascticsearch`'s version, then they should use numbers and downgrade from `elasticsearch` to *1, but name `elastcisearch` should follow latest available version of `elasticsearch`.
Ok, np it's just my opinion.

**Comment by kaedroho** [comment]
> As for python3 - I meant that when I entering apt install python3 - it doesn't tries to offer me python3.2 or python3.4 it installs me latest available from python3 - 3.5+

You're confusing major and minor versions here. Just like ``apt``, Wagtail suffixes the names with the *major* version. But that includes all *minor* versions as well. So the ``elasticsearch2`` backend supports Elasticsearch 2.4 (the latest minor version).

> And currently if I'm adding elasticsearch backend to wagtail, it means not latest one, it refers to 1st one.

The backend you need to use is documented here: http://docs.wagtail.io/en/v1.7/topics/search/backends.html#elasticsearch-backend

Unless they are guessing, the developer probably had to refer to this document and will know what backend name they need.

> If people updating their old wagtail installation - they always should read update manuals, changelog, how to migrate to new version etc.

Of course, but that doesn't mean we should take breaking backwards compatibility lightly though. Wagtail should be as easy as possible to update 

> If they need specific elasticsearch only then they adding version numbers

All of the major versions of Elasticsearch so far are incompatible with each other so developers would *always* need to define which major version they need.

**Comment by eyjolfur12** [comment]
If you follow the documentation there (http://docs.wagtail.io/en/v1.7/topics/search/backends.html#elasticsearch-backend),  pip will install elasticserach.py 5.0.1 and your search will break with an error : "search() got an unexpected keyword argument 'fields'". Should be pointed to specific version.

**Comment by SalahAdDin** [comment]
Here you can fine some about upgrade: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup-upgrade.html

And i ask, elastic search pypi package supports all versions or only support the latest elasticsearch version?

**Comment by kaedroho** [comment]
Thanks @SalahAdDin 

> And i ask, elastic search pypi package supports all versions or only support the latest elasticsearch version?

The pypi package has three major versions, each of which supports one version of Elasticsearch.

There's a list of which package versions to use against which Elasticsearch version here: http://elasticsearch-py.readthedocs.io/en/master/#compatibility

**Comment by gasman** [comment]
Have now documented the fact that a matching version of the elasticsearch library needs to be used, in 59e9a31bc1d19b06ee1c94e192bf6875a1f4d699 (master) and f7d9ccf54bb91ae114fcc009947cf0570f34234f (1.7.x).
