### ISSUE TITLE
RichText whitelisting of element attributes does not work for <a> tag

### ISSUE THREAD

**Issue by mevinbabuc** [torchbox/wagtail#3140]
### Issue Summary

RichText whitelisting of attributes of anchor tag does not work. It still strips of class or style attributes from the a tag. This prevents me from controlling the look of the anchor tag or prevents me from adding my own custom data attributes. I believe this is happening because the `PageLinkHandler` reconstructs the `a` tag by looking at the id and does not add other custom attributes that are added from the richtext editor by a custom plugin.

```
@hooks.register('construct_whitelister_element_rules')
def whitelister_element_rules():
    return {
        'a': attribute_rule({
            'style': True,
            'href': check_url,
            'class': True,
            'target': True
        }),
   }
```

### Technical details

* python 3.4
* Django version: 1.8.15
* Wagtail version: 1.6.2

**Comment by gasman** [comment]
Hi @mevinbabuc - this is covered by #897.
