### ISSUE TITLE
DocumentChooserPanel broken in 1.7

### ISSUE THREAD

**Issue by shacker** [torchbox/wagtail#3151]
I implemented DocumentChooserPanel precisely as shown in the [docs](http://docs.wagtail.io/en/v1.7/reference/pages/panels.html). The field shows up in the admin, allows me to select a file to upload, but I get a 500 error in console when I click Upload. 

`[09/Nov/2016 17:30:45] "GET /admin/documents/chooser/ HTTP/1.1" 500 256097`

If I access that URL in a browser I see:

```
NoReverseMatch at /admin/documents/chooser/
Reverse for 'wagtaildocs_serve' with arguments '(1, 'test.pdf')' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

Stack trace shows the crash on line 65 at:

```
.../virtualenvs/portal/lib/python3.5/site-packages/wagtail/wagtaildocs/models.py in url
        return reverse('wagtaildocs_serve', args=[self.id, self.filename]) 
```

**Comment by gasman** [comment]
Hi @shacker,

Assuming this is a project where you're integrating Wagtail into an existing Django codebase, rather than starting from scratch with `wagtail start` - have you set up urls.py as described in http://docs.wagtail.io/en/v1.7/getting_started/integrating_into_django.html#url-configuration?

**Comment by shacker** [comment]
You're right @gasman  - I had left documents out of my URL config, not initially thinking I'd be needing it. Since similar examples on [Available Panel Types](http://docs.wagtail.io/en/v1.7/reference/pages/panels.html) don't require additional URL configs, I thought I had encountered a bug. Might be worth a mention on that documentation page. Thanks.

**Comment by gasman** [comment]
Glad you got it sorted!

I don't think adding a note in the docs at that point would be very effective, to be honest. The missing urlconf line is just as likely to affect _any_ interaction with the documents module, and the fact that it surfaced while you were setting up panels is fairly arbitrary - it's vanishingly unlikely that any other user will encounter that specific configuration error in that same context. If we tried to anticipate every similar circumstance where something could go wrong, we wouldn't have room in the docs for anything else :-)
