### ISSUE TITLE
Images are not show when uploaded from Rich text editor

### ISSUE THREAD

**Issue by cheluis** [torchbox/wagtail#3152]
I am using version 1.6 and after uploading an image on the page body, using the image button, and try to check it on the published page I got nothing, the rendered tag is a embed tag:
`<embed id="1" alt="Algo" embedtype="image" format="fullwidth">`

What am I missing here, for editor or page to convert this to an image tag or to render the desired image?

**Comment by gasman** [comment]
Hi @cheluis - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

(You're probably missing the `|richtext` filter on your template: http://docs.wagtail.io/en/v1.7/topics/writing_templates.html#rich-text-filter)
