### ISSUE TITLE
Add a StreamField block type that just 'exists' and has no fields

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#3153]
As requested here <https://groups.google.com/d/msg/wagtail/bC0me-nRxck/5O6t-JgWBAAJ>, it would be useful to have a built-in block type that has no input fields and a stored value of `None`, but just exists as a marker to insert a particular bit of static content at that point in the stream. I suggest the name `StaticBlock`.

Assuming Benoît's implementation from that thread works as described (and he's happy for it to be included in core...), this just needs tests and docs.

**Comment by gasman** [comment]
Implemented in #3154

**Comment by timorieber** [comment]
I think this should be added to milestone 1.8 or isn't this relevant after closing?

**Comment by gasman** [comment]
@timorieber It's not really relevant, no. The milestones exist mainly as a way for the core team to prioritise work and ensure that we don't overlook any "must-have" issues for a particular release - it's fine (and expected) for outside contributions to be handled outside of that process.
