### ISSUE TITLE
Elasticsearch: Mapping definition for [title] has unsupported parameters

### ISSUE THREAD

**Issue by pirm-in** [torchbox/wagtail#3171]
On fresh and clean wagtail instance (following the [official docs](http://docs.wagtail.io/en/v1.7/getting_started/)) I wanted to add elasticsearch (also following the [wagtail docs](http://docs.wagtail.io/en/v1.7/advanced_topics/performance.html#search)). 

Running `./manage.py update_index` gives me 

> File "/yada/project/venv/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'Mapping definition for [title] has unsupported parameters:  [index_analyzer : edgengram_analyzer]')

Elasticsearch logs the following

> [2016-11-22 17:04:22,316][INFO ][cluster.metadata         ] [Freakmaster] [demo_wagtail_2] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2016-11-22 17:04:22,611][DEBUG][action.admin.indices.mapping.put] [Freakmaster] failed to put mappings on indices [[demo_wagtail_2]], type [wagtailcore_page_home_homepage]

### Technical details

* Wagtail version: 1.7 (also tried 1.6.3)
* Elasticsearch: 2.4 (also tried 2.3)

**Comment by kaedroho** [comment]
What do you have set as the ``BACKEND`` in ``WAGTAILSEARCH_BACKENDS`` (should be: ``elasticsearch2``).

What version of the elasticsearch python library do you have installed?

**Comment by pirm-in** [comment]
wow, that was quick.. `WAGTAILSEARCH_BACKENDS` is `wagtail.wagtailsearch.backends.elasticsearch2`

You were right about the elasticsearch python library, pip installed the v5 client. After installing v.2.4 it still won't work.. the error has changed slightly though

> TransportError(400, 'mapper_parsing_exception', 'Mapping definition for [_partials] has unsupported parameters:  [index_analyzer : edgengram_analyzer]')

**Comment by gasman** [comment]
Thanks for confirming!
