### ISSUE TITLE
RichTextField usage in snippets

### ISSUE THREAD

**Issue by ddfs** [torchbox/wagtail#3176]
adding a rich textfield  in snippets is not working.

only models.* (TextField etc) allowed to. rawhtml, richtext etc fields etc cannot be implemented within.

**Comment by gasman** [comment]
Hi @ddfs,

There's  not enough detail here to investigate this, sorry. Many Wagtail users are successfully using rich text fields in snippets. If you believe you've found a bug in Wagtail, please open a new issue giving full details of how to reproduce the bug, paying attention to the sections marked "Please fill out the sections below."

If you need assistance in getting your code to work, please send a message to the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) showing the section of code that's failing, and any error messages you receive.
