### ISSUE TITLE
Allow passing a callable to image tag for dynamic resize calculation

### ISSUE THREAD

**Issue by mr-bo-jangles** [torchbox/wagtail#3187]
### Issue Summary

`{% image %}` doesn't allow passing a callable for the filter. 

### Steps to Reproduce

I'm trying to build generic blocks, with customisable widths and trying to get the images to match automagically using the following

```
    def get_image_one_dimentions(self):
        return "fill-{width}x{height}-c50".format(width=1920/self.image_link_one_width, height=358)
```

I expected to be able to pass a callable to the image filter like:

```
{% image value.image_link_one_image value.get_image_one_dimentions as image_link_one_image %}
```

### Technical details

* Python version: 3.5.2
* Django version: 1.8.15
* Wagtail version: 1.7
* Browser version: All

**Comment by gasman** [comment]
Thanks for the report @mr-bo-jangles! I believe this is covered by the existing ticket #2090 - the process of getting the `{% image %}` tag to accept a non-constant parameter will be the same whether that parameter comes from a callable or an ordinary variable.
