### ISSUE TITLE
'str' object is not callable when trying to copy page with children

### ISSUE THREAD

**Issue by burritobill** [torchbox/wagtail#3195]
### Issue Summary

I am trying to copy an entire tree structure across for a multilingual site.
When trying to copy the home page with all the sub pages across I am getting this error.
I have this sort of structure
Home > Project Archive > Project
It will fail on the first Project.

![capture](https://cloud.githubusercontent.com/assets/2685027/20876912/591d3380-bb19-11e6-97f1-f46a79ad9a2f.JPG)

I can copy the projects across one by one at this point, anyone have any ideas?

### Technical details

* Python version: 3.4.3.
* Django version: 1.10.2
* Wagtail version: 1.7

**Comment by gasman** [comment]
Hi @burritobill,
Do any of your page models have a field or property with the name `copy`? That's the only thing I can immediately see which would cause this error.

(If you expand the 'Local vars' at the bottom, you'll be able to see which specific page is producing the error, which might give more clues...)

**Comment by burritobill** [comment]
Yep that will be it, I tend to call my richtextfields copy. I'll stop doing that.
Thanks so much that was dumb of me.
