### ISSUE TITLE
A few dependencies did not install on clone and setup

### ISSUE THREAD

**Issue by MattRijk** [torchbox/wagtail#3202]
### Issue:
Did not install babel, imagesize, lxml and jinja2 

### Steps to Reproduce
On Ubuntu
1. git clone https://github.com/torchbox/wagtail.git
2. cd wagtail
3. pip install -e .[testing,docs] -U

Manually installing solved the problem and the test suite ran without any problems
sudo pip install babel
sudo pip install imagesize
sudo pip install lxml
sudo pip install jinja2

### Technical details

* Wagtail: 1.7
* Python version: 2.7.6.
* Django version: Django==1.10.4
* Ubuntu 14.04.3 LTS

**Comment by gasman** [comment]
Hi @MattRijk - thanks for the report. Have just tried this out on a clean Ubuntu VM, and it looks like the `sphinxcontrib-spelling` dependency has problems when being installed simultaneously with the other packages - it seems to require babel and docutils during the installation (which haven't been installed at that point). This causes the `pip install` step to abort without completing installation of the remaining packages. I'll see if we can work around this by adding babel/docutils to Wagtail's own dependencies...

**Comment by MattRijk** [comment]
I have a solution to the sphinxcontrib-spelling dependency issue. Do I need permissions to do a pull request.

**Comment by gasman** [comment]
Fixed in #3207
