### ISSUE TITLE
More Dropdown don't work (1.8rc1)

### ISSUE THREAD

**Issue by Vorlif** [torchbox/wagtail#3208]
### Issue Summary

The action buttons from the 'more'-drop-down-menu in page explorer dont work.

### Steps to Reproduce

1. Create and activate a new virtualenv
2. pip install wagtail==1.8rc1
3. wagtail start project
4. python manage.py migrate / -createsuperuser / -runserver
5. Open your browser and clear/disable the cache
6. Go to the admin interface and try to use the 'more' button

![peek 2016-12-08 09-00](https://cloud.githubusercontent.com/assets/4333770/21002448/30b2a0ce-bd26-11e6-9589-4dbc2b39accd.gif)

If I downgrade to wagtail==1.7 the buttons work.

There are no exceptions from django or in the chrome javascript console.

### Technical details

* Python version: 3.5.2
* Django version: 1.10.4.
* Wagtail version: 1.8rc1
* Browser version: Google Chrome  55.0.2883.75 (64-bit) and Firefox 50.0.2

### Others

Thank you for the great software.

**Comment by gasman** [comment]
Confirmed on Chrome 54.0.2840.98. Oops!
