### ISSUE TITLE
Automatically generate robots.txt file

### ISSUE THREAD

**Issue by helenb** [torchbox/wagtail#324]
It would be good if wagtail could automatically generate this file, by default disallowing the following:

- /admin/
- /django-admin/
- any sections protected by the front end permissions feature

Potentially there could also be a means for this to be overridden by a developer if they wished to add their own sections, but that would require some consideration if it were dynamically updated according to which sections were protected by front end permissions. I believe there's a Drupal module which allows the user to add their own paths to a default list so potentially something like this could be done for wagtail.

**Comment by davecranwell** [comment]
Response in the interest of closing this:

The "noindex" / "nofollow" meta tag could be added to individual pages protected by FEP, which considerably reduces the need to automatic generate one.

I'd suggest this issue be re-raised in the wagtail-template repo to suggest the addition of a robots.txt there. It would only exclude `admin` and `django-admin` but it's worth adding - just not in the wagtail core repo.
