### ISSUE TITLE
Fields added to the model but not allocated to a panel appear outside the tab interface

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#338]
When fields are added to the model but not allocated to a panel (e.g not added to `BlogPage.content_panels`), they're displayed without label or js enhancement at the bottom of the page outside the tabbed interface. It's an ugliness I'd like to be tackled if possible. 

Perhaps the new field(s) should appear in the first tab, "Content", or they shouldn't appear at all and perhaps display a warning.

**Comment by gasman** [comment]
https://github.com/gasman/wagtail/tree/fix/stray-form-fields-2 now passes against the improved test suite in #933 - there's still a latent references to `rendered_fields` in the InlinePanel tests, though, so this should wait until that test has been updated too.
