### ISSUE TITLE
Add functionality for 'singleton snippets' (aka Settings)

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#368]
Sites often have user-editable content, like site title, tag line, contact details, etc. These should be accessible from the admin, should not be pages, and should only ever allow one instance of themselves (multiple site titles does not make sense!)

This sounds much like snippets, except for the single instance restriction, hence the 'singleton snippets'. Whether this is implemented using snippets is another matter entirely.

I can think of multiple ways this functionality could be implemented, each with their own pros and cons:

1. Extend snippets to allow singletons. This area of the admin already exists, and can be used for this kind of 'global' content that is not tied to a page. However, snippets would have to be modified to have a 'singleton' option, as well as some (potentially confusing and inconsistent) UI changes to handle this.

2. Add a new section to the admin for 'site-wide settings', or something of the sort. Allow models to register themselves to the settings section, much like snippets. The UI (and possibly some model options) would enforce the singleton aspect. Other wagtail plugins can then register themselves to this system as well.

3. Other approaches?

Personally, I prefer approach number 2. If the devs think this is a worthy feature, and a consensus on how to implement can be reached, I will develop it.

**Comment by chrxr** [comment]
In our weekly meeting we've agreed to reference @timheap's ``wagtailsettings`` module in our docs.

**Comment by timheap** [comment]
Haha, seeing that it is now officially endorsed or some such, I suppose I better polish it up!

I've just released 0.3.2, which fixes some issues in the README/docs, and adds tests. There are no functionality changes. Also note that as of version 0.3.0, `wagtailsettings` does not support Wagtail 0.8 or below, due to backwards incompatible changes in the internal Wagtail EditHandler API `wagtailsettings` uses.

The latest version can be found at https://pypi.python.org/pypi/wagtailsettings/

**Comment by timheap** [comment]
Also I am happy for this to be closed if you are not planning on adding a settings module to core. The `wagtailsettings` module covers all the functionality I wanted.

**Comment by timheap** [comment]
Closing in favour of [wagtailsettings](https://pypi.python.org/pypi/wagtailsettings/)

**Comment by denisvlr** [comment]
wagtailsettings hasn't been maintained and doesn't work with Django 1.9.
What is today the recommended solution to handle site-wide content such as a title, footer, etc?

To be very specific, i'm trying to build a fully configurable footer with multiple text fields, links, etc. A snippet looked like a nice solution, except it cannot be defined as a singleton.

**Comment by gasman** [comment]
Hi @denisvlr - wagtailsettings is now a contrib module within Wagtail itself: http://docs.wagtail.io/en/v1.6/reference/contrib/settings.html

(Please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries)
