### ISSUE TITLE
Choose a better name for 'Snippet'

### ISSUE THREAD

**Issue by tomdyson** [torchbox/wagtail#376]
Following comments from @sixpearls and @jeffrey-hearn, and initial discussion on #368, we're seeking a less confusing name than 'snippet'. What we mean by snippet is defined fairly clearly here:

http://wagtail.readthedocs.org/en/latest/snippets.html

Suggestions so far include 'leaf', 'feather' and 'attachment'.

**Comment by davecranwell** [comment]
May I suggest we close this and continue discussion on the Google Group? From what I can see we're still far from condensing thoughts sufficiently that this ticket could ever be closed.

**Comment by mhnbcu** [comment]
"Element" might be conceptually sensible for developers and users as a reusable part of something.

An element can be a composition of other elements or independent.

**Comment by pymarco** [comment]
Another possibility is to call a single snippet a `card`, and a group of snippets a `deck`. This would be a similar use case to the terminology chosen for the new [Bootstrap 4](http://v4-alpha.getbootstrap.com/components/card/)

**Comment by gasman** [comment]
A year on, the name 'snippet' is sufficiently well-established that, realistically, we're not going to change it now. What's more likely is that we'll phase out the use of snippets once our use of class-based views and ModelAdmins (#858) has matured to the point where that can replace the functionality of snippets.
