### ISSUE TITLE
Add Wagtail Tutorial to docs

### ISSUE THREAD

**Issue by chrxr** [torchbox/wagtail#394]
Tutorial to create a demo project from scratch, "Creating your first Wagtail site". 

Some of the topics below are already included in the docs, but would be helpful to many in the context of a specific project tutorial.

Initial topics to include:

- [ ] Downloading Wagtail template
- [ ] Creating first models
- [ ] Best practice for app management/maintenance
- [ ] Basic templating
  - [ ] Use of self.
  - [ ] Images manipulation
  - [ ] Custom tags
- [ ] Migrations using South
- [ ] Running locally
- [ ] Wagtail settings
- [ ] Deploying to servers

**Comment by SalahAdDin** [comment]
Hi, how can i help with documentation?

**Comment by zerolab** [comment]
A first pass can be found at https://gist.github.com/zerolab/39cb1abea01414f7cf31

Should we add it to docs or publish it as a blog post and reference it from the docs?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kaedroho** [comment]
Great work! :+1:

I think the docs need a good tutorial for beginners. So +1 for adding this to the getting started docs from me!

I did a couple of workshops last year and one thing I found from that is people get confused when you show them how to write a page model before they know what a page model actually is. Maybe we could create a separate "Overview" page that gives an introduction basic concepts of Wagtail (and obviously be written with as few words as possible) which they could flick through before staring the tutorial? Something like: https://docs.djangoproject.com/en/1.8/intro/overview/

**Comment by zerolab** [comment]
Thank you @SalahAdDin and @kaedroho.
Got a bit more feedback from @tomdyson to incorporate, then will submit a PR.

I like the Overview idea. Let's move it to a separate issue/PR, though. It should probaly include an example of a page model, `content_panels`, links to the advanced topics and certainly a link to the Django overview since 90% are Django concepts.
