### ISSUE TITLE
Pages implementing wagtailforms should contain a link to the results of that form and the number of submissions

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#406]
As a user interested in the submissions of a form I've created, I'd like to have a quick link between the page editor interface and the form submissions list for the form in question.

**Comment by dirtycoder** [comment]
I'm going to take a look at this.
At this point I'm only concerned about a good way to check if the current `page` in the `edit.html` is a form.
I'm thinking about checking if it subclass `AbstractForm`.
I could probably add something like a `is_form` method to the model, but maybe it's just better to check for it in the `edit view` and pass it to the template inside the context.

**Comment by gasman** [comment]
Hi @dirtycoder - thanks for taking this on!

Something to keep in mind - we want to avoid wagtailadmin having any direct knowledge of the wagtailforms module, or any other special-purpose page types. The wagtailforms app is not really a "core" part of Wagtail - it's more of an add-on, with a similar status to a package like [wagtailpolls](https://github.com/takeflight/wagtailpolls), built on top of the general-purpose framework provided by wagtailcore / wagtailadmin. (We would have called it `wagtail.contrib.forms`, but it was built before we came up with the idea of `wagtail.contrib` packages...) Just as we wouldn't give wagtailpolls special-case treatment within wagtailadmin (e.g. writing `if page.is_poll():` code blocks), we shouldn't give wagtailforms any special treatment either.

It _might_ be possible to implement this without any changes to wagtailadmin, by defining a new type of edit hander to go in AbstractForm's content_panels (normally edit handlers like FieldPanel would serve as containers for form fields, but there's nothing to stop them from being used for other things, like simply displaying a link):

    class AbstractForm(Page):
        ...
        content_panels = [
            FormResponsesPanel(),
        ] + Page.content_panels

If that doesn't work out, then there's no problem with extending wagtailadmin with new functionality - but it would have to be a general-purpose API that can be used by other third-party apps, not just something that exists for wagtailforms's benefit. For example, we could introduce the idea of customisable headers/footers that can be defined by any Page model:

    class AbstractForm(Page):
        ...
        def edit_form_header_block(self):
            return mark_safe("<p>this is my custom header</p>")

and then outputting `{{ page.edit_form_header_block }}` in the wagtailadmin view. This isn't necessarily the best design - just an example of how it could be done. (Maybe Django admin has some clever tricks with template block overriding that we could steal...)

**Comment by dirtycoder** [comment]
Exactly! That was my main concern about the approach to choose.
After a quick look in the code I also believe that using a new edit handler should do the trick, thanks for pointing this out.

**Comment by dirtycoder** [comment]
@gasman just some update here, in fact as you told it is possible to have it using an EditHandler.
I have a working example, the code needs more work though.
I'm using a very crude UI just for testing but I would appreciate some suggestions about how to lay the UI, obviously my design skills are pretty much zero.

@davecranwell as you originally opened the issue, do you have something in mind?

![captura de tela de 2016-05-01 10-10-44](https://cloud.githubusercontent.com/assets/1988429/14941960/210b1236-0f85-11e6-91e6-7478a89a1fb8.png)
