### ISSUE TITLE
Allow password resets to be disabled independently

### ISSUE THREAD

**Issue by ninepints** [torchbox/wagtail#467]
Right now, settings.WAGTAIL_PASSWORD_MANAGEMENT_ENABLED controls the availability of both the Wagtail password change page and the password reset flow. Someone might want to disable password resets while keeping the password change page, so I propose adding another setting (WAGTAIL_PASSWORD_RESET_ENABLED?) to provide more flexibility.

On a related note, setting WAGTAIL_PASSWORD_MANAGEMENT_ENABLED to False doesn't actually disable the relevant views, just removes the links to them.

**Comment by mic159** [comment]
Is this possible now?

**Comment by ninepints** [comment]
Yup. WAGTAIL_PASSWORD_MANAGEMENT_ENABLED and WAGTAIL_PASSWORD_RESET_ENABLED can be set independently, and the latter defaults to the value of the former.
