### ISSUE TITLE
Warn users before navigating away from a page (or any form?) with unsaved changes

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#475]
Doing it by accident is incredibly frustrating because any additions or rearrangements to inlinepanels aren't reflected in even chrome's cleverly cached history.

**Comment by davecranwell** [comment]
Streamfield has made this problem even more acute when editing large blocks of Stream content. The richness of copy possible with streamfield seems to somehow intensify the feeling of loss when you forget to save :P

**Comment by kaedroho** [comment]
I guess that streamfield is implemented as a chunk of HTML that gets rendered on the server-site and manipulated by jQuery. The way fields are dynamically added and removed probably upsets Chromes clever caching

I'd argue that this is a really good use-case for React.

We could send the streamfield data down to the client in JSON form in a hidden field and use React to render the tree of DOM nodes (each block type can map to a react component). When the streamfield gets altered, we can update that hidden field as well as the DOM representation. Hopefully, going forwards and backwards, Chrome will keep that hidden field cached so people don't lose their data.

**Comment by davecranwell** [comment]
That would certainly be nice yeah. @ollywillans was asking if we're able to revisit the auto-saving discussion, which is another solution. Perhaps one for the wagtail-dev list rather than here.

**Comment by ollywillans** [comment]
This sounds like a good solution though.

**Comment by Sheepzez** [comment]
I'd like to re-iterate the importance of this issue. I've only been using Wagtail a week or so, but I've already had a couple incidents in which I've lost posts by accidental pressing of the backspace key when I'm not focussed on an input.

**Comment by zerolab** [comment]
This will be fixed by #2160

**Comment by gasman** [comment]
Fixed by #2160.

**Comment by Sheepzez** [comment]
What's the release schedule like for moving versions to pip? How long will it be before recent fixes like these end up in the latest pip package?

**Comment by davecranwell** [comment]
@Sheepzez We're currently aiming to release 1.4 at the end of February but an exact date isn't known yet. A release candidate will be made available for a week on or before the end of the month, available via pip. The proper version will then be launched after the RC phase ends, assuming serious problems aren't discovered.
