### ISSUE TITLE
Ubuntu Versions

### ISSUE THREAD

**Issue by mjdavies** [torchbox/wagtail#480]
Morning all

I'm building a production server for a wagtail application.  It's easier all round for us if the development machine that we install via vagrant on our local machines, is the same as the production server.

I'm starting to build the server now and noticed this at the top of the screen when I logged in.

"Your current Hardware Enablement Stack (HWE) is going out of support
on 08/07/14.  After this date security updates for critical parts (kernel
and graphics stack) of your system will no longer be available."

I'm using the same version that your using in the wagtaildemo system.

ubuntu12.04LTS 32 bit 
config.vm.box_url = "http://downloads.torchbox.com/wagtail-base-v0.1.box"

So, I can't use that in production.

I've tried using ubuntu14.04LTS in Development, but the python modules you need to run wagtaildemo on that version of ubuntu don't all load, and we went through a process of adding them into our requirements.txt, but it seemed to be a never ending process so in the end we gave up, and went back to the proscribed ubuntu12 version.

Is there any chance you could create a vm.box_url using Ubuntu14LTS 64 bit so we can use that in development, and in production?

I'm happy to assist in any way if I can.

If there already is one and I'm being a doughnut sincere apologies.

**Comment by kaedroho** [comment]
We've updated the Wagtail base box to Ubuntu 14.04 32 bit.

Closing ticket as this looks like a support query (these have been moved to the Google group)
