### ISSUE TITLE
Documented list of all Wagtail's core apps and their purpose.

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#484]
As we add more features there are likely to be more that might not be suitable to be enabled by default in [wagtail-template](https://github.com/torchbox/wagtail/pull/456) or wagtaildemo. These might get forgotten or left undiscovered unless documented somewhere.

The documentation should be updated to list the official wagtail apps, and explain their purpose. Ideally this would be written in a non-technical way that would also form a convenient feature list for non-technical people to refer to when evaluating what wagtail offers.

**Comment by zerolab** [comment]
Discussed in documentation sprint. Closing as this is addressed in a different way in the other ways.
