### ISSUE TITLE
Hide tabs that are not used. e.g. content_panel = []

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#485]
Right now, FooPage.content_panels = [] results in an empty content tab that is selected by default.

It would be better if the empty tabs were hidden from view.  In this case the promote_panel should be shown by default and the link for the content panel should be hidden.

This is useful for pages that are automatically generated from other models and only allow users to edit information on the promote_panel

**Comment by gasman** [comment]
Dealing with this as part of #210.
