### ISSUE TITLE
Recommended method for changing runtests.py configuration?

### ISSUE THREAD

**Issue by btipling** [torchbox/wagtail#49]
wagtaildemo has a local.py mechanism for changing the db auth info and other settings but what is the recommended mechanism for doing the same with running tests for wagtail? Making a copy of runtests.py and then changing the values in the copy?

**Comment by kaedroho** [comment]
Things like database/elasticsearch location can be configured with environment variables:
 - ``DATABASE_ENGINE``
 - ``DATABASE_NAME``
 - ``DATABASE_USER``
 - ``DATABASE_PASS``
 - ``DATABASE_HOST``
 - ``ELASTICSEARCH_URL``

If you need any other local settings to run the tests, these should probably be in the ``settings.py`` file anyway.
