### ISSUE TITLE
Support for tel and other link types in external link form

### ISSUE THREAD

**Issue by nathan3d** [torchbox/wagtail#490]
It would be nice if the UI for adding links allowed for non http/ftp links to be added. Currently you get a validation error when trying to add tel/maps/etc...

**Comment by gasman** [comment]
Closing as per https://github.com/torchbox/wagtail/issues/490#issuecomment-53415721 - I don't think there's a legitimate use for these link types within rich text. Special-purpose pages that use them, such as contact pages, should build them into their data model / template instead.
