### ISSUE TITLE
snippet number handling

### ISSUE THREAD

**Issue by janrito** [torchbox/wagtail#499]
Both the listing of a snippet and the snippet chooser modal display all snippets of a given type at once. This behaviour is ok as long as there are only a few. Once the list gets bigger, it's completely unmanageable. There needs to be a method for sorting, searching, and/or browsing through them. 

Pagination would be a start, ideally search (#129). 

Custom choosers could solve half of the problem (eagerly awaiting docs).

**Comment by gasman** [comment]
Pagination added in #1003, search added in #1610.
