### ISSUE TITLE
Improve query parameter support in pagination include

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#507]
The pagination include is used throughout wagtail for both ajax and standard page requests. 

In non-ajax mode it supports being passed a URL (without query params), a string corresponding to a wildcard search term (confusingly called "query_string") and an "ordering" value.

This means any additional query parameters aren't supported. The pagination include should be updated to support any params, appending the necessary `p` (for 'page') after.

Furthermore the ajax version of the pagination doesn't support any parameters. The page chooser modal is currently unpaginated, so for some clients it will attempt to display several thousand pages at once. I tried to update the modal so it was paginated but discovered it didn't support the query params necessary to pass through the `page_type` param, used to limit which kinds of page the user is allowed to choose. As a result pagination would be possible, but beyond the first page of results, the `page_type` restriction would get removed.

**Comment by gasman** [comment]
Having just added pagination to a view that was missing it (#1849), I can confirm that @timheap's pagination helpers from #1496 handle query parameters wonderfully :-)
