### ISSUE TITLE
Paginate chooser modal page listings like standard page listing

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#508]
The standard explorer listing is paginated at 50 items to prevent particularly huge sections of the tree (e.g where a bulk import has taken place) from trying to render X-thousand results on one page.

The page chooser modal however is not paginated, but adding pagination is limited by what the pagination include can do (See https://github.com/torchbox/wagtail/issues/507) as it can't support the `page_type` query parameter.

**Comment by chrxr** [comment]
A client site currently has 1916 pages under a particular section. It's taking a very long time to load. It would be good if we could address this in the near future.

**Comment by kaedroho** [comment]
A client site currently has over 100000 pages under a particular section and the page chooser doesn't load at all.
