### ISSUE TITLE
Elasticsearch uses 'or' to build queries

### ISSUE THREAD

**Issue by timheap** [torchbox/wagtail#526]
The Elasticsearch search backend behaves in an unexpected manner when searching for multiple words, and behaves very differently than the database backend. I created three Pages with the title 'Foo', 'Bar', and 'Foo Bar'. Searching using the two backends gave different sets of pages:

Search term | Database | Elasticsearch
----------------|--------------|------------------
Foo | 'Foo' 'Foo Bar' | 'Foo' 'Foo Bar'
Bar | 'Bar' 'Foo Bar' | 'Bar' 'Foo Bar'
Foo Bar | 'Foo Bar' | 'Foo' 'Bar' 'Foo Bar'

When searching for two words: the database backend provided the expected results, with the search becoming more precise; while the elasticsearch backend provided unexpected results, becoming less precise.

**Comment by kaedroho** [comment]
I'm not sure it's going to be possible/easy to make the database backend behave like the Elasticsearch backend in every way. I like the way Elasticsearch gives all results that are considered "relevant" with the most relevant ones at the top. Shall we close this?

**Comment by timheap** [comment]
Yeah, now that I understand elastic search more I realise that this is actually the correct behavior, even if it is different to the database backend

**Comment by kaedroho** [comment]
Bringing this back up as I hope to make a couple of changes:
 - Allow the operator to be configured on the search query (eg: ``.search("Foo bar", operator="and")`` will require both terms to be in the result)
 - Change the default operator of the database backend to "or" to match the behaviour of the Elasticsearch backend

RFC (in the form of a PR) to be posted shortly....
