### ISSUE TITLE
Block quotes in rich text editor

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#532]
Would be a good/standard feature to include and helps editors break up long bits of text.

**Comment by gasman** [comment]
Now comprehensively addressed by StreamField.

**Comment by SalahAdDin** [comment]
@tmsndrs I'm created a hallo plugin for blog quotes, pull-out quotes and cite, do you want it?

**Comment by davecranwell** [comment]
Hi @SalahAdDin since this issue is now closed, it might be best to continue conversations like this on the Google groups.

**Comment by shacker** [comment]
Although it's true that this feature can be built by devs with a custom StreamField block, I'd suggest that this need is common enough that a BlockQuoteBlock should be one of the bundled block types. As it stands, it's far too much work  (especially for a wagtail beginner) to get something working that's bundled with virtually every other text editor for the web. I've made a gist showing how to create a working BlockQuoteBlock:

https://gist.github.com/shacker/0dfee4742e0626a20015018817af4126

and would be happy to make a pull request if Torchbox agrees it would be nice to bundle - let me know.

**Comment by gasman** [comment]
Hi @shacker - yes, I think this would be a very worthwhile addition!

I think you could probably get the definition a bit smaller by subclassing CharBlock.
