### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by mjdavies** [torchbox/wagtail#541]
Hi guys

Matt here from the University of Southwales.

I did mention I was going to harass you about allowing us to use Mysql, so here I am, harassing you about letting us use Mysql.

I realise there is this issue, but it's not exactly what I wanted to do, that being harass you about allowing us to use mysql

https://github.com/torchbox/wagtail/issues/215

I've just started using pgadmin3, and its totally alien to me :-(

I'm sure there'd be others who would like to use mysql as well.

Regards

Matt

**Comment by chhantyal** [comment]
@gasman Was reading this thread, just to let you know MySQL driver for Python MySQL-Python doesn't support Python 3.

Apart from that supporting MySQL should not be problem at all.

**Comment by gasman** [comment]
Taking a fresh look at the failures in https://github.com/torchbox/wagtail/issues/541#issuecomment-66192211, it seems that the common theme is "fetching the latest revision". Just speculating here, but bearing in mind that the tests are likely to be creating many revisions in the space of <1 second, I wonder if we're running into the limits of MySQL's timestamp resolution, meaning that it's not able to reliably determine the most recent revision? (Maybe we're unwittingly relying on some Postgres implementation artefact, such as it returning the most recently inserted record in the case of a 'tie'. Perhaps we shouldn't be relying on timestamps for absolute ordering at all, and should be allocating them a specific sequence number instead...)

Adding a sleep(1) command between page saves in the tests would be a quick and dirty way to test this theory!

**Comment by coredumperror** [comment]
I added a `time.sleep(1)` call at the start of every `test_*` function in  `wagtail.wagtailimages.tests.tests.TestImageTag`, but I still got the same errors on the second and third tests.

**Comment by gasman** [comment]
@coredumperror The `time.sleep(1)` suggestion is for the page revision test failures, not the image ones (and putting it at the start of the test wouldn't necessarily be enough - if there are multiple save operations in the test, it would have to go between them too)

**Comment by coredumperror** [comment]
Oh... darn. Just goes to show that I obviously can't debug this on my own, though. ;)

**Comment by salvadormrf** [comment]
I was playing around with Wagtail on AppEngine.
AppEngine does not support C extensions, such as psycopg (and pg8000 seems to be a slow solution). 
The alternative is to use mysql (AppEngine has support for MySQLdb)

MySQL >= 5.6.4 now supports fractional seconds

There is a Django patch for this
https://github.com/django/django/commit/22da5f8817ffff3917bcf8a652dce84f382c9202
https://code.djangoproject.com/ticket/19716

After updating my mysql version, there is still some tests failing.

**Comment by gasman** [comment]
Had a quick look at the page revision retrieval failures, and it appears that we can fix these in a single swoop just by ordering by `('-created_at', '-id')` instead of just `('-created_at')` - no need to patch things to support fractional second timestamps: https://github.com/gasman/wagtail/commit/a88b8be25b5adcab568bd1486fce2c1f318512a8

Just the image rendition stuff to fix now, hopefully!

**Comment by salvadormrf** [comment]
Thanks @gasman that sounds a better solution.

Related to the image rendition by some reason the Filter is not getting created on database when looking into the local cache. By commenting those lines the tests will pass. There is something funny going on here.

```python
class ImageNode(template.Node):
    def __init__(self, image_var_name, filter_spec, output_var_name=None, attrs={}):
        self.image_var = template.Variable(image_var_name)
        self.output_var_name = output_var_name
        self.attrs = attrs

        #if filter_spec not in filters:
        #filters[filter_spec], _ = Filter.objects.get_or_create(spec=filter_spec)
        #self.filter = filters[filter_spec]
        self.filter, _ = Filter.objects.get_or_create(spec=filter_spec)
```

**Comment by salvadormrf** [comment]
Been looking into the issue of the image filters, and compared the same behaviour between postgresql and mysql. This seems the last issue related to mysql support :(

Mysql tests are failing on this test,
test_simple (wagtail.wagtailimages.tests.test_admin_views.TestImageEditView)

```bash
DATABASE_ENGINE=django.db.backends.mysql DATABASE_USER=root DATABASE_PASS=root DATABASE_HOST='127.0.0.1' ./runtests.py wagtail.wagtailimages.tests.test_admin_views -v3 --failfast
```

```python
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.environ.get('DATABASE_NAME', 'wagtaildemo'),
        'TEST_NAME': os.environ.get('DATABASE_NAME', 'test_wagtaildemo'),
        'USER': os.environ.get('DATABASE_USER', 'postgres'),
        'PASSWORD': os.environ.get('DATABASE_PASS', None),
        'HOST': os.environ.get('DATABASE_HOST', None),
        'PORT': os.environ.get('DATABASE_PORT', None),
        
        'OPTIONS': {
            'autocommit': True,
            'sql_mode': 'TRADITIONAL',
            'charset': 'utf8',
            'init_command': 'SET '
                'storage_engine=INNODB,'
                'character_set_connection=utf8,'
                'collation_connection=utf8_bin,'
                'SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED',
        }  # Now we have a mild degree of confidence :-)

    }
}
```

```
(Pdb) rendition = image.get_rendition(self.filter)
*** IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_wagtaildemo`.`wagtailimages_rendition`, CONSTRAINT `wagtailimag_filter_id_b5a94d704fa1f7f_fk_wagtailimages_filter_id` FOREIGN KEY (`filter_id`) REFERENCES `wagtailimages_filter` (`id`))')
```

By some reason a filter object is not on database, but is available on Django ORM and it causes this error when saving the rendition "rendition, created = self.renditions.get_or_create(filter=filter,....)" 

When ignoring the local cache "rendition = image.get_rendition(self.filter.spec)" then it run all ok.

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/templatetags/wagtailimages_tags.py#L7 
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/templatetags/wagtailimages_tags.py#L55

I don't have the much knowledge on wagtail, but would be nice if we can fix this issue.
Any suggestions ?
Thanks

**Comment by johnbward** [comment]
I'd love to use Wagtail, but am limited to MySQL for my current project. Supporting MySQL would help me a lot.

**Comment by gasman** [comment]
The last remaining test failure (foreign key constraint failure on wagtailimages_rendition) has now been fixed by @kaedroho in #1061 and definitively diagnosed in my follow-up #1110 - it was due to us keeping a module-level cache of filter objects, which was persisting after the database was torn down and recreated between tests. Once #1110 is merged, we can happily declare MySQL officially supported!

**Comment by salvadormrf** [comment]
Thanks a lot wagtail team!

**Comment by johnbward** [comment]
Yes, Thanks Wagtail team!

**Comment by coredumperror** [comment]
YAAAAAAYYY!!! ;)
