### ISSUE TITLE
Exclude users with ID lower than 1 from userlist that is rendered in wagtail user list

### ISSUE THREAD

**Issue by MagdaN** [torchbox/wagtail#565]
I am using Django Guardian and have an Anonymous User with ID -1. When Django tries to render the userlist for the admin interface it fails because the pattern is ['cms-admin/users/(\d+)/$']. So it would be great to check if the user-queryset that is rendered in the list does not contain users with IDs lower than 1.

**Comment by davecranwell** [comment]
If a regex is all that stands between us closing this ticket, lets try and address this in 0.9
