### ISSUE TITLE
[RFC] New fields for Page

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#577]
Just looking for some comments on adding the following fields to Page:

- ``first_published_at``
  - For displaying on the frontend when this page was first made live
- ``last_published_at``
  - For displaying on the frontend when this page was last updated
  - Use in the sitemap as the last modified date
- ``last_edited_at``
  - For ordering pages on the backend by when they were last edited
    - This could also be done by adding an FK to the latest revision and doing ``.order_by('latest_revision__created_at')``

The ``*_published_at`` fields could also be implemented in a separate model like:
```python
class PagePublishLog(models.Model):
     page = models.ForeignKey(Page)
     revision = models.ForeignKey(PageRevision)
     published_at = models.DateTimeField()

first_published_at = page.publish_log.order_by('published_at').first()
last_published_at = page.publish_log.order_by('-published_at').first()
```

**Comment by davecranwell** [comment]
@kaedroho  see #896 which somewhat duplicates this but also suggests `created_at`.

Haven't most of these new fields/properties been added now?
