### ISSUE TITLE
Publishing UI

### ISSUE THREAD

**Issue by jimmymorrisuk** [torchbox/wagtail#581]
First time using the UI and I felt that it wasn't very clear where I could publish a post after initially saving it as a draft, which most users will do. I looked in the listing and clicked the draft button as I wasn't sure if this was a switch, I then tried editing the article and checking the settings tab  (This where Drupal stores publishing settings by default), still no luck and then found I needed to click the bottom tab arrow to change the publish settings.

I feel this could be improved as it's not very intuitive. 

Ideally the listing would allow single or mass publishing of posts (like Wordpress). I would also advise adding a publish link to either the tabs at the top or by the status in the top right or next to the Preview button in the bottom bar.  I ignored the 'Save as Draft' button initially because I'd already done this but perhaps just a different/additional icon by the arrow would make this clearer.

**Comment by davecranwell** [comment]
This ticket is now superseded by the more thorough debate on https://github.com/torchbox/wagtail/issues/2214
