### ISSUE TITLE
Create page UI / navigation

### ISSUE THREAD

**Issue by jimmymorrisuk** [torchbox/wagtail#582]
Considering adding new page options on the dashboard page. These could be hidden under a button call 'Add new page' when clicking this it could reveal the all the page types. 

An overview of the available page types should probably close to hand and is also a key user journey. This is something Drupal does badly and Wordpress does well. 

Minor point about linking to the homepage/dashboard via the logo. I would consider whether this is natural app behaviour. This is website user facing convention but apps don't really have homepages as such it's an actions page or all in the menu. I'd recommend adding a dashboard link to the left hand nav.

**Comment by gasman** [comment]
This is now solved by the modeladmin module http://docs.wagtail.io/en/latest/reference/contrib/modeladmin.html, which allows registering specific page types as top-level menu items and provides an 'Add page' button from there.

**Comment by SalahAdDin** [comment]
Documentation please!

**Comment by zerolab** [comment]
@SalahAdDin do check the link that @gasman posted - http://docs.wagtail.io/en/latest/reference/contrib/modeladmin.html
