### ISSUE TITLE
New image resize method like fill required, but with enforced ratio

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#595]
Given the template image tag `{% image self.photo fill-300x300 %}`...

* Applied to an image 400x400, the resulting image will be 300x300. The image is square.
* Applied to an image 400x200, the resulting image generated by this tag will be 300x150. The image is *not* square.

This is the intended result of the "no upscaling" rule we've adopted, but it causes undesirable inconsistency in the rendering on the template. The developer explicitly requested and expected a **square** image, but isn't given one.

#### An example:
Our most common usage of "fill" is to generate a grid of thumbnails of identical proportions. As all our sites are fluid-width and responsive, images are styled to fit the width of the container, in some cases making them larger than native. This means when an image smaller than 300x300 is uploaded, the resulting image at 300x150 is still made as *wide* as the others in the grid, but as a result its height becomes *taller* than the rest and the neat grid is broken.

It therefore would seem like a nice addition to me if a resize method existed that, when given an image it couldn't resize without upscaling, still created an image of the desired *ratio*, if not the *dimensions*.

**Comment by davecranwell** [comment]
Suggested syntax: `{% image self.photo fill-300x300-withratio %}`

**Comment by davecranwell** [comment]
Perhaps what this really needs is a means by which the developer can specify in the page model what the minimum dimensions for any given image field should be, which would then be enforced by validation, preventing users uploading or choosing an image which doesn't meet the criteria.

**Comment by kaedroho** [comment]
@davecranwell Have you tested this recently? I'm pretty sure this is the behaviour since the focal point changes.

**Comment by davecranwell** [comment]
Ah ha! Yes this does seem to be working now. I uploaded a 50x50 image, requested a rendition at 50x200 and it "correctly" gave a 12x48 in return.

**Comment by gasman** [comment]
So the semantics of `fill` silently changed between versions, in a way that contradicts the documentation? That's... not good.

**Comment by kaedroho** [comment]
@gasman It's always been documented as using the new behaviour.

**Comment by davecranwell** [comment]
The latest docs say `In this situation the ratio of the requested fill will be matched, but the dimension will not`

**Comment by gasman** [comment]
Ah, OK. Not great that the behaviour changed between versions, but if the new behaviour is what's actually desired in practice (and the old behaviour was effectively undocumented/undefined), then that's fair enough.

**Comment by davecranwell** [comment]
Yeah that given the documentation claimed otherwise, it was arguably a bug.

**Comment by SalahAdDin** [comment]
We can do this ```{% image self.photo fill-300x300-forceratio %}```?
I don't remember saw this in the docs. :'(
