### ISSUE TITLE
Traversing the site with the Explorer isn't intuitive.

### ISSUE THREAD

**Issue by jimmymorrisuk** [torchbox/wagtail#597]
Say you're at the root of your site in the Wagtail admin interface and you want to go down a level, it's not efficient or that clear that you need to go to the explorer to get to the next branch. I think it would be nice if you could quickly navigate up/down the tree via the main interface rather than having to go into the explorer each time, unless you want to jump branches.   

I feel the structure of the site could be better represented visually. Ideally some kind of tree overview might be useful. However, I understand that this might be a fairly large task. A less time consuming solution would be to have a pagination style links to traverse the tree's branches. One idea to make it slick and unintrusive would be to use a carousel like navigation and animation up and down the tree. 

The most applicable example of a tree structure that users would be used to using are file browsers on Windows or Mac. The current interface isn't really similar to that and might be lacking some usability and intuitiveness because of it. Perhaps some conventions could be copied from these interfaces?

**Comment by davecranwell** [comment]
Closed in favour of #1160 which has more exploration
