### ISSUE TITLE
Document new approach to multi lingual sites

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#612]
Currently, the documentation contains a tutorial about how to create multi lingual sites by duplicating your site tree.

Wagtail 0.6+ lets you use a different approach using Djangos ``i18n_patterns`` and ``LocaleMiddleware`` which is better in some ways as you can duplicate the fields instead of duplicating all pages. We should document this approach as well.

**Comment by BertrandBordage** [comment]
:+1: Is there some code sample available anywhere, as @h3nrik asked?
