### ISSUE TITLE
Wagtail redirects and GET parameters

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#647]
Could wagtail redirects ignore GET parameters instead of trying to match the slug with parameters and producing a 404?

Case use is that our marketing people have existing links to say /law (which use to be an old page, now is a redirect) and have many old links with Google Analytics parameters on the end for tracking campaigns. They now don't work and produce a 404, as the redirect bit matches the ?utm.... bit too.

Hope that makes sense.

**Comment by benje** [comment]
Any update on this? We've got a bunch of old urls that are causing 404's because of automatically added utm parameters. A fix would help us out a bunch! :+1:

**Comment by gasman** [comment]
Fixed in #1677
