### ISSUE TITLE
CompileError — file to import not found or unreadable: "../variables.scss"

### ISSUE THREAD

**Issue by tezro** [torchbox/wagtail#649]
After clean install and trying to log into the Admin interface:

CompileError at /admin/login/
```
d:\VirtualEnvironments\wagtail_test\lib\site-packages\wagtail\wagtailadmin\static\wagtailadmin\scss\layouts\login.scss:1: error: file to import not found or unreadable: "../variables.scss"
```

Windows 7 x64, Python 2.7 x32.

**Comment by gasman** [comment]
Wagtail no longer depends on django-libsass as of version 1.0.

(Current status of django-libsass on Windows is unknown, but no longer Wagtail's concern :-) Anyone interested in using that combination is welcome to report any issues against the [django-libsass project](https://github.com/torchbox/django-libsass))
