### ISSUE TITLE
Pages, Images, Documents and Snippets linked via Chooser Panels in a page, should also link to the edit screen for those items

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#653]
e.g As an editor choosing Images to appear in a page I'm editing, It's often the case I need to modify the record for the Image, to add a more appropriate alt tag, caption, or credit, as part of the process of editing the page. It would be great if I were able to easily navigate to the editing screen for that image, from within the Page Editor, but without leaving the editor.

Suggest we update all the chooser snippets to include an "Edit this X" link, alongside the "Clear" and "Choose another" options, which opens in a new tab/window

See also https://github.com/torchbox/wagtail/issues/586

**Comment by zerolab** [comment]
Fixed in #1014
