### ISSUE TITLE
Page preview loading bug

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/wagtail#659]
To replicate the issue: 

1. Edit a page
2. Preview changes (at this point the preview opens in a new tab and works as expected)
3. Make further changes in the CMS but don't close the preview tab 
4. Preview changes
5. The preview tries to load in the same tab as the previous preview but hangs

**Comment by zerolab** [comment]
Closing as #878 was merged.

**Comment by SalahAdDin** [comment]
Some times i have bugs as this, some thimes page preview don't load, other times i have to refresh the page many times, F5 many times for get any chage in the page, shure, i have get the page in the window using the full url, you know, localhost:8000/blog/bla-bla-bla... as i said, preview page don't change, left in white. 
Now i read this and i get that is not only muy bug.
