### ISSUE TITLE
Add ability to specify the number of related objects in InlinePanel

### ISSUE THREAD

**Issue by zerolab** [torchbox/wagtail#669]
There are times where you'd want to limit a related object to N instance. Say, I want up to 4 related links. Currently one can accomplish this via a separate property, or `serve` method.

Ideally we would specify the maximum and/or mininum number of objects and the InlinePanel would behave accordingly.

**Comment by davecranwell** [comment]
@gasman Karl was saying Django 1.7 introduces features equivalent to min/max on inline forms, on which I assume our InlinePanels are based. Could this be integrated here too?

**Comment by zemyatin** [comment]
Is this possible by now? It need to be able to limit the number of entries a user is able to add of a specified model field.
