### ISSUE TITLE
Cleanup Django 1.7 warnings

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#673]
See: https://travis-ci.org/torchbox/wagtail/jobs/37158134

Many of the warnings are coming from forms in Wagtail not having a "fields" or an "exclude" attribute. Which shouldn't take long to fix.

**Comment by kaedroho** [comment]
Cleaned up some more in: https://github.com/torchbox/wagtail/pull/969

All that remains is the image form, which we need to set the ``fields`` parameter on. This is a little tricky as we don't currently have a way on doing this. Shall we start getting developers set an ``admin_fields`` setting on their image models?

**Comment by gasman** [comment]
@kaedroho Sure, sounds like a good plan.

**Comment by zerolab** [comment]
Is #980 taking care of the last bit?

**Comment by kaedroho** [comment]
Nope, we still have a few more of those warnings somewhere...

**Comment by kaedroho** [comment]
All fixed
