### ISSUE TITLE
How do I access the domain of a page or the absolute URL of an image?

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#693]
There are occasions where it's necessary to generate absolute URLs, or at least determine the domain of a certain page.

For example with OpenGraph/Schema.org tags, the canonical URL of a page is necessary. This is possible with `page.full_url()`. However OpenGraph also requires an absolute URL for the `og:image` meta tag i.e an absolute URL for an image. How would that be generated? Perhaps, given that the image library is domain-agnostic, it would be better if there were an option to get the domain on it's own, of any page viewed, so it could be prefixed to a relative image URL?

It feels like there's a need for a `page.get_site()` (returning a `Site`) or similar, to make access easier for the non-technical.

**Comment by davecranwell** [comment]
Encountered while working on another wagtail project: what is `request.site`? I can use it for `request.site.hostname`, which solves my issues as far as accessing the domain at a template level goes.

**Comment by gasman** [comment]
`request.site` is populated by wagtailcore.middleware.SiteMiddleware, and gives you the site object corresponding to the hostname of the current HTTP request. Only useful if the page you're interested in is the currently requested one, of course.

**Comment by Braintelligence** [comment]
Hi guys, was this solved yet?
Thanks to @davecranwell for a temporary solution!

**Comment by gasman** [comment]
@Braintelligence Yes - see the links above. `get_site` was implemented in #2027.

**Comment by Braintelligence** [comment]
@gasman Hi, thank you for clarifying. How do I use it with an image rendition for the meta image then?

```
<meta property="og:image"         content="{% image page.header_image fill-821x400 as header_image %}{{ header_image.get_site }}" />
```

Doesn't work. {{ page.get_site }} returns the title of the page for me with [Default] behind it.

**Comment by gasman** [comment]
@Braintelligence Please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by Braintelligence** [comment]
@gasman Sorry for the misunderstanding. The issue is explicitly about this: 
> However OpenGraph also requires an absolute URL for the og:image meta tag
but I don't see the solution presented, thus I can't comprehend the solution. That's why I thought I could ask for it here.

I will tend to the Google group then.
