### ISSUE TITLE
Meta class description attribute is not allowed

### ISSUE THREAD

**Issue by jerel** [torchbox/wagtail#699]
The bottom of [this page of the docs](http://docs.wagtail.io/en/latest/core_components/pages/creating_pages.html) suggests adding a `description` attribute to a model's Meta class. However doing so in Wagtail 0.7 results in `TypeError: 'class Meta' got invalid attribute(s): description`

**Comment by kaedroho** [comment]
References to ``Meta.description`` were removed from the documentation a few months ago. There's still references to it within the Wagtail source code: https://github.com/torchbox/wagtail/search?utf8=%E2%9C%93&q=meta_description&type=Code

I think we should remove this functionality and reintroduce it when we have a less hacky way of implementing it (eg, ``PageMeta``).

**Comment by gasman** [comment]
https://github.com/torchbox/wagtail/search?utf8=%E2%9C%93&q=meta_description&type=Code no longer shows any results, so it looks like this has been eliminated now. `PageMeta` is addressed by #513, so closing.

**Comment by hbrls** [comment]
@gasman but the Google search still point to old documents. Maybe you can mention this in the latests doc.
