### ISSUE TITLE
Migrating PageRevisions

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#703]
At the moment, running migrations on pages can sometimes be very difficult as you sometimes have to migrate all of the revisions of the page you are migrating. This usually involves writing lots of custom code that can take a while to develop and test thoroughly.

I spent three hours on Friday developing a quite tricky migration to add a custom image model to a site. All page types that had an image field had to have all of its revisions migrated. Some even had them in child objects which were quite tricky. Testing it involved a lot of restoring and rerunning the migrations. This is not an uncommon thing, I must've done this at least 5 times before.

I really think we should look into developing some helpers in Wagtail to help save time and prevent mistakes. Heres some ideas (all of which are aimed at Django 1.7+):

**Create a ``MigratePageRevisions`` operation**

This operation would iterate through all the revisions of a particular page type and call a function giving the content of each revision in python form. This function would then return the modified content which would be automatically reserialised and put back in the revisions table.

For example, to rename a field you can write the following:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models, migrations

from wagtail.wagtailcore.migration_helpers import MigratePageRevisions
from myapp.models import MyPageType


def migrate_revision(apps, content):
    # Rename a field
    content['new_field_name'] = content['old_field_name']
    return content


class Migration(migrations.Migration):
    ...
    operations = [
        # Schema operation here

        MigratePageRevision(MyPageType, migrate_revision),
    ]

```

Something to think about is it is common to want to run an operation once for all revisions of a page but be able to access the result of that operation when migrating the individual revisions.

Another thing to think about is make the operation work when you only want to migrate the latest revision or only revisions that are likely to go live soon (latest revision + revision in moderation)

We could also create a ``MigrateChildRevision`` operation to make migrating child objects much easier.

The downside of this is you still have to write separate migrations for revisions. Users would also need to learn about this and why they should do it.

**Create a ``migratepagerevisions`` command**

This command would look at the migration operations for the model representing the revision and attempt to run them on the revisions. This may have difficulty with certian operations such as ``RunPython`` and ``RunSQL``. It also won't work with custom operations. We would also need to come up with a way of detecting which operations haven't been applied.

**Comment by BertrandBordage** [comment]
Is there a solution to this migration issue?
Deleting the PageRevisions linked to a migrated page works for me, but I guess it deletes important informations on draft pages.

**Comment by mevinbabuc** [comment]
@kaedroho is there some example I can look on how you did migration for blocks in pagerevisions ?

**Comment by glassresistor** [comment]
I'm running into the same problem.  Also its unclear to me what is stored in model itself and whats in the revision model?  Is it just published or also draft data?

**Comment by iaindillingham** [comment]
I'd like to second @glassresistor in asking for guidance on what is stored on `Page` and what is stored on `PageRevision`. This caught me out recently when I wanted to update pages programmatically. I updateted `page.field` rather than `page.get_latest_revision_as_page().field` before calling `page.save_revision()`. The result was a broken revision history, because `Page` does not seem to reflect the latest `PageRevision`.
