### ISSUE TITLE
Specify login_url on views decorated with permission_required

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#731]
I hit a snag incorporating wagtail with a frontend that used jquery mobile and custom authentication.  Since the wagtail dashboard doesn't produce jqm ajax compatible pages, linking to the dashboard from the jqm requires special markup.  The same is true for forms that redirect on successful post.  Since the custom authentication form page uses jqm, a blank page is displayed when the user is redirected back to the dashboard unless the form is marked data-ajax=false.

I've overcome this with a url override in urls.py that takes precedence over wagtail's entries.
```
url(r'^dashboard/login/$', jqm_incompatible_login_redirect_view, name='wagtailadmin_login'),
```

Since protected pages in wagtail do not specify they want to be redirected to wagtailadmin_login, I also had to mask the dashboard home view like so:
```
@permission_required('wagtailadmin.access_admin', login_url='wagtailadmin_login')
def wagtailadmin_home_override(request):
    return wagtail_home_view(request)

...

url(r'^dashboard/$', wagtailadmin_home_override, name='wagtailadmin_home'),
```

Since it would be unmanageable to override all of the wagtail views, I am only doing this for the dashboard home view.

Would there be any objections to a pull request that defaults permission_required to use login_url='wagtailadmin_login' for wagtail?  The django admin seems to use an approach like this because it redirects to admin/login/ and admin/logout/ regardless of the value of settings.LOGIN_URL which is handy for this situation.

If you don't want to explicitly specify login_url for every view it could be made default for the decorator like:
```
def wagtail_permission_required(*args, **kwargs):
    kwargs.setdefault('login_url', 'wagtailadmin_login')
    return permission_required(*args, **kwargs)
```

This would allow staff users to bookmark dashboard pages and access them directly when they are not logged in.  Currently, this flow doesn't work.

**Comment by kaedroho** [comment]
Hi @thenewguy 
I've created a pull request (https://github.com/torchbox/wagtail/pull/912) which applies the ``permission_required`` decorator centally from ``wagtailadmin/urls.py``. This lets us easily set the ``login_url`` parameter globally.

Please could you check it to see if it solves your issue?

**Comment by thenewguy** [comment]
Hello @kaedroho 

Looking over this, I think this fixes the problem.  Nice!

**Comment by zerolab** [comment]
#912 now merged. 
@thenewguy please close if it fixes your issue.

Thank you.
