### ISSUE TITLE
Snippet in dashboard cannot attach file to FileField

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#740]
I am attempting to write a snippet that allows a user to attach a file to a page.  Here is a simple example:

```
@register_snippet
class Foo(Orderable):
    page = ParentalKey(Page)
    
    file = models.FileField(upload_to="foo/", max_length=255, blank=True)

    panels = [
        FieldPanel('file'),
    ]
    
    def __unicode__(self):
        return u"%s" % self.pk
```

The snippet is attached like so:
```
InlinePanel(Page, 'foo_set', label="Foo"),
```

After saving an attached file in the dashboard the Foo instance is saved and displayed, but the file is not there.

**Comment by gasman** [comment]
Being addressed by #1741.
