### ISSUE TITLE
PageQuerySet.unpublish doesn't call page_unpublished signal

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#745]
This may cause issues with pages not being purged from the cache. This method is only currently used in Wagtail to unpublish pages after copying them (which don't get their page_published signal fired anyway).

I suggest we remove this method and add a ``keep_live`` attribute to the ``Page.copy`` method which when set to false, will not publish the copied pages in the first place.

**Comment by chrxr** [comment]
Agreed that this should be done in team meeting. @kaedroho to address.

**Comment by kaedroho** [comment]
Fixed by #1934
