### ISSUE TITLE
Move setting of has_unpublished_changes and live into Page.save_revision

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#746]
See:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L194
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L312

I think this should be moved here:
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L431

Two reasons:
 - It improves the encapsulation of the ``Page`` model
 - It removes a query
 - Simplifies code a bit and makes it easier for people to save revisions outside of wagtailadmin

**Comment by chrxr** [comment]
Agreed that this makes sense in weekly meeting. @kaedroho to address.
