### ISSUE TITLE
Page type isn't displayed within the page's editor

### ISSUE THREAD

**Issue by nimasmi** [torchbox/wagtail#749]
I'm more than happy to be corrected on this one, but it seems to me that when I have the page editor is shown for a given page nowhere in the interface is the page type displayed. Even if I had an inkling of type from location, this wouldn't be inferrable from the URL as within the editor it becomes `http://content-management.systems/admin/pages/130/edit/`. My only options seem to be to infer it from the page's title, or to visit the explorer.

Which raises the question: why is it shown in the explorer, but not in the page editor?

In fairness, I've only needed to find a page's type when developing (e.g. so I could know where to look for the model's class definition), and I have no experience of using the CMS as an editor, so if it were a case of adding something that only shows when `settings.DEBUG == True` that may suit most needs for this.

**Comment by coredumperror** [comment]
It would also be really nice to have a class name added to the form that indicates the page type. This will allow javascript and css added through wagtail hooks to easily identify the page type, and limit themselves to specific types as needed.

**Comment by coredumperror** [comment]
I think this issue can be closed now that #904 is merged.

**Comment by zerolab** [comment]
Hi @coredumperror, you are correct.
Marking this a closed now.

@davecranwell if the solution from #904 requires further design input, it is probably best tackled with other "several pieces of meta information conspicuously absent from the page editor interface".
