### ISSUE TITLE
Add menu_name field to Page model 

### ISSUE THREAD

**Issue by dantium** [torchbox/wagtail#789]
Could there be a field on Page to use for the name of a Menu?

Currently it seems that the best way to generate a menu is using the title but in many instances a user might want a different menu name to the page title - e.g. with a home page they might want a title of 'Welcome to our website' and a menu title of 'Home' 

A solution to adding additional fields and properties to Page would be to make it an Abstract model so that it could be adapted for each use case.

**Comment by gasman** [comment]
Have created #836 to cover creating an AbstractPage model - I think that's going to be the best long-term solution for adding new global fields.
