### ISSUE TITLE
Upload form on document attach modal switches tabs on submit/failed validation

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#803]
Steps:

 1. In a RichText field, press the `Documents` button.
 1. Select the `Upload` tab.
 1. Choose a local file.
 1. Submit the form without entering a `Title`.

Expected result: Form shows validation error, stays on `Upload` tab.

Observed result: Form switches to default `Search` tab.

**Comment by zerolab** [comment]
Hi @edrex,

This is now fixed by #1263.
