### ISSUE TITLE
Alternate method of browsing pages

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#834]
Images, Documents, Snippets, Users etc exist outside any hierarchy, so searching for "a list of the most recently updated docs" is simple. Doing the same with pages however is not possible. The Explorer can only traverse sections and can't display a bigger picture, which as a content manager not interesting in any particular section, can be frustrating.

E.g As an implementer I'm aware a change I've recently made affects all pages using a specific template. It's months since I've edited the site and I can't remember where each page using that template occurs, nor any identifying feature such as a title of those pages. How do I *intuitively* find a list of those pages?

I'd like to be able to list:
* All pages using a certain content type, site-wide 
* All pages in by their last edited date, site-wide
* All pages last edited by user X, site-wide

**Comment by lee-kagiso** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by tomdyson** [comment]
Note that all of this is possible with https://github.com/rkhleics/wagtailmodeladmin, which works now and is scheduled for inclusion within Wagtail itself.

**Comment by coredumperror** [comment]
The readme make this look awesome! I can't wait to play around with it.

**Comment by gasman** [comment]
Now covered by the modeladmin module - http://docs.wagtail.io/en/latest/reference/contrib/modeladmin.html

**Comment by SalahAdDin** [comment]
Documentation please.
