### ISSUE TITLE
custom widgets overrides

### ISSUE THREAD

**Issue by janrito** [torchbox/wagtail#848]
There are some situations in which widgets need to be overridden:    

- the default widgets in geodjango load `openlayers.js` from `opelayers.org`, which is slow and does not work over https. The easiest way to deal with this is to subclass `OpenLayersWidget` and `OSMWidget` to load a local copy of `openlayers.js`.
- default options on the datetimepicker might not work in all cases – dates before 1950, dates within specific ranges, etc.

Currently, overrides to fields are set in a constant `FORM_FIELD_OVERRIDES` in `wagtail/wagtail/wagtailadmin/edit_handlers.py`. I'm not sure what is the best way to override this. 

Another problem, which I'm not sure there is a solution yet, is when the widgets need to be overridden for only some fields of the same type.

**Comment by janrito** [comment]
bump?

**Comment by gasman** [comment]
Thanks, looks good! Sorry for the delay in merging this.
