### ISSUE TITLE
Vagrant configuration in template forwards port 8000 to 8111

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#853]
This confusing behaviour was copied from ``vagrant-django-template``, why do we do this?
https://github.com/torchbox/wagtail/blob/master/wagtail/project_template/Vagrantfile#L11

**Comment by davecranwell** [comment]
@kaedroho I think the next steps here are just to change the ports to something else/better. If there's no real reason for it, lets fix it. Being a very small tweak it would be great to get this out the way soon.

**Comment by gasman** [comment]
Is there anything we need to consider re updating documentation / making people aware of the change? I guess we'll be changing it in 1) the bundled project template 2) wagtail-template 3) wagtaildemo; obviously, any other existing projects will stay on port 8111. And people who have been using port 8111 for a while presumably won't be thrown off if the documentation suddenly changes to localhost:8000, so it seems to me this is harmless enough. Any issues I haven't thought of?

**Comment by zerolab** [comment]
#978 now merged. Will create separate PRs for wagtaildemo and wagtail-template.
