### ISSUE TITLE
Internal Server Error when DEBUG = False

### ISSUE THREAD

**Issue by elspiko** [torchbox/wagtail#855]
Hi all,

Just deployed my vanilla app to Heroku and I started receiving "Bad Request" responses from any URL. After some investigation I've discovered there appears to be a problem when DEBUG is set to False.

I've created a brand new virtualenv with only the requirements.txt installed, updated:

```
proj/settings/__init__.py

from .production import *
```

I've run the same code via Vagrant incase it was my machine's setup but 500s no matter what I try until I set DEBUG to True.

Any help or suggestions would be appreciated.

**Comment by krsmedlund** [comment]
["*"] and["*",] is the same thing. 

Check that you have the 400.html and 500.html templates, those are the primary suspects if sites do 500s when DFEBUG is set to False

**Comment by kaedroho** [comment]
Closing as general support queries should now be posted on the Google Group. Please post there if you are still having problems.

https://groups.google.com/forum/#!forum/wagtail
