### ISSUE TITLE
[RFC] Some restructuring ideas

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#857]
Here's some ideas for improving the general structure of Wagtail. I believe there are ways to do these in a backwards-compatible way (once Django 1.6 support is gone). This would briefly make the code a bit messy during the deprecation process though.

 - Move ``wagtailcore/{hooks,compat}`` into ``utils``
 - Rename ``wagtailcore`` to ``wagtailpages`` and move page views into ``wagtailpages``
  - This will make ``wagtailadmin`` the core of wagtail and ``wagtailpages`` will sit alongside ``wagtailimages`` and ``wagtaildocs``. ``wagtailpages`` would also become an optional module which allows it to be easily forked in a project (or even replaced completely).
   - This also improves encapsulation as all page code would be in a single module
 - Move ``Site`` model and ``SiteMiddleware`` into ``wagtailsites`` __?__
 - Move "account" views into ``wagtailusers``
 - Make ``wagtailforms``, ``wagtailredirects`` and ``wagtailembeds`` into contrib apps
 - Separate editors picks from ``wagtailsearch`` and make it a contrib app
 - Create class based search view in ``wagtailpages`` and add backwards compatibility for function based search views
 - Move what remains of ``wagtailsearch`` into separate project
 - Remove ``wagtail`` prefix from all modules (but rename ``wagtaildocs`` to ``documents``)

This leaves three categories of modules:
 - ``admin`` - Doesn't depend on anything within Wagtail except for utils
 - ``pages``, ``images``, ``documents``, ``snippets``, ``users`` and ``sites`` - Plug in to ``admin`` but can be installed and used on their own. These are all optional.
 - ``contrib.*`` - Other stuff which is only useful for certian projects

**Comment by timorieber** [comment]
Mostly superseded by #1504.
