### ISSUE TITLE
Replace snippets module with a ModelAdmin-like thing

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#858]
Snippets are just a way to take a Django model and putting it in the admin so an editor to view/edit/etc.

As it's now easy to add new sections to the admin, do you think it would be good idea to come of with a system within wagtailadmin which allows developers to easily create some admin CRUD views from a model and register them? This could replace snippets but it could also be something that we could make use of for our other modules like docs, images, users, groups, redirects, etc.

EDIT: Another thought, instead of completely replacing snippets, we could make the snippets module also make use the above system for backwards compatibility, but we would recommend that new projects use the new approach.

**Comment by ababic** [comment]
If it helps anyone, I've put together a package that does something similar to this (https://github.com/ababic/wagtailmodeladmin/). It doesn't change the way snippets and other listing pages work / link together... It just gives you an additional listing view that you have control of. It can be used for models that extend Page, or simpler models that are registered as Snippets. They need to be one of the two though, as what I've done links into the existing Wagtail views for creating and updating. 

It's still in it's early days, but hopefully it will be of use to others.

**Comment by SalahAdDin** [comment]
Very interesting :+1:

**Comment by jorge-marques** [comment]
:+1: This would be a fantastic feature.

**Comment by kaedroho** [comment]
I think @gasman is looking into this now

**Comment by pymarco** [comment]
Thank you @ababic for your work. 

:+1: for this feature

**Comment by ababic** [comment]
Thanks @pymarco

I recently finished version 2, which is a vast improvement on what I
released originally. Much closer to how I see this kind of thing working as
a feature, and I think much easier for developers to override/extend to
meet their needs.

**Comment by gasman** [comment]
With the addition of modeladmin in 1.5, the crux of this ticket has been achieved now. (There's still potentially more we can do to unify snippets with modeladmin, but we're now in a position where we can open more focused tickets for that work, if appropriate.)
