### ISSUE TITLE
Add optional tracking pixel

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#863]
During recent integration with Oscar I noted it has a "phone-home" pixel to record very basic information.

It's entirely optional and easily disabled. For some basic usage stats we should add on to Wagtail.

**Comment by chrxr** [comment]
We will take the simple approach for 1.0: Dashboard will request https://releases.wagtail.io/latest.txt

**Comment by tomdyson** [comment]
For now we have

http://releases.wagtail.io.s3-eu-west-1.amazonaws.com/latest.txt

I'm setting up a Cloudfront distribution with a releases.wagtail.io CNAME and SSL. @kaedroho, I suggest we request this URL from the dashboard when

- settings.CHECK_WAGTAIL_UPDATES is not False
- DEBUG is not True
- current host is not localhost / 127.0.0.1

If the contents of latest.txt are a bigger number than the version of Wagtail requesting the URL, administrators should see a notification on the dashboard: "You are running {{ current version }} of Wagtail, which can be upgraded to {{ latest version }}. More details at http://wagtail.readthedocs.org/en/stable/releases/index.html"

We also need to update the documentation for our release process so we remember to update the contents of latest.txt when there's a new stable release.

**Comment by davecranwell** [comment]
This decision seems to have unfortunately crossed over with a day of leave, despite having done 90% of the work on Monday. See https://github.com/torchbox/wagtail/pull/1138

**Comment by tomdyson** [comment]
Sorry, @davecranwell, my fault, I assumed you were off for the rest of Easter.

Your approach has many benefits from a reporting POV. The advantage of my approach is that there's a clearer benefit to the user: highlighting when updates are available, and that it's slightly more transparent what data we're gathering. In general I'm feeling unsure about asking users to expose their Wagtail / Django / Python versions, which are potentially attack vectors. What do you think?

**Comment by davecranwell** [comment]
My understanding was that we valued knowing those metrics, but if they're more a security hazard than a help, I've no issue with dropping them from my PR.

It seems the new direction is to combine phone-home stats for us, with my old suggestion https://github.com/torchbox/wagtail/issues/165 for the user, which I closed for reasons I can't remember. Obviously I'd like the upgrade notification message too, if possible.

**Comment by tomdyson** [comment]
We do value them, but not more than risking our users' security - I hadn't really thought this through properly, I'm afraid. 

Can we combine your approach with an upgrade notification system?

**Comment by davecranwell** [comment]
Is the cloudfront route necessary? I was going to rely on pypi's feeds: https://pypi.python.org/pypi/wagtail/json

**Comment by tomdyson** [comment]
PyPI says `info.version` is '1.0b1', which we wouldn't want to encourage users to upgrade to. Can we specify a stable version in PyPI? You're right, it would be better not to have to maintain a separate file containing the latest version.

The advantages of CloudFront are:

- it's always up
- it's fast and local
- it only costs users a few bytes
- requests are logged
- there's a simple UI for top level reports on referrer, browser type, country etc.

**Comment by davecranwell** [comment]
I'm still looking for a more procedural solution than maintaining `latest.txt`. Is Github's "Releases" api not an option? We could compare version number against this: https://api.github.com/repos/torchbox/wagtail/releases/latest

**Comment by kaedroho** [comment]
Python has a module called ``disutils.version`` that lets you, with a list of version numbers, filter out prereleses then find the latest one. We could write a little Python script that runs daily on a server somewhere and automatically updates the ``latest.txt`` file for us.

**Comment by gasman** [comment]
Updating the version number manually probably wouldn't be a bad thing - it's just one more step in the release process, and it gives us chance to test that the PyPI-uploaded package works properly before it gets fully announced to the world. (For the 1.0b1 release, I briefly neglected to tick github's 'this is a development release' checkbox, and it would have been awkward if that had triggered a notification.)

On a separate note - how are we going to ensure that this doesn't become the archetypal Notification That Everyone Ignores (which then gives users banner-blindness for when an actual relevant notification comes up)? Making sure that it's only shown to administrators would be a start, but how many Wagtail sites really go through the trouble of setting up restricted user roles rather than just making everyone an admin? And even then, how often are the site admins going to be the people capable of actually performing the upgrade? (In the case of Torchbox clients - not very often.) One possibility (which I've not fully thought through) might be to add a default 'sysadmin' group with a 'can receive upgrade notifications' permission, and fiddle the `./manage.py createsuperuser` task so that users created through it are automatically assigned to that group.

**Comment by davecranwell** [comment]
The fact that wagtail isn't a one-click-upgrade like wordpress, means using github's release json feed isn't that terrible if you make a mistake like your example. I'd also agree this should be something only visible to higher users so given those two facts it doesn't seem terrible to me if those users get a mistaken notification once, briefly.

As discussed in #165, despite only developers having the power to upgrade a site, it's nice to create a little excitement amongst other users too, particularly those in the "admin" role who are more likely to be management-types and will value new features or improvements, e.g our main contact at RCA.

As far as avoiding banner-blindness goes, I probably wouldn't make this a banner. It feels like it might be something that appears on the dashboard alongside the other overview reports.

**Comment by davecranwell** [comment]
Dropping GA version in favour of simple latest.txt on cloudfront. 

Add something to release procedures to update latest.txt

**Comment by zerolab** [comment]
Am I correct in thinking that this makes #1138 obsolete?
