### ISSUE TITLE
Feature: image credits/attribution

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#866]
We have a requirement to attach credits to images (not to particular placements of the image). The attribution info would be available through Image fields, but not in RichTextField image placements (seems ok given the move toward more structured content editing).

Upstream interest?

**Comment by edrex** [comment]
I did this yesterday, modeling closely on the RCA implementation, and it went through without problems. I'm starting a doc section "Using a custom image model" under "Images/Advanced topics".

I have a guess at what the `Rendition` model is for, but have treated it as a black box and just followed the example from RCA. Are there any additional warnings that should be in the docs about it?

Also, I was able to preserve existing data by the following procedure:
 - Deploy the new model, with no field additions, and run the migration to create it.
 - Dump a fixture from wagtailimages and manually edit it to:
   - Change the model names for `wagtailimages.image` and `wagtailimages.rendition` to our custom model names
   - Remove the filter records.
 - Restore the edited fixture.
 - Rename any `ForeignKey` fields into the image model to use the new model and deploy those migrations.

**Comment by ghostwords** [comment]
Thanks for sharing your migration experience!

I also migrated image tags:

1. Dump the fixture: `python manage.py dumpdata taggit | python -m json.tool > taggit.json`
2. Connect to the database and get your custom image model's content type ID by querying the `django_content_type` table. Also note the `wagtailimages.image` model's content type ID.
3. Edit taggit.json from step 1, removing `taggit.tag` entries and anything else that's not `taggit.taggeditem` model entries mapping images to tags.
4. Update all `content_type` properties for the `taggit.taggeditem` model to use the new ID.
5. Load the updated fixture with `python manage.py loaddata taggit.json`.

Finally, a Postgres table belonging to a model referencing the new image model failed to have its foreign key constraint updated (not sure why, two other tables had their constraints properly updated), which meant I got a "key ... is not present in table" IntegrityError on trying to update that table's model with a new image using the new image model. I then manually dropped the stale foreign key constraint, fixed the references and readded it.

**Comment by kutenai** [comment]
This is quite old, but not handled in any conclusive way that I'm aware of.
I was thinking that it might be easier (better?) to add an ImageAttribution table that has an FK to the current wagtail image model. This doesn't mess with wagtail, and attributions would be optional, or could be added as needed. 

I'd be curious if anyone had thought there? @gasman?

**Comment by boatcoder** [comment]
> Hi @edrex,
> This can be done by subclassing `wagtail.wagtailimages.models.AbstractImage` and `wagtail.wagtailimages.models.AbstractRendition` within your app (see https://github.com/torchbox/verdant-rca/blob/develop/django-verdant/rca/models.py for an example of this) and specifying `WAGTAILIMAGES_IMAGE_MODEL` in your settings. (Swapping the model on a site that already has existing content is quite tricky, unfortunately.)
> 
> This isn't really documented right now because I originally regarded it as a bit of a hack and didn't want to encourage it - however, it's used on multiple sites now and the feature is clearly here to stay, so it probably ought to get some proper documentation!

The link from above has changed to:

https://github.com/torchbox/verdant-rca/blob/d9ede994dbd1ef68eaa159ec930fd89a351c1329/django-verdant/rca/image_formats.py#L4-L25 Which might help the next person that comes along and reads this thread.
