### ISSUE TITLE
Preview doesn't reflect changes made to the order of Orderable items.

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#867]
I'm chugging along through the "Displaying Fields with the Editing API" page in the docs, and absolutely loving the power that Wagtail offers. But I've run into a bit of an annoying issue, which appears to be a bug in either wagtail or django-modelcluster.

When I click the Preview button while editing a Page-derived model attached to an Orderable, the order the items are displayed in is always the order in which the Page was saved (or, in the case of a page that hasn't been saved yet, the order in which the items were added to the editor), rather than the order that's currently displayed in the editor form (after clicking the Up and Down arrows to change their order).

How to replicate this bug (see bold note below for easier testing):
In wagtaildemo, add this to models.py:

```python
# The abstract model for related links, complete with panels
class RelatedString(models.Model):
    string = models.CharField(max_length=255)

    panels = [
        FieldPanel('string'),
    ]

    class Meta:
        abstract = True


class TestPageRelatedStrings(Orderable, RelatedString):
    page = ParentalKey('demo.TestPage', related_name='related_strings')


class TestPage(Page):
    body = RichTextField(blank=True)

TestPage.content_panels = [
    FieldPanel('title', classname="full title"),
    InlinePanel(TestPage, 'related_strings', label='Related Strings'),
]
```

Then add test_page.html to your templates, with these contents:
```
{% extends "demo/base.html" %}

{% block content %}
    {% include "demo/includes/body.html" with body=self.body only %}

    {% if self.related_strings %}
    <h3>Related Strings</h3>
      {% for related_string in self.related_strings.all %}
      <p>
        {{ related_string.string }}
      </p>
      {% endfor %}
    {% endif %}
{% endblock %}
```

Migrate your site, then add a new Test Page from the admin interface. Set the page's title, then add "String 1" and "String 2" to the Related Strings panel. 

Now click "Preview", and you'll see String 1 and String 2 in numerical order. Then, close the Preview tab and move String 2 above String 1 in the editor, and click Preview again. 

The bug is that String 1 will still appear above String 2, even though it's been moved below it in the editor.

**Note: I realized while writing this up that you can trigger the bug using just wagtaildemo's Standard Index Page content type.** Simply edit the page titled "Standard index" under wagtaildemo's "Home page", as its Related Links field has all the setup needed to trigger this bug.

Considering that django-modelcluster's README specifically promotes its ability to "render a preview of the data the user has just submitted, prior to saving", this is pretty significant problem. 

I'm not sure if this is a bug in wagtail or a bug in django-modelcluster, though. I'll post a link to this issue on that module's queue.

**Comment by edrex** [comment]
We're experiencing this too. Related to #222?

**Comment by gasman** [comment]
Have confirmed that this is a modelcluster bug, now fixed in https://github.com/torchbox/django-modelcluster/pull/16 - will get that merged and a new version of modelcluster released ASAP.

**Comment by coredumperror** [comment]
That's great to hear!
