### ISSUE TITLE
Set image size when inserting using the rich text editor

### ISSUE THREAD

**Issue by briknow** [torchbox/wagtail#874]
As a user I don't want to have to upload different sized images to the library. I should be able to set the image size when inserting from the library into a rich text area.

![sshot-2014-12-14- 12-23-16](https://cloud.githubusercontent.com/assets/5522412/5428922/1bd00d7a-838c-11e4-9751-4226a41fc05f.png)

**Comment by davecranwell** [comment]
@briknow does `register_image_format` help you in this situation? We'd like to close this issue if possible.

**Comment by nutztherookie** [comment]
Just for reference, since wagtail-docs have been moved around a lot:

http://docs.wagtail.io/en/latest/advanced_topics/customisation/page_editing_interface.html#image-formats-in-the-rich-text-editor  is the current link

@davecranwell could you maybe update your comment? thanks

**Comment by gasman** [comment]
Any link to the '/latest' docs is liable to break in future :-) This one should remain active: http://docs.wagtail.io/en/v1.8.1/advanced_topics/customisation/page_editing_interface.html#image-formats-in-the-rich-text-editor
