### ISSUE TITLE
What css classes for icons are available?

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#884]
I notice in the Wagtail docs that you can define the icon for a `wagtail.wagtailadmin.menu.MenuItem` using 'icon-folder'. However, I haven't found any listing anywhere of what other icons are available besides 'folder'. I dug around in the wagtail code and found the `icons.scss` file in the wagtailadmin app, but it's not a particularly user-friendly listing.

Is there a page somewhere that lists all the available icon classes, and what they look like?

**Comment by davecranwell** [comment]
@coredumperror Has your question been sufficiently answered? If so we'd like to close this ticket if we can.

**Comment by coredumperror** [comment]
Ah, yes. Sorry. I should have clicked "Close and comment" last time. I'll do so now.
