### ISSUE TITLE
Pages need a "created_at"/"first_published_at" for rapid query/ordering purposes

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#896]
Similar to #577. Sometimes you need to filter pages of a type and order them by descending date, as a crude way to feature the most fresh content first. 

When the date of creation is something you want the public to know/see e.g a blog posts or a press releases, dates warrant a field of their own in your custom model, but most of the time you just need an approximate measurement of freshness to use procedurally in the background, and don't want to have to add a field to store it.

I'd like a "created at", and also a "first published at", because the date of creation could with some workflows be far from the date of publication.

(The existing `latest_revision` isn't useful here because you don't want old pages appearing first after receiving a minor grammatical tweak.)

**Comment by kaedroho** [comment]
What would be the logic around ``first_published_at`` when unpublishing? It could either:
 - Only set on first publish. Unpublish/republishing won't change it
 - Set on first publish but blanked out on unpublish so republishing will set it again

**Comment by davecranwell** [comment]
I'd say the former - only set it once. They're both intended as rather lazy shortcuts and as such I don't think we need to over-think them.

**Comment by gasman** [comment]
If the use case is displaying dates on blog posts / news items, option 1 seems to make sense - you could imagine a scenario where a post is published, taken down for legal reasons or inaccuracy or whatever, and later published again, in which case it should retain its original date.

**Comment by zerolab** [comment]
:+1: on option 1.
The other option is overcomplicating things.

**Comment by zerolab** [comment]
Discussed in team meeting:

- Add publication date in the Promote tab
- Make it editable only on publication
- Can be changed after publication
- Editable by anyone who can edit the page
- Clear on unpublish

**Comment by davecranwell** [comment]
Some of these dates are going to need adding to the page editor interface, At present only the "latest edited" date is present, in the footer bar for some reason. If implementers are likely to to use these new fields to order content (as we are with current clients) it'll become necessary to see the same date information within the page editor interface.

**Comment by SalahAdDin** [comment]
So good man, thank you.

**Comment by chrxr** [comment]
Merged in https://github.com/torchbox/wagtail/pull/1054. Opened new ticket for UI implementation discussion https://github.com/torchbox/wagtail/issues/1126.

**Comment by nadersoliman** [comment]
`first_published_at` is implemented with `editable=False` and as such cannot be added as a UI field in any page editing tab, so why the decision of `editable=False` in first place?
