### ISSUE TITLE
Encapsulate wagtailadmin auth views better

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#900]
I'm currently working on a website which has login/logout/password reset views on the frontend.

I've hit the following issues:
 - By default, Djangos password reset views would route users to the wagtailadmin password reset urls from the frontend (redirect url needs to be overriden in each view)
 - Wagtail admin requires the ``LOGIN_URL`` and ``LOGIN_REDIRECT_URL`` global settings to be set, which need to have different values on the frontend. Django doesn't support setting this in urls.py so it's not nice to work around

**Comment by zerolab** [comment]
Closed by #912.
