### ISSUE TITLE
Custom embedhandlers for richtext fields

### ISSUE THREAD

**Issue by jordij** [torchbox/wagtail#905]
Hello,

I'd like to be able to embed snippets or other chunks of content into richtext fields. In order to do so, I'd like to do something similar to what you guys do with the MediaEmbedHandler, ImageEmbedHandler, etc..

I reckon a good way to do that would be declaring custom handlers in wagtailcore/rich_text.py to define how to treat the tag when getting attributes/contents depending when going into the editor or the front-end.

Would be possible to include a hook or something in order to achieve that? I just don't want to pollute/patch the core, I'm looking for an elegant solution. Anyone else trying to do something similar? Thanks!

**Comment by gasman** [comment]
Hi @jordij,
We're currently working on a major new feature to support this kind of mixed content while reducing our reliance on richtext fields - you can follow the progress of this on #823.
