### ISSUE TITLE
Handle video uploaded on site

### ISSUE THREAD

**Issue by s-y** [torchbox/wagtail#907]
Hi everyone!

How to add support of uploaded video files?

**Comment by gasman** [comment]
Hi @s-y,
Our recommended way of including video on Wagtail sites is to host the video on an external service such as Youtube or Vimeo, and then use Wagtail's 'embeds' feature to include it based on its URL - either within a rich text area, or using the `|embed` template filter (see https://github.com/torchbox/wagtaildemo/blob/master/demo/templates/demo/includes/carousel.html for example).

It's unlikely that we will ever implement direct video uploading within Wagtail - it would be a huge amount of work to support all the features that people expect from a video hosting platform (friendly uploading with progress bar, format conversion, multiple quality settings, creating preview images...), it would require extra setup work when hosting a site, and it's not clear what advantages it would give over using an external service. However, we would certainly be open to someone else implementing this as a third-party add-on to Wagtail.

**Comment by SalahAdDin** [comment]
I have a question related with this, two in fact.
How is the url format for embed youtube video? i try put a lot of link but say me that the url embed is no correct format.
Second, do you see django-embed-video? I don't know if have the same functionality, but, has some embed video tags very useful.

Thank you.

**Comment by gasman** [comment]
Hi @SalahAdDin - please use [the mailing list](https://groups.google.com/forum/#!forum/wagtail) for support queries.
