### ISSUE TITLE
Compression option per image when requesting wagtail to make images

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#908]
When you call wagtail externally or through the admin URL generator interface to produce an image using a filter and physical size, could there also be the option to specify the JPEG compression level? Currently the default 85 can be overridden in settings for all images only.

**Comment by kaedroho** [comment]
We could implement this by adding a new filter which gets chained with the resize:

for example, in the image tag:

``{% image "fill-100x100 compress-85" %}``

In the external URL generator:

``/images/<sig>/1/fill-100x100|compress-85/``

**Comment by mrgarethprice** [comment]
We’ve been discussing this a lot at Springload. What you’re suggesting in the template is perfect, consider a box of delicious craft beer yours when this ships ;) One thing we've noticed is that "original" isn’t actually original and is getting compression applied – compress-bypass might be good.

**Comment by davecranwell** [comment]
Sorry notsorry to hijack this issue for nefarious purposes, but could #1203 be in any way rolled into this?

**Comment by gasman** [comment]
@davecranwell Not really... the discussion on #1203 was a mishmash of several different issues, but as far as the it relates to improving lossless compression, that would be best handled entirely within Willow as a separate task (https://github.com/torchbox/Willow/issues/10).

**Comment by gasman** [comment]
Implemented in #2474 (documentation for new URL format added in 7ec734e9257e1da14b5b3f2c2437bc474940fda6).
