### ISSUE TITLE
Make wagtail set cache control settings

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#911]
This is a proposal for an enhancement to the ``frontendcache`` contrib module.

Wagtail doesn't currently return any cache control headers for varnish/squid to use. This would make users likely to just stick caching on top of the entire website without taking the following into account:
 - Pages which take POST requests such as login views and form pages are not cachable due to the CSRF token (that needs to be renewed on each request).
 - Pages in private sections need to be treated as private by the cache
 - Other non-page sections of the site (wagtailadmin, frontend user account views, etc). Would need to be taken into account individually in the cache configuration.

I propose that we add an ``after_serve_page`` hook into ``wagtailcore``. Then make the ``wagtailfrontendcache`` module hook onto that and set the cache-control headers automatically.

 - By default, all pages would have this cache-control header: ``Cache-Control: public, max-age=3600``. This would tell the cache to cache the page for one hour which would be configurable with a django setting.
  - This would not apply to custom views or the admin interface, only when serving pages
  - This would also not override the cache-control header if it is already set in the response (allowing form pages to set ``Cache-Control: no-cache``)
 - Private pages would have ``Cache-Control: private, no-cache, no-store``

Also, (kind of separate from the above proposal). ``wagtailadmin`` should set the following header on all responses: ``Cache-Control: private, no-cache, no-store``

**Comment by lee-kagiso** [comment]
Hi sorry to be a pain, on Wagtail 1.1 no cache control headers are set by default?

```
By default, all pages would have this cache-control header: Cache-Control: public, max-age=3600. This would tell the cache to cache the page for one hour which would be configurable with a django setting. 
```

**Comment by kaedroho** [comment]
Hi Lee,

This was a proposal but was closed due to lack of interest at the time.

It's possible to do this by using ``decorate_urlpatterns`` in ``urls.py``:

```python
from wagtail.utils.urlpatterns import decorate_urlpatterns

urlpatterns_private = [
    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^admin/', include(wagtailadmin_urls)),
]

urlpatterns_public = [
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^search/$', 'search.views.search', name='search'),
    url(r'', include(wagtail_urls)),
]

try:
    cache_length = settings.CACHE_CONTROL_AGE
except AttributeError:
    cache_length = 604800

# Decorate the public urls with cache settings
urlpatterns_public = decorate_urlpatterns(
    urlpatterns_public,
    cache_control(public=True, max_age=cache_length)
)

urlpatterns = urlpatterns_private + urlpatterns_public
```
