### ISSUE TITLE
The tagging system is too complex

### ISSUE THREAD

**Issue by kidlj** [torchbox/wagtail#916]
As a Django newbie, after having read the documents and demo site source for several times, I just can't understand it (and the 'django-taggit' and 'django-modelcluster' stuff, especially when binding these two together).

But I love Wagtail for it's beautiful interface and neat design(except for the tagging part of course). As a *production* built on Django, I think the tagging system should be as easy as possible, just like the other components of it.

What do you think?

**Comment by kidlj** [comment]
Well, that's my own problem :-)

**Comment by SalahAdDin** [comment]
I don't understand your point.

**Comment by tomdyson** [comment]
Hi @kidlj, sorry we didn't have a more helpful answer. We have just merged a contributed fix to multi-word tags: https://github.com/torchbox/wagtail/pull/825

I'm very interested to see your clone of freebsd.org. Are you proposing to use Wagtail for that site? Email my first name at torchbox.com.

Thanks

Tom
