### ISSUE TITLE
Image upload fails on iPad

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#918]
1. Login on iPad 
2. Tap "Images" in sidebar
3. Tap "Add an image"
4. Tap "Or choose from your computer"
5. Select a photo from your library and tap "Done"

After step 5 the progress bars will appear without progressing. After some time a message will appear "Sorry, upload failed."

Uploading to the same instance of Wagtail from the desktop succeeds.

Wagtail version: 0.8.4
Django version: 1.7.1
OS: Debian 7.8.0

**Comment by davecranwell** [comment]
Hi @mhnbcu, we've been unable to replicate this on an iPad Air, iOS 8.3 and on the latest version of wagtail (1.0rc2). Please could you try again using a more recent version of Wagtail? If you could also provide OS details of the iPad on which you experienced this, that would be helpful.

**Comment by mhnbcu** [comment]
@davecranwell I can confirm this issue is not present in the recent 1.x.x versions of Wagtail. Additionally the iOS version used is no longer the latest. Thanks!

**Comment by davecranwell** [comment]
Many thanks. Closing.
