### ISSUE TITLE
Provide integration with django-bakery for static publishing

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#923]
The [Django Bakery](http://github.com/datadesk/django-bakery) module from @palewire provides [next level](http://datadesk.latimes.com/posts/2012/03/introducing-django-bakery/#the-next-level) static publishing. @mtigas, the creator of Django Medusa, mentions it in his [blog](https://mike.tig.as/blog/2012/06/30/django-medusa-rendering-django-sites-static-html/) and [comments positively](https://news.ycombinator.com/item?id=3699554) on the module.

I made a [gist](https://gist.github.com/mhnbcu/d1a847f420fd0df5d377) to illustrate a basic integration.

Thoughts?

**Comment by gasman** [comment]
Thanks for the suggestion! We currently have support for generating static sites using django-medusa <http://docs.wagtail.io/en/latest/contrib_components/static_site_generation.html> - would there be any benefits from switching to Django Bakery (or supporting both libraries)?

**Comment by mhnbcu** [comment]
Django Bakery provides the following functionality not present in Django Medusa:

1. Targeted builds
2. Automatic publishing triggered when content is edited
3. Integration with Celery for publishing in background 

The first point means that one could rebuild one content type instead of the whole site. Incremental builds make static publishing more of a realistic case for a large site with complex content. 

The second point means after editing a page Django Bakery integration would make Wagtail capable of knowing which related detail and listing pages need republishing and only those would be rebuilt. 

The third point means that rebuilds would happen in the background without the editor having to wait for the process of rebuilding to complete.

Do these features make sense for Wagtail? 

More details can be found at this [post](http://datadesk.latimes.com/posts/2012/03/introducing-django-bakery/#the-next-level) about Django Bakery.

**Comment by mhnbcu** [comment]
A draft Django Bakery module for Wagtail, named (wagtailbakery)[https://github.com/mhnbcu/wagtailbakery), is completed. Feedback welcome.

Much thanks to the Torchbox team for hints on module structure from the Wagtail repository structure.

**Comment by gasman** [comment]
@mhnbcu Thanks! Added to the docs now - 149da7f5789f54b309aff34f04c2144ae7b2ba9b

@kaedroho will look at the possibility of adopting django-bakery as a replacement for django-medusa in a future release.

**Comment by mhnbcu** [comment]
@gasman Thank you for the note. @kaedroho Thank you for looking further into it.
