### ISSUE TITLE
A couple of redirects ideas

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#925]
- Mass import from CSV (we've done this manually a couple of times so we should have most of the code for this lying around somewhere)
- A modal that lists the common 404 URLs ranked by how many hits they've got in the past week (basically the same as what we do for promoted search results).
- When deleting a page with redirects to it. Those redirects would be deleted, maybe some indication to the user that this is going to happen and an option to point them somewhere else would be useful. Also, add a redirect when a page has been deleted might be handy as well.

**Comment by SalahAdDin** [comment]
For CSV, don't use you django-import-export? Maybe his author will be interesting in help you.
