### ISSUE TITLE
Wagtail API

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#926]
I'm looking to get some feedback on a new module for Wagtail called Wagtail API. It is currently implemented as an external module but will be pulled into Wagtail as a contrib module once finished (hopefully for 0.9 release).

When enabled, this module will provide a read-only RESTful API into your Wagtail content. This is useful for when the UI is all on the client-side (eg, mobile app) and you're just using Wagtail for content editing.

It provides endpoints for pages, images and documents.

The initial implementation will not support authentication, so will only serve public content and not support editing. I've designed this API so that it could be expanded to support editing while (hopefully) maintaining backwards compatibility.

To keep this post short, I won't be going into how to configure models side of the ``wagtailapi`` module. You can find documentation on that here: https://github.com/torchbox/wagtailapi/blob/master/readme.md. But please feel free to post feedback on that in this ticket.

The API!
========

As I said earlier, the API has three endpoints:

* **Pages:** ``/api/v1/pages/``
* **Images:** ``/api/v1/images/``
* **Documents:** ``/api/v1/documents/``

Listing views
-------------

Performing a ``GET`` request against one of these URLs will get you a listing of things. The response will look a little bit like this:

```json
    GET /api/v1/endpoint name/

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": "total number of results"
        },
        "endpoint name": [
            {

            },
            {

            }
        ]
    }
```

This is the basic structure of all of the listing views. They all have a ``meta`` section with a ``total_count`` variable and a listing of things.

Detail views
------------

All of the endpoints also contain a "detail" view which returns information on an individual object. This view is always acessed by appending the id of the object to the URL.

The ``pages`` endpoint
----------------------

This endpoint includes all live pages in your site that have not been put in a private section.

#### The listing view (``/api/v1/pages/``)

Here I'll go into the specific details about the ``pages`` listing.

This is what a typical response from a ``GET`` request would look like:

```json
    GET /api/v1/pages/

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 2
        },
        "pages": [
            {
                "id": 2,
                "meta": {
                    "type": "demo.HomePage"
                },
                "title": "Homepage"
            },
            {
                "id": 3,
                "meta": {
                    "type": "demo.BlogIndexPage"
                },
                "title": "Blog"
            }
        ]
    }
```

Each page object contains the id, a meta section and the fields with their values.

##### ``meta``

This section is for any piece of information that is useful, but not a database field. The initial implementation only includes the type name here, but possible additions would be things like urls to relevant parts of the api (eg. detail/edit views), status, parent page, etc.

I think this would be really useful in the future when we implement writing to the API. A client can easily tell what's a database field (and could be written to) and what's not.

##### Dealing with different model classes

The main challenge I faced while creating this view is that different pages can use different types so will have a different set of fields to view/filter/sort on.

The way the pages endpoint works around this is as follows:
 - By default, the main listing view lists all pages. The only extra field returned is ``title`` and you can only filter/order on the ``id`` and the ``title`` fields.
 - You can access fields of a specific class by using the ``type`` query parameter. This filters the results to only show pages of the chosen type and also gives the user access to view/filter/order on all of the extra fields of that specific type.

```json
    GET /api/v1/pages/?type=demo.BlogPage

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 3
        },
        "pages": [
            {
                "id": 4,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 1"
            },
            {
                "id": 5,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 2"
            },
            {
                "id": 6,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 3"
            }
        ]
    }
```

##### Specifying a list of fields to return

As you can see, we still only get the ``title`` field by default. I didn't want to just throw in all fields onto the listing as I imagine most of them won't be used in listings (and are intended to only be used in detail pages).

As the client probably knows best about what fields they want, I added another query parameter to allow them to choose a list of fields called ``fields``.

```json
    GET /api/v1/pages/?type=demo.BlogPage&fields=title,date_posted,feed_image

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 3
        },
        "pages": [
            {
                "id": 4,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 1",
                "date_posted": "2015-01-23",
                "feed_image": 1
            },
            {
                "id": 5,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 2",
                "date_posted": "2015-01-24",
                "feed_image": 2
            },
            {
                "id": 6,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 3",
                "date_posted": "2015-01-25",
                "feed_image": 3
            }
        ]
    }
```

We now have enough information to make a basic blog listing with a feed image and date which the blog was posted.

Note that images are returned as ids. I decided not to nest so much in these documents for a few of reasons:
 - Reduce the amount of potentially uneeded data in the response
 - Makes cache-purging methods easier to implement
 - If you just want to download the images, the id is all that's needed

(side note)
One possible future expansion of the API would be to add an ``expand`` query parameter which also takes a list of fields. Adding the feed image to this would make the API embed a summary of the image into the listing so not as many lookups need to be made.

##### Filtering on fields

Exact matches on field values can be done by using a query parameter with the same name as the field. Any pages with the field that exactly matches the value of this parameter will be returned.

```json
    GET /api/v1/pages/?type=demo.BlogPage&date_posted=2015-01-24

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 1
        },
        "pages": [

            {
                "id": 5,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 2",
                "date_posted": "2015-01-24",
                "feed_image": 2
            }
        ]
    }
```

Range querys are also supported but require extra configuration (see the ``wagtailapi`` readme).

##### Filtering by section of the tree

It is also possible to filter the listing to only include pages with a particular parent. This is useful if you have multiple blog listings with the same page type for example.

For example (imagine we are in the same project as all previous examples, and page id ``7`` refers to the other blog index):

```json
    GET /api/v1/pages/?type=demo.BlogPage&child_of=7

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 1
        },
        "pages": [
            {
                "id": 4,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "Other blog 1"
            }
        ]
    }
```

For simplicity, I decided not to implement descendants, siblings or ancestors. I think ``child_of`` satisfies most use-cases.

##### Ordering

Like filtering, it is also possible to order on database fields. The endpoint accepts a query parameter called ``order``. This is a list of field names to order by. Field names can be prefixed with a ``-`` to reverse order. It is also possible to order randomly by setting this parameter to ``random``.

```json
    GET /api/v1/pages/?type=demo.BlogPage&order=-date_posted

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 3
        },
        "pages": [
            {
                "id": 6,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 3",
                "date_posted": "2015-01-25",
                "feed_image": 3
            },
            {
                "id": 5,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 2",
                "date_posted": "2015-01-24",
                "feed_image": 2
            },
            {
                "id": 4,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 1",
                "date_posted": "2015-01-23",
                "feed_image": 1
            }
        ]
    }
```

##### Pagination

Pagination can be done using two query parameters called ``limit`` and ``offset``. ``limit`` sets the number of results to return and ``offset`` is the index of the first result to return. The default value for ``limit`` is ``20`` and its maximum value is ``100`` (which can be changed using the ``WAGTAILAPI_MAX_RESULTS`` setting).

```json
    GET /api/v1/pages/?limit=1&offset=1

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 2
        },
        "pages": [
            {
                "id": 3,
                "meta": {
                    "type": "demo.BlogIndexPage"
                },
                "title": "Blog"
            }
        ]
    }
```

Pagination will not change the ``total_count`` value in the meta.

##### Searching

Full text search is supported. This uses the ``wagtailsearch`` module so will make use of Elasticsearch if that is specified in your backends. To perform a full-text search, set the ``search`` parameter to the query string you would like to search on.

```json
    GET /api/v1/pages/?search=Blog

    HTTP 200 OK
    Content-Type: application/json

    {
        "meta": {
            "total_count": 3
        },
        "pages": [
            {
                "id": 3,
                "meta": {
                    "type": "demo.BlogIndexPage"
                },
                "title": "Blog"
            },
            {
                "id": 4,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 1",
            },
            {
                "id": 5,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 2",
            },
            {
                "id": 6,
                "meta": {
                    "type": "demo.BlogPage"
                },
                "title": "My blog 3",
            }
        ]
    }
```

The results are ordered by relevance. It is not possible to use the ``order`` parameter with a search.

Also, when using Elasticsearch, you do not need to select a type to access specific fields. This will search anything that's defined in the models ``search_fields``.

Sometimes full-text search is not wanted, it is possible to switch it off by setting the ``WAGTAILAPI_SEARCH_ENABLED`` setting to ``False``.

##### Reference

Parameters:
 * ``type``
 * ``limit``
 * ``offset``
 * ``fields``
 * ``child_of``
 * ``order``
 * ``search``

#### The detail view (``/api/v1/pages/{id}/``)

This view gives you access to all of the details for a particular page.

```json
    GET /api/v1/pages/6/

    HTTP 200 OK
    Content-Type: application/json

    {
        "id": 6,
        "meta": {
            "type": "demo.BlogPage",
            "parent_id": 3
        },
        "title": "My blog 3",
        "date_posted": "2015-01-25",
        "feed_image": 3,
        "related_links": [
            {
                "title": "Other blog page",
                "page": 6
            }
        ]
    }
```

The format is the same as what is returned inside the listing view, with two additions:
 - All of the available fields are added to the detail page by default
 - The ``meta`` section has a ``parent_id`` field that contains the ID of the parent page

The ``images`` endpoint
-----------------------

This endpoint gives access to all uploaded images. This will use the custom image model if one was specified. Otherwise, it falls back to ``wagtailimages.Image``.

#### The detail view (``/api/v1/images/{id}/``)

The ``documents`` endpoint
--------------------------

This endpoint gives access to all uploaded documents.

#### The detail view (``/api/v1/documents/{id}/``)

Tasks
=====

- Pages endpoint
 - Listing
  - [x] List all pages
  - [x] ``type`` filter
  - [x] Selecting extra fields in listing
  - [x] Field filters
  - [x] ``child_of`` filter
  - Ordering
   - [x] Basic field ordering
   - [x] Random ordering
   - [ ] Order by multiple fields
   - [x] Reverse ordering
  - Pagination
   - [x] Limit
   - [x] Offset
  - [x] Formatting errors as JSON documents
 - Page detail
  - [x] Get a page and show all fields
  - [x] Parent page ID link
  - [x] Frontend cache invalidation
 - [x] Child objects and callable attributes
- Images endpoint
 - Listing
  - [x] List all pages
  - [x] Selecting extra fields in listing
  - [x] Field filters
  - Ordering
   - [x] Basic field ordering
   - [x] Random ordering
   - [ ] Order by multiple fields
   - [x] Reverse ordering
  - Pagination
   - [x] Limit
   - [x] Offset
  - [x] Formatting errors as JSON documents
- Documents endpoint
 - Listing
  - [x] List all pages
  - [x] Field filters
  - Ordering
   - [x] Basic field ordering
   - [x] Random ordering
   - [ ] Order by multiple fields
   - [x] Reverse ordering
  - Pagination
   - [x] Limit
   - [x] Offset
  - [x] Formatting errors as JSON documents

 - [x] Tests
 - [x] Documentation

Future expansion
================

Streamfield support
-------------------

Streamfield uses JSON documents, It would be nice if we could embed these into the response.

Submitting form pages
--------------------

Writing back API
----------------

I've put some thought into this. Heres what I've come up with

#### Images and Documents

These could be added/changed/deleted like most other APIs.

``POST`` to ``/api/v1/{images,document}/`` will create an image or a document
``PUT`` to ``/api/v1/{images,document}/{id}/`` will update an image or a document
``DELETE`` to ``/api/v1/{images,document}/{id}/`` will delete an image or a document

#### Pages

Adding and deleting pages could be implemented the same way as images/documents. Editing would be slightly more complicated due to Wagtails revisions. When we ``GET`` from ``/api/v1/pages/{id}/`` we would recieve data on the live revision, not the draft revision.

Since most editing operations is done on revisions, I think we should create a sub api for them: ``/api/v1/pages/{id}/revisions/``. This is how you would get and edit a draft revision of a page. This API would be open to authenticated users only.

##### Getting the latest draft revision

Firstly, perform a ``GET`` request on the page. A variable called ``latest_revision_id`` would be added into that pages meta section.

Using that ID, perform a ``GET`` request on the revision: ``/api/v1/pages/{id}/revisions/{revision-id}/``. This would return a document in the same format as the main page endpoint but with data from the latest draft instead of the live data.

##### Saving a revision

Perform a ``POST`` request against ``/api/v1/pages/{id}/revisions/`` with the new data. The format must be the exact same as what was returned by the previous ``GET`` request. All fields will be validated on the server side. Don't change read only fields such as the ID as this will result in a validation error.

Once the request is complete, the new revision will become the latest draft.

##### Publishing a revision

Not yet decided on the best approach for this. Here's a few options:

- Allow a ``PUT`` request to the page itself which would update the live version of the page
- Add an action to the revisions section so ``POST``ing to ``/api/v1/pages/{id}/revisions/{revision-id}/publish/`` will publish that revision
- Send an ``Action: publish`` header to the create revision view that publishes the new revision (my preferred choice)

**Comment by kaedroho** [comment]
I've just deployed a wagtaildemo instance with the ``wagtailapi`` module installed.

Try it here:
 - http://wagtailapi.kaed.uk/api/v1/pages/
 - http://wagtailapi.kaed.uk/api/v1/images/

**Comment by mhnbcu** [comment]
Encountered a small issue posted in the wagtailapi repo https://github.com/torchbox/wagtailapi/issues/2
