### ISSUE TITLE
Tree comments 

### ISSUE THREAD

**Issue by s-y** [torchbox/wagtail#927]
How to make this? I am new with wagtail.

**Comment by gasman** [comment]
Hi @s-y,

Please use the [mailing list](https://groups.google.com/forum/#!forum/wagtail) for support queries. However, I don't understand what you mean by "tree comments" - do you mean allowing users to comment on pages? We don't have any built-in support for this in Wagtail, but there are some suggestions here: https://groups.google.com/d/msg/wagtail/xw46DQh0qY4/oEpcW0Wi2fcJ
