### ISSUE TITLE
Searching Pages with InlinePanel models?

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#932]
We have a page type where the page text is split into sections, each with its own media fields etc. How should I approach indexing the fields in the section model?

From reading the docs it sounds like having the section model [inherit from](http://wagtail.readthedocs.org/en/latest/core_components/search/indexing.html#indexing-non-page-models) `index.Indexed` and then adding a `search_fields` attribute will get the fields indexed.

The other part of the problem is how to extend the default search_results view to display section results, ideally linking to the full page. Also, it would be nice if multiple hits for sections of a page didn't generate multiple results.

**Comment by kaedroho** [comment]
Hi @edrex 
You can index the section fields onto the page itself by creating a method which returns the text in all of the sections and indexing that.

For example:

```python
class ContentPageSection(Orderable):
    page = ParentalKey('ContentPage', related_name='sections')
    text = models.TextField()

class ContentPage(Page):
    ...

    def get_section_texts(self):
        # Get list of texts and concatenate them
        return '\n'.join(self.sections.values_list('text', flat=True))

    search_fields = Page.search_fields + [
        ...
        index.SearchField('get_section_texts'),
    ]
```

I've written up some ideas on how to implement a nicer API for indexing related objects like this: https://github.com/torchbox/wagtail/issues/459

**Comment by edrex** [comment]
Oh that is much simpler, and seems obvious now that you spelled it out.

**Comment by zerolab** [comment]
Closing as this was documented in #936 which is now merged
