### ISSUE TITLE
Tag autocomplete list behind image upload modal.

### ISSUE THREAD

**Issue by dRockolla** [torchbox/wagtail#943]
When inserting an image into a text editor and selecting to upload an image rather than use an existing image, if there is a tag field the autocomplete list that allows a user to select existing tags is behind the popup modal window.

If the list is short, it may not even be visible, and makes using tags difficult. If the list is long, you can see it below the modal window.

![image](https://cloud.githubusercontent.com/assets/7663577/5947395/8512fbde-a6f1-11e4-9d77-41984111597c.png)

I used this as a temporary fix:
.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all {
    z-index:520;
}

**Comment by davecranwell** [comment]
Fixed in https://github.com/torchbox/wagtail/commit/a5edb0ce0f6452b7c49404918f70d5cba670bc6e
