### ISSUE TITLE
The ability to create soft link to any page in the Editor's interface?

### ISSUE THREAD

**Issue by kidlj** [torchbox/wagtail#948]
It should work just like `ln -s` on Unix systems.
It would be useful when you want to list a page from deep hierarchy in the top menu, for example.

**Comment by zerolab** [comment]
Hi @kidlj,

On the front-end, you can achieve that using a PageAlias model, see #655.

For the admin interface, you can follow https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailusers/wagtail_hooks.py. The [Wagtail docs](http://docs.wagtail.io/en/latest/core_components/pages/editing_api.html?highlight=menuitem) provide some insight on custom menu items.

Does that help?
Dan

**Comment by kidlj** [comment]
@zerolab Thanks, your information helps.

But what I am wondering is that if it is good or important enough to be a builtin feature?

**Comment by zerolab** [comment]
Hi @kidlj,

The answer is: it depends. If there is enough demand, we can start looking at it. There are a lot of things to consider (e.g. the user experience, the UI, developer considerations).

As per @gasman's comment from [on the groups](https://groups.google.com/d/msg/wagtail/bazansXVElA/V7MZHCqDVrIJ) - there are a lot of things we want to implement, but with limited resources we have to prioritize on.

You can always implement it as an app (see the contrib folder, or wagtailapi for examples).

Best,
Dan

**Comment by kidlj** [comment]
@zerolab Thank you, Dan.
