### ISSUE TITLE
Rendition delete receiver should listen to post_delete instead of pre_delete

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#950]
Noticed this when copying listeners over to my custom rendition model.  Shouldn't [models.py#L369](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/models.py#L369) connect to post_delete instead of pre_delete so that the file isn't deleted if the Rendition.delete method is interrupted/cancelled?

**Comment by gasman** [comment]
Fixed in #2963
