### ISSUE TITLE
Parent link from search results always displays listing page 1

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#953]
A user after clicking on the "Parent" link of a search result item will always be shown page 1 of the parent listing. It could be reasonably expected that the page containing the search result item will be shown, possibly even anchored at the item within the listing.

Any varying thoughts on this?

**Comment by davecranwell** [comment]
I can see what you mean, but I don't believe this would be expected. The search listing makes no suggestion that by clicking the "Parent" link, you'll be shown the search result _in situ_, the parent link is merely provided as a convenience and for context.

That isn't to say what you're suggesting is a bad idea, however everywhere else where a page's parent is linked in this way, the link takes you to page 1 of the parent. That presents an issue of consistency to address if we were to change the behaviour in the case of search results.

**Comment by mhnbcu** [comment]
@davecranwell thank you for following up on this. It could have just been my frame of mind at the time. I think I expected my context to remain consistent with me as far as possible with each action in the system and was surprised when the context was reset. In the Kano model that would have been delightful :-)

I can see how this could be a decent chunk of work to change in a consistent manner. Once the UI is run off the API and untangled from the backend these changes might be less work. This issue/enhancement may not be worth pursuing depending on your roadmap and what others think.

**Comment by davecranwell** [comment]
I think this issue has merit, but relatively speaking this would be very low in a rather long list of priorities. In the interest of reducing the overhead of managing this many open tickets in a small team, we'd rather close it. We'd welcome you to re-opened again later as the situation changes.
