### ISSUE TITLE
Make PageChooserPanel/SnippetChooserPanel/ImageChooserPanel etc reusable outside content_panels system

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#962]
Custom models are sometimes required in which fields are foreign keys to Wagtail's images, documents or pages. e.g wagtail's own `Redirect` model.

These require the use of the modal UI to choose images/pages/etc but the only way of implementing them currently is by converting the whole view to use the edit handler system. 

Ideally these choosers would be implemented as custom field Widgets.

Latest need: creating a custom document model in which users can choose Wagtail Images for use as "cover image".

**Comment by gasman** [comment]
@timheap implemented this as part of #598 (to be included in Wagtail 0.9) - an example of this in action is https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsites/forms.py

**Comment by davecranwell** [comment]
Oh sweet! I must have only skimmed those comments previously.
