### ISSUE TITLE
Rounding inprecision in wagtailimages template tag image

### ISSUE THREAD

**Issue by abossard** [torchbox/wagtail#968]
With
{% image self.photo fill-200x200 %}
the returned image is sometimes 200x199 instead of 200x200. Without focal point.

The solution could be to check in FillOperation whether the to-be-cropped area matches the requested area and increase with one pixel line if required.

**Comment by kaedroho** [comment]
The operations code have been changed quite a bit in the next version of wagtail. Are you using Wagtail ``0.9-dev0``  or a previous version?

**Comment by abossard** [comment]
Oh wow, true. Yes I'm using 0.8.x. The original size is 539x720.

**Comment by SalahAdDin** [comment]
I'm using 0.8.x version too.

**Comment by kaedroho** [comment]
Just added a fix to this in #974. This particular fix will only work for 0.9 due to the many changes around image operations we've made recently.
