### ISSUE TITLE
Hide "promote" panel

### ISSUE THREAD

**Issue by benjaoming** [torchbox/wagtail#972]
Thanks for a great project with a great care for Django models!! What this world needs!!

Promote panel doesn't make sense in all settings. I'm especially thinking about Intranet-like settings where promoting something doesn't make any sense.

So if `Model.promote_panels = []`, I would expect the tab to disappear, however it looks like this:

![empty_promote_panel](https://cloud.githubusercontent.com/assets/374612/6090958/ab44b4d4-ae47-11e4-95c8-41c2c6d0cf12.png)

**Comment by benjaoming** [comment]
This seems to be related to #485, sorry I didn't search thoroughly enough. Could call it a dupe, however I find it more obvious to be able to hide "promote" rather than contents, which is a more basic thing, what else would one want to display...

**Comment by gasman** [comment]
Addressing this as part of #210. (Just a note - if you remove the Promote tab in this way, you'll need to add the 'slug' field to content_panels, as this is required for a valid form submission. The other fields can be safely left out - and with the fix from #957 in place, they won't appear as extra stray form fields like they do now!)

**Comment by davecranwell** [comment]
The term "Promote" has been slightly misunderstood I think.

It's not the advertising definition of promotion, but rather the *encouragement* one. We intended it to suggest a group of fields responsible for the page's representation elsewhere on the web *including within the same site itself*. Fields in the promote tab aren't the content of the page itself, rather they're the bits that control how the page appears when linked from elsewhere.

e.g in our sites, Promote fields are are things like a summary, or an appropriate accompanying image, or the internal search result description, or tagging fields that determine terms for which this page might also appear as a search match. All of these things are pertinent in any site, even an Intranet.

I'd agree this isn't clear, we've struggled to come up with a better term.

**Comment by benjaoming** [comment]
I don't mean to make a big discussion on the "Promote" term, to me it
seemed really good in lots of situations where I'd think that using terms
like "meta data" would scare off people.

But in this case, it's an intranet, and the users have never managed a
website before, they might not even understand tabs.. so I needed to just
hide it :) Also, the layout is so well-made that all the fields sit well in
just a single long page IMO.
