### ISSUE TITLE
Image chooser tags are click enabled but do not function as expected

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtail#973]
When selecting a tag from the image chooser the tag text will be placed in the search field to search the title but not the tag.

![Image 1](https://cloud.githubusercontent.com/assets/696337/6095128/7c302876-af01-11e4-905c-cb827c237da0.png)

![Image 2](https://cloud.githubusercontent.com/assets/696337/6095129/8301e59a-af01-11e4-9eea-47663abd7ea4.png)

This issue seems related to torchbox/wagtail#278. It is unclear if this behavior is intended but it feels like a bug or an incomplete implementation of tag search.

Wagtail 0.8.4
Django 1.7.1

**Comment by gasman** [comment]
As per @davecranwell's comment on https://github.com/torchbox/wagtail/issues/278#issuecomment-73481293, the 'Search term' field should be searching tags as well as title - so the UI behaviour here is correct, and the problem (if confirmed...) is entirely within #278. Therefore, closing this as a duplicate.
