### ISSUE TITLE
Error serving documents with Django Cache Middleware enabled

### ISSUE THREAD

**Issue by jordij** [torchbox/wagtail#983]
I get an error each time I serve an uploaded document (pdf file) and my Django cache middleware is enabled. I'm using Redis as a cache backend, probably happens with any backend but I'm not sure. Some of the details are:
```
Django Version:	1.7.1
Exception Type:	TypeError
Exception Value:	
can't pickle instancemethod objects
Exception Location:	/var/www/bcito/venvs/test.com/lib/python2.7/copy_reg.py in _reduce_ex, line 70
Python Executable:	/usr/bin/uwsgi-core
Python Version:	2.7.6
```

I've found a workaround editing the way I include the wagtaildocs urls.py in my app. I make use of the *never_cache* decorator. Instead of having:

```
urlpatterns = patterns(
    ...
    url(r'^documents/', include(wagtaildocs_urls)),
    ...
```

Have this:

```
...
from wagtail.wagtaildocs.views import serve
...
urlpatterns = patterns(
    ...
    url(r'^documents/(\d+)/(.*)$', never_cache(serve.serve), name='wagtaildocs_serve'),
    ...

```

Cheers,
Jordi

**Comment by zerolab** [comment]
Thank you Jordi,

@kaedroho are you happy with the proposed solution? 
Does this relate to what you are thinking on #911?

**Comment by gasman** [comment]
@jordij Can you paste the full stack trace, please?

**Comment by jordij** [comment]
TypeError at /documents/51/testar2013spreads.pdf
can't pickle instancemethod objects
Request Method: GET
Request URL:    http://test.co.nz/documents/xxx.pdf
Django Version: 1.7.1
Exception Type: TypeError
Exception Value:    
can't pickle instancemethod objects
Exception Location: /var/www/test/venvs/test.org.nz/lib/python2.7/copy_reg.py in _reduce_ex, line 70
Python Executable:  /usr/bin/uwsgi-core
Python Version: 2.7.6
Python Path:    
['.',
 '',
 '/var/www/test/venvs/test.org.nz/src/wagtailembedder',
 '/var/www/test/venvs/test.org.nz/src/wagtailgmaps',
 '/var/www/test/venvs/test.org.nz/lib/python2.7',
 '/var/www/test/venvs/test.org.nz/lib/python2.7/plat-x86_64-linux-gnu',
 '/var/www/test/venvs/test.org.nz/lib/python2.7/lib-tk',
 '/var/www/test/venvs/test.org.nz/lib/python2.7/lib-old',
 '/var/www/test/venvs/test.org.nz/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/var/www/test/venvs/test.org.nz/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/var/www/test/test.org.nz/test',
 '/var/www/test/test.org.nz/test']
Server time:    Thu, 12 Feb 2015 17:31:58 +1300

Traceback Switch back to interactive view

Environment:


Request Method: GET
Request URL: http://test.co.nz/documents/51/testar2013spreads.pdf

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'import_export',
 'taggit',
 'modelcluster',
 'djcelery',
 'core',
 'lookingforwork',
 'floppyforms',
 'widget_tweaks',
 'wagtail.contrib.wagtailsitemaps',
 'wagtail.contrib.wagtailroutablepage',
 'wagtail.wagtailcore',
 'wagtail.wagtailadmin',
 'wagtail.wagtaildocs',
 'wagtail.wagtailsnippets',
 'wagtail.wagtailusers',
 'wagtail.wagtailsites',
 'wagtail.wagtailimages',
 'wagtail.wagtailembeds',
 'wagtail.wagtailsearch',
 'wagtail.wagtailredirects',
 'wagtail.wagtailforms',
 'wagtailembedder',
 'utils',
 'debug_toolbar')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.BrokenLinkEmailsMiddleware',
 'django.middleware.cache.UpdateCacheMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware',
 'wagtail.wagtailcore.middleware.SiteMiddleware',
 'wagtail.wagtailredirects.middleware.RedirectMiddleware')


Traceback:
File "/var/www/test/venvs/test.org.nz/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  204.                 response = middleware_method(request, response)
File "/var/www/test/venvs/test.org.nz/local/lib/python2.7/site-packages/django/middleware/cache.py" in process_response
  121.                 self.cache.set(cache_key, response, timeout)
File "/var/www/test/venvs/test.org.nz/local/lib/python2.7/site-packages/redis_cache/cache.py" in set
  239.             result = self._set(key, pickle.dumps(value), timeout, client, _add_only)
File "/var/www/test/venvs/test.org.nz/lib/python2.7/copy_reg.py" in _reduce_ex
  70.             raise TypeError, "can't pickle %s objects" % base.__name__

Exception Type: TypeError at /documents/xxx.pdf
Exception Value: can't pickle instancemethod objects

**Comment by gasman** [comment]
OK - it looks like the problem is in the `wagtail.wagtaildocs.views.serve` view, which uses `FileWrapper` to generate a streamed response that avoids loading the file into memory. (It turns out that FileWrapper is not a documented Django feature - it's provided by the `wsgiref` package, and the relevant alias has been [quietly dropped from Django as of several days ago](https://github.com/django/django/commit/bbe28496d32f76ca161f5c33787d6ad62267fcc6), so it's a good thing we're spotting this now! I suspect I borrowed the code from [this StackOverflow question](http://stackoverflow.com/questions/8600843/serving-large-files-with-high-loads-in-django).)

The cache middleware can't cache streamed responses, and usually it will identify and ignore those because they're using `StreamingHttpResponse` instead of `HttpResponse`... however, our code is currently using a plain HttpResponse. (Sure enough, that StackOverflow question [was also using HttpResponse until someone fixed it a few days ago](http://stackoverflow.com/posts/8601118/revisions)...)

So, I think what we need to do here is:

* check that we can rely on the `wsgiref` package always being available. (I think it's part of the Python standard library, but would be good to make sure)
* change the import to `from wsgiref.utils import FileWrapper`
* update the view to return a StreamingHttpResponse

**Comment by jordij** [comment]
Hi guys, I think I'm having the same problem but when serving images using the URL generator. Funny enough it does work if I'm logged-in in the site but doesn't when I'm not.

Cheers,
Jordi

Internal Server Error: /images/2dMQIUOPwS5DlZuprp_E_WFdfhw=/47/width-75/
Traceback (most recent call last):
  File "/var/www/buildability/venvs/buildability.co.nz/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/var/www/buildability/venvs/buildability.co.nz/local/lib/python2.7/site-packages/django/middleware/cache.py", line 121, in process_response
    self.cache.set(cache_key, response, timeout)
  File "/var/www/buildability/venvs/buildability.co.nz/local/lib/python2.7/site-packages/redis_cache/cache.py", line 239, in set
    result = self._set(key, pickle.dumps(value), timeout, client, _add_only)
  File "/var/www/buildability/venvs/buildability.co.nz/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle instancemethod objects

Request repr(): 
<WSGIRequest
path:/images/2dMQIUOPwS5DlZuprp_E_WFdfhw=/47/width-75/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.3.1219121887.1434427204',
 'csrftoken': 'GNhfTEGBu40y8wRAFPa15lQTV66F9WCs'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'GNhfTEGBu40y8wRAFPa15lQTV66F9WCs',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': '_ga=GA1.3.1219121887.1434427204; csrftoken=GNhfTEGBu40y8wRAFPa15lQTV66F9WCs',
 'HTTP_HOST': 'www.buildability.co.nz',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36',
 'PATH_INFO': u'/images/2dMQIUOPwS5DlZuprp_E_WFdfhw=/47/width-75/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '131.203.137.142',
 'REMOTE_PORT': '51455',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/images/2dMQIUOPwS5DlZuprp_E_WFdfhw%3D/47/width-75/',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'www.buildability.co.nz',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'UWSGI_SCHEME': 'http',
 'uwsgi.core': 7,
 'uwsgi.node': 'avinton',
 'uwsgi.version': '1.9.17.1-debian',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f0548a548a0>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f0548a20a08>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
