### ISSUE TITLE
PNG alpha not retained in this image

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#989]
![ugmap](https://cloud.githubusercontent.com/assets/352835/6166175/bb31f6e2-b2a5-11e4-94eb-3c200ae7fd67.png)

Something about this image means that when uploaded to wagtail the alpha data isn't being applied.

**Comment by kaedroho** [comment]
Are you getting this on Wagtail 0.9?

**Comment by davecranwell** [comment]
Yup.

**Comment by kaedroho** [comment]
Sounds like a Willow thing, will look into it

**Comment by gasman** [comment]
Possibly relevant: #808. Basically PIL doesn't have a good way of preserving alpha when converting from paletted images to RGB or vice versa, so IIRC the fix there involved finding a way to drop the alpha without totally screwing up the image (e.g. giving it a solid black background).

**Comment by zerolab** [comment]
To confirm, the alpha channel is preserved in 0.8.4

**Comment by zerolab** [comment]
Note from some tests from last week. With latest master, alpha is preserved for larger images. It seems that the alpha channel is lost when resizing to small images (e.g. the Images list thumbnail)

**Comment by willseward** [comment]
I am seeing this error as well. Alpha channel is not preserved in thumbnail-sized PNGs.
